### ISSUE TITLE
docker文档README.md描述2个地方错误

### ISSUE THREAD

**Issue by wencuoren** [RayWangQvQ/BiliBiliToolPro#105]
拉启容器命令中间漏了个-号，新文件夹的bilibili_tool，漏了个i

**Comment by catlair** [comment]
docker compose 版本为2时，这个命令其实是正确的，也是推荐的。

查看版本时，应该使用 `docker compose version` ，而不是 `docker compose --version`

![image](https://user-images.githubusercontent.com/44313800/163518009-76cb1022-c578-426e-b9ef-de715ea99095.png)

![image](https://user-images.githubusercontent.com/44313800/163518034-63f913e8-213b-4ee5-9caf-38514fcbfcdc.png)
