### ISSUE TITLE
【建议】增加批量取关相关设置的GitHub Secrets

### ISSUE THREAD

**Issue by Cairl** [RayWangQvQ/BiliBiliToolPro#106]
增加批量取关相关设置的GitHub Secrets，包括设置取关频率、列表、数量等，不然2-3天关注列表就多了一百多个，B站号要废了

**Comment by RayWangQvQ** [comment]
加`GitHub Secrets`是用来干嘛呢？运行`Actions`用？

**Comment by Cairl** [comment]
> 加`GitHub Secrets`是用来干嘛呢？运行`Actions`用？

就是用来给aciton做自定义配置设置用的嘛，我是通过action部署到云函数的，感觉批量取关真的很重要

**Comment by DoveBoy** [comment]
@Cairl 建议使用Google浏览器，打开需要取消关注up主的页面，F12打开控制台，输入`$(".be-dropdown-item:contains('取消关注')").click()`回车，当前页面显示的所有up主全部已取关

**Comment by RayWangQvQ** [comment]
云函数的配置在yml里，跟`GitHub Secrets`没关系

**Comment by Cairl** [comment]
> @Cairl 建议使用Google浏览器，打开需要取消关注up主的页面，F12打开控制台，输入`$(".be-dropdown-item:contains('取消关注')").click()`回车，当前页面显示的所有up主全部已取关

好的，我回去试试
