### ISSUE TITLE
【Bug】消息过长超出telegram bot限制

### ISSUE THREAD

**Issue by jizizr** [RayWangQvQ/BiliBiliToolPro#12]
版本号：0.01

运行环境：ubuntu 20.04

问题描述：telegram bot 推送消息过长

日志信息：

telegram bot 发送消息的限制为2500字，故可以先转换为文本文档，再发送这个文件。或者可以简单描述执行情况再附上文件

**Comment by RayWangQvQ** [comment]
为什么会超过2500字？是因为多账号吗？

**Comment by jizizr** [comment]
> 为什么会超过2500字？是因为多账号吗？

是的

**Comment by RayWangQvQ** [comment]
或者，添加一个配置，可以设置每个账号单独推送，是否可以解决这个问题？

**Comment by jizizr** [comment]
请问tg推送

> 或者，添加一个配置，可以设置每个账号单独推送，是否可以解决这个问题？

我觉得如果加上天选时刻，单账号的消息就超过2500字了

**Comment by jizizr** [comment]
所以推送消息可以简结一点，比如：
*签到* =>成功 经验 +5
*天选时刻* => 成功 共参加 n 次抽奖

**Comment by RayWangQvQ** [comment]
当前推送的消息，之所以不够简洁，是因为当初构想是，运行时控制台（console）打印什么日志，最后推送出来就是什么样。

后面可以考虑加个简介模式，运行时先记录信息到缓存里，运行结束后再统一生成固定文本，然后推送。

**Comment by RayWangQvQ** [comment]
v0.0.6版本已新增每个账号单独推送的配置
