### ISSUE TITLE
云函数资源使用昨天开始突然变得过多

### ISSUE THREAD

**Issue by JangSuk** [RayWangQvQ/BiliBiliToolPro#122]
正常吗
![批注 2022-04-19 210857](https://user-images.githubusercontent.com/46544622/164011596-f1e0a0a1-ca5a-4213-a371-761292f5d60f.png)

**Comment by sysfox** [comment]
只要不超过月免费额度不久就行了（滑稽

**Comment by forchannot** [comment]
> 只要不超过月免费额度不久就行了（滑稽

已经给我超过了，一天暴涨1w多调用，直接给我扣费了

**Comment by sysfox** [comment]
> > 只要不超过月免费额度不久就行了（滑稽
> 
> 已经给我超过了，一天暴涨1w多调用，直接给我扣费了

你不是那个issue的吗 #123

**Comment by sysfox** [comment]
哦，原来这是你的issue，搞错了。也就是说这个bug出现在了很多案例上？？

**Comment by JangSuk** [comment]
我的也提醒收费了，就是这个资源使用量超了。
