### ISSUE TITLE
为什么会使云函数触发收费机制，而且费额巨高？

### ISSUE THREAD

**Issue by Cairl** [RayWangQvQ/BiliBiliToolPro#123]
前几天每天0.46元的时候我就想暂时给关了等更新的，结果今天一看，光是一天的费用就达到10块钱左右，这一天的花销比腾讯一个月的VIP还贵啊。

![微信截图_20220419221758](https://user-images.githubusercontent.com/20336299/164034498-ed4fab6f-8d86-4a32-ac3e-5b66c00f5d49.png)

**Comment by Cairl** [comment]
![image](https://user-images.githubusercontent.com/20336299/164043202-0cd1777c-1b77-455f-aedf-dacf05c95228.png)


我不太清楚，要是因为日志产生的收费，该这么把这个日志给关了呢？

**Comment by sysfox** [comment]
这似乎不是日志服务的费用，能把你云函数的环境变量设置截一下图吗（注意把cookie打码）？我看一下，不过个人猜测是你的休眠或两次api请求间隔设置的太长了。

**Comment by forchannot** [comment]
> 这似乎不是日志服务的费用，能把你云函数的环境变量设置截一下图吗（注意把cookie打码）？我看一下，不过个人猜测是你的休眠或两次api请求间隔设置的太长了。

我自己的云函数环境变量没有改默认api请求，休眠仅仅聪默认的20改为了10。也是今天突然开始收费，我直接把他删除了，不过他提示我给我自动停止了日志cls服务。

**Comment by sysfox** [comment]
1.看一下云函数的日志，看一下每一次运行用时多少，是否运行时间过长或出现错误
2.从头开始安装一遍(除cookie外都保持默认设置)，再看一看会不会产生费用

**Comment by forchannot** [comment]
> 1.看一下云函数的日志，看一下每一次运行用时多少，是否运行时间过长或出现错误 2.从头开始安装一遍(除cookie外都保持默认设置)，再看一看会不会产生费用

已经触发付费了，不敢继续用了，我就是除了cookie外都默认，就是改了下up的uid而已，这个不影响吧。云函数收费太高了，我已经暂时删了，再试一次不知道又会花多少钱。看看有没有其他人试一下的

**Comment by forchannot** [comment]
> emmmm，那我也就不清楚了，你看一下我的配置，我的云函数目前一切正常。你把云函数首页的概览截图给我看一下吧



![Screenshot_2022-04-20-09-20-06-129_mark via](https://user-images.githubusercontent.com/100580891/164127996-9ab285e4-cc5f-4f64-a0d3-e7048df48daa.png)
电脑不在身边，手机截的图，函数已经删了看不到日志了，不过这张图能看到确实是bili工具导致的超量扣费

**Comment by forchannot** [comment]
> ![41233FCC-39F9-4361-9B34-342511AC904D](https://user-images.githubusercontent.com/99103591/164127967-3356b025-32fa-43ad-85dc-db3387dd1e20.jpeg) ![BD8D885B-9C40-448A-BC42-D8CE6E2205BC](https://user-images.githubusercontent.com/99103591/164127979-eb5b3bc7-17d8-4e68-bcb1-5c6c35061018.jpeg) emmmm，那我也就不清楚了，你看一下我的配置，我的云函数目前一切正常。你把云函数首页的概览截图给我看一下吧

我也是之前一直没问题，就今天突然暴涨一两万GBs，给我干扣费了

**Comment by sysfox** [comment]
你还有一个云函数？

**Comment by forchannot** [comment]
> 你还有一个云函数？

我有三个云函数，图上也能看出来吧，不过另外两个基本没任何占用。那两个挂了好久了没出过问题

**Comment by sysfox** [comment]
恐怕就是那两个云函数导致的，你有设置它们每日自动运行吗？

**Comment by forchannot** [comment]
> 恐怕就是那两个云函数导致的，你有设置它们每日自动运行吗？

有啊，但是那两个云函数运行时间和bili运行时间完全不同啊，调用也显示的是bili一天多了1w多GPs的

**Comment by sysfox** [comment]
每一个云函数对于资源的请求都是巨大的，腾讯云会将所耗资源加在一起来结算

**Comment by sysfox** [comment]
bili一天1万？

**Comment by forchannot** [comment]
> 每一个云函数对于资源的请求都是巨大的，腾讯云会将所耗资源加在一起来结算

你看我发的那张图，最下面有函数分别的调用量的，明显是bili在调用

**Comment by sysfox** [comment]
。。。那我也就无法解释了

**Comment by sysfox** [comment]
如果高兴的话你可以再开一个小号

**Comment by sysfox** [comment]
或者使用其他方法来代替

**Comment by forchannot** [comment]
> 如果高兴的话你可以再开一个小号

我换成电脑本地运行通过任务计划程序定时调用了，云函数确实不敢用了，不知道是bug还是啥

**Comment by sysfox** [comment]
那就这样吧，看作者以后更新了再试试，应该是bug。issue可以关了(狗头）

**Comment by catlair** [comment]
这是什么鬼

![image](https://user-images.githubusercontent.com/44313800/164149122-611e0fe1-4183-47a2-91c5-c5ed9da7e40b.png)

我觉得你们这资源占用都好高

> 用户资源使用量，由函数配置内存，乘以函数运行时的计费时长得出。

![image](https://user-images.githubusercontent.com/44313800/164149582-2601e5db-fbc3-4f76-9a1a-46420994e441.png)

**Comment by sysfox** [comment]
有些人的SCF好像出了点bug，截至目前有两个。我的SCF是正常的

**Comment by RayWangQvQ** [comment]
你们的部署方式都是啥？会不会手动和actions两种部署方式的产出有不一样的地方？

**Comment by forchannot** [comment]
> 你们的部署方式都是啥？会不会手动和actions两种部署方式的产出有不一样的地方？

我是action部署

**Comment by sysfox** [comment]
> 你们的部署方式都是啥？会不会手动和actions两种部署方式的产出有不一样的地方？

我是手动，没有出现问题。

**Comment by JangSuk** [comment]
我的也是Action

**Comment by catlair** [comment]
> > emmmm，那我也就不清楚了，你看一下我的配置，我的云函数目前一切正常。你把云函数首页的概览截图给我看一下吧
> 
> ![Screenshot_2022-04-20-09-20-06-129_mark via](https://user-images.githubusercontent.com/100580891/164127996-9ab285e4-cc5f-4f64-a0d3-e7048df48daa.png) 电脑不在身边，手机截的图，函数已经删了看不到日志了，不过这张图能看到确实是bili工具导致的超量扣费

免费的并发配额为 128 GB，看你这个好像是256GB了，不过现在无所谓了，SCF即将全面收费
