### ISSUE TITLE
【Bug】青龙添加了PUSH_PLUS_TOKEN没有推送

### ISSUE THREAD

**Issue by remiliyaScarlet** [RayWangQvQ/BiliBiliToolPro#126]
请问是哪里配置的有问题吗
<img width="698" alt="image" src="https://user-images.githubusercontent.com/38554772/164357217-7fe9af97-3106-436e-a6f0-cbc00eb0cb65.png">

**Comment by RayWangQvQ** [comment]
[配置说明文档](https://github.com/RayWangQvQ/BiliBiliToolPro/blob/main/docs/configuration.md#15-%E6%96%B9%E5%BC%8F%E4%BA%94%E6%89%98%E7%AE%A1%E5%9C%A8%E9%9D%92%E9%BE%99%E9%9D%A2%E6%9D%BF%E4%B8%8A%E4%BD%BF%E7%94%A8%E9%9D%A2%E6%9D%BF%E7%9A%84%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F%E9%A1%B5%E6%88%96%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E9%A1%B5%E8%BF%9B%E8%A1%8C%E9%85%8D%E7%BD%AE)
