### ISSUE TITLE
pushplus推送异常

### ISSUE THREAD

**Issue by Qiu1127** [RayWangQvQ/BiliBiliToolPro#127]
![image](https://user-images.githubusercontent.com/97421199/164443960-157189fe-9c6b-45b6-b00d-6f35719a87a4.png)
显示请求成功，公众号未收到通知，已检查token和channel配置没有错误

**Comment by Qiu1127** [comment]
![image](https://user-images.githubusercontent.com/97421199/164578076-3cd4ac0d-291b-4097-8ee2-fbf2e3732f6c.png)
![image](https://user-images.githubusercontent.com/97421199/164578122-8b4fdec6-ecb6-4468-b6f9-5409cf693d64.png)
昨晚反馈后恢复正常，但从设备通知变成了告警通知，是正常情况吗？另外怎么在每周一自动更新部署之前配置好pushplus和appsettings的部分设置呢，常见问题里对此类描述可能不够完整

**Comment by weiqngg** [comment]
请问  你这个推送是在哪里设置的 我设置之后没有反应啊

**Comment by Qiu1127** [comment]
就是appsettings.json函数文件里填入了pushplus的token

**Comment by catlair** [comment]
这其实是
push+的问题，公众号也没有消息
