### ISSUE TITLE
【建议】优化重构tencent函数部署的设计

### ISSUE THREAD

**Issue by RayWangQvQ** [RayWangQvQ/BiliBiliToolPro#128]
建议内容：
#123 #122 

* [ ] 云函数关于睡眠时长的默认配置是否可以相应缩短，以缩短每次触发的运行时长？
* [ ] 排查下函数的资源用量的判断，除了运行时长还有什么其他影响因素？
* [ ] `actions`定时触发部署云函数的周期是否可以增大，不需要太频繁？
* [ ] 排查异常处理流程，异常是否会导致函数超载消耗资源？

**Comment by catlair** [comment]
从5.23起，除了新用户3个月外，不再享受免费额度，最低需要每月消费9.9元购买资源包。

**Comment by RayWangQvQ** [comment]
每月10￥，那不如买个虚机了。。。

**Comment by chuyua** [comment]
建议改路线 整阿里云 感激

**Comment by RayWangQvQ** [comment]
close and will not do: 
will change to ali cloud function in the future#133
