### ISSUE TITLE
【腾讯云函数部署测试报错】按照提示进行操作之后，测试报错，目前不明白报错的含义，无法定位问题。

### ISSUE THREAD

**Issue by MaxwelsDonc** [RayWangQvQ/BiliBiliToolPro#13]
**版本号**：
<img width="1234" alt="image" src="https://user-images.githubusercontent.com/99466301/154626577-287adfc9-7b32-4955-a1dd-04c212be63f6.png">

**运行环境**：腾讯云函数

**问题描述**：按照教程部署到腾讯云函数之后，测试后报错。

**日志信息**：

```
Invoke function BiliTool [RequestId:18954d20-56f0-4263-9d22-45f3e9adf409]
Response: 
{"errorCode":1,"errorMessage":"ReloadFail: Bootstrap not executable\n","requestId":"18954d20-56f0-4263-9d22-45f3e9adf409","statusCode":443}
Output:

Summary:
  Request ID: 18954d20-56f0-4263-9d22-45f3e9adf409
  Run Duration: 0
  Bill Duration: 0
  Usage Memory: 0
  Invoke Result: -1
```

**Comment by RayWangQvQ** [comment]
Bootstrap not executable，bootstrap文件不可执行。

release包里有个bootstrap文件，如果下载zip包后自己改动过该文件，可能会引起异常。

建议下载后不要动zip文件，直接上传。

或者选择使用 GitHub Actions 的方式来部署云函数。
