### ISSUE TITLE
【Bug】运行脚本出错

### ISSUE THREAD

**Issue by jiuaiyun** [RayWangQvQ/BiliBiliToolPro#135]
版本号：最新版
运行环境：青龙面板

问题描述：脚本拉到库以后执行不了 

日志信息：
![QQ截图20220425085339](https://user-images.githubusercontent.com/83531201/165004560-8b129b5b-8734-4501-b7bb-31c784a1b030.png)

**Comment by RayWangQvQ** [comment]
#79

**Comment by funxiaop** [comment]
有无解决？

**Comment by RayWangQvQ** [comment]
已有解决办法，请参考 #266
