### ISSUE TITLE
【请教】请问大家有办法知道天选中的是什么么

### ISSUE THREAD

**Issue by Cyiming** [RayWangQvQ/BiliBiliToolPro#136]
有的光看名字不知道是啥 有办法进入到当初的抽奖页面看介绍么

比如这个
![image](https://user-images.githubusercontent.com/45073586/165661924-70dcc640-90bf-42cf-899b-886308b9fc9b.png)

**Comment by yangxinyue1995** [comment]
这个没什么用，跟你打一把游戏而已
