### ISSUE TITLE
在docker容器运行时出现new crontab file is missing newline before EOF, can't install.

### ISSUE THREAD

**Issue by hujihan** [RayWangQvQ/BiliBiliToolPro#140]
建议内容：
（提issue前请先确认没有其他人提过相同的议题）
在docker容器运行时，我查看logs文件，最下面出现new crontab file is missing newline before EOF, can't install.
![image](https://user-images.githubusercontent.com/46958243/165967234-f8fc6778-0b5e-4dc0-ac55-e55d360d9a90.png)

**Comment by Zzznopay** [comment]
怎么解决的问题没看到呀
