### ISSUE TITLE
青龙面板部署，天选时刻日志显示正常，但是实际上并未关注主播参加抽奖

### ISSUE THREAD

**Issue by moon4869** [RayWangQvQ/BiliBiliToolPro#142]
前几天都是正常关注并抽奖的，但是今天开始全部都失效了，日志却是显示正常的，查看关注列表却没有新增。是我每天跑太多次了吗？还是cookie失效或者其他问题？

**Comment by ylegeb** [comment]
同问题，ck于昨日失效，重新抓取后可以过ck测试、正常做日常、取消关注；唯独天选抽奖运行日志正常无报错，实际却无法执行相应活动如：关注主播（这点太致命了，大部分抽奖前提是关注主播）、为新关注主播自动分组（应该是前一步没有自动关注的问题）

**Comment by moon4869** [comment]
> 同问题，ck于昨日失效，重新抓取后可以过ck测试、正常做日常、取消关注；唯独天选抽奖运行日志正常无报错，实际却无法执行相应活动如：关注主播（这点太致命了，大部分抽奖前提是关注主播）、为新关注主播自动分组（应该是前一步没有自动关注的问题）

经测试，与上述情况完全一致，已排除了cookie失效的可能

**Comment by ylegeb** [comment]
> > 同理，运行于昨天没有故障，重新问题后进行测试、正常做日常、取消关注；唯独天选奖正常报错，实际无法执行日志活动如：关注主播这点太绝对关注了，自动抽奖）、播音是主播（应该是前一步没有自动关注的新问题）
> 
> 经测试，与上述情况完全一致，已解决 cookie 失效的可能

今天自己好了，MD，绝了！

**Comment by moon4869** [comment]
> > > 同理，运行于昨天没有故障，重新问题后进行测试、正常做日常、取消关注；唯独天选奖正常报错，实际无法执行日志活动如：关注主播这点太绝对关注了，自动抽奖）、播音是主播（应该是前一步没有自动关注的新问题）
> > 
> > 
> > 经测试，与上述情况完全一致，已解决 cookie 失效的可能
> 
> 今天自己好了，MD，绝了！

我是今天中午突然把昨天参加抽奖的主播全部关注了，就像是延迟到今天中午关注一样。。。今天还没有测试效果

**Comment by aefa6** [comment]
@moon4869 @ylegeb 话说你们解决了么，我这也出这个bug了，一个月了都这样
