### ISSUE TITLE
青龙面板里面收不到推送呢

### ISSUE THREAD

**Issue by dalmie** [RayWangQvQ/BiliBiliToolPro#143]
（提issue前请先确认没有其他人提过相同的议题）
群晖docker拉取的青龙，建立任务后看日志都可以正常运行，就是收不到tg的推送，其他项目可以正常收到推送，谢谢

**Comment by dalmie** [comment]
tg做了反代，不知道这个变量怎么填写？

**Comment by RayWangQvQ** [comment]
#65
