### ISSUE TITLE
Connecting to 172.17.0.1:7890... failed: Connection refused.

### ISSUE THREAD

**Issue by cuncun-edg** [RayWangQvQ/BiliBiliToolPro#148]
版本号：（请贴出你的版本号，请确认是否已通过升级到最新版来解决当前问题？）
青龙最新版
运行环境：（请贴出运行环境，比如是Actions或docker或本地？是Win还是Linux？）
docker
Connecting to 172.17.0.1:7890... failed: Connection refused.
![image](https://user-images.githubusercontent.com/77426305/166627860-7b460435-eb60-40c4-a35b-09f51044e356.png)

**Comment by catlair** [comment]
ghproxy这个网站挂了，现在应该已经恢复

**Comment by cuncun-edg** [comment]
> 
没用呢，好像不是代理的问题，是网络的问题，一直拒绝连接呢

**Comment by catlair** [comment]
好吧，或许你可以换一种方式，进入容器再尝试

**Comment by cuncun-edg** [comment]
> 好吧，或许你可以换一种方式，进入容器再尝试

进入容器也是拒绝连接呢，想不到什么办法了
