### ISSUE TITLE
【建议】大佬能不能出个手机青龙的教程呀？改了路径也还是执行不了

### ISSUE THREAD

**Issue by Jimlu-666** [RayWangQvQ/BiliBiliToolPro#167]
![image](https://user-images.githubusercontent.com/75733210/169471031-2dcea808-39f5-451b-a193-71cc0a016ca2.png)
改了路径也还是执行不了

**Comment by RayWangQvQ** [comment]
手机版是啥？🤨

**Comment by Jimlu-666** [comment]
现在手机可以搭建青龙面板了，手机用turmux终端可以搭建青龙，但是我按照教程上的运行，报错了

**Comment by lzyr9010** [comment]
手机的路径不一样 安装不了DONATE环境

**Comment by lzyr9010** [comment]
ln -s /home/dotnet/dotnet /usr/local/bin
这条执行不了

**Comment by Jimlu-666** [comment]
这样啊，我用ql extra命令把dotnet安装了，换了shared.sh的路径也没用

**Comment by Jimlu-666** [comment]
好吧，我明白了，和手机搭建的青龙还是不一样的，我还是继续用云函数吧

**Comment by lzyr9010** [comment]
Failed to create CoreCLR
