### ISSUE TITLE
docker部署时怎么配置Unfollowed取关参数？

### ISSUE THREAD

**Issue by smallmayi** [RayWangQvQ/BiliBiliToolPro#168]
![image](https://user-images.githubusercontent.com/42774709/169766517-6f86f2a8-3a98-4c0c-9d60-0c30fdac7994.png)
![image](https://user-images.githubusercontent.com/42774709/169766571-74ae1893-8835-4cde-a949-1bca9fb9445a.png)
参数怎么拼接？

**Comment by smallmayi** [comment]
还有第二个抽奖怎么配置次数？

**Comment by RayWangQvQ** [comment]
`docker-compose.yml`里配
