### ISSUE TITLE
建议大会员权益领取设置为计时每31天领取

### ISSUE THREAD

**Issue by djjia** [RayWangQvQ/BiliBiliToolPro#169]
现在大会员权益领取规则已经更改，从每月刷新变更为每31天领取一次。如果继续使用每月固定日期方式，可能会导致该月无法自动领取，或者影响下个月的领取时间。

![image](https://user-images.githubusercontent.com/59391439/169787179-0abbcf0f-ca14-4362-b65a-d63d06415270.png)

**Comment by RayWangQvQ** [comment]
恶心啊，哪个睿智想出来的规则。。。

**Comment by djjia** [comment]
> 

叔叔大概是缺米了，想让我们少薅几次羊毛

**Comment by RayWangQvQ** [comment]
已与当前版本（v0.1.2）改为每天都会尝试领取一次
