### ISSUE TITLE
青龙面板面板提示以下错误，已按要求装了微软的库

### ISSUE THREAD

**Issue by dongoufei** [RayWangQvQ/BiliBiliToolPro#17]
Process terminated. Couldn't find a valid ICU package installed on the system. Please install libicu using your package manager and try again. Alternatively you can set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support. Please see https://aka.ms/dotnet-missing-libicu for more information.

**Comment by RayWangQvQ** [comment]
请检查`extra.sh`中的`apk add bash icu-libs krb5-libs libgcc libintl libssl1.1 libstdc++ zlib`命令有没有跑成功

**Comment by RayWangQvQ** [comment]
已解决：#266
