### ISSUE TITLE
在docker容器运行时出现new crontab file is missing newline before EOF, can't install. 

### ISSUE THREAD

**Issue by Zzznopay** [RayWangQvQ/BiliBiliToolPro#173]
（提issue前请先确认没有其他人提过相同的议题）未看到解决方法
在docker容器运行时，我查看logs文件，最下面出现new crontab file is missing newline before EOF, can't install.
`[step 1/4]导入环境变量
=>完成
[step 2/4]配置cron定时任务
=>检测到自定义了cron定时任务，使用自定义配置
=>完成
[step 3/4]启动定时任务，开启每日定时运行
new crontab file is missing newline before EOF, can't install.
[step 1/4]导入环境变量
=>完成
[step 2/4]配置cron定时任务
=>检测到自定义了cron定时任务，使用自定义配置
=>完成
[step 3/4]启动定时任务，开启每日定时运行
new crontab file is missing newline before EOF, can't install.
[step 1/4]导入环境变量
=>完成
[step 2/4]配置cron定时任务
=>检测到自定义了cron定时任务，使用自定义配置
=>完成
[step 3/4]启动定时任务，开启每日定时运行
new crontab file is missing newline before EOF, can't install.`

**Comment by RayWangQvQ** [comment]
末尾少个换行
