### ISSUE TITLE
【Bug】ARM机器无法找到可执行程序

### ISSUE THREAD

**Issue by Nozomi22** [RayWangQvQ/BiliBiliToolPro#185]
版本号：v0.1.0 linux-arm 独立包
运行环境：ubuntu-arm64

问题描述：chmod +x执行权限已给，文件信息也能查看，但执行时则找不到执行文件 No such file or directory

日志信息：
![捕获](https://user-images.githubusercontent.com/96679593/171963733-6d7e1f16-b0e3-453e-8c78-6a5672a43b7e.PNG)

**Comment by RayWangQvQ** [comment]
`chmod 777`试试

**Comment by 1772440725** [comment]
> 
0.2.2同样遇到该问题
