### ISSUE TITLE
【其他】退出账号后cookie过期
我使用腾讯云函数添加多个cookie，但是只有在浏览器登录了的账号cookie是有用的，之前退出的就过期了，有这个问题该怎么解决

### ISSUE THREAD

**Issue by sikishana** [RayWangQvQ/BiliBiliToolPro#186]

**Comment by catlair** [comment]
不要退出账号，退出会在b站后台清空登录状态的。你可以选择开一个匿名窗口，或者清空浏览器cookie

如图，清空以后刷新页面登录其它账号
![image](https://user-images.githubusercontent.com/44313800/171994941-259b4897-7dbd-4b69-a75d-6b9db08066c2.png)

或者新建匿名窗口，这是没有cookie的，直接登录就行

![image](https://user-images.githubusercontent.com/44313800/171994975-b9907f4b-705a-460c-a1a3-c8e7cb1d23a6.png)

**Comment by sikishana** [comment]
嗯嗯谢谢我回去了试试
