### ISSUE TITLE
【其他】使用青龙面板一直运行失败

### ISSUE THREAD

**Issue by ZTX2005** [RayWangQvQ/BiliBiliToolPro#188]
![屏幕截图 2022-06-05 185437](https://user-images.githubusercontent.com/57275588/172047237-9dcfd4fd-0c21-4605-b713-983f60b72870.png)
如图，该如何解决？

**Comment by tx1538** [comment]
bili_task_test.sh: line 17: dotnet: command not found

**Comment by hengxin007** [comment]
![3333](https://user-images.githubusercontent.com/84392511/172568456-ff2abfea-4021-41de-a83c-e5e2d244f7d3.png)

**Comment by gclm** [comment]
报错日志
```
## 开始执行... 2022-06-16 18:24:06

repo目录: /ql/repo
bili仓库目录: /ql/repo/raywangqvq_bilibilitoolpro

/home/dotnet/sdk/6.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(172,5): error MSB4018: “GenerateDepsFile”任务意外失败。 [/ql/repo/raywangqvq_bilibilitoolpro/src/Ray.BiliBiliTool.Application.Contracts/Ray.BiliBiliTool.Application.Contracts.csproj]
/home/dotnet/sdk/6.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(172,5): error MSB4018: System.IO.IOException: The process cannot access the file '/ql/repo/raywangqvq_bilibilitoolpro/src/Ray.BiliBiliTool.Application.Contracts/bin/Debug/net6.0/Ray.BiliBiliTool.Application.Contracts.deps.json' because it is being used by another process. [/ql/repo/raywangqvq_bilibilitoolpro/src/Ray.BiliBiliTool.Application.Contracts/Ray.BiliBiliTool.Application.Contracts.csproj]
/home/dotnet/sdk/6.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(172,5): error MSB4018:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Init(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize) [/ql/repo/raywangqvq_bilibilitoolpro/src/Ray.BiliBiliTool.Application.Contracts/Ray.BiliBiliTool.Application.Contracts.csproj]
/home/dotnet/sdk/6.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(172,5): error MSB4018:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize) [/ql/repo/raywangqvq_bilibilitoolpro/src/Ray.BiliBiliTool.Application.Contracts/Ray.BiliBiliTool.Application.Contracts.csproj]
/home/dotnet/sdk/6.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(172,5): error MSB4018:    at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize) [/ql/repo/raywangqvq_bilibilitoolpro/src/Ray.BiliBiliTool.Application.Contracts/Ray.BiliBiliTool.Application.Contracts.csproj]
/home/dotnet/sdk/6.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(172,5): error MSB4018:    at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize) [/ql/repo/raywangqvq_bilibilitoolpro/src/Ray.BiliBiliTool.Application.Contracts/Ray.BiliBiliTool.Application.Contracts.csproj]
/home/dotnet/sdk/6.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(172,5): error MSB4018:    at System.IO.File.Create(String path) [/ql/repo/raywangqvq_bilibilitoolpro/src/Ray.BiliBiliTool.Application.Contracts/Ray.BiliBiliTool.Application.Contracts.csproj]
/home/dotnet/sdk/6.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(172,5): error MSB4018:    at Microsoft.NET.Build.Tasks.GenerateDepsFile.WriteDepsFile(String depsFilePath) [/ql/repo/raywangqvq_bilibilitoolpro/src/Ray.BiliBiliTool.Application.Contracts/Ray.BiliBiliTool.Application.Contracts.csproj]
/home/dotnet/sdk/6.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(172,5): error MSB4018:    at Microsoft.NET.Build.Tasks.GenerateDepsFile.ExecuteCore() [/ql/repo/raywangqvq_bilibilitoolpro/src/Ray.BiliBiliTool.Application.Contracts/Ray.BiliBiliTool.Application.Contracts.csproj]
/home/dotnet/sdk/6.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(172,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute() [/ql/repo/raywangqvq_bilibilitoolpro/src/Ray.BiliBiliTool.Application.Contracts/Ray.BiliBiliTool.Application.Contracts.csproj]
/home/dotnet/sdk/6.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(172,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/ql/repo/raywangqvq_bilibilitoolpro/src/Ray.BiliBiliTool.Application.Contracts/Ray.BiliBiliTool.Application.Contracts.csproj]
/home/dotnet/sdk/6.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(172,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [/ql/repo/raywangqvq_bilibilitoolpro/src/Ray.BiliBiliTool.Application.Contracts/Ray.BiliBiliTool.Application.Contracts.csproj]
/home/dotnet/sdk/6.0.201/Microsoft.Common.CurrentVersion.targets(4631,5): warning MSB3026: 无法将“obj/Debug/net6.0/Ray.BiliBiliTool.Agent.dll”复制到“bin/Debug/net6.0/Ray.BiliBiliTool.Agent.dll”。1000 毫秒后将开始第 1 次重试。The process cannot access the file '/ql/repo/raywangqvq_bilibilitoolpro/src/Ray.BiliBiliTool.Agent/obj/Debug/net6.0/Ray.BiliBiliTool.Agent.dll' because it is being used by another process.  [/ql/repo/raywangqvq_bilibilitoolpro/src/Ray.BiliBiliTool.Agent/Ray.BiliBiliTool.Agent.csproj]

生成失败。请修复生成错误并重新运行。

## 执行结束... 2022-06-16 18:24:46 耗时 40 秒
```

**Comment by TheKing1991** [comment]
![image](https://user-images.githubusercontent.com/81273686/174525797-540e4340-9df5-4da7-91ad-92e71483729a.png)
都一样的，青龙各种问题

**Comment by x1737886903** [comment]
请问如何解决，我的玩客云arm框架的

**Comment by AITNR** [comment]
> ![3333](https://user-images.githubusercontent.com/84392511/172568456-ff2abfea-4021-41de-a83c-e5e2d244f7d3.png)
我也是这样，你解决了吗？

**Comment by 1332186865** [comment]
## 开始执行... 2022-08-20 08:00:00

repo目录: /ql/data/repo
bili仓库目录: /ql/data/repo/RayWangQvQ_BiliBiliToolPro

MSBUILD : error MSB1009: 项目文件不存在。
开关:./src/Ray.BiliBiliTool.Console

生成失败。请修复生成错误并重新运行。

## 执行结束... 2022-08-20 08:00:01 耗时 1 秒

我也是这样，不知道原因

**Comment by RayWangQvQ** [comment]
> 报错日志
> 
> ```
> ## 开始执行... 2022-06-16 18:24:06
> 
> repo目录: /ql/repo
> bili仓库目录: /ql/repo/raywangqvq_bilibilitoolpro
> 
> /home/dotnet/sdk/6.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(172,5): error MSB4018: “GenerateDepsFile”任务意外失败。 [/ql/repo/raywangqvq_bilibilitoolpro/src/Ray.BiliBiliTool.Application.Contracts/Ray.BiliBiliTool.Application.Contracts.csproj]
> /home/dotnet/sdk/6.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(172,5): error MSB4018: System.IO.IOException: The process cannot access the file '/ql/repo/raywangqvq_bilibilitoolpro/src/Ray.BiliBiliTool.Application.Contracts/bin/Debug/net6.0/Ray.BiliBiliTool.Application.Contracts.deps.json' because it is being used by another process. [/ql/repo/raywangqvq_bilibilitoolpro/src/Ray.BiliBiliTool.Application.Contracts/Ray.BiliBiliTool.Application.Contracts.csproj]
> /home/dotnet/sdk/6.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(172,5): error MSB4018:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Init(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize) [/ql/repo/raywangqvq_bilibilitoolpro/src/Ray.BiliBiliTool.Application.Contracts/Ray.BiliBiliTool.Application.Contracts.csproj]
> /home/dotnet/sdk/6.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(172,5): error MSB4018:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize) [/ql/repo/raywangqvq_bilibilitoolpro/src/Ray.BiliBiliTool.Application.Contracts/Ray.BiliBiliTool.Application.Contracts.csproj]
> /home/dotnet/sdk/6.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(172,5): error MSB4018:    at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize) [/ql/repo/raywangqvq_bilibilitoolpro/src/Ray.BiliBiliTool.Application.Contracts/Ray.BiliBiliTool.Application.Contracts.csproj]
> /home/dotnet/sdk/6.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(172,5): error MSB4018:    at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize) [/ql/repo/raywangqvq_bilibilitoolpro/src/Ray.BiliBiliTool.Application.Contracts/Ray.BiliBiliTool.Application.Contracts.csproj]
> /home/dotnet/sdk/6.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(172,5): error MSB4018:    at System.IO.File.Create(String path) [/ql/repo/raywangqvq_bilibilitoolpro/src/Ray.BiliBiliTool.Application.Contracts/Ray.BiliBiliTool.Application.Contracts.csproj]
> /home/dotnet/sdk/6.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(172,5): error MSB4018:    at Microsoft.NET.Build.Tasks.GenerateDepsFile.WriteDepsFile(String depsFilePath) [/ql/repo/raywangqvq_bilibilitoolpro/src/Ray.BiliBiliTool.Application.Contracts/Ray.BiliBiliTool.Application.Contracts.csproj]
> /home/dotnet/sdk/6.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(172,5): error MSB4018:    at Microsoft.NET.Build.Tasks.GenerateDepsFile.ExecuteCore() [/ql/repo/raywangqvq_bilibilitoolpro/src/Ray.BiliBiliTool.Application.Contracts/Ray.BiliBiliTool.Application.Contracts.csproj]
> /home/dotnet/sdk/6.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(172,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute() [/ql/repo/raywangqvq_bilibilitoolpro/src/Ray.BiliBiliTool.Application.Contracts/Ray.BiliBiliTool.Application.Contracts.csproj]
> /home/dotnet/sdk/6.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(172,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/ql/repo/raywangqvq_bilibilitoolpro/src/Ray.BiliBiliTool.Application.Contracts/Ray.BiliBiliTool.Application.Contracts.csproj]
> /home/dotnet/sdk/6.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.Sdk.targets(172,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [/ql/repo/raywangqvq_bilibilitoolpro/src/Ray.BiliBiliTool.Application.Contracts/Ray.BiliBiliTool.Application.Contracts.csproj]
> /home/dotnet/sdk/6.0.201/Microsoft.Common.CurrentVersion.targets(4631,5): warning MSB3026: 无法将“obj/Debug/net6.0/Ray.BiliBiliTool.Agent.dll”复制到“bin/Debug/net6.0/Ray.BiliBiliTool.Agent.dll”。1000 毫秒后将开始第 1 次重试。The process cannot access the file '/ql/repo/raywangqvq_bilibilitoolpro/src/Ray.BiliBiliTool.Agent/obj/Debug/net6.0/Ray.BiliBiliTool.Agent.dll' because it is being used by another process.  [/ql/repo/raywangqvq_bilibilitoolpro/src/Ray.BiliBiliTool.Agent/Ray.BiliBiliTool.Agent.csproj]
> 
> 生成失败。请修复生成错误并重新运行。
> 
> ## 执行结束... 2022-06-16 18:24:46 耗时 40 秒
> ```

文件占用，把repo下的bilibili仓库文件删了再重新拉库试试
