### ISSUE TITLE
青龙运行从6月18号开始就不好使了

### ISSUE THREAD

**Issue by TheKing1991** [RayWangQvQ/BiliBiliToolPro#195]
如题

**Comment by TheKing1991** [comment]
17号还好好的了呢。

**Comment by naiveclub** [comment]
我是用docker运行的，前几天cookie失效之后就重新抓了下，结果更新为抓的cookie后一直出错，pushplus推送  “显示登录异常，请检查cookie是否错误或者过期”显示登录异常，请检查cookie是否错误或者过期”，是官方作出限制了？

**Comment by Night-stars-1** [comment]
我今天运行的没有问题
cookie是很久之前的
![IMG_20220620_122003](https://user-images.githubusercontent.com/99261160/174524663-1f6da496-7b2f-460c-9145-3ae6d88ce8aa.jpg)

**Comment by TheKing1991** [comment]
![image](https://user-images.githubusercontent.com/81273686/174525176-202d5559-eb15-4a3b-a8c4-910fdea2dded.png)
我现实这个。。。

**Comment by TheKing1991** [comment]
不知道啥情况。。。

**Comment by TheKing1991** [comment]
![image](https://user-images.githubusercontent.com/81273686/174525595-16f30d85-3652-4303-ae24-b4c368864c76.png)
应该是库出问题了

**Comment by TheKing1991** [comment]
![image](https://user-images.githubusercontent.com/81273686/174528940-fc24ad7a-2038-4887-a772-9dc8ffab0be1.png)
docker也有问题。。。。

**Comment by naiveclub** [comment]
> ![image](https://user-images.githubusercontent.com/81273686/174528940-fc24ad7a-2038-4887-a772-9dc8ffab0be1.png) docker也有问题。。。。

我刚刚把容器删除重建之后又可以了

**Comment by TheKing1991** [comment]
> 

这。。。。

**Comment by TheKing1991** [comment]
apt-get update && apt-get upgrade -y 一把梭哈就好了

**Comment by kreva11** [comment]
青龙转helloworld试试：https://supermanito.github.io/Helloworld/#/README?id=helloworld

**Comment by tx1538** [comment]
我是一只青龙就用不了。。## 开始执行... 2022-06-21 16:18:34

repo目录: /ql/data/repo
bili仓库目录: /ql/data/repo/raywangqvq_bilibilitoolpro

bili_task_daily.sh: line 17: dotnet: command not found

## 执行结束... 2022-06-21 16:18:34 耗时 0 秒

**Comment by RayWangQvQ** [comment]
青龙可以跑的

**Comment by TheKing1991** [comment]
apt update &amp;&amp; apt upgrade -y

一把梭哈就好了




发自我的iPhone


------------------ 原始邮件 ------------------
发件人: tx1538 ***@***.***&gt;
发送时间: 2022年6月21日 16:18
收件人: RayWangQvQ/BiliBiliToolPro ***@***.***&gt;
抄送: Mr.Wang ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [RayWangQvQ/BiliBiliToolPro] 青龙运行从6月18号开始就不好使了 (Issue #195)





 
我是一只青龙就用不了。。## 开始执行... 2022-06-21 16:18:34
 
repo目录: /ql/data/repo
 bili仓库目录: /ql/data/repo/raywangqvq_bilibilitoolpro
 
bili_task_daily.sh: line 17: dotnet: command not found
 
执行结束... 2022-06-21 16:18:34 耗时 0 秒
