### ISSUE TITLE
【建议】新增Helloworld面板支持

### ISSUE THREAD

**Issue by kreva11** [RayWangQvQ/BiliBiliToolPro#198]
青龙老是抽风的可以试试这个，功能一样的：https://supermanito.github.io/Helloworld/#/README?id=helloworld

**Comment by RayWangQvQ** [comment]
没找到其开源地址，知道朋友麻烦帮忙贴一下

**Comment by kreva11** [comment]
@RayWangQvQ sorry，忘记补充这是闭源项目，可以无视了

**Comment by RayWangQvQ** [comment]
> @RayWangQvQ sorry，忘记补充这是闭源项目，可以无视了

ok，那先观望下吧，后面有需求使用时再考虑集成吧
