### ISSUE TITLE
【其他】大佬有人在某社区上搬取你的资源并且标明原创

### ISSUE THREAD

**Issue by issuesd** [RayWangQvQ/BiliBiliToolPro#20]
希望您知道一下
![Uploading IMG_20220227_115416.jpg…]()

**Comment by issuesd** [comment]
http://bbs.huluxia.com/wap/thread/258031.html?para=37Hftd%2B537Dftt%2Bx37Hfsd%2B33p%2Ffst%2B137jfsN%2Bz37E%3D&product=tool
这是链接，我在试试上传图片
![IMG_20220227_181610](https://user-images.githubusercontent.com/66192842/155878409-9371e908-f1ce-4533-91ba-fd2eec516cba.jpg)

**Comment by issuesd** [comment]
这是可以牟利的，通过奖励货币可以兑换钱

**Comment by vision820** [comment]
居然是葫芦侠

**Comment by HarryXin71** [comment]
葫芦侠有个叫长川的也是这样,但是不说自己原创,直说要搬运需要他的许可.东西一模一样.也就骗骗小白,上github都懂,我帮他贴了github网站的库,然后长川就不回帖了.
