### ISSUE TITLE
【其他】docker的crontab时区问题

### ISSUE THREAD

**Issue by windskyxb** [RayWangQvQ/BiliBiliToolPro#200]
请问在docker的my_crontab文件中所使用的crontab表达式使用的是哪个时区？

**Comment by catlair** [comment]
你进入docker运行一下`date`命令就知道了

**Comment by hecarli555** [comment]
> 你进入docker运行一下`date`命令就知道了

请问大佬，群晖的docker的安装指令是怎么写的？有没有模板？
