### ISSUE TITLE
cron表达式书写错误（已解决）

### ISSUE THREAD

**Issue by ddyagoo** [RayWangQvQ/BiliBiliToolPro#201]
[错误页面](https://github.com/RayWangQvQ/BiliBiliToolPro/blob/main/tencentScf/README.md#313-%E9%80%9A%E8%BF%87-secrets-%E6%B7%BB%E5%8A%A0%E9%85%8D%E7%BD%AE)其中Ⅱ.填写触发器信息

```
触发方式：定时触发
定时任务名称：DailyTask
触发周期：自定义触发周期
Cron表达式：自己根据需求指定，10 15 * * * 表示每天15点10分运行，不会的可以做下搜索工作，规则很简单
附加信息：是
信息内容：Daily
立即启用：勾选启用 填完后点击提交按钮提交，即可完成。如下图：
```
_10 15 * * *_ 应该是指每小时15分10秒执行一次吧？

**Comment by catlair** [comment]
没有错，5位的corn不支持秒
每小时15分是 `* 15 * * *`

**Comment by catlair** [comment]
没有问题，这是5位的没有秒级。参考官方文档https://cloud.tencent.com/document/product/583/9708#cron-.E8.A1.A8.E8.BE.BE.E5.BC.8F.E8.AF.AD.E6.B3.95.E4.B8.80.EF.BC.88.E6.8E.A8.E8.8D.90.EF.BC.89
