### ISSUE TITLE
【建议】大会员的大积分任务什么时候会支持呢

### ISSUE THREAD

**Issue by FlechazoPh** [RayWangQvQ/BiliBiliToolPro#204]
- 建议内容：
一个月做满10000积分，6000积分可以换一个月大会员，感觉还是挺不错的

- 活动路径（APP iOS）：tab我的 -> 我的大会员 -> 大积分 -> 做任务得大积分

- 活动页面截图：

![66A38A8D-9B16-49DF-8226-4F60F4A8C303](https://user-images.githubusercontent.com/94276146/175524602-88deb0e9-c0f4-4bc6-8b65-922bd26f5e36.png)

![CA144466-AA99-4D06-B3AF-BBD084818896_1_101_o](https://user-images.githubusercontent.com/94276146/175524678-a87e3fb8-a59f-495d-9d0a-fd8da711bb0d.jpeg)

**Comment by jdhai** [comment]
这个好像支持，可以参考一下 https://btdocs.vercel.app/guide/#%E6%9B%B4%E6%96%B0

**Comment by RayWangQvQ** [comment]
抽空我来试试

**Comment by RayWangQvQ** [comment]
已于当前版本 [v0.2.0](https://github.com/RayWangQvQ/BiliBiliToolPro/releases/tag/0.2.0) 添加大会员大积分任务。

![image](https://user-images.githubusercontent.com/31154238/185180773-e7c347b4-bab3-4247-9be2-e4b15aee6e7a.png)

**Comment by KudouRan** [comment]
> 已于当前版本 [v0.2.0](https://github.com/RayWangQvQ/BiliBiliToolPro/releases/tag/0.2.0) 添加大会员大积分任务。
> 
> ![image](https://user-images.githubusercontent.com/31154238/185180773-e7c347b4-bab3-4247-9be2-e4b15aee6e7a.png)

不知道大佬完成浏览会员购没有，接口可以参考

https://github.com/catlair/BiliTools/blob/54bf79f6047d7055cb1a0aef373bfe12365cf01d/src/net/big-point.request.ts#L88-L109

```js
showDispatch('hevent_oy4b7h3epeb');
```

**Comment by 56warmers** [comment]
> 已于当前版本 [v0.2.0](https://github.com/RayWangQvQ/BiliBiliToolPro/releases/tag/0.2.0) 添加大会员大积分任务。
> 
> ![image](https://user-images.githubusercontent.com/31154238/185180773-e7c347b4-bab3-4247-9be2-e4b15aee6e7a.png)

2022.08.20 大会员大积分运行出现非法访问，其他功能正常
[23:04:22 INF] ---开始 签到 ---
[23:04:29 ERR] 签到失败，继续其他任务。失败信息:{"Code":-401,"Message":"非法访问","Data":null}

**Comment by RayWangQvQ** [comment]
自己账号试了下，没发现问题：

![image](https://user-images.githubusercontent.com/31154238/186217784-d2404393-dc76-4330-9964-a76ca4c7816a.png)

能否提供下Debug级别的详细日志信息

**Comment by leieerr** [comment]
![1](https://user-images.githubusercontent.com/106761073/186288814-cebf0f74-2d4c-4f93-b0d4-d77ecff74d62.png)
![2](https://user-images.githubusercontent.com/106761073/186288834-22406a33-b561-48fd-a6f0-c792850f9eba.png)
腾讯云函数

**Comment by RayWangQvQ** [comment]
> 
> ![1](https://user-images.githubusercontent.com/106761073/186288814-cebf0f74-2d4c-4f93-b0d4-d77ecff74d62.png)
> ![2](https://user-images.githubusercontent.com/106761073/186288834-22406a33-b561-48fd-a6f0-c792850f9eba.png)
> 腾讯云函数
> 

确定cookie没问题吗？登陆信息都是空的

**Comment by leieerr** [comment]
是的，某些信息我删掉了

**Comment by leieerr** [comment]
这个问题的原因是，没有大会员，是无法完成相关任务的
建议 任务开始时候检测并打印会员状态

**Comment by Xuhuanhua** [comment]
建议类似每日任务的操作，不是大会员自动跳过任务

**Comment by RayWangQvQ** [comment]
Done with #259
