### ISSUE TITLE
【建议】建议增加逻辑到LV6后则不再自动投币

### ISSUE THREAD

**Issue by Air433up** [RayWangQvQ/BiliBiliToolPro#209]
建议增加逻辑到LV6后则不再自动投币

**Comment by layui0320** [comment]
https://github.com/RayWangQvQ/BiliBiliToolPro/pull/237#issue-1322041831

**Comment by RayWangQvQ** [comment]
是不是改下配置就行了？

这样写死在代码里了，万一有人LV6之后就是还想继续投币咋搞

**Comment by RayWangQvQ** [comment]
已新增配置，Lv6后开启白嫖模式。
