### ISSUE TITLE
serverless怎么添加多个环境变量

### ISSUE THREAD

**Issue by sundys** [RayWangQvQ/BiliBiliToolPro#21]
后面自己加了几行环境变量参数，就部署不成功，想要在部署时自动加几个变量,求大佬指点迷津。谢谢！

**Comment by Alaskawolves** [comment]
一样。只添加cookie就行，加了其他几个变量就部署不到云函数那里

**Comment by catlair** [comment]
![image](https://user-images.githubusercontent.com/44313800/156384161-23dc623e-62d7-44a4-abcc-6c6ebc1e0004.png)

你的yaml格式是错的

```bash
  environment:
    variables: # 根据自己的需要修改
      Ray_BiliBiliCookies__1: 123 # cookie，必填
      xxxxxx: yyyyyy
      xxxxxxxxx: yyyyyy
      xxxxxx: yyyyyy
```

缩进必须是对等的
