### ISSUE TITLE
【建议】自动更新cookie

### ISSUE THREAD

**Issue by Streamer-stars** [RayWangQvQ/BiliBiliToolPro#211]
cookie经常会失效，手动更新很麻烦也违背了自动化的初衷，希望添加自动更新cookie的功能。
可以使用leancloud来储存cookie，免费好用。

**Comment by KudouRan** [comment]
第一，也不知道什么时候作者会更新。第二，云函数还需要引进额外数据库，增加了配置难度。

理论上cookie能保持很久，可以参考这里试试 https://btdocs.vercel.app/config/get_value.html (忽略chrome 编码那里，项目不同)

**Comment by 9k001** [comment]
> 第一，也不知道什么时候作者会更新。第二，云函数还需要引进额外数据库，增加了配置难度。
> 
> 理论上cookie能保持很久，为了避免 cookie 被刷新失效（例如你时常使用浏览器访问 b 站，那就不要直接复制它的 cookie，因为目前存在 cookie 自动刷新的情况，你保留的就会失效了），你应该使用隐私窗口重新登录哔站，并获取新的 cookie。

目前观察到B站的cookie会刷新，这个按照你的意思，最好是减少挂机的账号登录b站？

**Comment by catlair** [comment]
@9k001 目前最主要的原因有两个，1是账号异常被风控了，这种会可能会有站内信或者直接所有平台退出登录。2 就是我提到的浏览器会刷新cookie，解决办法我已经说了啊，你用隐私窗口获取 cookie，这样你正常使用就不会影响脚本了。


这个值存在就会刷新 cookie。

![image](https://user-images.githubusercontent.com/44313800/182182448-63f31206-24cd-416c-ace7-c3cee5bc9178.png)

**Comment by 9k001** [comment]
> @9k001 目前最主要的原因有两个，1是账号异常被风控了，这种会可能会有站内信或者直接所有平台退出登录。2 就是我提到的浏览器会刷新cookie，解决办法我已经说了啊，你用隐私窗口获取 cookie，这样你正常使用就不会影响脚本了。
> 
> 登录 b 站会有新的登录记录，和旧的互不影响，你别把正常使用时的 cookie 挂脚本就行了。
> 
> 这个值存在就会刷新 cookie，你每次进入b站主页他都会尝试刷新。
> 
> ![image](https://user-images.githubusercontent.com/44313800/182182448-63f31206-24cd-416c-ace7-c3cee5bc9178.png)
感谢回复。
按照你的回复，根据我的理解，挂机的条件应有如下几个重点：
1. 使用正常可以登录的，没有被风控的账号。
2. 最好在一个账号中，登录两次。1). 正常使用浏览器登录，这个做正常浏览用；2). 使用隐私模式登录，这个做挂机使用。
上述问题中还有一个点没有确认，
即 重点 2 中，两次登录。应该是不会出现互相挤掉账号的情况。
不知道 我的理解是否正确。再次感谢

**Comment by catlair** [comment]
@9k001 两次登录不存在挤的。之所以要用隐私窗口见#186

**Comment by 9k001** [comment]
> @9k001 两次登录不存在挤的。之所以要用隐私窗口见#186

感谢，另我按照你的开发者模式找寻 ac_time_value，发现没有该值的存在,可能是不同账号之间的区别。

**Comment by catlair** [comment]
> > @9k001 两次登录不存在挤的。之所以要用隐私窗口见#186
> 
> 感谢，另我按照你的开发者模式找寻 ac_time_value，发现没有该值的存在,可能是不同账号之间的区别。

如果位置正确，可能原因是登录时间在b站改版之前，这个值是登录时获取的(类似于app的refresh token)

**Comment by RayWangQvQ** [comment]
如果非要自动更新cookie，我更倾向于把用户名、密码配进去，自动登录拿cookie。

但这样同时安全性也就降低了

**Comment by RayWangQvQ** [comment]
v0.3.0新增了扫码登录的功能，https://github.com/RayWangQvQ/BiliBiliToolPro/issues/351

这样应该能一定程度的降低你说的登录的复杂度
