### ISSUE TITLE
请问cookies过期时间是多久呢？

### ISSUE THREAD

**Issue by mythbobo** [RayWangQvQ/BiliBiliToolPro#212]
我这边隔两三天就得重新更新一下cookies,不知道这是否正常？

**Comment by KudouRan** [comment]
理论上cookie能保持很久，可以参考这里试试 https://btdocs.vercel.app/config/get_value.html (忽略chrome 编码那里，项目不同)

**Comment by mythbobo** [comment]
明白了,感谢。原来访问B站会自动刷新cookies.
