### ISSUE TITLE
6月27日之后，拉库后没有定时任务

### ISSUE THREAD

**Issue by HelperInCa** [RayWangQvQ/BiliBiliToolPro#213]
如题

**Comment by binstc** [comment]
+1

**Comment by RayWangQvQ** [comment]
啥？

**Comment by HelperInCa** [comment]
@RayWangQvQ  拉库日志如下：

## 开始执行... 2022-08-15 16:47:01

开始更新仓库：/ql/repo/RayWangQvQ_BiliBiliToolPro

Fetching origin

更新/ql/repo/RayWangQvQ_BiliBiliToolPro成功...


## 执行结束... 2022-08-15 16:47:01  耗时 0 秒

**Comment by KevinClair** [comment]
> 啥？

fork仓库之后，Actions里面没有把ci也同步过来。

**Comment by RayWangQvQ** [comment]
https://github.com/RayWangQvQ/BiliBiliToolPro/blob/main/qinglong/README.md#13-%E7%99%BB%E5%BD%95%E9%9D%92%E9%BE%99%E9%9D%A2%E6%9D%BF%E5%B9%B6%E4%BF%AE%E6%94%B9%E9%85%8D%E7%BD%AE

这步有没有做？

**Comment by KevinClair** [comment]
> https://github.com/RayWangQvQ/BiliBiliToolPro/blob/main/qinglong/README.md#13-%E7%99%BB%E5%BD%95%E9%9D%92%E9%BE%99%E9%9D%A2%E6%9D%BF%E5%B9%B6%E4%BF%AE%E6%94%B9%E9%85%8D%E7%BD%AE
> 
> 这步有没有做？

是用的Github的Actions，仓库fork之后，fork仓库里面的Actions没有bilibili-daily-task

**Comment by RayWangQvQ** [comment]
> 

目前不支持GA了，会被封号的。建议换其他方式部署。

**Comment by HelperInCa** [comment]
> > 
> 
> 目前不支持GA了，会被封号的。建议换其他方式部署。

青龙也不行吗

**Comment by zhan-zw** [comment]
同问青龙不能吗

**Comment by RayWangQvQ** [comment]
青龙可以
