### ISSUE TITLE
不好意思不会删这个issue

### ISSUE THREAD

**Issue by zhiyoua** [RayWangQvQ/BiliBiliToolPro#214]

**Comment by nibazshab** [comment]
百度搜一下不行吗？不仅不自己解决问题，还要再开一个issus来表示你不会删？

**Comment by zhiyoua** [comment]
> 百度搜一下不行吗？不仅不自己解决问题，还要再开一个issus来表示你不会删？

我一开始提的问题我解决了，但是这个issus删不掉我有啥办法。百度了人家说有一个删除的按钮，我这没没显示，只有一个结束的按钮我能咋整。
