### ISSUE TITLE
【Bug】话说你们最近天选中过么，我一周多没中过奖了

### ISSUE THREAD

**Issue by aefa6** [RayWangQvQ/BiliBiliToolPro#216]
是出bug了么，天选没中过，以前一周的时间肯定中过

**Comment by shadow6336** [comment]
酋长你好

**Comment by aefa6** [comment]
啊，不是bug么。。我挂了五个号，难道这个还会黑号之类的？

**Comment by shadow6336** [comment]
你这么多的号，怎么来的啊，你只要看到你一直在关注up主就没问题的

**Comment by nibazshab** [comment]
？天选从来就没中过，我还以为那只是个心理安慰

**Comment by Star-Seven** [comment]
中过，这玩意毕竟是僧多粥少。时间久了，关注的人多了（就算取关，有些再关注也不给。。）机会也少了

**Comment by aefa6** [comment]
我发现有问题，参与天选了，结果没关注主播，所以一直没中奖，因为条件就是关注主播

**Comment by nibazshab** [comment]
> 我发现有问题，参与天选了，结果没关注主播，所以一直没中奖，因为条件就是关注主播

会自动关注主播的

**Comment by aefa6** [comment]
@nibazshab 我猜测可能会有封禁这种操作

**Comment by djjia** [comment]
> 我发现有问题，参与天选了，结果没关注主播，所以一直没中奖，因为条件就是关注主播

最近一挂这个脚本，本地账号一段时间后就会退出登录，而且好像虽然推送已成功参与抽奖，但是没有新增关注的主播

**Comment by gujiwuqing** [comment]
> 我发现有问题，参与天选了，结果没关注主播，所以一直没中奖，因为条件就是关注主播

中了。。结果没关注主播。。
<img width="342" alt="image" src="https://user-images.githubusercontent.com/44566835/181656560-71d7f9b8-3b0f-4afc-befc-4b361945525c.png">

**Comment by aefa6** [comment]
@djjia 是的，我现在就是这个情况，然后我去app手动试了下天选，发现天选已参与，主播也关注了，然而，回到主界面去看发现没有新增这个关注，再点进直播间发现真的变回未关注状态了，我猜测可能是账号被哔哩哔哩官方封禁天选活动了

**Comment by Star-Seven** [comment]
@aefa6 好像是有这样的问题。。。我现在禁用了天选脚本。因为感觉有点不对劲。。。。。

**Comment by jizizr** [comment]
天选如果运行过于频繁会出现无法关注的情况，我大号出现这样情况之后，创建了一个小号，配置文件仅仅修改了ck，发现小号可以正常运行
