### ISSUE TITLE
【建议】添加详细最新的Github Action部署教程

### ISSUE THREAD

**Issue by Kihh** [RayWangQvQ/BiliBiliToolPro#217]
原本的Github action部署教程已经失效并老化，请添加最新版教程，GA是个公益项目相对于其他部署方式更稳定更快捷

**Comment by KudouRan** [comment]
> GA是个公益项目相对于其他部署方式更稳定更快捷

原项目就是因为滥用 Github Action 被封了，同样被封的还有一堆。不知道为啥能得出更稳定这个结论。

**Comment by Kihh** [comment]
> 原项目就是因为滥用 Github Action 被封了，同样被封的还有一堆。不知道为啥能得出更稳定这个结论。
> 
> 如果你自己创建 Github Action 那可以直接使用 Docker 啊
这涉及GA的风控机制，我账号几年了，照样能跑好几个定时任务，那些刚创的就来跑肯定封啊
