### ISSUE TITLE
【Bug】无法正常使用

### ISSUE THREAD

**Issue by qazedc-abcd** [RayWangQvQ/BiliBiliToolPro#219]
版本号：V0.1.0 依赖包（请贴出你的版本号，请确认是否已通过升级到最新版来解决当前问题？）
运行环境：Windows10教育版 21H2（请贴出运行环境，比如是Actions或docker或本地？是Win还是Linux？）

问题描述：没有复制进cookie时使用正常并有log输出，但复制进log之后就没有任何log输出，cmd最后显示如下
![image](https://user-images.githubusercontent.com/96916669/178764377-7424b16c-20f5-424f-8b25-2c13d473db09.png)
（提issue前请先确认没有其他人已提过相同的议题，请清晰的描述所您所遇到的问题。）

日志信息：没有log输出（如果可以，请贴出Debug级别的日志信息，以便更高效的确定和解决问题。）

**Comment by 589463** [comment]
+1

**Comment by qazedc-abcd** [comment]
啊，是复制cookie进去就没有log输出了

**Comment by RayWangQvQ** [comment]
不贴log出来，盖茨来了也解决不了😂
