### ISSUE TITLE
【Bug】tgbot推送不正常

### ISSUE THREAD

**Issue by xkcxkc** [RayWangQvQ/BiliBiliToolPro#221]
版本号：v 0.1.1
运行环境：docker

问题描述：tgbot收不到推送

日志信息：Exception while emitting periodic batch from Ray.Serilog.Sinks.TelegramBatched.TelegramBatchedSink: The request was canceled due to the configured HttpClient.Timeout of 5 seconds elapsing.

**Comment by RayWangQvQ** [comment]
网络问题，后面会考虑加个代理的配置

**Comment by RayWangQvQ** [comment]
done #65
