### ISSUE TITLE
【Bug】腾讯云函数 pushplus无法推送topic群组消息

### ISSUE THREAD

**Issue by TdlicheZ** [RayWangQvQ/BiliBiliToolPro#222]
版本号：0.1.1
运行环境：腾讯SCF，win

问题描述：pushplus可以推送token，但无法推送topic消息，无论是在环境变量中使用Ray_Serilog__WriteTo__9__Args__topic和Ray_Serilog__WriteTo__9__Args__channel配置，还是在appsettings.json中手动添加wechat和群组编码，都无法正常推送

日志信息：

[04:30:18 INF] ·开始推送·Daily任务·

[04:30:18 INF] 运行结束

函数结束

=>返回 {"key1":"test value 1","key2":"test value 2"}

=>推送函数处理结果

Response RequestId: 81858d15-cca0-400c-a5f8-7910245a17a4 RetMsg: {"key1":"test value 1","key2":"test value 2"}

END RequestId: 81858d15-cca0-400c-a5f8-7910245a17a4

Report RequestId: 81858d15-cca0-400c-a5f8-7910245a17a4 Duration: 1348ms Memory: 128MB MemUsage: 24.16MB

=>长轮询获取事件

**Comment by RayWangQvQ** [comment]
腾讯云函数开始收费了，可以考虑迁移下了
