### ISSUE TITLE
【建议】增加投币对象限制在SupportUP

### ISSUE THREAD

**Issue by mentlesoul** [RayWangQvQ/BiliBiliToolPro#225]
将投币对象限制在SupportUPID栏离，而不是看排行榜什么的

**Comment by layui0320** [comment]
[优先选择支持的up主Id集合](https://github.com/RayWangQvQ/BiliBiliToolPro/blob/main/docs/configuration.md#335-%E4%BC%98%E5%85%88%E9%80%89%E6%8B%A9%E6%94%AF%E6%8C%81%E7%9A%84up%E4%B8%BBid%E9%9B%86%E5%90%88)

**Comment by RayWangQvQ** [comment]
排行榜是最后的选择，配置——>关注——>排行榜

**Comment by RayWangQvQ** [comment]
排行榜是最后的选择，配置——>关注——>排行榜

**Comment by mentlesoul** [comment]
事实上我填的配置里面up总共几百个视频，但是投币五个只有一个在里面，剩下都是排行榜投币，很奇怪
