### ISSUE TITLE
青龙面板无法安装dotnet

### ISSUE THREAD

**Issue by 2451965602** [RayWangQvQ/BiliBiliToolPro#227]
执行 docker exec -it qinglong bash /ql/data/config/extra.sh后报错
[
![](https://pan.yxyz.ml/api/raw/?path=/C6FA6C51-B4EE-48C5-AB37-8E5C51F685B1.png)
](url)

**Comment by x1737886903** [comment]
2022-08-03 11:52:32 (4.72 MB/s) - 'dotnet-sdk.tar.gz' saved [172539795/172539795]

ln: failed to create symbolic link '/usr/local/bin/dotnet': File exists
Error relocating /usr/local/bin/dotnet: __time64: symbol not found
Error relocating /usr/local/bin/dotnet: __gmtime64: symbol not found
Error relocating /usr/local/bin/dotnet: __fstat_time64: symbol not found
Error relocating /usr/local/bin/dotnet: __dlsym_time64: symbol not found
Error relocating /usr/local/bin/dotnet: __fstatat_time64: symbol not found
我这边报错是这个
