### ISSUE TITLE
请问群晖的docker安装指令是怎么写的？有例子作业抄一下么？

### ISSUE THREAD

**Issue by hecarli555** [RayWangQvQ/BiliBiliToolPro#231]
请问群晖的docker安装指令是怎么写的？有例子作业抄一下么？谢谢大佬

**Comment by franco1013** [comment]
我也是群晖的，我是直接在群晖的docker页面里注册表那搜索BiliBiliToolPro，安装，再在高级设置里设环境变量运行就行了

**Comment by hecarli555** [comment]
额。。。。这种方法很久没用了。。。我都是习惯抄作业ssh直接用指令，这种方便简单。。。不知道BiliBiliToolPro有没有这种的呢？





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RayWangQvQ/BiliBiliToolPro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月29日(星期五) 下午4:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RayWangQvQ/BiliBiliToolPro] 请问群晖的docker安装指令是怎么写的？有例子作业抄一下么？ (Issue #231)





 
我也是群晖的，我是直接在群晖的docker页面里注册表那搜索BiliBiliToolPro，安装，再在高级设置里设环境变量运行就行了

**Comment by franco1013** [comment]
我记得是有的，作者介绍页面也是用ssh的。（我主要是连群晖sshdocker就是设置不起来，就还是直接用页面设置了。）没搞懂过代码的docker设置

**Comment by hecarli555** [comment]
我看他github上没找到代码模板。。。dockerhub上也没找到。。。。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RayWangQvQ/BiliBiliToolPro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月29日(星期五) 下午5:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RayWangQvQ/BiliBiliToolPro] 请问群晖的docker安装指令是怎么写的？有例子作业抄一下么？ (Issue #231)





 
我记得是有的，作者介绍页面也是用ssh的。（我主要是连群晖sshdocker就是设置不起来，就还是直接用页面设置了。）没搞懂过代码的docker设置

**Comment by layui0320** [comment]
其实很简单的，根据docker-compose.yml来修改启动。自行参考。
所有的环境变量需要双引号，例：-e Ray_BiliBiliCookies__1="cookie"
不懂后续再回复。

> 每次容器启动会去跑一遍 Test 任务，用于测试 Cookie 。其他任务由设定的cron来指定定时触发，如需修改定时运行时间，请修改my_crontab中的cron表达式，然后再次执行启动容器命令。

```
docker run -d --restart always --name="bilibili_tool_pro" \
    -e Ray_BiliBiliCookies__1="cookie" \
    -e Ray_Security__RandomSleepMaxMin="0" \
    -e Ray_Security__UserAgent="Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36" \
    -v /root/test/logs:/app/Logs \
    -v /root/test/my_crontab:/app/custom_crontab \
    zai7lou/bilibili_tool_pro
```

**Comment by hecarli555** [comment]
多个ck之间是用英文逗号分隔么？





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RayWangQvQ/BiliBiliToolPro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月30日(星期六) 下午3:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RayWangQvQ/BiliBiliToolPro] 请问群晖的docker安装指令是怎么写的？有例子作业抄一下么？ (Issue #231)





 
其实很简单的，根据docker-compose.yml来修改启动。自行参考。
 所有的环境变量需要双引号，例：-e Ray_BiliBiliCookies__1="cookie"
 不懂后续再回复。
  
每次容器启动会去跑一遍 Test 任务，用于测试 Cookie 。其他任务由设定的cron来指定定时触发，如需修改定时运行时间，请修改my_crontab中的cron表达式，然后再次执行启动容器命令。
  docker run -d --restart always --name="bilibili_tool_pro" \     -e Ray_BiliBiliCookies__1="cookie" \     -e Ray_Security__RandomSleepMaxMin="0" \     -e Ray_Security__UserAgent="Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36" \     -v /root/test/logs:/app/Logs \     -v /root/test/my_crontab:/app/custom_crontab \     zai7lou/bilibili_tool_pro

**Comment by layui0320** [comment]
多账号应该是这个，一个参数一行代码
```
-e Ray_BiliBiliCookies__1="cookie" \
-e Ray_BiliBiliCookies__2="cookie" \
```

**Comment by hecarli555** [comment]
好吧，谢谢大佬解答，我先去试试，有不懂再来麻烦大佬，哈哈哈哈哈，感谢





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RayWangQvQ/BiliBiliToolPro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月30日(星期六) 下午3:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RayWangQvQ/BiliBiliToolPro] 请问群晖的docker安装指令是怎么写的？有例子作业抄一下么？ (Issue #231)





 
多账号应该是这个，一个参数一行代码
 -e Ray_BiliBiliCookies__1="cookie" \ -e Ray_BiliBiliCookies__2="cookie" \

**Comment by hecarli555** [comment]
我认真再看了下作者原文，CK及产量参数应该写到docker-compose.yml文件里才对，那么问题来了…安装指令docker run应该怎么映射文件夹呢？直接映射config么…？然后把docker-compose.yml这个文件放到config里？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: layui0320 ***@***.***&gt;
发送时间: 2022年7月30日 15:54
收件人: RayWangQvQ/BiliBiliToolPro ***@***.***&gt;
抄送: hecarli555 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [RayWangQvQ/BiliBiliToolPro] 请问群晖的docker安装指令是怎么写的？有例子作业抄一下么？ (Issue #231)






其实很简单的，根据docker-compose.yml来修改启动。自行参考。
所有的环境变量需要双引号，例：-e Ray_BiliBiliCookies__1="cookie"
不懂后续再回复。

每次容器启动会去跑一遍 Test 任务，用于测试 Cookie 。其他任务由设定的cron来指定定时触发，如需修改定时运行时间，请修改my_crontab中的cron表达式，然后再次执行启动容器命令。
docker run -d --restart always --name="bilibili_tool_pro" \    -e Ray_BiliBiliCookies__1="cookie" \    -e Ray_Security__RandomSleepMaxMin="0" \    -e Ray_Security__UserAgent="Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36" \    -v /root/test/logs:/app/Logs \    -v /root/test/my_crontab:/app/custom_crontab \    zai7lou/bilibili_tool_pro

**Comment by layui0320** [comment]
是的没错。容器就是这样子，除非作者改程序

发自我的iPhone

**Comment by RayWangQvQ** [comment]
> 那用-e来添加产量…那容器建立起来后，我想再添加CK那岂不是得重建容器，重写-e来增加CK？😂 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: layui0320 ***@***.***&gt; 发送时间: 2022年8月3日 19:41 收件人: RayWangQvQ/BiliBiliToolPro ***@***.***&gt; 抄送: hecarli555 ***@***.***&gt;, Author ***@***.***&gt; 主题: Re: [RayWangQvQ/BiliBiliToolPro] 请问群晖的docker安装指令是怎么写的？有例子作业抄一下么？ (Issue #231) 作者只写docker compose启动方式，因为使用docker run的启动方式的话，参数命令太长了。即两者启动方式不相关。 你想用docker compose方式启动容器，就修改docker-compose.yml的文件参数，按作者教程操作就行。 docker run启动方式就是上面的命令，需要其他配置增加-e并填写相应的环境参数就行。 最后是docker映射目录，冒号前面是宿主机的目录，冒号后面是容器的目录路径不用动。 -v /root/test/logs:/app/Logs \-v /root/test/my_crontab:/app/custom_crontab \ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

也可以用-v把appSetting.json挂在出来，后面改配置直接编辑appSetting.json就行了

**Comment by RayWangQvQ** [comment]
稍后我来更新下文档

**Comment by hecarli555** [comment]
希望能出个群晖nas的docker的教程，谢谢大佬了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 在7楼 ***@***.***&gt;
发送时间: 2022年8月18日 11:38
收件人: RayWangQvQ/BiliBiliToolPro ***@***.***&gt;
抄送: hecarli555 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [RayWangQvQ/BiliBiliToolPro] 请问群晖的docker安装指令是怎么写的？有例子作业抄一下么？ (Issue #231)






稍后我来更新下文档

**Comment by layui0320** [comment]
映射appSetting.json是好主意，启动容器就不用带那么多的参数了。

**Comment by hecarli555** [comment]
> 稍后我来更新下文档

大佬能给个群晖docker的指令安装模板么？谢谢了

**Comment by layui0320** [comment]
我已经更新Docker的部署文档，已提交PR。

**Comment by hecarli555** [comment]
//Cookie集合，取自浏览器，必填   "BiliBiliCookies": [ //Cookie字符串集合，登录bilibili后F12获取，形如"_uuid=abcd; buvid3=1234; sid=abc123"     ""   ],请问大佬这个多账号ck格式应该怎么填。。。？ "BiliBiliCookies": "xxx","yyy"这样？





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RayWangQvQ/BiliBiliToolPro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月21日(星期天) 下午4:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RayWangQvQ/BiliBiliToolPro] 请问群晖的docker安装指令是怎么写的？有例子作业抄一下么？ (Issue #231)





 
我已经更新Docker的部署文档，已提交PR。

**Comment by layui0320** [comment]
应该是这样吧:
```
 "BiliBiliCookies": [
    "cookies1",
    "cookies2",
    "cookies3"
  ],
```

**Comment by hecarli555** [comment]
学习了，在写配置了





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RayWangQvQ/BiliBiliToolPro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月21日(星期天) 下午5:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RayWangQvQ/BiliBiliToolPro] 请问群晖的docker安装指令是怎么写的？有例子作业抄一下么？ (Issue #231)





 
应该是这样吧:
  "BiliBiliCookies": [     "cookies1",     "cookies2",     "cookies3"   ],

**Comment by hecarli555** [comment]
又遇到问题了呃，，，my_crontab这个是什么格式的文件？？？如何把cron写进去。。。。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RayWangQvQ/BiliBiliToolPro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月21日(星期天) 下午5:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RayWangQvQ/BiliBiliToolPro] 请问群晖的docker安装指令是怎么写的？有例子作业抄一下么？ (Issue #231)





 
应该是这样吧:
  "BiliBiliCookies": [     "cookies1",     "cookies2",     "cookies3"   ],

**Comment by layui0320** [comment]
默认15点执行签到任务，默认22点执行直播天选时刻。第一个是分钟，第二个是小时。另外三个不用看。
```
0 15 * * * dotnet /app/Ray.BiliBiliTool.Console.dll --runTasks=Daily >> /var/log/cron.log
0 22 * * * dotnet /app/Ray.BiliBiliTool.Console.dll --runTasks=LiveLottery >> /var/log/cron.log
```

**Comment by hecarli555** [comment]
文件已经丢进去了。。。容器启动不起来。。。提示docker api失败，看日志提示cp: -r not specified; omitting directory '/app/custom_crontab'


大佬方便加微信，向日葵远程指导一下么？





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RayWangQvQ/BiliBiliToolPro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月21日(星期天) 晚上6:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RayWangQvQ/BiliBiliToolPro] 请问群晖的docker安装指令是怎么写的？有例子作业抄一下么？ (Issue #231)





 
默认15点执行签到任务，默认22点执行直播天选时刻。第一个是分钟，第二个是小时。另外三个不用看。
 0 15 * * * dotnet /app/Ray.BiliBiliTool.Console.dll --runTasks=Daily &gt;&gt; /var/log/cron.log 0 22 * * * dotnet /app/Ray.BiliBiliTool.Console.dll --runTasks=LiveLottery &gt;&gt; /var/log/cron.log

**Comment by layui0320** [comment]
v：muyou199903

**Comment by RayWangQvQ** [comment]
已更新文档：https://github.com/RayWangQvQ/BiliBiliToolPro/blob/main/docker/README.md#3-%E6%96%B9%E5%BC%8F%E4%BA%8Cdocker%E6%8C%87%E4%BB%A4

**Comment by hecarli555** [comment]
感觉分支里那个把appsettings映射出来那个命令要好些，改ck方便





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RayWangQvQ/BiliBiliToolPro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月25日(星期四) 晚上11:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RayWangQvQ/BiliBiliToolPro] 请问群晖的docker安装指令是怎么写的？有例子作业抄一下么？ (Issue #231)





 
已更新文档：https://github.com/RayWangQvQ/BiliBiliToolPro/blob/main/docker/README.md#3-%E6%96%B9%E5%BC%8F%E4%BA%8Cdocker%E6%8C%87%E4%BB%A4

**Comment by RayWangQvQ** [comment]
嗯，docker compose是把`appsettings.json`挂载出来的。

**能用docker compose的推荐全用docker compose，实在用不了的再考虑docker run。**

docker run想挂载`appsettings.json`的，需要自己先wget下载`appsettings.json`到宿主机，然后再-v挂载，逻辑跟compose一样的。

**Comment by hecarli555** [comment]
好的，感谢大佬





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RayWangQvQ/BiliBiliToolPro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月25日(星期四) 晚上11:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RayWangQvQ/BiliBiliToolPro] 请问群晖的docker安装指令是怎么写的？有例子作业抄一下么？ (Issue #231)





 
嗯，docker compose是把appsettings.json挂载出来的。
 
能用docker compose的推荐全用docker compose，实在用不了的再考虑docker run。
 
docker run想挂载appsettings.json的，需要自己先wget下载appsettings.json到宿主机，然后再-v挂载，逻辑跟compose一样的。

**Comment by hecarli555** [comment]
好的谢谢大佬，我之前有在用bilibili助手的项目，它CK是写在config里面的，算是比较方便，但是一个容器只能跑一个CK，而且能跑的任务没这个多，所以才想试试这个，btw，大佬解释得很清楚了非常棒👍🏻



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: layui0320 ***@***.***&gt;
发送时间: 2022年8月3日 19:54
收件人: RayWangQvQ/BiliBiliToolPro ***@***.***&gt;
抄送: hecarli555 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [RayWangQvQ/BiliBiliToolPro] 请问群晖的docker安装指令是怎么写的？有例子作业抄一下么？ (Issue #231)





是的没错。容器就是这样子，除非作者改程序

发自我的iPhone

&gt; 在 2022年8月3日，19:52，hecarli555 ***@***.***&gt; 写道：
&gt; 
&gt; ﻿
&gt; 那用-e来添加产量…那容器建立起来后，我想再添加CK那岂不是得重建容器，重写-e来增加CK？😂 
&gt; 
&gt; 
&gt; 
&gt; 发自我的iPhone 
&gt; 
&gt; 
&gt; ------------------ 原始邮件 ------------------ 
&gt; 发件人: layui0320 ***@***.***&amp;gt; 
&gt; 发送时间: 2022年8月3日 19:41 
&gt; 收件人: RayWangQvQ/BiliBiliToolPro ***@***.***&amp;gt; 
&gt; 抄送: hecarli555 ***@***.***&amp;gt;, Author ***@***.***&amp;gt; 
&gt; 主题: Re: [RayWangQvQ/BiliBiliToolPro] 请问群晖的docker安装指令是怎么写的？有例子作业抄一下么？ (Issue #231) 
&gt; 
&gt; 
&gt; 
&gt; 
&gt; 
&gt; 
&gt; 作者只写docker compose启动方式，因为使用docker run的启动方式的话，参数命令太长了。即两者启动方式不相关。 
&gt; 
&gt; 你想用docker compose方式启动容器，就修改docker-compose.yml的文件参数，按作者教程操作就行。 
&gt; 
&gt; docker run启动方式就是上面的命令，需要其他配置增加-e并填写相应的环境参数就行。 
&gt; 最后是docker映射目录，冒号前面是宿主机的目录，冒号后面是容器的目录路径不用动。 
&gt; -v /root/test/logs:/app/Logs \-v /root/test/my_crontab:/app/custom_crontab \ 
&gt; — 
&gt; Reply to this email directly, view it on GitHub, or unsubscribe. 
&gt; You are receiving this because you authored the thread.Message ID: ***@***.***&amp;gt;
&gt; —
&gt; Reply to this email directly, view it on GitHub, or unsubscribe.
&gt; You are receiving this because you commented.
