### ISSUE TITLE
【建议】自定义使用Bark API推送

### ISSUE THREAD

**Issue by layui0320** [RayWangQvQ/BiliBiliToolPro#233]
使用方法：
添加参数`Ray_Serilog__WriteTo__8__Args__api`的值为`https://api.day.app/push`

添加参数`Ray_Serilog__WriteTo__8__Args__bodyJsonTemplate`值为`{"device_key":"keyQAQ","title":"BiliBili\u7B7E\u5230","body":#msg#}` 其中`keyQAQ`更改自己的Bark的Key即可使用。

Bark是一个iOS系统优秀的消息推送软件，Github项目链接：https://github.com/Finb/Bark
希望项目后续能够支持该API，拜谢！

**Comment by RayWangQvQ** [comment]
ok

**Comment by RayWangQvQ** [comment]
gotify搞定了（#240），要不要考虑下gotify呢，是同时支持安卓，iOS，wed的，这个Bark只支持ios

**Comment by layui0320** [comment]
好的，谢谢。目前暂用Bark没问题，就不换了。该问题我关了

**Comment by dfbb9216** [comment]
按照一楼的测试了好几条不成功，后来BiliBili\u7B7E\u5230改成BiliBili，成功了

**Comment by ssmmtt** [comment]
> 

gotify没有ios的app呀。。。
