### ISSUE TITLE
我的ck只能维持2天，你们是么？

### ISSUE THREAD

**Issue by Cyiming** [RayWangQvQ/BiliBiliToolPro#239]
太短了啊 以前不这样

网页复制的  网页登录一直也不掉啊

**Comment by KudouRan** [comment]
是说这id这么眼熟，看到你提了一堆issues，你这个问题，在issues搜索一下不就有了

**Comment by KudouRan** [comment]
#212

**Comment by Cyiming** [comment]
> 是说这id这么眼熟，看到你提了一堆issues，你这个问题，在issues搜索一下不就有了

是提了挺多 希望脚本变得越来越好嘛

提之前看了下没有提到ck问题才提的  之前也没这个情况

**Comment by 1260074755** [comment]
朋友，请问你拉取的是哪一个分支啊？
