### ISSUE TITLE
建议添加gotify推送

### ISSUE THREAD

**Issue by love-evol** [RayWangQvQ/BiliBiliToolPro#240]
gotify支持安卓，iOS，wed强烈推荐
支持本地部署操作方便

**Comment by RayWangQvQ** [comment]
ok，下个版本安排~

**Comment by RayWangQvQ** [comment]
已更新到dev先行版，稍后会包含再下个release版本中

![image](https://user-images.githubusercontent.com/31154238/186453904-16f7b8fa-4f99-461b-9e36-dbc49c3aef29.png)

![image](https://user-images.githubusercontent.com/31154238/186453992-212937f1-29d6-44d7-ac36-941f959b1edc.png)

**Comment by lbbboy** [comment]
> 

Nice 好用

**Comment by banjuer** [comment]
> 已更新到dev先行版，稍后会包含再下个release版本中
> 
> ![image](https://user-images.githubusercontent.com/31154238/186453904-16f7b8fa-4f99-461b-9e36-dbc49c3aef29.png)
> 
> ![image](https://user-images.githubusercontent.com/31154238/186453992-212937f1-29d6-44d7-ac36-941f959b1edc.png)

怎么用啊， 文档里没找到:)

**Comment by gongjuecloak** [comment]
配置了推送失败了
