### ISSUE TITLE
Error relocating /usr/local/bin/dotnet: 

### ISSUE THREAD

**Issue by x1737886903** [RayWangQvQ/BiliBiliToolPro#241]
版本号：
运行环境：青龙V2.11.1（玩客云）

问题描述：
根据教程教程，但无法安装dotnet环境

日志信息：
2022-08-07 18:41:41 (1.86 MB/s) - 'dotnet-sdk.tar.gz' saved [172539795/172539795]

Error relocating /usr/local/bin/dotnet: __time64: symbol not found
Error relocating /usr/local/bin/dotnet: __gmtime64: symbol not found
Error relocating /usr/local/bin/dotnet: __fstat_time64: symbol not found
Error relocating /usr/local/bin/dotnet: __dlsym_time64: symbol not found
Error relocating /usr/local/bin/dotnet: __fstatat_time64: symbol not found
## 开始执行... 2022-08-07 18:40:09

--------------------------------------------------------------

-------set up dot net env-------
OK: 312 MiB in 107 packages

-------set up dot net env finish-------

**Comment by TishonL** [comment]
我也是这样qwq

**Comment by Goodyaoshi** [comment]
同样的错误
Error relocating /usr/local/bin/dotnet: __time64: symbol not found
Error relocating /usr/local/bin/dotnet: __gmtime64: symbol not found
Error relocating /usr/local/bin/dotnet: __fstat_time64: symbol not found
Error relocating /usr/local/bin/dotnet: __dlsym_time64: symbol not found
Error relocating /usr/local/bin/dotnet: __fstatat_time64: symbol not found
