### ISSUE TITLE
off

### ISSUE THREAD

**Issue by ycyfff** [RayWangQvQ/BiliBiliToolPro#242]
off

**Comment by KudouRan** [comment]
pro只支持大会员是啥意思。pro和原来的也没区别啊，就是改了个名字。
全部登录下线是被风控了。

**Comment by ycyfff** [comment]
> pro只支持大会员是啥意思。pro和原来的也没区别啊，就是改了个名字。 全部登录下线是被风控了

但是换回BiliBiliTool v2.0.1就正常不掉CK

**Comment by KudouRan** [comment]
那有换回来试过？运行的活动都是一样的？

**Comment by ycyfff** [comment]
> 那有换回来试过？运行的活动都是一样的？

一样的定时规则，之前版本不掉CK

**Comment by KudouRan** [comment]
我说的是有换回来试过？

**Comment by ycyfff** [comment]
> 我说的是有换回来试过？

我之前用的是BiliBiliTool v2.0.1，不掉，换了pro 掉了好几次，又换回去了，没掉。没换回pro
