### ISSUE TITLE
天选时刻的数据是怎么抓取的？

### ISSUE THREAD

**Issue by UnderTides** [RayWangQvQ/BiliBiliToolPro#243]
我真的毫无思路，求指教

**Comment by layui0320** [comment]
你需要这个？https://github.com/RayWangQvQ/BiliBiliToolPro/blob/main/src/Ray.BiliBiliTool.Agent/BiliBiliAgent/Interfaces/ILiveApi.cs

**Comment by RayWangQvQ** [comment]
楼上贴的就是代码里的Api地址了，调用逻辑都在Domain Service里。

如果还是有疑问，可以加群细聊。
