### ISSUE TITLE
青龙面板拉库失败

### ISSUE THREAD

**Issue by 1260074755** [RayWangQvQ/BiliBiliToolPro#244]
ql repo https://github.com/raywangqvq/bilibilitoolpro.git "bili_task_"
该项目分支找不到

**Comment by RayWangQvQ** [comment]
可以试下：

1. 加代理：ql repo https://ghproxy.com/https://github.com/RayWangQvQ/BiliBiliToolPro.git "bili_task_"
2. 改用订阅管理：https://github.com/RayWangQvQ/BiliBiliToolPro/blob/main/qinglong/README.md#151-%E8%AE%A2%E9%98%85%E7%AE%A1%E7%90%86
