### ISSUE TITLE
运行失败Microsoft.Extensions.Configuration.EnvironmentVariables

### ISSUE THREAD

**Issue by misakajialin** [RayWangQvQ/BiliBiliToolPro#245]
版本号：2.10.13
运行环境：linux 青龙

问题描述：
日志信息：在那里看
/home/dotnet/sdk/6.0.201/NuGet.targets(130,5): error : 未能从远程源“https://api.nuget.org/v3-flatcontainer/microsoft.extensions.configuration.environmentvariables/index.json”检索有关“Microsoft.Extensions.Configuration.EnvironmentVariables”的信息。 [/ql/repo/raywangqvq_bilibilitoolpro/src/Ray.BiliBiliTool.Console/Ray.BiliBiliTool.Console.csproj]
/home/dotnet/sdk/6.0.201/NuGet.targets(130,5): error :   The SSL connection could not be established, see inner exception. [/ql/repo/raywangqvq_bilibilitoolpro/src/Ray.BiliBiliTool.Console/Ray.BiliBiliTool.Console.csproj]
/home/dotnet/sdk/6.0.201/NuGet.targets(130,5): error :    Received an unexpected EOF or 0 bytes from the transport stream. [/ql/repo/raywangqvq_bilibilitoolpro/src/Ray.BiliBiliTool.Console/Ray.BiliBiliTool.Console.csproj]

生成失败。请修复生成错误并重新运行

**Comment by RayWangQvQ** [comment]
Nuget拉包失败了，应该是你服务器网络环境问题，换个时间再跑下试试
