### ISSUE TITLE
【Bug】腾讯云部署失败

### ISSUE THREAD

**Issue by mataxiangyun** [RayWangQvQ/BiliBiliToolPro#25]
在fork中运行auto-deploy-tencent-scf显示成功，但是在自己的腾讯云函数中没有见到新函数。
必填项已填写。

**Comment by mataxiangyun** [comment]
`# https://github.com/serverless-components/tencent-scf/blob/master/docs/configure.md

#组件信息
component: scf
name: bilibili_tool

#组件参数配置
inputs:
  name: ${name}_scf
  enableRoleAuth: false
  src: ./bin/publish/
  handler: index.main_handler
  runtime: CustomRuntime
  region: ap-guangzhou # 函数所在区域，默认广州ap-hongkong-2
  description: This is a function in ${app} application.
  memorySize: 128
  initTimeout: 30
  timeout: 86400
  asyncRunEnable: true
  traceEnable: true
  events: # 根据自己的需要修改
    - timer: # 每日任务 触发器
        parameters:
          name: DailyTask
          cronExpression: "0 30 12 * * * *"
          enable: true
          argument: Daily
    - timer: # 天选抽奖触发器
        parameters:
          name: LiveLotteryTask
          cronExpression: "0 0 */4 * * * *"
          enable: true
          argument: LiveLottery
    - timer: # 自动取关
        parameters:
          name: UnfollowBatchedTask
          cronExpression: "0 0 0 * * MON *"
          enable: true
          argument: UnfollowBatched
  environment:
    variables: # 根据自己的需要修改
      Ray_BiliBiliCookies__1: @@@@@@@
      Ray_Security__RandomSleepMaxMin: 30
      Security__IntervalSecondsBetweenRequestApi: 15
      Ray_Security__IntervalMethodTypes: 
      Ray_Security__UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.82 Safari/537.36
      Ray_DailyTaskConfig__NumberOfCoins: 5
      Ray_DailyTaskConfig__SelectLike: true
      Ray_DailyTaskConfig__DayOfAutoCharge: -1
      Ray_DailyTaskConfig__AutoChargeUpId: -1
      Ray_DailyTaskConfig__DayOfReceiveVipPrivilege: 1
      Ray_Serilog__WriteTo__3__Args__chatId: @@@@@@@
      Ray_Serilog__WriteTo__3__Args__botToken: @@@@@@@
      Ray_UnfollowBatchedTaskConfig__Count: 10
      Ray_DailyTaskConfig__DayOfReceiveVipPrivilege: 19 # 会员权益日期
      Ray_DailyTaskConfig__SupportUpIds: -1
      Ray_UnfollowBatchedTaskConfig__Count: 10
      
`

**Comment by KudouRan** [comment]
配置有错，环境变量 Ray_DailyTaskConfig__DayOfReceiveVipPrivilege 是重复的。
