### ISSUE TITLE
 方式三：添加环境变量（推荐）Linux变量填写到哪个文件中？

### ISSUE THREAD

**Issue by x1737886903** [RayWangQvQ/BiliBiliToolPro#250]
下面添加环境变量的应该填写到哪个文件中
# 添加环境变量作为配置：
set Ray_RunTasks=Daily
set Ray_BiliBiliCookies__1=abc
set Ray_BiliBiliCookies__2=efg
set Ray_DailyTaskConfig__NumberOfCoins=3

# 开始运行程序：
dotnet Ray.BiliBiliTool.Console.dll
注意区分单下划线和双下划线，linux系统使用 export 关键字代替 set

**Comment by distance857** [comment]
config.sh
