### ISSUE TITLE
宝塔+青龙运行一直报错

### ISSUE THREAD

**Issue by youzouzach** [RayWangQvQ/BiliBiliToolPro#258]
repo目录: /ql/repo
bili仓库目录: /ql/repo/RayWangQvQ_BiliBiliToolPro

bili_task_daily.sh: line 17: dotnet: command not found

几个任务测试下来都是提示17行报错

**Comment by RayWangQvQ** [comment]
你这问题有点多啊...
1. 青龙版本有点老，现在青龙的仓库目录之前就改到`ql/data`下了，推荐尽量使用较新版本
2. DotNet的环境没有装好，建议根据文档（extra.sh部分）操作
