### ISSUE TITLE
【建议】VipBigPoint 大会员任务开始时候检测并打印会员状态

### ISSUE THREAD

**Issue by leieerr** [RayWangQvQ/BiliBiliToolPro#259]
建议内容：
VipBigPoint 大会员任务开始时候检测并打印会员状态
![2](https://user-images.githubusercontent.com/106761073/186335452-3615d7be-4818-407f-aa39-9fce46526307.png)

出现此情况是的原因是，有账号并并不是大会员，无法完成相关任务

**Comment by RayWangQvQ** [comment]
done
![image](https://user-images.githubusercontent.com/31154238/186698235-6822bf5c-3833-4d47-b6e5-6d880a90c471.png)
