### ISSUE TITLE
青龙运行脚本报错

### ISSUE THREAD

**Issue by xddlang** [RayWangQvQ/BiliBiliToolPro#261]
bili_task_liveLottery.sh: line 6: /shell/share.sh: No such file or directory
repo目录: 
bili仓库目录: 

MSBUILD : error MSB1009: Project file does not exist.
Switch: ./src/Ray.BiliBiliTool.Console

The build failed. Fix the build errors and run again.

## 执行结束... 2022-08-24 23:38:15 耗时 0 秒

**Comment by RayWangQvQ** [comment]
不要提重复issue

**Comment by xddlang** [comment]
第一次问怎么就重复问问题了啊
