### ISSUE TITLE
【其他】請問能夠使用podman來執行嗎?

### ISSUE THREAD

**Issue by NeiL978** [RayWangQvQ/BiliBiliToolPro#263]
請問能夠使用podman來執行嗎? (類似Docker)
相關設定指令該怎麼執行?
謝謝

**Comment by layui0320** [comment]
据我所知，podman和docker的命令是一样的，你可以尝试使用docker run的部署代码，其中docker更换podman使用。

**Comment by NeiL978** [comment]
> 据我所知，podman和docker的命令是一样的，你可以尝试使用docker run的部署代码，其中docker更换podman使用。

好 我晚點試試看 但我是用windows不知道能不能成功？ 謝謝

**Comment by RayWangQvQ** [comment]
ok下個版本會提供文檔教程

**Comment by NeiL978** [comment]
> ok下個版本會提供文檔教程

太棒了，昨天試了一下，可能是我的指令不熟悉打錯了，都不成功。
謝謝

**Comment by RayWangQvQ** [comment]
> > ok下個版本會提供文檔教程
> 
> 太棒了，昨天試了一下，可能是我的指令不熟悉打錯了，都不成功。 謝謝

可以先参考Dev分支： https://github.com/RayWangQvQ/BiliBiliToolPro/tree/develop/podman
