### ISSUE TITLE
【Bug】青龙安装dotnet时报错Couldn't find a valid ICU package installed on the system

### ISSUE THREAD

**Issue by 1332850913** [RayWangQvQ/BiliBiliToolPro#266]
运行环境：N1部署的青龙 青龙版本2.11.3

1. 问题描述：
![photo_2022-08-30_08-29-13](https://user-images.githubusercontent.com/38727187/187332095-10c1457e-21c5-4f13-82f3-dbe90b1c5b15.jpg)

**Comment by 1332850913** [comment]
@Mr-Quin @AmazingDM @hjkl950217 @ChanceLuo

**Comment by layui0320** [comment]
环境没安装成功

**Comment by 1332850913** [comment]
> 环境没安装成功

大佬求教 留下联系方式

**Comment by layui0320** [comment]
https://github.com/RayWangQvQ/BiliBiliToolPro/blob/main/qinglong/README.md#11-安装-dotnet-环境   细读教程

**Comment by 1332850913** [comment]
这个已经安装了

**Comment by 1332850913** [comment]
![photo_2022-08-30_08-51-40](https://user-images.githubusercontent.com/38727187/187358173-7048953a-126c-43af-a051-f437cd9319ca.jpg)

**Comment by 1332850913** [comment]
最后也是提示这个报错

**Comment by 1332850913** [comment]
Process terminated. Couldn't find a valid ICU package installed on the system. Please install libicu using your package manager and try again. Alternatively you can set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support. Please see https://aka.ms/dotnet-missing-libicu for more information.
at System.Environment.FailFast(System.String)
at System.Globalization.GlobalizationMode+Settings..cctor()
at System.Globalization.CultureData.CreateCultureWithInvariantData()
at System.Globalization.CultureData.get_Invariant()
at System.Globalization.CultureInfo..cctor()
at System.Globalization.CultureInfo.get_CurrentUICulture()
at System.TimeZoneInfo.GetUtcStandardDisplayName()
at System.TimeZoneInfo.CreateUtcTimeZone()
at System.TimeZoneInfo..cctor()
at System.DateTime.get_Now()
at Microsoft.DotNet.Cli.Program.Main(System.String[])
bili_task_daily.sh: line 17: 1160 Aborted (core dumped) dotnet run --project ./src/Ray.BiliBiliTool.Console

**Comment by layui0320** [comment]
你这个问题跟 #255 一样，DotNet环境没装好，贴下运行extra.sh的日志

**Comment by RayWangQvQ** [comment]
服务器架构是amd还是arm？

我一直也比较好奇，为啥有个别人安装dotnet会不成功，已经不只一个issue提过同样问题了。

DotNet的安装教程在这：https://docs.microsoft.com/zh-cn/dotnet/core/install/linux-alpine

可以进到青龙容器，自己尝试安装

docker exec -it qinglong bash

如果能找到原因，记得回来告诉我一下，解决我的好奇心。

**Comment by layui0320** [comment]
n1是arm架构的

**Comment by 1332850913** [comment]
N1 ARM架构的

**Comment by RayWangQvQ** [comment]
那我怀疑可能跟arm有关系

**Comment by 1332850913** [comment]
> 那我怀疑可能跟arm有关系

我该怎么操作大佬。。。

**Comment by RayWangQvQ** [comment]
> ![photo_2022-08-30_08-51-40](https://user-images.githubusercontent.com/38727187/187358173-7048953a-126c-43af-a051-f437cd9319ca.jpg)

这个日志前面还有东西吗

**Comment by 1332850913** [comment]
有的 正常下载的

**Comment by 1332850913** [comment]
我去重新跑一下

**Comment by 1332850913** [comment]
![QQ截图20220830140059](https://user-images.githubusercontent.com/38727187/187361255-af170965-732e-4f2b-8d4f-3ec66fa0e453.png)

**Comment by 1332850913** [comment]
> > ![photo_2022-08-30_08-51-40](https://user-images.githubusercontent.com/38727187/187358173-7048953a-126c-43af-a051-f437cd9319ca.jpg)
> 
> 这个日志前面还有东西吗

全部日志在这

**Comment by RayWangQvQ** [comment]
下载的是arm64的dotnet sdk，看着没问题，n1应该就是arm64吧？

但是我看你设置了apk的镜像地址到阿里云镜像，也可能是这个镜像有问题。

可以把镜像地址删了再试试

**Comment by 1332850913** [comment]
> 下载的是arm64的dotnet sdk，看着没问题，n1应该就是arm64吧？
> 
> 但是我看你设置了apk的镜像地址到阿里云镜像，也可能是这个镜像有问题。
> 
> 可以把镜像地址删了再试试

# 安装 dotnet 环境
sh -c "$(wget https://ghproxy.com/https://raw.githubusercontent.com/RayWangQvQ/BiliBiliToolPro/main/qinglong/ray-dotnet-install.sh -O -)"

我是用大佬你写的指令粘贴的

**Comment by RayWangQvQ** [comment]
是的，里面会执行`apk add bash icu-libs krb5-libs libgcc libintl libssl1.1 libstdc++ zlib`

apk会去安装依赖包，你给apk添加了国内镜像，你再回一下，应该是你自己之前手动设置的

**Comment by 1332850913** [comment]
> 是的，里面会执行`apk add bash icu-libs krb5-libs libgcc libintl libssl1.1 libstdc++ zlib`
> 
> apk会去安装依赖包，你给apk添加了国内镜像，你再回忆一下，应该是你自己之前手动设置的

我记得没有呀 阿里云镜像啥的 但是我青龙上面依赖管理是都有安装的

**Comment by RayWangQvQ** [comment]
运行`cat /etc/apk/repositories`，贴出来看看

**Comment by 1332850913** [comment]
![image](https://user-images.githubusercontent.com/38727187/187363677-778848da-1440-4745-ae3d-d7cd73a5afce.png)

**Comment by RayWangQvQ** [comment]
进青龙容器里再执行，docker exec -it qinglong bash cat /etc/apk/repositories

**Comment by 1332850913** [comment]
对了 N1上的文件好像跟服务器上的不一样
就比如大佬你写的docker exec -it qinglong bash /ql/data/config/extra.sh
在N1上 没有data 直接是docker exec -it qinglong bash /ql/config/extra.sh

**Comment by 1332850913** [comment]
![image](https://user-images.githubusercontent.com/38727187/187364015-024efc71-cf58-4690-8027-06423cf1e895.png)

**Comment by 1332850913** [comment]
![image](https://user-images.githubusercontent.com/38727187/187364246-7fe82c2d-df8a-475a-9105-fe64afb995f6.png)

**Comment by 1332850913** [comment]
这个对了吧 大佬

**Comment by RayWangQvQ** [comment]
有没有data只跟青龙版本有关，新版有data目录。

你这显然是换成了阿里云的镜像源

试试换回去

```
sed -i 's/mirrors.aliyun.com/dl-cdn.alpinelinux.org/g' /etc/apk/repositories
cat /etc/apk/repositories
apk update
apk add bash icu-libs krb5-libs libgcc libintl libssl1.1 libstdc++ zlib
```

**Comment by 1332850913** [comment]
> 

进青龙容器运行是吧

**Comment by 1332850913** [comment]
> 

![image](https://user-images.githubusercontent.com/38727187/187365618-b139d383-b955-4cdc-949d-16ea8861b5f6.png)
您看一下

**Comment by 1332850913** [comment]
> Reference

![image](https://user-images.githubusercontent.com/38727187/187365708-2315d90f-0a2b-4518-acd3-650d8d59fe86.png)
您看一下。

**Comment by 1332850913** [comment]
![image](https://user-images.githubusercontent.com/38727187/187366819-42ba0d16-9fca-4c55-a91e-ff963ab10148.png)

**Comment by RayWangQvQ** [comment]
![image](https://user-images.githubusercontent.com/31154238/187368567-6b894cc2-6c66-4712-8834-e706726e3e16.png)

还是apk安装依赖失败的问题，试试中科大的源吧

```
sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories
cat /etc/apk/repositories
apk update
apk add bash
apk add icu-libs
apk add krb5-libs
apk add libgcc
apk add libintl
apk add libssl1.1 
apk add libstdc++ 
apk add zlib
```

**Comment by 1332850913** [comment]
![image](https://user-images.githubusercontent.com/38727187/187369431-fe14433a-070e-4d6d-bd5a-bd556a0f310a.png)

**Comment by 1332850913** [comment]
好像也一样的报错

**Comment by 1332850913** [comment]
我看挺多青龙用户反馈都是这样

**Comment by layui0320** [comment]
https://dotnet.microsoft.com/en-us/download/dotnet

**Comment by 1332850913** [comment]
> https://dotnet.microsoft.com/en-us/download/dotnet
具体怎么操作大佬

**Comment by layui0320** [comment]
https://www.cnblogs.com/lwhzj/p/16571833.html 你看看吧，二进制文件应该没问题

**Comment by 1332850913** [comment]
> https://www.cnblogs.com/lwhzj/p/16571833.html 你看看吧，二进制文件应该没问题

这个对小白有点难度。。 嘿嘿

**Comment by RayWangQvQ** [comment]
一样的，脚本里做的就是这个事情：下载二进制，创建软链接

或者你试试报错提示让做的：

```
export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1 && dotnet --version
```

**Comment by 1332850913** [comment]
> 一样的，脚本里做的就是这个事情：下载二进制，创建软链接
> 
> 或者你试试报错提示让做的：
> 
> ```
> export DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1 && dotnet --version
> ```

![image](https://user-images.githubusercontent.com/38727187/187376656-9493a1c3-6408-48d9-91d4-790cd410c854.png)

**Comment by RayWangQvQ** [comment]
可以了。。。

**Comment by 1332850913** [comment]
> 可以了。。。

直接运行脚本就好了嘛

**Comment by RayWangQvQ** [comment]
把上面那个配到青龙面板的环境变量里

**Comment by 1332850913** [comment]
![image](https://user-images.githubusercontent.com/38727187/187378721-563b7fb0-ef5e-4c84-914b-e6eb6a982d2c.png)

**Comment by 1332850913** [comment]
跑不起来

**Comment by RayWangQvQ** [comment]
别急，让控制台飞一会儿

**Comment by 1332850913** [comment]
![image](https://user-images.githubusercontent.com/38727187/187379657-111d4c6a-4707-4367-9bba-a4385bf48d2b.png)
我让他飞一会 一会反馈

**Comment by 1332850913** [comment]
![image](https://user-images.githubusercontent.com/38727187/187384435-b4951954-8b30-4427-af17-28391f37fa93.png)
这算正常嘛 就是感觉飞好久

**Comment by 1332850913** [comment]
![image](https://user-images.githubusercontent.com/38727187/187386340-ea6877d2-ec74-494b-bc30-0d550f6f6727.png)
大佬牛逼！！！！！！
