### ISSUE TITLE
Linux运行异常，缺少运行权限，建议补充到文档

### ISSUE THREAD

**Issue by Barry04** [RayWangQvQ/BiliBiliToolPro#27]
版本号：[BiliBiliTool-V0.0.5](https://github.com/RayWangQvQ/BiliBiliToolPro/releases/tag/0.0.5)
运行环境：Linux

问题描述：服务器报错
![image](https://user-images.githubusercontent.com/61132615/156958816-d1ba1d3e-6813-488a-9fec-3bc1cebb2a51.png)

**Comment by Barry04** [comment]
https://github.com/RayWangQvQ/BiliBiliToolPro/issues/27#issuecomment-1060381380
![image](https://user-images.githubusercontent.com/61132615/157004435-69cde2a4-6118-41a9-8916-a2927e35a644.png)
肯定是有的。

**Comment by RayWangQvQ** [comment]
./Ray.BiliBiliTool.Console

**Comment by Barry04** [comment]
> ./Ray.BiliBiliTool.Console
还是不行啊，管理员运行也不行。
![Screenshot_2022-03-07-20-29-03-691_com server auditor ssh client](https://user-images.githubusercontent.com/61132615/157034835-65c50440-af53-430c-ba5d-8a0927a8c0a8.jpg)

**Comment by Barry04** [comment]
https://github.com/RayWangQvQ/BiliBiliToolPro/issues/27#issuecomment-1060677751
好的，谢谢！
