### ISSUE TITLE
请问这个如何操作

### ISSUE THREAD

**Issue by AlvaTsou** [RayWangQvQ/BiliBiliToolPro#274]
如题 arm服务器遇到了同样的问题，看到这一步不知道怎么操作了？请问大佬需要添加什么变量填什么啊

把上面那个配到青龙面板的环境变量里

_Originally posted by @RayWangQvQ in https://github.com/RayWangQvQ/BiliBiliToolPro/issues/266#issuecomment-1231269830_

**Comment by RayWangQvQ** [comment]
![image](https://user-images.githubusercontent.com/31154238/188322418-8bd89540-2be9-4688-a3f8-80532c483c07.png)

**Comment by AlvaTsou** [comment]
> ![image](https://user-images.githubusercontent.com/31154238/188322418-8bd89540-2be9-4688-a3f8-80532c483c07.png)

出现新的bug
<img width="512" alt="image" src="https://user-images.githubusercontent.com/8097830/193954919-ab1cbffa-e018-4f60-adff-d92e49139e13.png">
