### ISSUE TITLE
【建议】能不能添加一个cookie失效的脚本，然后直接通过通知提醒

### ISSUE THREAD

**Issue by syu2021** [RayWangQvQ/BiliBiliToolPro#276]
如上

**Comment by RayWangQvQ** [comment]
你说的是它不
![image](https://user-images.githubusercontent.com/31154238/188298174-1212ab94-7de1-40c3-b2ac-46067db6c3a2.png)

**Comment by syu2021** [comment]
对的，但是按照说明添加完显示缺少access_token参数

**Comment by syu2021** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，三天之内会回复

**Comment by syu2021** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，三天之内会回复
