### ISSUE TITLE
【Bug】docker定时任务配置问题和my_crontab文件问题

### ISSUE THREAD

**Issue by franco1013** [RayWangQvQ/BiliBiliToolPro#281]
版本号：最新版本
运行环境：docker

[问题描述：**1.docker运行的代码有问题。应该是docker-compose up -d   中间有个“-”的，否则一直报错的。**
<img width="514" alt="屏幕截图 2022-09-09 223830" src="https://user-images.githubusercontent.com/62698590/189376989-fa3dc8d2-3d58-4e0b-90fa-3886548133af.png">

**2.这两个文件内容有重复的，是只用填一个就行了吗。我目前是两个都填的，但好像在运行的时候显示出现了两个corn**
<img width="942" alt="屏幕截图 2022-09-09 223815" src="https://user-images.githubusercontent.com/62698590/189376952-543990ec-e12e-45be-b0cf-c140ed48cb72.png">
<img width="674" alt="屏幕截图 2022-09-09 223958" src="https://user-images.githubusercontent.com/62698590/189377003-5f4513b3-e22b-4def-9954-b633435efd34.png">

**3.在设置文件中只设置运行Daily&VipBigPoint但运行时运行了LiveLottery**
<img width="559" alt="屏幕截图 2022-09-09 224011" src="https://user-images.githubusercontent.com/62698590/189377024-be242de2-a92e-4526-ac71-48aaabba20cd.png">
<img width="524" alt="屏幕截图 2022-09-09 224031" src="https://user-images.githubusercontent.com/62698590/189377030-c5e82a43-93b2-4ef0-b60c-af8204f07676.png">
<img width="1148" alt="屏幕截图 2022-09-09 224042" src="https://user-images.githubusercontent.com/62698590/189377046-875035e9-55fb-4d7e-9a95-b59585415ba5.png">

<img width="692" alt="屏幕截图 2022-09-09 225246" src="https://user-images.githubusercontent.com/62698590/189379240-3e92c471-50f6-4990-a369-3c77025f72d0.png">

日志信息：
[bilibili_tool_pro.csv](https://github.com/RayWangQvQ/BiliBiliToolPro/files/9536505/bilibili_tool_pro.csv)

**Comment by franco1013** [comment]
目前将appsettings.json文件还原清零了。cron显示正常了但，任务运行还未到时间，不清楚正不正常，明天看看

**Comment by Jisu-Woniu** [comment]
docker compose 最新版本中不需要加横线（加横线报错），建议检查 docker 官方网站安装最新版 compose

**Comment by franco1013** [comment]
> 

好的好的，谢谢

**Comment by franco1013** [comment]
<img width="549" alt="image" src="https://user-images.githubusercontent.com/62698590/189457594-9a0796f6-611e-42c4-ac78-f5785fe12b8f.png">
使用查询cron内容发现就是没设置过的样子，并没有按照在docker-compose.yml中设置的运行

**Comment by franco1013** [comment]
> <img alt="image" width="549" src="https://user-images.githubusercontent.com/62698590/189457594-9a0796f6-611e-42c4-ac78-f5785fe12b8f.png">
> 
> 使用查询cron内容发现就是没设置过的样子，并没有按照在docker-compose.yml中设置的运行

这个我又在文件里添加了my_crontab文件设置内容就正常了，在environment里设置的不知道为什么无效。但目前能用了，就还是老的设置方法了，docker-compose.yml+my_crontab。。。appsettings.json并没有用得起来（这问题同上面说过的情况

**Comment by RayWangQvQ** [comment]
定时器，my_crontab和环境变量选其他一个就可以了，两个都配，linux的crontab会报错。

建议按照文档里步骤操作：https://github.com/RayWangQvQ/BiliBiliToolPro/blob/main/docker/README.md，文档里已经没有my_crontab相关的内容了，只是为了兼容以前版本，功能还保留了。

推荐使用环境变量。

环境变量是在docker-compose.yml里或docker run指令里指定的，在appsetting.json里没用。参考 文档或 https://github.com/RayWangQvQ/BiliBiliToolPro/blob/main/docker/sample/docker-compose.yml

appsetting.json里本来是计划重构用quartz的，一直没做，忽视就行了。
