### ISSUE TITLE
请问dotnet环境什么命令可以卸载。。。N1内存不够了

### ISSUE THREAD

**Issue by 1332850913** [RayWangQvQ/BiliBiliToolPro#282]
版本号：（请贴出你的版本号，请确认是否已通过升级到最新版来解决当前问题？）
运行环境：（请贴出运行环境，比如是Actions或docker或本地？是Win还是Linux？）

问题描述：（提issue前请先确认没有其他人已提过相同的议题，请清晰的描述所您所遇到的问题。）

日志信息：（如果可以，请贴出Debug级别的日志信息，以便更高效的确定和解决问题。）

**Comment by 1332850913** [comment]
ARM64

**Comment by nibazshab** [comment]
docker运行？本地运行？win运行？linux运行？

什么都不说怎么告诉你怎么卸载

**Comment by 1332850913** [comment]
青龙运行。

**Comment by nibazshab** [comment]
> 

青龙运行你直接把青龙关了，环境自动消失

**Comment by 1332850913** [comment]
我容器青龙卸载了 瞬间腾出3G空间 换个路径安装就解决拉 谢谢大佬
