### ISSUE TITLE
【已解决】当使用自定义api推送到go-cqhttp时，替换词参数导致的报错

### ISSUE THREAD

**Issue by dextersa** [RayWangQvQ/BiliBiliToolPro#285]
此问题源于配置信息不太正确
## 正确的配置：
export Ray_Serilog__WriteTo__8__Args__bodyJsonTemplate='{"user_id": "XXXX440","message": #msg#}' 

## 过时问题
版本号： v0.2.1 
运行环境：ubuntu 20.04 + 青龙面板

问题描述：只要替换词placeholder 参数生效就会导致报错。
如果bodyJsonTemplate不出现替换词，消息可以正常发送。
无论placeholder如何设置，只要能在bodyJsonTemplate中匹配就会导致报错
不配置placeholder使用默认参数#msg#也会报错。
推测原因，推送消息里是否有""等特殊字符导致传输异常？

相关参数配置：
export Ray_Serilog__WriteTo__8__Args__api="http://192.168.137.2:8000/send_private_msg"
export Ray_Serilog__WriteTo__8__Args__placeholder="#mmm#"
export Ray_Serilog__WriteTo__8__Args__bodyJsonTemplate="{\\"user_id\": \\"XXXXX440\\",\\"message\\": \\"哔哩哔哩自定义通知：\\n#mmm# \\",\\"auto_escape\\": \\"false\\"}"

日志信息：
========================
 v0.2.1 in Production env.
开源 by https://github.com/RayWangQvQ/BiliBiliToolPro

[19:31:41 INF] ·开始推送·Test任务·
2022-09-15T11:31:41.6594062Z 开始推送到:自定义
2022-09-15T11:31:41.8166525Z Response status: BadRequest.
2022-09-15T11:31:41.8167313Z Response content: .

[19:31:41 INF] 运行结束

**Comment by hfuulzy** [comment]
你好，发现你用的这个语法很像go-cqhttp，是这个吗？能否告知一下你自定义api上的实现

**Comment by dextersa** [comment]
是go-cqhttp，刚刚发现我不知道你缺少什么信息，总体而言现在的问题是Ray_Serilog__WriteTo__8__Args__bodyJsonTemplate里面不是有个替换词#mmm#吗？
如果bodyJsonTemplate没有这个替换词，是可以正常发送消息的。


假设配置改成这样：

我就能正常收到这样一条消息：

哔哩哔哩自定义通知：
=================
 #msg#

**Comment by dextersa** [comment]
> 你好，发现你用的这个语法很像go-cqhttp，是这个吗？能否告知一下你自定义api上的实现

发现个问题，原来是咱俩在互聊

**Comment by hfuulzy** [comment]
![image](https://user-images.githubusercontent.com/38681237/194692401-05a90d24-8eb1-413e-a587-647f9e36577c.png)
通过bao'cu报错可知，还是json的问题，我在尝试不同组合，发现并不能通过

**Comment by hfuulzy** [comment]
> 

我甚至设置的和你截图一样的都发送不了，报错非法json

**Comment by dextersa** [comment]
那我不了解了，你用别的工具调用过go-cqhttp么？能正常发么？

**Comment by hfuulzy** [comment]
> 那我不了解了，你用别的工具调用过go-cqhttp么？能正常发么？

可以的，包括青龙本身通知也支持cqhttp，也没问题，通知实现也很简单，不过我不清楚bilibilitoolpro的通知实现是在哪

**Comment by layui0320** [comment]
该问题我之前遇到过，有没有试过：
```{"user_id": "XXXXX440","message": #mmm#}```

**Comment by hfuulzy** [comment]
如果你没解决的话，我推荐一个可以暂且做规避的方案，就是用coolpush的私有化部署，它现在就是基于go-cqhttp做的实现。
可以不用coolpush自定义的软件，直接用官方版本，在coolpush中绑定qq和私有化部署的ip、token，也可以发送。
不过前提是你得有公网ip。。或者你能实现内网穿透也行。
缺点就是消息中的\n不能正确转义

**Comment by dextersa** [comment]
我解决了，按照上面仁兄提供的建议

> 如果你没解决的话，我推荐一个可以暂且做规避的方案，就是用coolpush的私有化部署，它现在就是基于go-cqhttp做的实现。 可以不用coolpush自定义的软件，直接用官方版本，在coolpush中绑定qq和私有化部署的ip、token，也可以发送。 不过前提是你得有公网ip。。或者你能实现内网穿透也行。 缺点就是消息中的\n不能正确转义

**Comment by hfuulzy** [comment]
> 我解决了，按照上面仁兄提供的建议，方案1测试通过了，方案2不行
> 
> > 如果你没解决的话，我推荐一个可以暂且做规避的方案，就是用coolpush的私有化部署，它现在就是基于go-cqhttp做的实现。 可以不用coolpush自定义的软件，直接用官方版本，在coolpush中绑定qq和私有化部署的ip、token，也可以发送。 不过前提是你得有公网ip。。或者你能实现内网穿透也行。 缺点就是消息中的\n不能正确转义

能否发一下你的消息体实际实现，有试过加token可行吗

**Comment by dextersa** [comment]
> > 我解决了，按照上面仁兄提供的建议，方案1测试通过了，方案2不行
> > > 如果你没解决的话，我推荐一个可以暂且做规避的方案，就是用coolpush的私有化部署，它现在就是基于go-cqhttp做的实现。 可以不用coolpush自定义的软件，直接用官方版本，在coolpush中绑定qq和私有化部署的ip、token，也可以发送。 不过前提是你得有公网ip。。或者你能实现内网穿透也行。 缺点就是消息中的\n不能正确转义
> 
> 能否发一下你的消息体实际实现，有试过加token可行吗

我编辑了问题，放到了问题最前面

**Comment by Fahaxikiii** [comment]
> > 我解决了，按照上面仁兄提供的建议，方案1测试通过了，方案2不行
> > > 如果你没解决的话，我推荐一个可以暂且做规避的方案，就是用coolpush的私有化部署，它现在就是基于go-cqhttp做的实现。 可以不用coolpush自定义的软件，直接用官方版本，在coolpush中绑定qq和私有化部署的ip、token，也可以发送。 不过前提是你得有公网ip。。或者你能实现内网穿透也行。 缺点就是消息中的\n不能正确转义
> 
> 能否发一下你的消息体实际实现，有试过加token可行吗

![image](https://github.com/RayWangQvQ/BiliBiliToolPro/assets/93320886/7dfc6376-3844-431e-a6c3-4db56aed708c)
export Ray_Serilog__WriteTo__8__Args__api="http://172.18.0.1:17218/send_group_msg?access_token=161122"
token加在这个变量里面

**Comment by adnogpu** [comment]
> > > 我解决了，按照上面仁兄提供的建议，方案1测试通过了，方案2不行
> > > > 如果你没解决的话，我推荐一个可以暂且做规避的方案，就是用coolpush的私有化部署，它现在就是基于go-cqhttp做的实现。 可以不用coolpush自定义的软件，直接用官方版本，在coolpush中绑定qq和私有化部署的ip、token，也可以发送。 不过前提是你得有公网ip。。或者你能实现内网穿透也行。 缺点就是消息中的\n不能正确转义
> > 
> > 
> > 能否发一下你的消息体实际实现，有试过加token可行吗
> 
> ![image](https://private-user-images.githubusercontent.com/93320886/302968799-7dfc6376-3844-431e-a6c3-4db56aed708c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2NjI0NzEsIm5iZiI6MTcyMjY2MjE3MSwicGF0aCI6Ii85MzMyMDg4Ni8zMDI5Njg3OTktN2RmYzYzNzYtMzg0NC00MzFlLWE2YzMtNGRiNTZhZWQ3MDhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAzVDA1MTYxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2YzUzMmNkNDkyZDVlOWU3NGM0YTU0ZTRjYjJjMWI1YmM2NDkwMTVjNGUzOTZhMjQxMDQ2ZWI4ZjQxYTMzN2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IhAUxyk3N6B_3oTnQvy2pT20_8Hdx_2bgz3SsV8oSN0) export Ray_Serilog__WriteTo__8__Args__api="http://172.18.0.1:17218/send_group_msg?access_token=161122" token加在这个变量里面

我和你配置一样但是我这推送的时候提示 
2024-08-03T05:02:15.6238292Z Response content: {"status":"failed","retcode":200,"data":null,"message":"消息体无法解析，请检查是否发送了不支持的消息类型","wording":"消息体无法解析，请检查是否发送了不支持的消息类型","echo":null}.
