### ISSUE TITLE
【其他】现在CK两天就过期怎么处理？

### ISSUE THREAD

**Issue by tx1538** [RayWangQvQ/BiliBiliToolPro#289]
（提issue前请先确认没有其他人提过相同的议题）
而且没有推送，不知道什么时候过期的

**Comment by 1772440725** [comment]
隐身模式下抓ck试试

**Comment by RayWangQvQ** [comment]
用扫码登录（ https://github.com/RayWangQvQ/BiliBiliToolPro/issues/351 ），时效半年

**Comment by Remonli** [comment]
@RayWangQvQ  linux服务器本地部署的话，扫码登录的cookie存在哪儿了呢？ 我想把他复制回去appsettings.Production.json. 还是我可以把appsettings.Production.json文件中cookie的部分省掉，其他地方自定义配置？

**Comment by RayWangQvQ** [comment]
在cookies.json里，这个文件优先级最高，计划只用来存cookie。

其他地方的cookie可以删除，或者移到这个文件里。
