### ISSUE TITLE
【Bug】更换新镜像后日志提示无权限运行

### ISSUE THREAD

**Issue by bjl101501** [RayWangQvQ/BiliBiliToolPro#29]
版本号：最新
运行环境：Docker on linux, amd64

问题描述：佬，更换新镜像后运行，日志提示/bin/bash: line 1: /app/entry.sh: Permission denied，容器也进不去，使用docker exec -it bilibili_tool_pro bash，一直提示Container is restarting, wait until the container is running

日志信息：
![image](https://user-images.githubusercontent.com/82082262/157428889-672822e5-af30-4a19-a0fa-9b78011abd4d.png)
![image](https://user-images.githubusercontent.com/82082262/157429016-e587efff-559b-4b83-9b02-f9b999fb16d7.png)

**Comment by RayWangQvQ** [comment]
已修复。

```
docker compose down
docker pull zai7lou/bilibili_tool_pro
docker compose up -d
```

**Comment by bjl101501** [comment]
欧了
