### ISSUE TITLE
【建议】【已解决】推送方式期望增加go-cqhttp，或请教告知自定义API实现方式

### ISSUE THREAD

**Issue by hfuulzy** [RayWangQvQ/BiliBiliToolPro#290]
建议内容：
作为为数不多的支持推送到QQ的推送工具来说，之前的coolpush已经可以放弃了，因为现在它也是基于go-cqhttp做了私有化部署版本。
十分期待能添加此推送工具
项目地址：
https://github.com/Mrs4s/go-cqhttp
-----------
参考2楼回复

**Comment by dextersa** [comment]
go-cqhttp，理论上自定义API可以实现，但目前似乎有点问题，我用自定义API尝试实现，但遇到了一些bug，发布者正在尝试解决。#285
