### ISSUE TITLE
【Bug】任务无法运行.   运算符“==”无法应用于“int”和“VipType”类型的操作数 

### ISSUE THREAD

**Issue by wimotek** [RayWangQvQ/BiliBiliToolPro#293]
repo目录: /ql/data/repo
bili仓库目录: /ql/data/repo/raywangqvq_bilibilitoolpro

/ql/data/repo/raywangqvq_bilibilitoolpro/src/Ray.BiliBiliTool.Application/VipBigPointAppService.cs(40,17): error CS0019: 运算符“==”无法应用于“int”和“VipType”类型的操作数 [/ql/data/repo/raywangqvq_bilibilitoolpro/src/Ray.BiliBiliTool.Application/Ray.BiliBiliTool.Application.csproj]

生成失败。请修复生成错误并重新运行。

**Comment by wimotek** [comment]
装了develop分支 可以 没有报错.  同时main分支的也可以运行. 但是有报错.  报错如何:

repo目录: /ql/data/repo
bili仓库目录: /ql/data/repo/raywangqvq_bilibilitoolpro

/ql/data/repo/raywangqvq_bilibilitoolpro/src/Ray.Serilog.Sinks/Ray.Serilog.Sinks.GotifyBatched/GotifyConfigurationExtensions.cs(17,46): warning CS8625: 无法将 null 字面量转换为非 null 的引用类型。 [/ql/data/repo/raywangqvq_bilibilitoolpro/src/Ray.Serilog.Sinks/Ray.Serilog.Sinks.GotifyBatched/Ray.Serilog.Sinks.GotifyBatched.csproj]
[10:51:54 INF] BiliBiliToolPro 开始运行...

[10:51:55 INF] 【目标任务】Daily
[10:51:55 INF] 【账号个数】2个

[10:51:55 INF] ######### 账号 1 #########

**Comment by RayWangQvQ** [comment]
当前版本已解决。
