### ISSUE TITLE
【建议】建议增加LV6后不投币的配置项

### ISSUE THREAD

**Issue by cluom** [RayWangQvQ/BiliBiliToolPro#300]
建议可以添加一个布尔值的配置项 设置后可以控制六级后是否继续投币获取经验
因为多账号时NumberOfCoins配置会给所有账号生效 那么不到六级的账号每日获取经验就变少了 所以萌生了这个想法

**Comment by RayWangQvQ** [comment]
Good idea, its better than hard code.

**Comment by RayWangQvQ** [comment]
文档已更新
