### ISSUE TITLE
【Bug】视频分享失败，原因: 账号异常，操作失败

### ISSUE THREAD

**Issue by Remonli** [RayWangQvQ/BiliBiliToolPro#31]
版本号：RayBiliBiliToolPro-v0.0.5 in Production env.
运行环境：Linux -x64 本地，

问题描述： 偶尔会提示视频分享失败，账号异常，但实际账号没有问题。该错误也并非每天都会产生，大概20~30%概率吧。

日志信息：

ℹ️ ---开始 观看、分享视频 ---
ℹ️ 【随机视频】哈哈，小猫咪能有什么坏心眼呢
ℹ️ 今天已经观看过了，不需要再看啦
❗️ 视频分享失败，原因: 账号异常，操作失败
ℹ️ ----------结束----------

**Comment by mrshengzyzy** [comment]
same issue

**Comment by youzouzach** [comment]
same issue

**Comment by RayWangQvQ** [comment]
由 #228 统一追踪，暂时先关闭该issus

**Comment by RayWangQvQ** [comment]
已修复
