### ISSUE TITLE
error MSB4018: “ResolvePackageAssets”任务意外失败

### ISSUE THREAD

**Issue by Toylee2019** [RayWangQvQ/BiliBiliToolPro#313]
## 开始执行... 2022-11-14 01:02:32

# 正在应用 优先Cookie 模式...
repo目录: /ql/data/repo
bili仓库目录: /ql/data/repo/RayWangQvQ_BiliBiliToolPro_develop

/home/dotnet/sdk/6.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): error MSB4018: “ResolvePackageAssets”任务意外失败。 [/ql/data/repo/RayWangQvQ_BiliBiliToolPro_develop/src/Ray.BiliBiliTool.Console/Ray.BiliBiliTool.Console.csproj]
/home/dotnet/sdk/6.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): error MSB4018: System.IndexOutOfRangeException: Index was outside the bounds of the array. [/ql/data/repo/RayWangQvQ_BiliBiliToolPro_develop/src/Ray.BiliBiliTool.Console/Ray.BiliBiliTool.Console.csproj]
/home/dotnet/sdk/6.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader.ReadItem() [/ql/data/repo/RayWangQvQ_BiliBiliToolPro_develop/src/Ray.BiliBiliTool.Console/Ray.BiliBiliTool.Console.csproj]
/home/dotnet/sdk/6.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader.ReadItemGroup() [/ql/data/repo/RayWangQvQ_BiliBiliToolPro_develop/src/Ray.BiliBiliTool.Console/Ray.BiliBiliTool.Console.csproj]
/home/dotnet/sdk/6.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ReadItemGroups() [/ql/data/repo/RayWangQvQ_BiliBiliToolPro_develop/src/Ray.BiliBiliTool.Console/Ray.BiliBiliTool.Console.csproj]
/home/dotnet/sdk/6.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): error MSB4018:    at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ExecuteCore() [/ql/data/repo/RayWangQvQ_BiliBiliToolPro_develop/src/Ray.BiliBiliTool.Console/Ray.BiliBiliTool.Console.csproj]
/home/dotnet/sdk/6.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): error MSB4018:    at Microsoft.NET.Build.Tasks.TaskBase.Execute() [/ql/data/repo/RayWangQvQ_BiliBiliToolPro_develop/src/Ray.BiliBiliTool.Console/Ray.BiliBiliTool.Console.csproj]
/home/dotnet/sdk/6.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/ql/data/repo/RayWangQvQ_BiliBiliToolPro_develop/src/Ray.BiliBiliTool.Console/Ray.BiliBiliTool.Console.csproj]
/home/dotnet/sdk/6.0.201/Sdks/Microsoft.NET.Sdk/targets/Microsoft.PackageDependencyResolution.targets(267,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [/ql/data/repo/RayWangQvQ_BiliBiliToolPro_develop/src/Ray.BiliBiliTool.Console/Ray.BiliBiliTool.Console.csproj]

生成失败。请修复生成错误并重新运行。

**Comment by Toylee2019** [comment]
请指点一下 什么情况

**Comment by Lisuyang426** [comment]
执行的天选抽奖任务执行一段时间后就无法关注该主播。不知是什么原因



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月14日(周一) 凌晨1:04
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [RayWangQvQ/BiliBiliToolPro] 【Bug】请在标题中清晰地概述你要反馈的异常或缺陷 (Issue #313)




 
请指点一下 什么情况

**Comment by Toylee2019** [comment]
shh进入openwrt cd /etc/PWD  rm -r ql删除了ql的全部文件后 重新部署后解决

**Comment by RayWangQvQ** [comment]
每次执行前，在脚本里先把bin和obj文件夹删了，应该就可以了。

下个版本我来加。

**Comment by RayWangQvQ** [comment]
重新拉下库，会多一个任务，然后跑一下试试：

![image](https://user-images.githubusercontent.com/31154238/201673599-599ad177-7771-4c3e-9d64-ada85469e6fb.png)
