### ISSUE TITLE
【Bug】青龙问题

### ISSUE THREAD

**Issue by i2stay** [RayWangQvQ/BiliBiliToolPro#315]
版本号：（青龙2.13.2）
运行环境：（docker）

问题描述：（从你昨天更新之后今天就开始报错了怎么回事？这个是啥报错，以前也没有这种报错）

日志信息：![image](https://user-images.githubusercontent.com/74423471/201720750-c8b073cf-f38c-4daa-9a2d-ffd7f7e3744d.png)

**Comment by 805828526** [comment]
一样

**Comment by i2stay** [comment]
没人处理？？？

**Comment by cnxjg** [comment]
你是怎么解决的，我2.15.0一样提示这个

**Comment by i2stay** [comment]
> 你是怎么解决的，我2.15.0一样提示这个

没解决啊，等作者怎么说，

**Comment by cnxjg** [comment]
只有等了

**Comment by RayWangQvQ** [comment]
这是没拉库吧？找不到代码

**Comment by i2stay** [comment]
> 这是没拉库吧？找不到代码

我目录不在root，我目录在opt

**Comment by i2stay** [comment]
> 这是没拉库吧？找不到代码

昨天更新之后就不行了，之前一直一直一直都可以

**Comment by RayWangQvQ** [comment]
啊我的错，master和先行版都去扫描先行版目录了，我来改下

**Comment by i2stay** [comment]
> 啊我的错，master和先行版都去扫描先行版目录了，我来改下

难怪！！！！

**Comment by i2stay** [comment]
> 啊我的错，master和先行版都去扫描先行版目录了，我来改下

可以了，跟我说，我拉试试

**Comment by RayWangQvQ** [comment]
好了
![image](https://user-images.githubusercontent.com/31154238/201919338-e0204194-b78d-42c0-a2b8-c75209f1a0e1.png)
