### ISSUE TITLE
【bug】未能从远程源

### ISSUE THREAD

**Issue by liuranya** [RayWangQvQ/BiliBiliToolPro#317]
repo目录: /ql/repo
bili仓库目录: /ql/repo/RayWangQvQ_BiliBiliToolPro

/ql/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.Serilog.Sinks/Ray.Serilog.Sinks.Batched/Ray.Serilog.Sinks.Batched.csproj : error NU1301: 未能从远程源“https://api.nuget.org/v3-flatcontainer/serilog/index.json”检索有关“Serilog”的信息。 [/ql/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/Ray.BiliBiliTool.Console.csproj]
/ql/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Application/Ray.BiliBiliTool.Application.csproj : error NU1301: 未能从远程源“https://api.nuget.org/v3-flatcontainer/microsoft.extensions.dependencyinjection.abstractions/index.json”检索有关“Microsoft.Extensions.DependencyInjection.Abstractions”的信息。 [/ql/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/Ray.BiliBiliTool.Console.csproj]
/ql/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.Serilog.Sinks/Ray.Serilog.Sinks.MicrosoftTeamsBatched/Ray.Serilog.Sinks.MicrosoftTeamsBatched.csproj : error NU1301: 未能从远程源“https://api.nuget.org/v3-flatcontainer/microsoft.extensions.configuration.abstractions/index.json”检索有关“Microsoft.Extensions.Configuration.Abstractions”的信息。

**Comment by RayWangQvQ** [comment]
![image](https://user-images.githubusercontent.com/31154238/201953749-b46509de-c906-4cf8-94c5-af33048cd999.png)

**Comment by liuranya** [comment]
## 开始执行... 2022-11-15 20:35:35


repo目录: /ql/repo
bili仓库目录: /ql/repo/RayWangQvQ_BiliBiliToolPro

清理缓存...


## 执行结束... 2022-11-15 20:35:35 耗时 0 秒

**Comment by liuranya** [comment]
运行过了，没有作用

**Comment by RayWangQvQ** [comment]
api.nuget.org这个域名你虚机里确定能ping的通？

**Comment by liuranya** [comment]
不通，奇怪

**Comment by liuranya** [comment]
ping api.nuget.org
PING api.nuget.org (23.101.10.141): 56 data bytes

**Comment by liuranya** [comment]
root@check:/ql $ dotnet --list-sdks
6.0.403 [/root/.dotnet/sdk]

但是这个环境是安装成的

**Comment by RayWangQvQ** [comment]
那就是网络问题了，可以试试打开代理或关闭已有代理。
