### ISSUE TITLE
【建议】增加企业微信应用推送

### ISSUE THREAD

**Issue by rogueme** [RayWangQvQ/BiliBiliToolPro#32]
企业微信机器人只能企业微信app能接收消息,但企业微信应用的话可以微信接收甚至可以设定接收人范围,感觉比企业微信机器人更方便更好用,第三方的又有各种限制!如果太麻烦的话麻烦添加下青龙面板的推送接口,青龙面板的推送接口还是挺全的!

**Comment by sunsikai** [comment]
附议

**Comment by RayWangQvQ** [comment]
已于`v0.1.0`版本新增企业微信应用推送

![image](https://user-images.githubusercontent.com/31154238/161430809-57932e22-a0b7-43a8-95e5-3ac6b367dc9a.png)

![image](https://user-images.githubusercontent.com/31154238/161430970-71d93de7-23ae-47ea-8e35-32a1b1d06982.png)

**Comment by rogueme** [comment]
@RayWangQvQ 请更新下企业微信应用推送教程的环境变量,目前是错误的,没有加上前缀Ray_,目测微软的推送好像也没加上,经测试,拿corpId举例,完整的环境变量名称应为Ray_Serilog__WriteTo__11__Args__corpId才收到推送而Serilog__WriteTo__11__Args__corpId是收不到推送的!

**Comment by DoveBoy** [comment]
@rogueme TG的推送似乎也是有问题的，环境变量配置`Ray_Serilog__WriteTo__3__Args__chatId``Ray_Serilog__WriteTo__3__Args__botToken`也不行

**Comment by RayWangQvQ** [comment]
`v0.1.1`文档已更新
