### ISSUE TITLE
 dotnet: command not found

### ISSUE THREAD

**Issue by stengger** [RayWangQvQ/BiliBiliToolPro#323]
运行环境：青龙 centos7

问题描述：更新最新版后报错 已安装dotnet

日志信息：

repo目录: /ql/repo
bili仓库目录: /ql/repo/raywangqvq_bilibilitoolpro

bili_task_daily.sh: line 9: dotnet: command not found

**Comment by RayWangQvQ** [comment]
https://github.com/RayWangQvQ/BiliBiliToolPro/issues/316
