### ISSUE TITLE
【求助】获取telegram机器人的chatId返回404

### ISSUE THREAD

**Issue by fmz200** [RayWangQvQ/BiliBiliToolPro#327]
我的请求链接如下：
```
https://api.telegram.org/bot{5293494076:AAGP2TKMY8sVO6htcVoNKA36hyW7gkcbruc}/getUpdates
```
返回内容如下：
```json
{
    ok: false,
    error_code: 404,
    description: "Not Found"
}
```
![image](https://user-images.githubusercontent.com/57740735/203342437-7c0b6ce5-7d40-4475-b21f-0aeeea201c44.png)

有没有大佬遇到的？😅

**Comment by catlair** [comment]
https://api.telegram.org/bot5293494076:AAGP2TKMY8sVO6htcVoNKA36hyW7gkcbruc/getUpdates

**Comment by fmz200** [comment]
> https://api.telegram.org/bot5293494076:AAGP2TKMY8sVO6htcVoNKA36hyW7gkcbruc/getUpdates

可以了，谢谢😁
