### ISSUE TITLE
青龙拉库问题

### ISSUE THREAD

**Issue by cz15632** [RayWangQvQ/BiliBiliToolPro#329]
大佬，我的服务器最近重置了一下，用的青龙面板重新拉库，显示拉库成功，但是文件夹里面只有notify和sendnotify两个js文件，并且面板里面也不会添加任务，尝试更换代理、反复尝试多次拉库都是这样，但是更换先行版可以正常添加任务，这个是我操作问题吗还是

**Comment by RayWangQvQ** [comment]
https://github.com/RayWangQvQ/BiliBiliToolPro/blob/main/qinglong/README.md
