### ISSUE TITLE
【Bug】启动映像后只会测试cookie不会执行每日任务

### ISSUE THREAD

**Issue by momo325** [RayWangQvQ/BiliBiliToolPro#330]
版本号：v0.2.3 in Production env.今晚刚设置的
运行环境：群晖docker
问题描述：启动映像后只会测试cookie不会执行每日任务
日志信息：
![](http://test.imgurl.org/imgs/2022/11/24/2839770b23d70204.jpg)

**Comment by RayWangQvQ** [comment]
其他任务是定时跑的，想手动跑，可以进容器用命令触发
