### ISSUE TITLE
cookie失效不会推送，建议推送下

### ISSUE THREAD

**Issue by momo325** [RayWangQvQ/BiliBiliToolPro#333]
只推送了成功的，而且cookie一天就失效了/(ㄒoㄒ)/~~
但本地浏览器的cookie却还正常
[![zNPeUS.jpg](https://s1.ax1x.com/2022/11/26/zNPeUS.jpg)](https://imgse.com/i/zNPeUS)

**Comment by momo325** [comment]
我的意思是cookie失效后执行任务失败并不会通过server酱推送，希望cookie失效/执行任务失败也可以通过server酱通知

**Comment by RayWangQvQ** [comment]
配置推送了吗？配了都会推送的，cookie过不过期都会推

![image](https://user-images.githubusercontent.com/31154238/206910113-200b9e6e-e0fe-4e6b-bd20-9acb416e1103.png)
