### ISSUE TITLE
【其他】添加多账号失败

### ISSUE THREAD

**Issue by JunWeiLi233** [RayWangQvQ/BiliBiliToolPro#334]
请问是以这种形式添加多账号吗？
  //Cookie集合，取自浏览器，必填
  "BiliBiliCookies": [ //Cookie字符串集合，登录bilibili后F12获取，形如"_uuid=abcd; buvid3=1234; sid=abc123"
      “_uuid=abcd; buvid3=1234; sid=abc123”,
      “_uuid=abcd; buvid3=1234; sid=abc123”,
      “_uuid=abcd; buvid3=1234; sid=abc123”,

  ],

**Comment by RayWangQvQ** [comment]
是的，当前支持扫码登录了，直接扫码就行，不需要关系怎么配置了。
