### ISSUE TITLE
Actions手动运行后，腾讯云函数没有创建相关函数服务。

### ISSUE THREAD

**Issue by mofeisi23** [RayWangQvQ/BiliBiliToolPro#34]
运行环境：腾讯云函数
问题描述：auto-deploy-tencent-scf运行完成，云函数没有创建。
![360截图20220315200859508](https://user-images.githubusercontent.com/100343785/158377101-6c394d74-56d4-4e53-af08-f77720d1d086.jpg)

**Comment by catlair** [comment]
这个是你的配置错误，其实部署是失败的。已经提 issues 了，可能下个版本就修复了

**Comment by nlfc001** [comment]
为什么我测试半天都没反应
