### ISSUE TITLE
钉钉收不到通知，已经填写token

### ISSUE THREAD

**Issue by senqi77** [RayWangQvQ/BiliBiliToolPro#340]
![image](https://user-images.githubusercontent.com/83161455/204504229-e2f6c7b8-6fb1-4eb5-be26-a5bfef5c4977.png)
请问我已经在配置文件里，系统设置里的通知配置里，都填写了钉钉的token，保存的时候都会收到钉钉通知：测试
但是在运行任务后，没有通知？
上方图里，脚本配置里也要填写token吗？我也试过填写，但是也不通知，折腾一下午了，求个大佬解答一下，万分感谢

**Comment by RayWangQvQ** [comment]
你截图上的是青龙的推送，shell脚本写的，跟bili不是一个系统。

bili的钉钉推送可以看这里：https://github.com/RayWangQvQ/BiliBiliToolPro/blob/main/docs/configuration.md#364-%E9%92%89%E9%92%89%E6%9C%BA%E5%99%A8%E4%BA%BA

**Comment by senqi77** [comment]
请问是这样吗大佬

**Comment by senqi77** [comment]
![image](https://user-images.githubusercontent.com/83161455/206862572-4447456e-3d4e-430c-8bc3-38c2491d7adf.png)
请问是这样吗大佬，这样添加变量还是没推送啊

**Comment by RayWangQvQ** [comment]
新建机器人时，安全策略你选的什么

**Comment by RayWangQvQ** [comment]
新建机器人时有个安全策略选项，选“关键字”：
![image](https://user-images.githubusercontent.com/31154238/206863288-df176f2e-17fc-4e6e-b791-fd8fb67b952e.png)


还有推送的时候，日志里会显示推送日志，可以用来debug：
![image](https://user-images.githubusercontent.com/31154238/206863276-ff50f44f-5206-49da-b42b-fa994a7ae863.png)

**Comment by senqi77** [comment]
好了好了，经过测试，就是值那里需要填写完整的机器人url，我之前只填写了token那串数字

**Comment by senqi77** [comment]
> 新建机器人时有个安全策略选项，选“关键字”： ![image](https://user-images.githubusercontent.com/31154238/206863288-df176f2e-17fc-4e6e-b791-fd8fb67b952e.png)
> 
> 还有推送的时候，日志里会显示推送日志，可以用来debug： ![image](https://user-images.githubusercontent.com/31154238/206863276-ff50f44f-5206-49da-b42b-fa994a7ae863.png)

感谢大佬，现在没问题了
