### ISSUE TITLE
【Bug】请支持 Ctrl+C 退出

### ISSUE THREAD

**Issue by seiuneko** [RayWangQvQ/BiliBiliToolPro#344]
版本号：0.2.3.r7.gcc45c4f
运行环境：Arch Linux
问题描述：在 Linux 执行时按 Ctrl+C 无法退出程序。

**Comment by RayWangQvQ** [comment]
OK

**Comment by RayWangQvQ** [comment]
学习了一波，原因是dotnet启动过程是，先构建host，然后遍历已注册的所有HostedService，挨个执行StartAsync，全部执行结束后，被视为启动成功。在这之后，Console会监控Ctrl+C事件，触发后会终止应用（HostApplication）。

当前bilibili_tool是利用一个BiliHostedService，在它StartAsync里跑任务，也就是跑完任务才算启动结束（也是bili任务的终止），所以在跑任务过程中没法Ctrl+C退出。

解决方案的话，我想到2个：

1. 在启动过程中自己想办法监控Ctrl+C事件（但设计上有点冗余和丑陋）
2. 想办法把执行任务的逻辑从HostedService分离出去，让应用先启动完成，然后在去执行任务（比如把任务交给Hangfire或Quartz去触发）

**Comment by RayWangQvQ** [comment]
打脸了，其实是一直在监控着`Ctrl+C`的（由`ConsoleLifetime`），没触发是因为没有传递`CancellationToken`

**Comment by RayWangQvQ** [comment]
已于`v1.0.0`发布支持
