### ISSUE TITLE
【建议】扫码登录并更新cookie

### ISSUE THREAD

**Issue by KevinXu07** [RayWangQvQ/BiliBiliToolPro#351]
经常失效，手动配置很麻烦

**Comment by RayWangQvQ** [comment]
已于0.3.0版本发布扫码登录功能，基于 @AFUL1991 朋友提供的api，重构了下，使之支持多部署平台、多账号。

在青龙面板里，扫码后会将cookie更新到青龙的环境变量里：

![qinglong-login.png](https://raw.githubusercontent.com/RayWangQvQ/BiliBiliToolPro/main/docs/imgs/qinglong-login.png)

![qinglong-env.png](https://raw.githubusercontent.com/RayWangQvQ/BiliBiliToolPro/main/docs/imgs/qinglong-env.png)

在docker或其他平台里，扫码后会将cookie存储到配置文件中：

![docker-login.png](https://raw.githubusercontent.com/RayWangQvQ/BiliBiliToolPro/main/docs/imgs/docker-login.png)
