### ISSUE TITLE
手机版青龙无法定时运行

### ISSUE THREAD

**Issue by lll666666** [RayWangQvQ/BiliBiliToolPro#359]
（提issue前请先确认没有其他人提过相同的议题）
![image](https://user-images.githubusercontent.com/98231341/207022317-2df9bd92-f085-44f9-8243-bede2e1cfbcb.png)
定时运行就会这样，手动运行就正常，有谁知道怎么解决吗？

**Comment by RayWangQvQ** [comment]
你的青龙环境咋装的？为啥`$QL_DIR`是根目录？

**Comment by lll666666** [comment]
> 你的青龙环境咋装的？为啥`$QL_DIR`是根目录？

我是用手机刷的青龙面具

**Comment by RayWangQvQ** [comment]
手动成功的日志来一个

**Comment by lll666666** [comment]
> 手动成功的日志来一个
![image](https://user-images.githubusercontent.com/98231341/207511835-b305fd0e-b08e-44d8-b57b-82ea276c814d.png)
![image](https://user-images.githubusercontent.com/98231341/207511936-f793a16f-385e-49e4-8ca0-9cb26a42c6fa.png)

**Comment by RayWangQvQ** [comment]
那说明定时任务没有读取到环境变量。

你在青龙的环境变量页，配置上试试。

Key: QL_DIR
Value: /ql

**Comment by lll666666** [comment]
> 那说明定时任务没有读取到环境变量。
> 
> 你在青龙的环境变量页，配置上试试。
> 
> Key: QL_DIR Value: /ql
> 
> ![image](https://user-images.githubusercontent.com/31154238/207551754-c7c95ba1-aab7-4b26-b71a-177b8c995fd1.png)

可以了，谢谢
