### ISSUE TITLE
想请教一下青龙如何打开银瓜子兑换硬币

### ISSUE THREAD

**Issue by yihanxx** [RayWangQvQ/BiliBiliToolPro#36]
有相关变量吗，脚本日志提示：已配置为关闭，跳过

**Comment by Leon19960120** [comment]
同问一下，哪里去设置这个参数，谢谢

**Comment by h7ml** [comment]
> 同问一下，哪里去设置这个参数，谢谢

应该是设置 `Ray_DailyTaskConfig__DayOfExchangeSilver2Coin`
 [每月几号进行直播中心银瓜子兑换硬币](https://github.com/RayWangQvQ/BiliBiliToolPro/blob/5cd2aa1de0230efb31717ee314dbb2c79e73501f/docs/configuration.md#339-%E6%AF%8F%E6%9C%88%E5%87%A0%E5%8F%B7%E8%BF%9B%E8%A1%8C%E7%9B%B4%E6%92%AD%E4%B8%AD%E5%BF%83%E9%93%B6%E7%93%9C%E5%AD%90%E5%85%91%E6%8D%A2%E7%A1%AC%E5%B8%81)
