### ISSUE TITLE
【其他】云函数同步失败

### ISSUE THREAD

**Issue by zonbar** [RayWangQvQ/BiliBiliToolPro#360]
secret是不是以后就不能用了，只能用环境变量？
![image](https://user-images.githubusercontent.com/44555226/207038164-66cadc8e-cead-41aa-9c4b-b4ed001ea562.png)

**Comment by RayWangQvQ** [comment]
![image](https://user-images.githubusercontent.com/31154238/207327428-ef81b6cb-ca5e-4c9b-900f-bc9cd489c7f1.png)

格式错误，检查下格式

**Comment by zonbar** [comment]
大意了，ok了
