### ISSUE TITLE
【Bug】DockerCompose运行Login问题以及临时解决方案

### ISSUE THREAD

**Issue by yblpoi** [RayWangQvQ/BiliBiliToolPro#361]
版本号：

```
image:
    - zai7lou/bilibili_tool_pro:latest
```
运行环境：
    - ARM64 
    - 树莓派4B 4GB 
    - docker-compose version: '2.2'

问题描述：
配置compose文件会影响Login任务写入cookies.json

```
volumes: 
    -  ./cookies.json:/app/cookies.json
 ```

 配置了这一项后可能导致无法正常写入cookies.json。出现拒绝访问的错误。

```
[00:16:48 INF] ---开始 添加ck到json配置文件 ---
[00:16:48 INF] 目标json地址：/app/cookies.json
[00:16:48 ERR] 程序发生异常：Access to the path '/app/cookies.json' is denied.
[00:16:48 ERR] 程序发生异常：Access to the path '/app/cookies.json' is denied.
[00:16:48 ERR] 程序异常终止，原因：Access to the path '/app/cookies.json' is denied.
[00:16:48 INF] 运行环境：Production
[00:16:48 INF] 应用目录：/app/
```

注释掉这一行后，正常运行~

```
[00:18:22 INF] ---开始 添加ck到json配置文件 ---
[00:18:22 INF] 目标json地址：/app/cookies.json
[00:18:22 INF] 未配置过cookie，初始化并新增
[00:18:22 INF] 新增成功！
[00:18:22 INF] ----------------结束----------------
```

截图如下：
    - 报错
![报错](https://user-images.githubusercontent.com/66136793/207100098-eb9fd7c2-5b5a-43ba-bc3f-4a36566e7e4d.png)

    - 修改
![修改代码1](https://user-images.githubusercontent.com/66136793/207101040-98012a1a-e5c6-4f63-a9a0-7f058736ab1e.png)

![修改代码](https://user-images.githubusercontent.com/66136793/207100159-1d1af6cb-6a38-4c55-95db-68c7b898f659.png)

    - 成功
 
![成功](https://user-images.githubusercontent.com/66136793/207100189-1d0be858-9e5b-4978-aef3-dfa40aac42d7.png)

**Comment by RayWangQvQ** [comment]
奇怪了，只是挂载到宿主机，应该不会占用才对。

不挂载出来，重启容器cookie就丢了。

**Comment by RayWangQvQ** [comment]
关于挂载cookies.json，我再Win上用docker测了下，没有问题

![image](https://user-images.githubusercontent.com/31154238/207564520-17c8d77e-b275-40ef-8d0e-c2fe62318a78.png)

**Comment by RayWangQvQ** [comment]
Linux试了下，也是正常的

![image](https://user-images.githubusercontent.com/31154238/207567166-65818bc6-d036-4279-8176-a2a030e920bc.png)

**Comment by yblpoi** [comment]
那应该是Linux上权限的锅

**Comment by yblpoi** [comment]
我再试试看

**Comment by moonipulate** [comment]
root下
docker compose down -v后 改用docker run重新create后 可以正常set cookie了

**Comment by yblpoi** [comment]
现在正常了，幸苦幸苦！！！
