### ISSUE TITLE
【其他】docker-compose自定义配置-定时任务 是否存在问题

### ISSUE THREAD

**Issue by simpread** [RayWangQvQ/BiliBiliToolPro#379]
疑惑点：不**全部配置** 默认[docker-compose.yml](https://github.com/RayWangQvQ/BiliBiliToolPro/blob/main/docker/sample/docker-compose.yml)的#定时任务 17-21行
```
Ray_DailyTaskConfig__Cron=
Ray_LiveLotteryTaskConfig__Cron=
Ray_UnfollowBatchedTaskConfig__Cron=
Ray_VipBigPointConfig__Cron=
```
就会启用默认的定时任务配置。

1. [相关文档](https://github.com/RayWangQvQ/BiliBiliToolPro/blob/main/docs/configuration.md) 的3.7.4定时任务里，描述如下
`以下环境变量的值应为有效的 cron 表达式。
当被设置时，对应定时任务将开启。`
但是实际中，对于不想启用的：不管是留空，还是整行删除，均会导致启用默认设置，并覆盖掉自定义部分。另外，通过docker指令的方法安装似乎同样出现这种情况。

```
# 日志
“[step 1/4]导入环境变量

=>完成

[step 2/4]配置cron定时任务

=>使用默认的定时任务配置

SHELL=/bin/bash

BASH_ENV=/etc/cron.env

0 15 * * * dotnet /app/Ray.BiliBiliTool.Console.dll --runTasks=Daily >> /var/log/cron.log

0 22 * * * dotnet /app/Ray.BiliBiliTool.Console.dll --runTasks=LiveLottery >> /var/log/cron.log

7 1 * * * dotnet /app/Ray.BiliBiliTool.Console.dll --runTasks=VipBigPoint >> /var/log/cron.log

=>完成

=>使用默认的定时任务配置”
```
2. 个人做法：#定时任务 全部配置，把不想开启的设置成一年的某天。
本人只是小白，欢迎交流( ˘ 3˘)♥ (

**Comment by hilphen** [comment]
我在Docker容器里面安装，无论是设置定时任务变量还是直接修改默认定时任务文件，都会陷入无限重启

**Comment by simpread** [comment]
> 我在Docker容器里面安装，无论是设置定时任务变量还是直接修改默认定时任务文件，都会陷入无限重启

看看日志呗。实在不行docker里装青龙再跑这个也行的

**Comment by hilphen** [comment]
> > 我在Docker容器里面安装，无论是设置定时任务变量还是直接修改默认定时任务文件，都会陷入无限重启
> 
> 看看日志呗。实在不行docker里装青龙再跑这个也行的

日志就是一开始导入用户自定义定时设置就开始重启，默认没修改过的定时任务就能过。
我用的群晖的Docker，找天虚拟个Linux再试试吧
至于再在容器里面装个青龙，这种套娃行为，不太想这么干

```
[step 2/4]配置cron定时任务
=>使用用户指定的定时任务配置
SHELL=/bin/bash
BASH_ENV=/etc/cron.env
0 15 * * * cd /app && dotnet Ray.BiliBiliTool.Console.dll --runTasks=Daily
0 30 * * * cd /app && dotnet Ray.BiliBiliTool.Console.dll --runTasks=LiveLottery
0 6 1 * * cd /app && dotnet Ray.BiliBiliTool.Console.dll --runTasks=UnfollowBatched
"/etc/cron.d/bilicron":3: bad hour
errors in crontab file, can't install.
```

**Comment by simpread** [comment]
> > > 我在Docker容器里面安装，无论是设置定时任务变量还是直接修改默认定时任务文件，都会陷入无限重启
> > 
> > 
> > 看看日志呗。实在不行docker里装青龙再跑这个也行的
> 
> 日志就是一开始导入用户自定义定时设置就开始重启，默认没修改过的定时任务就能过。 我用的群晖的Docker，找天虚拟个Linux再试试吧 至于再在容器里面装个青龙，这种套娃行为，不太想这么干
> 
> ```
> [step 2/4]配置cron定时任务
> =>使用用户指定的定时任务配置
> SHELL=/bin/bash
> BASH_ENV=/etc/cron.env
> 0 15 * * * cd /app && dotnet Ray.BiliBiliTool.Console.dll --runTasks=Daily
> 0 30 * * * cd /app && dotnet Ray.BiliBiliTool.Console.dll --runTasks=LiveLottery
> 0 6 1 * * cd /app && dotnet Ray.BiliBiliTool.Console.dll --runTasks=UnfollowBatched
> "/etc/cron.d/bilicron":3: bad hour
> errors in crontab file, can't install.
> ```

单纯看日志，错误出在这四项的cron表达式上。我今天也遇到了，不知道是不是同一个问题。通过[在线cron表达式](http://cron.ciding.cc/)不断调整，不留秒那一位，最后弄好了。我贴一下docker-compose里这一部分的设置你试试看
```
# 定时任务
- Ray_DailyTaskConfig__Cron=56 11 * * *
- Ray_LiveLotteryTaskConfig__Cron=15 9 20 8 *
- Ray_UnfollowBatchedTaskConfig__Cron=40 9 20 8 *
- Ray_VipBigPointConfig__Cron=40 12 5 * *

```

**Comment by simpread** [comment]
> > > 我在Docker容器里面安装，无论是设置定时任务变量还是直接修改默认定时任务文件，都会陷入无限重启
> > 
> > 
> > 看看日志呗。实在不行docker里装青龙再跑这个也行的
> 
> 日志就是一开始导入用户自定义定时设置就开始重启，默认没修改过的定时任务就能过。 我用的群晖的Docker，找天虚拟个Linux再试试吧 至于再在容器里面装个青龙，这种套娃行为，不太想这么干
> 
> ```
> [step 2/4]配置cron定时任务
> =>使用用户指定的定时任务配置
> SHELL=/bin/bash
> BASH_ENV=/etc/cron.env
> 0 15 * * * cd /app && dotnet Ray.BiliBiliTool.Console.dll --runTasks=Daily
> 0 30 * * * cd /app && dotnet Ray.BiliBiliTool.Console.dll --runTasks=LiveLottery
> 0 6 1 * * cd /app && dotnet Ray.BiliBiliTool.Console.dll --runTasks=UnfollowBatched
> "/etc/cron.d/bilicron":3: bad hour
> errors in crontab file, can't install.
> ```

我今天试了试在青龙里装，结果遇上了[这问题](https://github.com/RayWangQvQ/BiliBiliToolPro/issues/336)。害，又回docker了(:3[▓▓]

**Comment by hilphen** [comment]
> > > > 我在Docker容器里面安装，无论是设置定时任务变量还是直接修改默认定时任务文件，都会陷入无限重启
> > > 
> > > 
> > > 看看日志呗。实在不行docker里装青龙再跑这个也行的
> > 
> > 
> > 日志就是一开始导入用户自定义定时设置就开始重启，默认没修改过的定时任务就能过。 我用的群晖的Docker，找天虚拟个Linux再试试吧 至于再在容器里面装个青龙，这种套娃行为，不太想这么干
> > ```
> > [step 2/4]配置cron定时任务
> > =>使用用户指定的定时任务配置
> > SHELL=/bin/bash
> > BASH_ENV=/etc/cron.env
> > 0 15 * * * cd /app && dotnet Ray.BiliBiliTool.Console.dll --runTasks=Daily
> > 0 30 * * * cd /app && dotnet Ray.BiliBiliTool.Console.dll --runTasks=LiveLottery
> > 0 6 1 * * cd /app && dotnet Ray.BiliBiliTool.Console.dll --runTasks=UnfollowBatched
> > "/etc/cron.d/bilicron":3: bad hour
> > errors in crontab file, can't install.
> > ```
> 
> 单纯看日志，错误出在这四项的cron表达式上。我今天也遇到了，不知道是不是同一个问题。通过[在线cron表达式](http://cron.ciding.cc/)不断调整，不留秒那一位，最后弄好了。我贴一下docker-compose里这一部分的设置你试试看
> 
> ```
> # 定时任务
> - Ray_DailyTaskConfig__Cron=56 11 * * *
> - Ray_LiveLotteryTaskConfig__Cron=15 9 20 8 *
> - Ray_UnfollowBatchedTaskConfig__Cron=40 9 20 8 *
> - Ray_VipBigPointConfig__Cron=40 12 5 * *
> ```

不行，5位6位我都试了个遍，怎么都过不了，表达式的说明文档都要快翻烂了

**Comment by simpread** [comment]
> > > > > 我在Docker容器里面安装，无论是设置定时任务变量还是直接修改默认定时任务文件，都会陷入无限重启
> > > > 
> > > > 
> > > > 看看日志呗。实在不行docker里装青龙再跑这个也行的
> > > 
> > > 
> > > 日志就是一开始导入用户自定义定时设置就开始重启，默认没修改过的定时任务就能过。 我用的群晖的Docker，找天虚拟个Linux再试试吧 至于再在容器里面装个青龙，这种套娃行为，不太想这么干
> > > ```
> > > [step 2/4]配置cron定时任务
> > > =>使用用户指定的定时任务配置
> > > SHELL=/bin/bash
> > > BASH_ENV=/etc/cron.env
> > > 0 15 * * * cd /app && dotnet Ray.BiliBiliTool.Console.dll --runTasks=Daily
> > > 0 30 * * * cd /app && dotnet Ray.BiliBiliTool.Console.dll --runTasks=LiveLottery
> > > 0 6 1 * * cd /app && dotnet Ray.BiliBiliTool.Console.dll --runTasks=UnfollowBatched
> > > "/etc/cron.d/bilicron":3: bad hour
> > > errors in crontab file, can't install.
> > > ```
> > 
> > 
> > 单纯看日志，错误出在这四项的cron表达式上。我今天也遇到了，不知道是不是同一个问题。通过[在线cron表达式](http://cron.ciding.cc/)不断调整，不留秒那一位，最后弄好了。我贴一下docker-compose里这一部分的设置你试试看
> > ```
> > # 定时任务
> > - Ray_DailyTaskConfig__Cron=56 11 * * *
> > - Ray_LiveLotteryTaskConfig__Cron=15 9 20 8 *
> > - Ray_UnfollowBatchedTaskConfig__Cron=40 9 20 8 *
> > - Ray_VipBigPointConfig__Cron=40 12 5 * *
> > ```
> 
> 不行，5位6位我都试了个遍，怎么都过不了，表达式的说明文档都要快翻烂了

默认的能运行，自定义就拉胯...这。。
可以尝试下：把旧的容器删了，创建一个新的文件夹，在文件夹里
```
#下载文件
wget https://raw.githubusercontent.com/RayWangQvQ/BiliBiliToolPro/main/src/Ray.BiliBiliTool.Console/appsettings.json
wget https://raw.githubusercontent.com/RayWangQvQ/BiliBiliToolPro/main/docker/sample/cookies.json
wget https://raw.githubusercontent.com/RayWangQvQ/BiliBiliToolPro/main/docker/sample/docker-compose.yml
```
只更改`docker-compose.yml`里#定时任务那4个，别的不加也不改。
这样还是没办法那就没辙了┓( ´∀` )┏

**Comment by RayWangQvQ** [comment]
稍后我来重新整理下定时任务的配置逻辑。

目前可以先使用workaround方案：
```
# 进入容器
docker exec -it bili bash

# 查看并编辑定时任务列表（可以使用vim），修改后保存即可
crontab -e
```

**Comment by Jisu-Woniu** [comment]
https://github.com/RayWangQvQ/BiliBiliToolPro/blob/a2803da3f36e7d9e3fc9e90104bb410bd2552bd2/docker/scripts/entry.sh#L18-L21

18 行缺少了 `$Ray_DailyTaskConfig__Cron` 配置，导致只设置 DailyTask 时会直接进入 `else` 分支

**Comment by Jisu-Woniu** [comment]
同时设置DailyTask与另一任务时，不触发默认配置

![图片](https://user-images.githubusercontent.com/31986081/213902409-5f27021a-c747-4a0c-9064-5a732dd5b229.png)
