### ISSUE TITLE
bili_task_test.sh: line 9: dotnet: command not found

### ISSUE THREAD

**Issue by zadishu** [RayWangQvQ/BiliBiliToolPro#382]
bili_task_test.sh: line 9: dotnet: command not found
如何处理

**Comment by zadishu** [comment]
创建软链接...
/dev/stdin: line 108: /usr/local/bin/dotnet: No such file or directory

**Comment by FAITH-WEN** [comment]
老哥，你是怎么解决的，我也是这个问题
