### ISSUE TITLE
【建议】青龙平台添加环境变量问题

### ISSUE THREAD

**Issue by 1302557841** [RayWangQvQ/BiliBiliToolPro#387]
建议内容：
青龙平台添加环境变量能否统一名字如Ray_BiliBiliCookies呢
然后批量读取。这样好像更方便一点

**Comment by RayWangQvQ** [comment]
没get到方便在哪儿唉，可以细说下不

**Comment by 1302557841** [comment]
> 没get到方便在哪儿唉，可以细说下不

大佬这样写变量会更方便，不用写后面了，而且青龙支持远程提交Cookie到变量里，统一成Ray_BiliBiliCookies就不用读取有多少Ray_BiliBiliCookies_x，直接添加就好了

**Comment by 1302557841** [comment]
> 没get到方便在哪儿唉，可以细说下不

还有大佬，我支付宝捐赠了，是发邮箱那个，能给一下群号啥的吗

**Comment by 1302557841** [comment]
> 

大佬能把您的微信号发在那个邮箱里面吗，我加您

**Comment by RayWangQvQ** [comment]
可以发我邮箱：zai7lou@outlook.com
