### ISSUE TITLE
【建议】tg推送是否可以增加，自建 Telegram 的反向代理地址

### ISSUE THREAD

**Issue by kwxos** [RayWangQvQ/BiliBiliToolPro#389]
建议内容：
![image](https://user-images.githubusercontent.com/102129419/212095085-a392be7d-597f-4f4d-8ccf-9b64c94f5f83.png)
如图所示

**Comment by lolseru** [comment]
可以使用自定义api 来临时代替
`Ray_Serilog__WriteTo__8__Args__api`:`https://[反代IP]/bot[botID]/sendMessage`
`Ray_Serilog__WriteTo__8__Args__bodyJsonTemplate `:`{"chat_id":[userID],"text":"#msg#"}`

**Comment by kwxos** [comment]
> 可以使用自定义api来临时代替 `Ray_Serilog__WriteTo__8__Args__api`: `https://[反代IP]/bot[botID]/sendMessage` `Ray_Serilog__WriteTo__8__Args__bodyJsonTemplate `:`{"chat_id":[userID],"text":"#msg#"}`

感谢，通过自定义配置确实成功了，但是在配置文件里更改，会报json格式错误，琢磨了下应该写成这样
```
//8.自定义Api
     ``` {
        "Name": "TG",
        "Args": {
          "api": "https://xxx.xxxx.xxx/botxxxxxx:xxxxxxxxxxxxxxxxxxxxxxxxxx/sendMessage",
          "placeholder": "#msg#", //占位符
          "bodyJsonTemplate": "{\"chat_id\":\"xxxxxxxx\",\"text\":#msg#}",
          "restrictedToMinimumLevel": "Information"
        }
      },
```

**Comment by quan-ge** [comment]
为什么我用会报错啊
```
2026-08-06T04:01:12.8327911Z 开始推送到:自定义
2026-08-06T04:01:14.5038401Z Response status: BadRequest.
2026-08-06T04:01:14.5046553Z Response content: {"ok":false,"error_code":400,"description":"Bad Request: message text is empty"}.
```

不管怎么设置都是这样
