### ISSUE TITLE
【Bug】拉库完成后，执行 bili 扫码登录任务，报错

### ISSUE THREAD

**Issue by cy920820** [RayWangQvQ/BiliBiliToolPro#398]
![image](https://user-images.githubusercontent.com/21211512/213659322-fc0ceed3-9b71-4c73-a31d-5eca1b2ebb9a.png)

**Comment by cy920820** [comment]
青龙面板版本：v2.11.3

**Comment by RayWangQvQ** [comment]
提示很清楚，UserAgent重新配
