### ISSUE TITLE
【其他】请问是否被ghproxy屏蔽了？

### ISSUE THREAD

**Issue by AlvaTsou** [RayWangQvQ/BiliBiliToolPro#405]
rt，国内网络，使用ghproxy拉不下来脚本了
然后换了个代理网址拉下来了。

但是换的网址拉dotnet装不上。。。。

请问能否有不通过github而是通过微软官方安装dotnet的方法啊？
line 9: dotnet: command not found

**Comment by AlvaTsou** [comment]
另：用docker版本的部署以后，扫二维码扫不出来，点链接显示高清二维码扫后显示不支持该链接

**Comment by RayWangQvQ** [comment]
> rt，国内网络，使用ghproxy拉不下来脚本了 然后换了个代理网址拉下来了。

未复现，个人测试可以正常使用

> 请问能否有不通过github而是通过微软官方安装dotnet的方法啊？ line 9: dotnet: command not found

暂时没有。

> 用docker版本的部署以后，扫二维码扫不出来，点链接显示高清二维码扫后显示不支持该链接

未复现，建议检查下自己的网络环境。在线二维码只是使用了一个免费的三方站点，不是bilitool server的。
