### ISSUE TITLE
【Bug】bili扫码登录异常

### ISSUE THREAD

**Issue by Akiyama730** [RayWangQvQ/BiliBiliToolPro#406]
版本号：v2.15.5
运行环境：青龙docker
两个版本都用过
## 开始执行... 2023-01-28 22:12:16

repo目录: /ql/data/repo
bili仓库目录: /ql/data/repo/RayWangQvQ_BiliBiliToolPro

bili_task_login.sh: line 9: dotnet: command not found

**Comment by RayWangQvQ** [comment]
未安装.net

**Comment by yating1022** [comment]
> 未安装.net

很奇怪，我也是这个问题，我都安装好了dotnet了，还是这样子
![image](https://user-images.githubusercontent.com/73951475/218405976-82402748-8c11-4c8c-bbf6-571bdf45b1a9.png)
