### ISSUE TITLE
【建议】合并通知

### ISSUE THREAD

**Issue by swRains** [RayWangQvQ/BiliBiliToolPro#408]
期望能加入合并通知功能，比如每天早上8点通知下昨天的运行情况就行了，一天四条是否显得有些多。在账号cookie异常和任务失败时可以即时通知，期望能引入这个选项。除天选时刻外，其他的甚至可以在升级的时候再通知。
主要是有多个任务通知走一个渠道会略显复杂。望作者采纳

**Comment by RayWangQvQ** [comment]
目前整个架构是无状态的，没有持久化数据到任何地方，暂时做不到。
