### ISSUE TITLE
【Bug】Telegram无法推送

### ISSUE THREAD

**Issue by ZYGLQexplorer** [RayWangQvQ/BiliBiliToolPro#416]
版本号：0.4.0
运行环境：香港开的Docker 宿主是Ubuntu 20.04 用Portainer做的web管理

问题描述：Telegram无法推送 无详细日志

日志信息：日志开到Debug等级 但是没有tg推送方面的详细日志
已经确认Bot Token和Chat ID正确配置 因为同样的Token和ID在我其他推送bot可以使用
有需要可以联系我TG @ZYGLQexplorer233 

docker-compose.yml配置
![image](https://user-images.githubusercontent.com/66054495/216746733-5fff30ce-2265-420e-a611-b492f2708843.png)

appsettings.json配置
![image](https://user-images.githubusercontent.com/66054495/216746753-0410112c-7081-4dcb-bea0-9d88e2028d30.png)

运行后返回
![image](https://user-images.githubusercontent.com/66054495/216746690-af868a05-e3b9-40ba-9756-40a8d0e76ac0.png)

**Comment by RayWangQvQ** [comment]
没有日志，就是环境变量没有读到，没有往telegram推送。

可以检查下环境变量，或者重启下试试
