### ISSUE TITLE
【建议】建议更新SCF的教程

### ISSUE THREAD

**Issue by qazedc-abcd** [RayWangQvQ/BiliBiliToolPro#417]
都更新扫二维码登陆了，scf教程还在说获取cookie

**Comment by qazedc-abcd** [comment]
顺便说一嘴，SCF虽然收费但是很便宜，一个月也才花一块五六毛的样子

**Comment by RayWangQvQ** [comment]
scf应该是不支持扫码登录的，我还没试过，你可以试一下

**Comment by qazedc-abcd** [comment]
是扫不了，但是建议把抓取cookie的教程也留下，难免有时候cookie失效（
