### ISSUE TITLE
secrets选那个子目录

### ISSUE THREAD

**Issue by hanxiao23** [RayWangQvQ/BiliBiliToolPro#42]
（提issue前请先确认没有其他人提过相同的议题）
![image](https://user-images.githubusercontent.com/100828673/159623437-649d6923-cccd-460f-9b46-a7b45d287d4a.png)

**Comment by yiyungent** [comment]
使用 `GitHub Actions` 的话就选 `Actions`,

**Comment by hanxiao23** [comment]
> 使用 的话就选 ,`GitHub Actions``Actions`

腾讯云函数自动部署也是选Actions吗
