### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by hanxiao23** [RayWangQvQ/BiliBiliToolPro#43]
（提issue前请先确认没有其他人提过相同的议题）
![image](https://user-images.githubusercontent.com/100828673/159826256-44b534fb-a3b5-4317-bf3e-28e5d92793fe.png)
![image](https://user-images.githubusercontent.com/100828673/159826497-84c62446-cbc3-4031-b21e-f41f4aeabbf0.png)
![image](https://user-images.githubusercontent.com/100828673/159826613-cc394ac8-e6ac-4811-97c6-2c9d92e18955.png)

我按照教程下载yml文件后只添加了cookie文件。之后全部拷贝上传了上去

**Comment by KudouRan** [comment]
为啥是中文，甚至连标点都是中文，这个配置文件除了注释都是是英文啊。
