### ISSUE TITLE
青龙容器的目录结果出现了变化，导致无法正常运行任务，请更新MD文件和脚本文件的相关路径

### ISSUE THREAD

**Issue by sunsikai** [RayWangQvQ/BiliBiliToolPro#44]
版本号：BiliBiliToolPro-V0.0.6
运行环境：青龙容器 V2.12.0

问题描述：新版本青龙容器的配置目录等脚本存放相关目录，已经由原本的 /ql 目录移动到 /ql/data 目录，请更新本项目的MD说明文件（[MD文件链接](https://github.com/RayWangQvQ/BiliBiliToolPro/blob/main/qinglong/README.md)），和脚本运行文件（raywangqvq_bilibilitoolpro下的几个bili_task文件）

日志信息：MSBUILD : error MSB1009 项目文件不存在 生成失败。请修复生成错误并重新运行 /ql/data/repo/raywangqvq_bilibilitoolpro/src/Ray.BiliBiliTool.Console

**Comment by rogueme** [comment]
谢谢,我手动改了,昨晚更新死活不知道问题在哪!

**Comment by TwShuai** [comment]
> 谢谢,我手动改了,昨晚更新死活不知道问题在哪!

这个怎么改？

**Comment by rogueme** [comment]
> > 谢谢,我手动改了,昨晚更新死活不知道问题在哪!
> 
> 这个怎么改？

把所有脚本文件内容里面的路径/ql/repo改成/ql/data/repo/
就是所有后缀sh的脚本文件里面的内容的路径ql后面都加上data
拿个脚本文件bili_task_daily.sh
里面的内容是:
`#!/usr/bin/env bash
# new Env("bili每日任务")
# cron 0 9 * * * bili_task_daily.sh

dotnet run --project /ql/repo/raywangqvq_bilibilitoolpro/src/Ray.BiliBiliTool.Console --ENVIRONMENT=Production --runTasks=Daily`
改成后内容是:
`#!/usr/bin/env bash
# new Env("bili每日任务")
# cron 0 9 * * * bili_task_daily.sh

dotnet run --project /ql/data/repo/raywangqvq_bilibilitoolpro/src/Ray.BiliBiliTool.Console --ENVIRONMENT=Production --runTasks=Daily`

**Comment by RayWangQvQ** [comment]
已于 `v0.0.7` 修复，重新运行下拉库任务即可
