### ISSUE TITLE
【其他】我的安装 dotnet 环境异常现象

### ISSUE THREAD

**Issue by ly123voo** [RayWangQvQ/BiliBiliToolPro#440]
![mmexport1676256944258.jpg](https://user-images.githubusercontent.com/55238929/218360534-7a3825ff-c40e-47b1-a833-ce9f9d22538b.jpg)

![mmexport1676256940398.jpg](https://user-images.githubusercontent.com/55238929/218360573-8a6c17ea-7d7c-48bc-a4d7-ad228fa61c80.jpg)

不知道怎么处理了，面具青龙版本2.10.13

**Comment by RayWangQvQ** [comment]
docker exec -it qinglong bash /ql/data/config/extra.sh

**Comment by RayWangQvQ** [comment]
解决了？

我发现github的raw文件好像是有缓存，访问后返回的还是以前的老版本。

实际文件：

![image](https://user-images.githubusercontent.com/31154238/218376167-1296de0e-a8ef-44f2-aafa-28d40ca93be6.png)

raw：

![image](https://user-images.githubusercontent.com/31154238/218376249-68c3bef4-8b7f-4070-9c98-c35976c8ef78.png)

**Comment by ly123voo** [comment]
> 解决了？
> 
> 我发现github的raw文件好像是有缓存，访问后返回的还是以前的老版本。
> 
> 实际文件：
> 
> ![image](https://user-images.githubusercontent.com/31154238/218376167-1296de0e-a8ef-44f2-aafa-28d40ca93be6.png)
> 
> raw：
> 
> ![image](https://user-images.githubusercontent.com/31154238/218376249-68c3bef4-8b7f-4070-9c98-c35976c8ef78.png)
> 

没解决，我刚开始玩不敢问😥 不知道docker exec -it qinglong bash /ql/data/config/extra.sh要在哪里执行，正在搜了 。 
可能我加载的是之前的版本吧，我之前也是不能用，不知道是不是面具青龙的问题

**Comment by ly123voo** [comment]
我在青龙里添加了  task /ql/data/config/extra.sh运行  不知道和  docker exec -it qinglong bash /ql/data/config/extra.sh  效果是不是一样的

**Comment by RayWangQvQ** [comment]
那你重启下青龙容器，效果一样的

**Comment by ljun223** [comment]
如果是酷安望月大佬做的面具版本青龙面板，装dotnet不要用cur命令，使用ssh连接后台，输入apk add dotnet6-sdk命令即可

**Comment by ly123voo** [comment]
> > > 如果是酷安望月大佬做的面具版本青龙面板，装dotnet不要用cur命令，使用ssh连接后台，输入apk add dotnet6-sdk命令即可
> > 
> > 对是望月大佬的，可以问一下ssh连接后台要怎么操作吗，我用了connectbot但是连不上
> 
> 下载juicessh软件，这个好用

我的一加7用juice会卡到juice主界面，不知道啥原因，我去多试试吧

**Comment by ljun223** [comment]
> > > > 如果是酷安望月大佬做的面具版本青龙面板，装dotnet不要用cur命令，使用ssh连接后台，输入apk add dotnet6-sdk命令即可
> > > 
> > > 对是望月大佬的，可以问一下ssh连接后台要怎么操作吗，我用了connectbot但是连不上
> > 
> > 下载juicessh软件，这个好用
> 
> 我的一加7用juice会卡到juice主界面，不知道啥原因，我去多试试吧

juice最好直接从Googleplay下载官方版，酷安的修改版我用着都不好用，不是闪退就是打不开

**Comment by ly123voo** [comment]
> > > > > 如果是酷安望月大佬做的面具版本青龙面板，装dotnet不要用cur命令，使用ssh连接后台，输入apk add dotnet6-sdk命令即可
> > > > 
> > > > 对是望月大佬的，可以问一下ssh连接后台要怎么操作吗，我用了connectbot但是连不上
> > > 
> > > 下载juicessh软件，这个好用
> > 
> > 我的一加7用juice会卡到juice主界面，不知道啥原因，我去多试试吧
> 
> juice最好直接从Googleplay下载官方版，酷安的修改版我用着都不好用，不是闪退就是打不开

![IMG_20230213_141133.jpg](https://user-images.githubusercontent.com/55238929/218383884-70d26c66-f958-474a-b3f6-5e0f0b98a723.jpg)

google商店直接下的也是卡死，应该不是很兼容安卓10吧

**Comment by ljun223** [comment]
> > > > > > 如果是酷安望月大佬做的面具版本青龙面板，装dotnet不要用cur命令，使用ssh连接后台，输入apk add dotnet6-sdk命令即可
> > > > > 
> > > > > 对是望月大佬的，可以问一下ssh连接后台要怎么操作吗，我用了connectbot但是连不上
> > > > 
> > > > 下载juicessh软件，这个好用
> > > 
> > > 我的一加7用juice会卡到juice主界面，不知道啥原因，我去多试试吧
> > 
> > juice最好直接从Googleplay下载官方版，酷安的修改版我用着都不好用，不是闪退就是打不开
> 
> ![IMG_20230213_141133.jpg](https://user-images.githubusercontent.com/55238929/218383884-70d26c66-f958-474a-b3f6-5e0f0b98a723.jpg)
> 
> google商店直接下的也是卡死，应该不是很兼容安卓10吧

试试termux吧，先pkg install sshopen
在输入 ssh root@127.0.0.1 -p 22
看看能不能连接上

**Comment by ljun223** [comment]
实在不行，你在青龙面板里新建一个定时任务，名称和定时规则随便填，命令填apk add  dotnet6-sdk，让后立即运行
这应该也行

**Comment by ly123voo** [comment]
> 实在不行，你在青龙面板里新建一个定时任务，名称和定时规则随便填，命令填apk add  dotnet6-sdk，让后立即运行
> 这应该也行

行 我都去试试，太谢谢兄弟了，成的话请你喝红牛

**Comment by ly123voo** [comment]
> 实在不行，你在青龙面板里新建一个定时任务，名称和定时规则随便填，命令填apk add  dotnet6-sdk，让后立即运行
> 这应该也行

留个v吧，成功了

**Comment by RayWangQvQ** [comment]
> 实在不行，你在青龙面板里新建一个定时任务，名称和定时规则随便填，命令填apk add  dotnet6-sdk，让后立即运行
> 这应该也行

alphine系统现在可以直接用apk安装dotnet了？

**Comment by ljun223** [comment]
> > 实在不行，你在青龙面板里新建一个定时任务，名称和定时规则随便填，命令填apk add  dotnet6-sdk，让后立即运行
> > 这应该也行
> 
> alphine系统现在可以直接用apk安装dotnet了？

对，可以的

**Comment by ljun223** [comment]
> > 实在不行，你在青龙面板里新建一个定时任务，名称和定时规则随便填，命令填apk add  dotnet6-sdk，让后立即运行
> > 这应该也行
> 
> alphine系统现在可以直接用apk安装dotnet了？

大佬可以直接在文档里说一下，省的他们在问了

**Comment by ly123voo** [comment]
> > 实在不行，你在青龙面板里新建一个定时任务，名称和定时规则随便填，命令填apk add  dotnet6-sdk，让后立即运行
> > 这应该也行
> 
> alphine系统现在可以直接用apk安装dotnet了？

不能，我连接ssh安装的

**Comment by ly123voo** [comment]
> > > 实在不行，你在青龙面板里新建一个定时任务，名称和定时规则随便填，命令填apk add  dotnet6-sdk，让后立即运行
> > > 这应该也行
> > 
> > alphine系统现在可以直接用apk安装dotnet了？
> 
> 大佬可以直接在文档里说一下，省的他们在问了

兄弟那个apk add我试的不行，也可能方法错了吧，我用juice安装的

**Comment by RayWangQvQ** [comment]
> > > 实在不行，你在青龙面板里新建一个定时任务，名称和定时规则随便填，命令填apk add  dotnet6-sdk，让后立即运行
> > > 这应该也行
> > 
> > alphine系统现在可以直接用apk安装dotnet了？
> 
> 大佬可以直接在文档里说一下，省的他们在问了

好的，那可太棒了，之前官网没找到说可以apk安装，用脚本装很蛋疼。
今晚我来测试然后更新下。
感谢分享。

**Comment by ljun223** [comment]
> > > > 实在不行，你在青龙面板里新建一个定时任务，名称和定时规则随便填，命令填apk add  dotnet6-sdk，让后立即运行
> > > > 这应该也行
> > > 
> > > alphine系统现在可以直接用apk安装dotnet了？
> > 
> > 大佬可以直接在文档里说一下，省的他们在问了
> 
> 兄弟那个apk add我试的不行，也可能方法错了吧，我用juice安装的

你在juice里用cur命令装成功的？

**Comment by ly123voo** [comment]
> > > > > 实在不行，你在青龙面板里新建一个定时任务，名称和定时规则随便填，命令填apk add  dotnet6-sdk，让后立即运行
> > > > > 这应该也行
> > > > 
> > > > alphine系统现在可以直接用apk安装dotnet了？
> > > 
> > > 大佬可以直接在文档里说一下，省的他们在问了
> > 
> > 兄弟那个apk add我试的不行，也可能方法错了吧，我用juice安装的
> 
> 你在juice里用cur命令装成功的？

不好意思我糊涂了，可以安装😢

**Comment by RayWangQvQ** [comment]
已更新，以后不需要手动安装dotnet了，运行脚本时会自动安装
