### ISSUE TITLE
不播放天选时刻关注up的视频

### ISSUE THREAD

**Issue by duudukaka** [RayWangQvQ/BiliBiliToolPro#442]
建议内容：
（提issue前请先确认没有其他人提过相同的议题）
每日任务之随机播放关注up的视频，希望不播放天选时刻关注的up（不播放在天选列表中用户的视频
因天选抽奖关注up后对方会发问好消息，希望事先删除对方的打招呼信息

**Comment by RayWangQvQ** [comment]
> 每日任务之随机播放关注up的视频，希望不播放天选时刻关注的up（不播放在天选列表中用户的视频

每日任务播放视频，本身是有优先级了，指定id——>特别关注——>普通关注——>陌生随机，可以自己利用优先级解决。

> 因天选抽奖关注up后对方会发问好消息，希望事先删除对方的打招呼信息

没懂。
