### ISSUE TITLE
【Bug】老版本青龙提示安装dotnet异常

### ISSUE THREAD

**Issue by yuanter** [RayWangQvQ/BiliBiliToolPro#443]
版本号：青龙2.10.13
运行环境：Linux

问题描述：请问大伙有碰到这个问题吗？

日志信息：
![image](https://user-images.githubusercontent.com/32212075/218547647-64d08354-81ea-43f0-963b-e8856a903974.png)
![image](https://user-images.githubusercontent.com/32212075/218547795-727706dd-3b58-479d-8dbb-e972fcf4c867.png)

**Comment by RayWangQvQ** [comment]
青龙版本过低，可以升级，或者自行安装dotnet

**Comment by RayWangQvQ** [comment]
老版本青龙的aiphine系统版本比较低，无法使用`apk add`来安装`dotnet`。

以前一直是我自己维护了一个dotnet的shell安装脚本，来为青龙安装dotnet。但是由于各个系统、各个cpu架构不同，老是出现不同问题。

近期，青龙已经将它的基础镜像进行了变更和升级，当前青龙的基础镜像是python的alphine系统，是支持直接使用系统安装包工具安装dotnet的，这样就使得安装过程变得很简单（也不用像以前一样还要去修改extra.sh文件了）。

对于老版本是否需要兼容，目前还在考虑中。

或者，谁能说下，老版本青龙有什么特别之处，或者说有什么不想升级的理由，作为是否去兼容的参考。

**Comment by yuanter** [comment]
主要是这之后的版本，api已经更改，难于使用一些登录面板对接。同时这个版本能跑脚本的环境都差不多集成了，可以不需要额外的一些其他功能。所以没有考虑升级青龙的打算

**Comment by RayWangQvQ** [comment]
> 主要是这之后的版本，api已经更改，难于使用一些登录面板对接

对接登录是指跟bilibilitool扫码登录一样更新cookie的功能吗？这个env的api很简单，升级下2分钟的事，你可以把原仓库folk过来，自己改改的

**Comment by 3184876** [comment]
版本号：青龙2.11.0
运行环境：Linux
`ERROR: unable to select packages:
  MODULE_NOT_FOUND (no such package):
    required by: world[MODULE_NOT_FOUND]
  actInfo (no such package):
    required by: world[actInfo]
  bizCode (no such package):
    required by: world[bizCode]
  bizMsg (no such package):
    required by: world[bizMsg]
  completionCnt (no such package):
    required by: world[completionCnt]
  dotnet6-sdk (no such package):
    required by: world[dotnet6-sdk]
  jdActivityId (no such package):
    required by: world[jdActivityId]
  lxm (no such package):
    required by: world[lxm]
  lxml (no such package):
    required by: world[lxml]
  silly-dateetime (no such package):
    required by: world[silly-dateetime]
  sshd (no such package):
    required by: world[sshd]
bili_task_base.sh: line 10: dotnet: command not found`

**Comment by ljun223** [comment]
你这是centos，apk命令当然安装不了，目前官方只支持centos7的版本安装.net，具体看介绍https://learn.microsoft.com/zh-cn/dotnet/core/install/linux-centos

**Comment by RayWangQvQ** [comment]
这个issue置顶，看下大家的反馈情况

**Comment by yuanter** [comment]
> > 主要是这之后的版本，api已经更改，难于使用一些登录面板对接
> 
> 对接登录是指跟bilibilitool扫码登录一样更新cookie的功能吗？这个env的api很简单，升级下2分钟的事，你可以把原仓库folk过来，自己改改的

这个是我之前没看清源码，导致使用openApi时出错，认为api有问题，我这边的问题。
不过用久了某个版本，就不太想换了，毕竟升级了，一些环境会变，指不定会出现其他问题

**Comment by yuanter** [comment]
> 这个issue置顶，看下大家的反馈情况

linux依赖内，安装gcc和g++俩依赖，已经可以正常安装dotnet环境了。如果大佬没更新了啥，那应该就缺这俩依赖

**Comment by RayWangQvQ** [comment]
更新成3次尝试了，先尝试使用apk add，如果失败就再尝试官方脚本，如果还失败最后下载二进制包。

**Comment by yuanter** [comment]
> 更新成3次尝试了，先尝试使用apk add，如果失败就再尝试官方脚本，如果还失败最后下载二进制包。

大佬666，么么哒

**Comment by Lonely-Sit** [comment]
> 更新成3次尝试了，先尝试使用apk添加，如果失败就再尝试官方脚本，如果还失败最后下载二进制包。

我三次都失败了 呜呜呜
![image](https://github.com/RayWangQvQ/BiliBiliToolPro/assets/71547798/e21596a2-740a-4a2e-95c7-c12542ced569)
