### ISSUE TITLE
新版青龙脚本运行提示

### ISSUE THREAD

**Issue by 2536** [RayWangQvQ/BiliBiliToolPro#444]
## 开始执行... 2023-02-15 23:22:37

./bili_task_base.sh: line 10: /usr/local/bin/dotnet: cannot execute binary file: Exec format error
开始安装dotnet
------尝试使用apk安装------
OK: 1051 MiB in 198 packages
./bili_task_base.sh: line 19: /usr/local/bin/dotnet: cannot execute binary file: Exec format error
------再尝试使用官方脚本安装------

-------set up dot net env-------
安装依赖...
OK: 1051 MiB in 198 packages
install by offical script...
dotnet-install: Note that the intended use of this script is for Continuous Integration (CI) scenarios, where:
dotnet-install: - The SDK needs to be installed without user interaction and without admin rights.
dotnet-install: - The SDK installation doesn't need to persist across multiple CI runs.
dotnet-install: To set up a development environment or to run apps, use installers rather than this script. Visit https://dotnet.microsoft.com/download to get the installer.

dotnet-install: Calling: machine_has curl
dotnet-install: Calling: calculate_vars 
dotnet-install: Calling: get_normalized_architecture_from_architecture <auto>
dotnet-install: Calling: get_machine_architecture 
dotnet-install: Normalized architecture: 'arm64'.
dotnet-install: Calling: get_normalized_os 
dotnet-install: Calling: get_current_os_name 
dotnet-install: Calling: get_linux_platform_name 
dotnet-install: Normalized OS: 'linux-musl'.
dotnet-install: Calling: get_normalized_quality 
dotnet-install: Normalized quality: ''.
dotnet-install: Calling: get_normalized_channel 6.0
dotnet-install: Normalized channel: '6.0'.
dotnet-install: Calling: get_normalized_product 
dotnet-install: Normalized product: 'dotnet-sdk'.
dotnet-install: Calling: resolve_installation_path <auto>
dotnet-install: Calling: get_user_install_path 
dotnet-install: resolve_installation_path: user_install_path=/root/.dotnet
dotnet-install: InstallRoot: '/root/.dotnet'.
dotnet-install: Calling: get_normalized_architecture_for_specific_sdk_version Latest 6.0 arm64
dotnet-install: Calling: get_current_os_name 
dotnet-install: Calling: get_linux_platform_name 
dotnet-install: Calling: get_download_link_from_aka_ms 
dotnet-install: Retrieving primary payload URL from aka.ms for channel: '6.0', quality: '', product: 'dotnet-sdk', os: 'linux-musl', architecture: 'arm64'.
dotnet-install: Constructed aka.ms link: 'https://aka.ms/dotnet/6.0/dotnet-sdk-linux-musl-arm64.tar.gz'.
dotnet-install: Calling: get_http_header https://aka.ms/dotnet/6.0/dotnet-sdk-linux-musl-arm64.tar.gz true
dotnet-install: Calling: machine_has curl
dotnet-install: Calling: get_http_header_curl https://aka.ms/dotnet/6.0/dotnet-sdk-linux-musl-arm64.tar.gz true
dotnet-install: Received response: HTTP/1.1 301 Moved Permanently
Server: Kestrel
Location: https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.406/dotnet-sdk-6.0.406-linux-musl-arm64.tar.gz
Request-Context: appId=cid-v1:9b037ab9-fa5a-4c09-81bd-41ffa859f01e
X-Response-Cache-Status: True
Content-Length: 0
Expires: Wed, 15 Feb 2023 15:22:47 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Wed, 15 Feb 2023 15:22:47 GMT
Connection: keep-alive
Strict-Transport-Security: max-age=31536000 ; includeSubDomains

HTTP/2 200 
accept-ranges: bytes
age: 54695
content-md5: v2KwRvOIigeNdvd00zBlPg==
content-type: application/octet-stream
date: Wed, 15 Feb 2023 15:22:49 GMT
etag: 0x8DB0E8D929A3B7B
last-modified: Tue, 14 Feb 2023 13:15:41 GMT
server: ECAcc (hkc/BD49)
x-cache: HIT
x-ms-blob-type: BlockBlob
x-ms-lease-status: unlocked
x-ms-request-id: 9155d1e8-f01e-0075-03d2-40bfd2000000
x-ms-version: 2009-09-19
content-length: 179796831

dotnet-install: The redirect location retrieved: 'https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.406/dotnet-sdk-6.0.406-linux-musl-arm64.tar.gz'.
dotnet-install: Retrieved primary payload URL from aka.ms link: 'https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.406/dotnet-sdk-6.0.406-linux-musl-arm64.tar.gz'.
dotnet-install: Downloading using legacy url will not be attempted.
dotnet-install: Version: '6.0.406'.
dotnet-install: Calling: get_specific_product_version  6.0.406 https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.406/dotnet-sdk-6.0.406-linux-musl-arm64.tar.gz
dotnet-install: Calling: get_specific_product_version_url  6.0.406 true https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.406/dotnet-sdk-6.0.406-linux-musl-arm64.tar.gz
dotnet-install: Constructed productVersion link: https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.406/sdk-productVersion.txt
dotnet-install: Calling: get_specific_product_version_url  6.0.406 false https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.406/dotnet-sdk-6.0.406-linux-musl-arm64.tar.gz
dotnet-install: Constructed productVersion link: https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.406/productVersion.txt
dotnet-install: Checking for the existence of https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.406/sdk-productVersion.txt
dotnet-install: Calling: machine_has curl
dotnet-install: Calling: is_dotnet_package_installed /root/.dotnet sdk 6.0.406
dotnet-install: Calling: combine_paths /root/.dotnet sdk
dotnet-install: combine_paths: root_path=/root/.dotnet
dotnet-install: combine_paths: child_path=sdk
dotnet-install: Calling: combine_paths /root/.dotnet/sdk 6.0.406
dotnet-install: combine_paths: root_path=/root/.dotnet/sdk
dotnet-install: combine_paths: child_path=6.0.406
dotnet-install: is_dotnet_package_installed: dotnet_package_path=/root/.dotnet/sdk/6.0.406
dotnet-install: .NET Core SDK with version '6.0.406' is already installed.
添加PATH
/dev/stdin: line 116: /usr/local/bin/dotnet: cannot execute binary file: Exec format error

-------set up dot net env finish-------
./bili_task_base.sh: line 24: /usr/local/bin/dotnet: cannot execute binary file: Exec format error
------再尝试使用二进制包安装------

-------set up dot net env-------
安装依赖...
OK: 1051 MiB in 198 packages
install by binaries...
--2023-02-15 23:22:52--  https://download.visualstudio.microsoft.com/download/pr/207a3484-7524-4963-9c4e-dacf20ba3a66/4a3bc869dc7a93753022752aa5782989/dotnet-sdk-6.0.405-linux-musl-arm64.tar.gz
Resolving download.visualstudio.microsoft.com (download.visualstudio.microsoft.com)... 218.29.49.157
Connecting to download.visualstudio.microsoft.com (download.visualstudio.microsoft.com)|218.29.49.157|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 179300506 (171M) [application/octet-stream]
Saving to: 'dotnet-sdk.tar.gz'

     0K .......... .......... .......... .......... ..........  0% 6.49M 26s
    50K .......... .......... .......... .......... ..........  0% 1.25M 82s
  
175050K .......... .......... .......... .......... ........  100% 1.19M=71s

2023-02-15 23:24:04 (2.41 MB/s) - 'dotnet-sdk.tar.gz' saved [179300506/179300506]

添加PATH
/dev/stdin: line 116: /usr/local/bin/dotnet: cannot execute binary file: Exec format error

-------set up dot net env finish-------
./bili_task_base.sh: line 29: /usr/local/bin/dotnet: cannot execute binary file: Exec format error
安装失败，没办法了，毁灭吧，自己解决吧：https://learn.microsoft.com/zh-cn/dotnet/core/install/linux-alpine

## 执行结束... 2023-02-15 23:24:31  耗时 114 秒

**Comment by RayWangQvQ** [comment]
重启下qinglong容器试试

**Comment by 2536** [comment]
> 重新

重启了，还是不行

**Comment by RayWangQvQ** [comment]
咋重启的？

**Comment by 2536** [comment]
2

> 咋重启的？
青龙的容器也重启过，整个服务器也重启过

**Comment by RayWangQvQ** [comment]
重启了就不应该有`/usr/local/bin/dotnet`这个了

这是我刚才在重启后的容器里跑的:
![image](https://user-images.githubusercontent.com/31154238/219094935-8a790145-048e-4378-a411-f29913361828.png)

**Comment by 2536** [comment]
> 重新开始了就不应该有`/usr/local/bin/dotnet`这个了
> 
> 这是我刚在重新启动后的容器里跑的： ![图像](https://user-images.githubusercontent.com/31154238/219094935-8a790145-048e-4378-a411-f29913361828.png)
青龙那一版我是2.15.7

**Comment by RayWangQvQ** [comment]
一样，2.15.7
![image](https://user-images.githubusercontent.com/31154238/219096940-48d24bb7-161a-4596-b09c-d645ffe0d80e.png)

**Comment by 2536** [comment]
> 一样，2.15.7 ![图像](https://user-images.githubusercontent.com/31154238/219096940-48d24bb7-161a-4596-b09c-d645ffe0d80e.png)

能加个QQ吗214471918

**Comment by RayWangQvQ** [comment]
有微信吗

**Comment by 2536** [comment]
有

**Comment by 2536** [comment]
heningbai
