### ISSUE TITLE
青龙执行报错

### ISSUE THREAD

**Issue by MA1174** [RayWangQvQ/BiliBiliToolPro#447]
版本号：青龙v2.15.7
运行环境：docker

问题描述：
**bili批量取关主播**
## 开始执行... 2023-02-17 09:36:15

已安装dotnet，当前版本：6.0.113

repo目录: /ql/data/repo
bili仓库目录: /ql/data/repo/RayWangQvQ_BiliBiliToolPro

MSBUILD : error MSB4166: 子节点“2”过早退出。正在关闭。可以在“/tmp/MSBuildTemproot/”中的文件中找到诊断信息，并将其命名为 MSBuild_*.failure.txt。通过将 MSBUILDDEBUGPATH 环境变量设为其他目录，可更改此位置。
MSBUILD : error MSB4166: /tmp/MSBuildTemproot/MSBuild_pid-3027_85e72f2c72fe4dea812fbf00df01c9b9.failure.txt:
MSBUILD : error MSB4166: UNHANDLED EXCEPTIONS FROM PROCESS 3027:
MSBUILD : error MSB4166: =====================
MSBUILD : error MSB4166: 02/17/2023 09:36:31
MSBUILD : error MSB4166: System.Globalization.CultureNotFoundException: Only the invariant culture is supported in globalization-invariant mode. See https://aka.ms/GlobalizationInvariantMode for more information. (Parameter 'name')
MSBUILD : error MSB4166: zh-CN is an invalid culture identifier.
MSBUILD : error MSB4166:    at System.Globalization.CultureInfo..ctor(String name, Boolean useUserOverride)
MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.BinaryTranslator.BinaryReadTranslator.TranslateCulture(CultureInfo& value)
MSBUILD : error MSB4166:    at Microsoft.Build.Execution.BuildParameters.Microsoft.Build.BackEnd.ITranslatable.Translate(ITranslator translator)
MSBUILD : error MSB4166:    at Microsoft.Build.Execution.BuildParameters..ctor(ITranslator translator)
MSBUILD : error MSB4166:    at Microsoft.Build.Execution.BuildParameters.FactoryForDeserialization(ITranslator translator)
MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.TranslatorHelpers.Translate[T](ITranslator translator, T& instance, NodePacketValueFactory`1 valueFactory)
MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.NodeConfiguration.Translate(ITranslator translator)
MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.NodeConfiguration.FactoryForDeserialization(ITranslator translator)
MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.NodePacketFactory.DeserializeAndRoutePacket(Int32 nodeId, NodePacketType packetType, ITranslator translator)
MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.RunReadLoop(Stream localReadPipe, Stream localWritePipe, ConcurrentQueue`1 localPacketQueue, AutoResetEvent localPacketAvailable, AutoResetEvent localTerminatePacketPump)
MSBUILD : error MSB4166: ===================
MSBUILD : error MSB4166: 
MSBUILD : error MSB4166: 

生成失败。请修复生成错误并重新运行。

## 执行结束... 2023-02-17 09:36:32  耗时 17 秒　　

**bili直播粉丝牌**　

## 开始执行... 2023-02-17 09:36:14

通知失败(通知发送失败，请检查系统设置/通知配置)
已安装dotnet，当前版本：6.0.113

repo目录: /ql/data/repo
bili仓库目录: /ql/data/repo/RayWangQvQ_BiliBiliToolPro

MSBUILD : error MSB4166: 子节点“2”过早退出。正在关闭。可以在“/tmp/MSBuildTemproot/”中的文件中找到诊断信息，并将其命名为 MSBuild_*.failure.txt。通过将 MSBUILDDEBUGPATH 环境变量设为其他目录，可更改此位置。
MSBUILD : error MSB4166: /tmp/MSBuildTemproot/MSBuild_pid-3027_85e72f2c72fe4dea812fbf00df01c9b9.failure.txt:
MSBUILD : error MSB4166: UNHANDLED EXCEPTIONS FROM PROCESS 3027:
MSBUILD : error MSB4166: =====================
MSBUILD : error MSB4166: 02/17/2023 09:36:31
MSBUILD : error MSB4166: System.Globalization.CultureNotFoundException: Only the invariant culture is supported in globalization-invariant mode. See https://aka.ms/GlobalizationInvariantMode for more information. (Parameter 'name')
MSBUILD : error MSB4166: zh-CN is an invalid culture identifier.
MSBUILD : error MSB4166:    at System.Globalization.CultureInfo..ctor(String name, Boolean useUserOverride)
MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.BinaryTranslator.BinaryReadTranslator.TranslateCulture(CultureInfo& value)
MSBUILD : error MSB4166:    at Microsoft.Build.Execution.BuildParameters.Microsoft.Build.BackEnd.ITranslatable.Translate(ITranslator translator)
MSBUILD : error MSB4166:    at Microsoft.Build.Execution.BuildParameters..ctor(ITranslator translator)
MSBUILD : error MSB4166:    at Microsoft.Build.Execution.BuildParameters.FactoryForDeserialization(ITranslator translator)
MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.TranslatorHelpers.Translate[T](ITranslator translator, T& instance, NodePacketValueFactory`1 valueFactory)
MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.NodeConfiguration.Translate(ITranslator translator)
MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.NodeConfiguration.FactoryForDeserialization(ITranslator translator)
MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.NodePacketFactory.DeserializeAndRoutePacket(Int32 nodeId, NodePacketType packetType, ITranslator translator)
MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.RunReadLoop(Stream localReadPipe, Stream localWritePipe, ConcurrentQueue`1 localPacketQueue, AutoResetEvent localPacketAvailable, AutoResetEvent localTerminatePacketPump)
MSBUILD : error MSB4166: ===================
MSBUILD : error MSB4166: 
MSBUILD : error MSB4166: 
MSBUILD : error MSB4166: /tmp/MSBuildTemproot/MSBuild_pid-3040_85c3778d0c694db5b0b1400a6280f856.failure.txt:
MSBUILD : error MSB4166: UNHANDLED EXCEPTIONS FROM PROCESS 3040:
MSBUILD : error MSB4166: =====================
MSBUILD : error MSB4166: 02/17/2023 09:36:31
MSBUILD : error MSB4166: System.Globalization.CultureNotFoundException: Only the invariant culture is supported in globalization-invariant mode. See https://aka.ms/GlobalizationInvariantMode for more information. (Parameter 'name')
MSBUILD : error MSB4166: zh-CN is an invalid culture identifier.
MSBUILD : error MSB4166:    at System.Globalization.CultureInfo..ctor(String name, Boolean useUserOverride)
MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.BinaryTranslator.BinaryReadTranslator.TranslateCulture(CultureInfo& value)
MSBUILD : error MSB4166:    at Microsoft.Build.Execution.BuildParameters.Microsoft.Build.BackEnd.ITranslatable.Translate(ITranslator translator)
MSBUILD : error MSB4166:    at Microsoft.Build.Execution.BuildParameters..ctor(ITranslator translator)
MSBUILD : error MSB4166:    at Microsoft.Build.Execution.BuildParameters.FactoryForDeserialization(ITranslator translator)
MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.TranslatorHelpers.Translate[T](ITranslator translator, T& instance, NodePacketValueFactory`1 valueFactory)
MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.NodeConfiguration.Translate(ITranslator translator)
MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.NodeConfiguration.FactoryForDeserialization(ITranslator translator)
MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.NodePacketFactory.DeserializeAndRoutePacket(Int32 nodeId, NodePacketType packetType, ITranslator translator)
MSBUILD : error MSB4166:    at Microsoft.Build.BackEnd.NodeEndpointOutOfProcBase.RunReadLoop(Stream localReadPipe, Stream localWritePipe, ConcurrentQueue`1 localPacketQueue, AutoResetEvent localPacketAvailable, AutoResetEvent localTerminatePacketPump)
MSBUILD : error MSB4166: ===================
MSBUILD : error MSB4166: 
MSBUILD : error MSB4166: 

生成失败。请修复生成错误并重新运行。

## 执行结束... 2023-02-17 09:36:32  耗时 18 秒　　　　　

日志信息：（如果可以，请贴出Debug级别的日志信息，以便更高效的确定和解决问题。）

**Comment by RayWangQvQ** [comment]
运行“尝试修复异常“任务解决

**Comment by MA1174** [comment]
> 运行“尝试修复异常”任务解决

好像不会通知  我配置了企业微信机器人通知

**Comment by RayWangQvQ** [comment]
上面问题解决了吗？通知如果还有问题，可以单独提

**Comment by MachRB** [comment]
更新至0.4.6后发生投币异常欸

**Comment by MA1174** [comment]
> 上面的问题解决了吗？如果还有问题，可以单独提出

解决了
