### ISSUE TITLE
【Bug】Docker运行报错，容器自动退出

### ISSUE THREAD

**Issue by Cp0204** [RayWangQvQ/BiliBiliToolPro#449]
版本号：
docker pull ghcr.io/raywangqvq/bilibili_tool_pro
Using default tag: latest
latest: Pulling from raywangqvq/bilibili_tool_pro
Digest: sha256:d45da8f46f9e2031e499a1c21f1e673af5fc277ee7fd8579f059d95f5f76f7c9
Status: Image is up to date for ghcr.io/raywangqvq/bilibili_tool_pro:latest
ghcr.io/raywangqvq/bilibili_tool_pro:latest

运行环境：linux docker amd64

问题描述：运行报错，容器自动退出

日志信息：
```
[step 2/4]配置cron定时任务
=>使用用户指定的定时任务配置
SHELL=/bin/bash
BASH_ENV=/etc/cron.env
0 15 * * * cd /app && dotnet Ray.BiliBiliTool.Console.dll --runTasks=Daily
0 22 * * * cd /app && dotnet Ray.BiliBiliTool.Console.dll --runTasks=LiveLottery
0 6 1 * * cd /app && dotnet Ray.BiliBiliTool.Console.dll --runTasks=UnfollowBatched
7 1 * * * cd /app && dotnet Ray.BiliBiliTool.Console.dll --runTasks=VipBigPoint
  cd /app && dotnet Ray.BiliBiliTool.Console.dll --runTasks=LiveFansMedal
"/etc/cron.d/bilicron":6: bad minute
errors in crontab file, can't install.
```

**Comment by RayWangQvQ** [comment]
怎么安装的？

**Comment by Cp0204** [comment]
> 怎么安装的？

用这里的命令：https://github.com/RayWangQvQ/BiliBiliToolPro/blob/main/docker/README.md

4.1. Docker启动
# 生成并运行容器
docker pull ghcr.io/raywangqvq/bilibili_tool_pro
docker run -d --name="bili" \
    -v /bili/Logs:/app/Logs \
    -e Ray_DailyTaskConfig__Cron="0 15 * * *" \
    -e Ray_LiveLotteryTaskConfig__Cron="0 22 * * *" \
    -e Ray_UnfollowBatchedTaskConfig__Cron="0 6 1 * *" \
    -e Ray_VipBigPointConfig__Cron="7 1 * * *" \
    ghcr.io/raywangqvq/bilibili_tool_pro

**Comment by RayWangQvQ** [comment]
有一键安装脚本，可以试下

**Comment by RayWangQvQ** [comment]
link: #448

**Comment by RayWangQvQ** [comment]
已修复
