### ISSUE TITLE
【Bug】运行任务异常结束，提示 Segmentation fault      (core dumped) 

### ISSUE THREAD

**Issue by KazeW** [RayWangQvQ/BiliBiliToolPro#453]
版本号：最新
运行环境：Linux，青龙面板

问题描述：运行任务提示Segmentation fault      (core dumped) 
之前是正常运行的，最近几个脚本运行都提示这个，哪位能帮解释下是为什么呢

日志信息：
## 开始执行... 2023-02-19 23:35:41

已安装dotnet，当前版本：6.0.403
repo目录: /ql/data/repo
.................（中间有很多如下的find:部分省略了）
find: /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Application/obj/Debug/net6.0/Ray.BiliBiliTool.Application.csproj.Fody.CopyLocal.cache: No error information
find: /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Application/obj/Debug/net6.0/refint/Ray.BiliBiliTool.Application.dll: No error information
bili仓库目录: /ql/data/repo/RayWangQvQ_BiliBiliToolPro

bili_task_daily.sh: line 9:   834 ****Segmentation fault      (core dumped) dotnet run --ENVIRONMENT=Production****

**Comment by RayWangQvQ** [comment]
运行“尝试修复异常”任务解决

**Comment by KazeW** [comment]
> 运行“尝试修复异常”任务解决

**运行这个倒是挺正常的，但是运行完了还是不能正常执行其他任务呢**

开始执行... 2023-02-20 20:01:17
repo目录: /ql/data/repo
find: /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.DomainService/bin/Debug/net6.0/Ray.BiliBiliTool.Config.pdb: No error information
find: /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.DomainService/bin/Debug/net6.0/Ray.BiliBiliTool.DomainService.deps.json: No error information
find: /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.DomainService/bin/Debug/net6.0/Ray.BiliBiliTool.DomainService.pdb: No error information
find: /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.DomainService/bin/Debug/net6.0/Ray.BiliBiliTool.Infrastructure.dll: No error information
find: /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.DomainService/bin/Debug/net6.0/Ray.BiliBiliTool.Infrastructure.pdb: No error information
find: /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.DomainService/obj/Debug/net6.0/Ray.BiliBiliTool.DomainService.csproj.FileListAbsolute.txt: No error information
find: /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.DomainService/obj/Debug/net6.0/Ray.BiliBiliTool.DomainService.csproj.CopyComplete: No error information
find: /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Application/bin/Debug/net6.0/Ray.BiliBiliTool.DomainService.dll: No error information
find: /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Application/bin/Debug/net6.0/Ray.BiliBiliTool.Config.pdb: No error information
find: /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Application/bin/Debug/net6.0/Ray.BiliBiliTool.Application.deps.json: No error information
find: /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Application/bin/Debug/net6.0/Ray.BiliBiliTool.DomainService.pdb: No error information
find: /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Application/bin/Debug/net6.0/Ray.BiliBiliTool.Application.Contracts.dll: No error information
find: /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Application/bin/Debug/net6.0/Ray.BiliBiliTool.Agent.dll: No error information
find: /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Application/bin/Debug/net6.0/Ray.BiliBiliTool.Agent.pdb: No error information
find: /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Application/bin/Debug/net6.0/Ray.BiliBiliTool.Application.dll: No error information
find: /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Application/bin/Debug/net6.0/Ray.BiliBiliTool.Infrastructure.dll: No error information
find: /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Application/bin/Debug/net6.0/Ray.BiliBiliTool.Infrastructure.pdb: No error information
find: /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Application/bin/Debug/net6.0/Ray.BiliBiliTool.Application.Contracts.pdb: No error information
find: /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Application/obj/Debug/net6.0/Ray.BiliBiliTool.Application.pdb: No error information
find: /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Application/obj/Debug/net6.0/Ray.BiliBiliTool.Application.csproj.CopyComplete: No error information
find: /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Application/obj/Debug/net6.0/Ray.BiliBiliTool.Application.GeneratedMSBuildEditorConfig.editorconfig: No error information
find: /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Application/obj/Debug/net6.0/Ray.BiliBiliTool.Application.csproj.CoreCompileInputs.cache: No error information
find: /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Application/obj/Debug/net6.0/.NETCoreApp,Version=v6.0.AssemblyAttributes.cs: No error information
find: /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Application/obj/Debug/net6.0/Ray.BiliBiliTool.Application.dll: No error information
find: /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Application/obj/Debug/net6.0/Ray.BiliBiliTool.Application.csproj.Fody.CopyLocal.cache: No error information
find: /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Application/obj/Debug/net6.0/refint/Ray.BiliBiliTool.Application.dll: No error information
bili仓库目录: /ql/data/repo/RayWangQvQ_BiliBiliToolPro

清理缓存...

find: ./src/Ray.BiliBiliTool.DomainService/bin/Debug/net6.0/Ray.BiliBiliTool.Config.pdb: No error information
find: ./src/Ray.BiliBiliTool.DomainService/bin/Debug/net6.0/Ray.BiliBiliTool.DomainService.deps.json: No error information
find: ./src/Ray.BiliBiliTool.DomainService/bin/Debug/net6.0/Ray.BiliBiliTool.DomainService.pdb: No error information
find: ./src/Ray.BiliBiliTool.DomainService/bin/Debug/net6.0/Ray.BiliBiliTool.Infrastructure.dll: No error information
find: ./src/Ray.BiliBiliTool.DomainService/bin/Debug/net6.0/Ray.BiliBiliTool.Infrastructure.pdb: No error information
find: ./src/Ray.BiliBiliTool.DomainService/obj/Debug/net6.0/Ray.BiliBiliTool.DomainService.csproj.FileListAbsolute.txt: No error information
find: ./src/Ray.BiliBiliTool.DomainService/obj/Debug/net6.0/Ray.BiliBiliTool.DomainService.csproj.CopyComplete: No error information
find: ./src/Ray.BiliBiliTool.Application/bin/Debug/net6.0/Ray.BiliBiliTool.DomainService.dll: No error information
find: ./src/Ray.BiliBiliTool.Application/bin/Debug/net6.0/Ray.BiliBiliTool.Config.pdb: No error information
find: ./src/Ray.BiliBiliTool.Application/bin/Debug/net6.0/Ray.BiliBiliTool.Application.deps.json: No error information
find: ./src/Ray.BiliBiliTool.Application/bin/Debug/net6.0/Ray.BiliBiliTool.DomainService.pdb: No error information
find: ./src/Ray.BiliBiliTool.Application/bin/Debug/net6.0/Ray.BiliBiliTool.Application.Contracts.dll: No error information
find: ./src/Ray.BiliBiliTool.Application/bin/Debug/net6.0/Ray.BiliBiliTool.Agent.dll: No error information
find: ./src/Ray.BiliBiliTool.Application/bin/Debug/net6.0/Ray.BiliBiliTool.Agent.pdb: No error information
find: ./src/Ray.BiliBiliTool.Application/bin/Debug/net6.0/Ray.BiliBiliTool.Application.dll: No error information
find: ./src/Ray.BiliBiliTool.Application/bin/Debug/net6.0/Ray.BiliBiliTool.Infrastructure.dll: No error information
find: ./src/Ray.BiliBiliTool.Application/bin/Debug/net6.0/Ray.BiliBiliTool.Infrastructure.pdb: No error information
find: ./src/Ray.BiliBiliTool.Application/bin/Debug/net6.0/Ray.BiliBiliTool.Application.Contracts.pdb: No error information
find: ./src/Ray.BiliBiliTool.Application/obj/Debug/net6.0/Ray.BiliBiliTool.Application.pdb: No error information
find: ./src/Ray.BiliBiliTool.Application/obj/Debug/net6.0/Ray.BiliBiliTool.Application.csproj.CopyComplete: No error information
find: ./src/Ray.BiliBiliTool.Application/obj/Debug/net6.0/Ray.BiliBiliTool.Application.GeneratedMSBuildEditorConfig.editorconfig: No error information
find: ./src/Ray.BiliBiliTool.Application/obj/Debug/net6.0/Ray.BiliBiliTool.Application.csproj.CoreCompileInputs.cache: No error information
find: ./src/Ray.BiliBiliTool.Application/obj/Debug/net6.0/.NETCoreApp,Version=v6.0.AssemblyAttributes.cs: No error information
find: ./src/Ray.BiliBiliTool.Application/obj/Debug/net6.0/Ray.BiliBiliTool.Application.dll: No error information
find: ./src/Ray.BiliBiliTool.Application/obj/Debug/net6.0/Ray.BiliBiliTool.Application.csproj.Fody.CopyLocal.cache: No error information
find: ./src/Ray.BiliBiliTool.Application/obj/Debug/net6.0/refint/Ray.BiliBiliTool.Application.dll: No error information
rm: cannot remove './src/Ray.BiliBiliTool.DomainService/bin/Debug/net6.0/Ray.BiliBiliTool.Config.pdb': No error information
rm: cannot remove './src/Ray.BiliBiliTool.DomainService/bin/Debug/net6.0/Ray.BiliBiliTool.DomainService.deps.json': No error information
rm: cannot remove './src/Ray.BiliBiliTool.DomainService/bin/Debug/net6.0/Ray.BiliBiliTool.DomainService.pdb': No error information
rm: cannot remove './src/Ray.BiliBiliTool.DomainService/bin/Debug/net6.0/Ray.BiliBiliTool.Infrastructure.dll': No error information
rm: cannot remove './src/Ray.BiliBiliTool.DomainService/bin/Debug/net6.0/Ray.BiliBiliTool.Infrastructure.pdb': No error information
rm: cannot remove './src/Ray.BiliBiliTool.Application/bin/Debug/net6.0/Ray.BiliBiliTool.DomainService.dll': No error information
rm: cannot remove './src/Ray.BiliBiliTool.Application/bin/Debug/net6.0/Ray.BiliBiliTool.Config.pdb': No error information
rm: cannot remove './src/Ray.BiliBiliTool.Application/bin/Debug/net6.0/Ray.BiliBiliTool.Application.deps.json': No error information
rm: cannot remove './src/Ray.BiliBiliTool.Application/bin/Debug/net6.0/Ray.BiliBiliTool.DomainService.pdb': No error information
rm: cannot remove './src/Ray.BiliBiliTool.Application/bin/Debug/net6.0/Ray.BiliBiliTool.Application.Contracts.dll': No error information
rm: cannot remove './src/Ray.BiliBiliTool.Application/bin/Debug/net6.0/Ray.BiliBiliTool.Agent.dll': No error information
rm: cannot remove './src/Ray.BiliBiliTool.Application/bin/Debug/net6.0/Ray.BiliBiliTool.Agent.pdb': No error information
rm: cannot remove './src/Ray.BiliBiliTool.Application/bin/Debug/net6.0/Ray.BiliBiliTool.Application.dll': No error information
rm: cannot remove './src/Ray.BiliBiliTool.Application/bin/Debug/net6.0/Ray.BiliBiliTool.Infrastructure.dll': No error information
rm: cannot remove './src/Ray.BiliBiliTool.Application/bin/Debug/net6.0/Ray.BiliBiliTool.Infrastructure.pdb': No error information
rm: cannot remove './src/Ray.BiliBiliTool.Application/bin/Debug/net6.0/Ray.BiliBiliTool.Application.Contracts.pdb': No error information
find: ./src/Ray.BiliBiliTool.DomainService/bin/Debug/net6.0/Ray.BiliBiliTool.Config.pdb: No error information
find: ./src/Ray.BiliBiliTool.DomainService/bin/Debug/net6.0/Ray.BiliBiliTool.DomainService.deps.json: No error information
find: ./src/Ray.BiliBiliTool.DomainService/bin/Debug/net6.0/Ray.BiliBiliTool.DomainService.pdb: No error information
find: ./src/Ray.BiliBiliTool.DomainService/bin/Debug/net6.0/Ray.BiliBiliTool.Infrastructure.dll: No error information
find: ./src/Ray.BiliBiliTool.DomainService/bin/Debug/net6.0/Ray.BiliBiliTool.Infrastructure.pdb: No error information
find: ./src/Ray.BiliBiliTool.DomainService/obj/Debug/net6.0/Ray.BiliBiliTool.DomainService.csproj.FileListAbsolute.txt: No error information
find: ./src/Ray.BiliBiliTool.DomainService/obj/Debug/net6.0/Ray.BiliBiliTool.DomainService.csproj.CopyComplete: No error information
find: ./src/Ray.BiliBiliTool.Application/bin/Debug/net6.0/Ray.BiliBiliTool.DomainService.dll: No error information
find: ./src/Ray.BiliBiliTool.Application/bin/Debug/net6.0/Ray.BiliBiliTool.Config.pdb: No error information
find: ./src/Ray.BiliBiliTool.Application/bin/Debug/net6.0/Ray.BiliBiliTool.Application.deps.json: No error information
find: ./src/Ray.BiliBiliTool.Application/bin/Debug/net6.0/Ray.BiliBiliTool.DomainService.pdb: No error information
find: ./src/Ray.BiliBiliTool.Application/bin/Debug/net6.0/Ray.BiliBiliTool.Application.Contracts.dll: No error information
find: ./src/Ray.BiliBiliTool.Application/bin/Debug/net6.0/Ray.BiliBiliTool.Agent.dll: No error information
find: ./src/Ray.BiliBiliTool.Application/bin/Debug/net6.0/Ray.BiliBiliTool.Agent.pdb: No error information
find: ./src/Ray.BiliBiliTool.Application/bin/Debug/net6.0/Ray.BiliBiliTool.Application.dll: No error information
find: ./src/Ray.BiliBiliTool.Application/bin/Debug/net6.0/Ray.BiliBiliTool.Infrastructure.dll: No error information
find: ./src/Ray.BiliBiliTool.Application/bin/Debug/net6.0/Ray.BiliBiliTool.Infrastructure.pdb: No error information
find: ./src/Ray.BiliBiliTool.Application/bin/Debug/net6.0/Ray.BiliBiliTool.Application.Contracts.pdb: No error information
find: ./src/Ray.BiliBiliTool.Application/obj/Debug/net6.0/Ray.BiliBiliTool.Application.pdb: No error information
find: ./src/Ray.BiliBiliTool.Application/obj/Debug/net6.0/Ray.BiliBiliTool.Application.csproj.CopyComplete: No error information
find: ./src/Ray.BiliBiliTool.Application/obj/Debug/net6.0/Ray.BiliBiliTool.Application.GeneratedMSBuildEditorConfig.editorconfig: No error information
find: ./src/Ray.BiliBiliTool.Application/obj/Debug/net6.0/Ray.BiliBiliTool.Application.csproj.CoreCompileInputs.cache: No error information
find: ./src/Ray.BiliBiliTool.Application/obj/Debug/net6.0/.NETCoreApp,Version=v6.0.AssemblyAttributes.cs: No error information
find: ./src/Ray.BiliBiliTool.Application/obj/Debug/net6.0/Ray.BiliBiliTool.Application.dll: No error information
find: ./src/Ray.BiliBiliTool.Application/obj/Debug/net6.0/Ray.BiliBiliTool.Application.csproj.Fody.CopyLocal.cache: No error information
find: ./src/Ray.BiliBiliTool.Application/obj/Debug/net6.0/refint/Ray.BiliBiliTool.Application.dll: No error information
rm: cannot remove './src/Ray.BiliBiliTool.DomainService/obj/Debug/net6.0/Ray.BiliBiliTool.DomainService.csproj.FileListAbsolute.txt': No error information
rm: cannot remove './src/Ray.BiliBiliTool.DomainService/obj/Debug/net6.0/Ray.BiliBiliTool.DomainService.csproj.CopyComplete': No error information
rm: cannot remove './src/Ray.BiliBiliTool.Application/obj/Debug/net6.0/Ray.BiliBiliTool.Application.pdb': No error information
rm: cannot remove './src/Ray.BiliBiliTool.Application/obj/Debug/net6.0/Ray.BiliBiliTool.Application.csproj.CopyComplete': No error information
rm: cannot remove './src/Ray.BiliBiliTool.Application/obj/Debug/net6.0/Ray.BiliBiliTool.Application.GeneratedMSBuildEditorConfig.editorconfig': No error information
rm: cannot remove './src/Ray.BiliBiliTool.Application/obj/Debug/net6.0/Ray.BiliBiliTool.Application.csproj.CoreCompileInputs.cache': No error information
rm: cannot remove './src/Ray.BiliBiliTool.Application/obj/Debug/net6.0/.NETCoreApp,Version=v6.0.AssemblyAttributes.cs': No error information
rm: cannot remove './src/Ray.BiliBiliTool.Application/obj/Debug/net6.0/Ray.BiliBiliTool.Application.dll': No error information
rm: cannot remove './src/Ray.BiliBiliTool.Application/obj/Debug/net6.0/Ray.BiliBiliTool.Application.csproj.Fody.CopyLocal.cache': No error information
rm: cannot remove './src/Ray.BiliBiliTool.Application/obj/Debug/net6.0/refint/Ray.BiliBiliTool.Application.dll': No error information
清理完成
检测dotnet
已安装dotnet，当前版本：6.0.403
执行结束... 2023-02-20 20:01:28  耗时 11 秒

**Comment by KazeW** [comment]
不知道是不是我磁盘出问题了，-- 打算重装发现那几个文件删除不掉了

**Comment by RayWangQvQ** [comment]
嗯，rm命令报错了，可以把青龙容器停了再删试试

**Comment by KazeW** [comment]
我关了问题吧，感谢回复
因为之前在一个老旧机顶盒上面跑的，磁盘可能确实坏了没修复好，准备换个盒子再弄了
