### ISSUE TITLE
【其他】NuGet.targets(132,5): warning : Problem reading the cache file

### ISSUE THREAD

**Issue by iCouldFly** [RayWangQvQ/BiliBiliToolPro#454]
/root/.dotnet/sdk/6.0.406/NuGet.targets(132,5): error : Found invalid data while decoding. [/ql/data/repo/RayWangQvQ_BiliBiliToolPro_develop/src/Ray.BiliBiliTool.Console/Ray.BiliBiliTool.Console.csproj]

老哥们，所有BILI脚本都是这个NUGET报错，咋整

**Comment by RayWangQvQ** [comment]
运行尝试修复异常任务解决

**Comment by iCouldFly** [comment]
> 运行尝试修复异常任务解决

清理缓存...

清理完成

检测dotnet...
已安装dotnet，当前版本：6.0.406
检测dotnet结束

运行后还是一样报错
