### ISSUE TITLE
安装不了dotnet

### ISSUE THREAD

**Issue by buyikun** [RayWangQvQ/BiliBiliToolPro#455]
开始安装dotnet
------尝试使用apk安装------
ERROR: unable to select packages:
  dotnet6-sdk (no such package):
    required by: world[dotnet6-sdk]
bili_task_base.sh: line 20: dotnet: command not found
安装成功

好像是软件源的问题。但我真的搞了好久了，没搞成，大佬help

**Comment by buyikun** [comment]
![截图](https://user-images.githubusercontent.com/116563059/220330646-633600a3-4e95-4840-92da-991cd2ec5c89.png)
通过之前那个脚本安装似乎也不太行

**Comment by RayWangQvQ** [comment]
拉最新的bili库

**Comment by buyikun** [comment]
> 拉最新的bili库

已经是最新的了
![image](https://user-images.githubusercontent.com/116563059/220546784-40addb46-3d95-42a6-a371-71368af4f881.png)
![image](https://user-images.githubusercontent.com/116563059/220546966-c4566a6f-99fb-4542-8022-eb6c9f869655.png)

**Comment by RayWangQvQ** [comment]
好我来排查下

**Comment by gitcps** [comment]
同样的问题，之前可以最近就不行了
