### ISSUE TITLE
无法安装dotnet

### ISSUE THREAD

**Issue by gitcps** [RayWangQvQ/BiliBiliToolPro#458]
`bili_task_base.sh: line 10: dotnet: command not found
which dotnet: 
开始安装dotnet
------尝试使用apk安装------
ERROR: unable to select packages:
  bizCode (no such package):
    required by: world[bizCode]
  bizMsg (no such package):
    required by: world[bizMsg]
  dotnet6-sdk (no such package):
    required by: world[dotnet6-sdk]
  lxml (no such package):
    required by: world[lxml]
bili_task_base.sh: line 20: dotnet: command not found
安装成功`

其实这些依赖都安装好了，不知道为什么不能扫码登录，其他脚本也都是同样报错。

**Comment by RayWangQvQ** [comment]
不要重复提issue
