### ISSUE TITLE
【建议】可以选择启用或关闭每日任务中的部分任务

### ISSUE THREAD

**Issue by asdqp233** [RayWangQvQ/BiliBiliToolPro#46]
建议内容：
例如每日任务中b币卷充电等 任务 可以选择关闭不执行
找了文档 没看到在哪设置

**Comment by asdqp233** [comment]
已经找到了

**Comment by naiveclub** [comment]
请问你是使用docker容器部署的吗？能不能关闭天选时刻抽奖的任务

**Comment by asdqp233** [comment]
> 请问你是使用docker容器部署的吗？能不能关闭天选时刻抽奖的任务

直接下的release包部署到腾讯云的 可以关闭

**Comment by mentlesoul** [comment]
没找到怎么关天选或者直播抽奖的，求教
我是windows server运行，用的x86 64...那个release

**Comment by RoyLi-Pvt** [comment]
0 0 5 31 2 ? 永不执行的 cron

**Comment by naiveclub** [comment]
> 0 0 5 31 2 ? 永不执行的 cron 不知道可不可以~~
> 
> 
> 
> Update 
> 
> 试了下 2月31这种是不行的 但是似乎兼容7段格式的cron 所以可以指定 2099年执行~~
> 
> 0 22 * * * ? 2099 这样

我现在直接部署在青龙面板上了，不想执行的任务直接禁用就行了
