### ISSUE TITLE
【Bug】青龙获取dotnet-sdk-6.0.406-linux-musl-x64.tar.gz失败

### ISSUE THREAD

**Issue by Suk-Li** [RayWangQvQ/BiliBiliToolPro#468]
版本号：git抓取的最新版本
运行环境：青龙

问题描述：青龙获取dotnet-sdk-6.0.406-linux-musl-x64.tar.gz一直失败

日志信息：
dotnet-install: Calling: combine_paths /root/.dotnet/sdk 6.0.406
dotnet-install: combine_paths: root_path=/root/.dotnet/sdk
dotnet-install: combine_paths: child_path=6.0.406
dotnet-install: is_dotnet_package_installed: dotnet_package_path=/root/.dotnet/sdk/6.0.406
dotnet-install: Generated 1 links.
dotnet-install: Link 0: aka.ms, 6.0.406, https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.406/dotnet-sdk-6.0.406-linux-musl-x64.tar.gz
dotnet-install: Calling: install_dotnet 
dotnet-install: Zip path: /tmp/dotnet.0qaKxIbi1
dotnet-install: Attempting to download using aka.ms link https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.406/dotnet-sdk-6.0.406-linux-musl-x64.tar.gz
dotnet-install: Calling: download https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.406/dotnet-sdk-6.0.406-linux-musl-x64.tar.gz /tmp/dotnet.0qaKxIbi1
dotnet-install: Calling: machine_has curl
dotnet-install: Calling: downloadcurl https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.406/dotnet-sdk-6.0.406-linux-musl-x64.tar.gz /tmp/dotnet.0qaKxIbi1
curl: (56) OpenSSL SSL_read: Connection reset by peer, errno 104
dotnet-install: Calling: get_http_header_curl https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.406/dotnet-sdk-6.0.406-linux-musl-x64.tar.gz false
dotnet-install: Unable to download https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.406/dotnet-sdk-6.0.406-linux-musl-x64.tar.gz.
dotnet-install: Download attempt #1 has failed: 200 Unable to download https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.406/dotnet-sdk-6.0.406-linux-musl-x64.tar.gz.
dotnet-install: Attempt #2 will start in 10 seconds.
dotnet-install: Calling: machine_has curl
dotnet-install: Calling: downloadcurl https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.406/dotnet-sdk-6.0.406-linux-musl-x64.tar.gz /tmp/dotnet.0qaKxIbi1

**Comment by Suk-Li** [comment]
## 开始执行... 2023-03-01 11:09:39

bili_task_base.sh: line 10: dotnet: command not found
which dotnet: 
开始安装dotnet
------尝试使用apk安装------
fetch http://mirrors.tuna.tsinghua.edu.cn/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://mirrors.tuna.tsinghua.edu.cn/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
ERROR: unable to select packages:
  dotnet6-sdk (no such package):
    required by: world[dotnet6-sdk]
bili_task_base.sh: line 20: dotnet: command not found
------再尝试使用官方脚本安装------

-------set up dot net env-------
安装依赖...
(1/2) Installing icu-libs (67.1-r0)
(2/2) Installing libintl (0.20.2-r0)
OK: 286 MiB in 129 packages
install by offical script...
dotnet-install: Note that the intended use of this script is for Continuous Integration (CI) scenarios, where:
dotnet-install: - The SDK needs to be installed without user interaction and without admin rights.
dotnet-install: - The SDK installation doesn't need to persist across multiple CI runs.
dotnet-install: To set up a development environment or to run apps, use installers rather than this script. Visit https://dotnet.microsoft.com/download to get the installer.

dotnet-install: Calling: machine_has curl
dotnet-install: Calling: calculate_vars 
dotnet-install: Calling: get_normalized_architecture_from_architecture <auto>
dotnet-install: Calling: get_machine_architecture 
dotnet-install: Normalized architecture: 'x64'.
dotnet-install: Calling: get_normalized_os 
dotnet-install: Calling: get_current_os_name 
dotnet-install: Calling: get_linux_platform_name 
dotnet-install: Normalized OS: 'linux-musl'.
dotnet-install: Calling: get_normalized_quality 
dotnet-install: Normalized quality: ''.
dotnet-install: Calling: get_normalized_channel 6.0
dotnet-install: Normalized channel: '6.0'.
dotnet-install: Calling: get_normalized_product 
dotnet-install: Normalized product: 'dotnet-sdk'.
dotnet-install: Calling: resolve_installation_path <auto>
dotnet-install: Calling: get_user_install_path 
dotnet-install: resolve_installation_path: user_install_path=/root/.dotnet
dotnet-install: InstallRoot: '/root/.dotnet'.
dotnet-install: Calling: get_normalized_architecture_for_specific_sdk_version Latest 6.0 x64
dotnet-install: Calling: get_current_os_name 
dotnet-install: Calling: get_linux_platform_name 
dotnet-install: Calling: get_download_link_from_aka_ms 
dotnet-install: Retrieving primary payload URL from aka.ms for channel: '6.0', quality: '', product: 'dotnet-sdk', os: 'linux-musl', architecture: 'x64'.
dotnet-install: Constructed aka.ms link: 'https://aka.ms/dotnet/6.0/dotnet-sdk-linux-musl-x64.tar.gz'.
dotnet-install: Calling: get_http_header https://aka.ms/dotnet/6.0/dotnet-sdk-linux-musl-x64.tar.gz true
dotnet-install: Calling: machine_has curl
dotnet-install: Calling: get_http_header_curl https://aka.ms/dotnet/6.0/dotnet-sdk-linux-musl-x64.tar.gz true
dotnet-install: Received response: HTTP/1.1 301 Moved Permanently
Server: Kestrel
Location: https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.406/dotnet-sdk-6.0.406-linux-musl-x64.tar.gz
Request-Context: appId=cid-v1:26ef1154-5995-4d24-ad78-ef0b04f11587
X-Response-Cache-Status: True
Content-Length: 0
Expires: Wed, 01 Mar 2023 03:10:12 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Wed, 01 Mar 2023 03:10:12 GMT
Connection: keep-alive
Strict-Transport-Security: max-age=31536000 ; includeSubDomains

HTTP/2 200 
accept-ranges: bytes
age: 600651
content-md5: hlaFwDGSUxvcotNZ9rPrbA==
content-type: application/octet-stream
date: Wed, 01 Mar 2023 03:10:16 GMT
etag: 0x8DB0E8D9C77187E
last-modified: Tue, 14 Feb 2023 13:15:58 GMT
server: ECAcc (hkc/BD73)
x-cache: HIT
x-ms-blob-type: BlockBlob
x-ms-lease-status: unlocked
x-ms-request-id: e87b733a-601e-00da-3374-469d42000000
x-ms-version: 2009-09-19
content-length: 185571917

dotnet-install: The redirect location retrieved: 'https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.406/dotnet-sdk-6.0.406-linux-musl-x64.tar.gz'.
dotnet-install: Retrieved primary payload URL from aka.ms link: 'https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.406/dotnet-sdk-6.0.406-linux-musl-x64.tar.gz'.
dotnet-install: Downloading using legacy url will not be attempted.
dotnet-install: Version: '6.0.406'.
dotnet-install: Calling: get_specific_product_version  6.0.406 https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.406/dotnet-sdk-6.0.406-linux-musl-x64.tar.gz
dotnet-install: Calling: get_specific_product_version_url  6.0.406 true https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.406/dotnet-sdk-6.0.406-linux-musl-x64.tar.gz
dotnet-install: Constructed productVersion link: https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.406/sdk-productVersion.txt
dotnet-install: Calling: get_specific_product_version_url  6.0.406 false https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.406/dotnet-sdk-6.0.406-linux-musl-x64.tar.gz
dotnet-install: Constructed productVersion link: https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.406/productVersion.txt
dotnet-install: Checking for the existence of https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.406/sdk-productVersion.txt
dotnet-install: Calling: machine_has curl
dotnet-install: Calling: is_dotnet_package_installed /root/.dotnet sdk 6.0.406
dotnet-install: Calling: combine_paths /root/.dotnet sdk
dotnet-install: combine_paths: root_path=/root/.dotnet
dotnet-install: combine_paths: child_path=sdk
dotnet-install: Calling: combine_paths /root/.dotnet/sdk 6.0.406
dotnet-install: combine_paths: root_path=/root/.dotnet/sdk
dotnet-install: combine_paths: child_path=6.0.406
dotnet-install: is_dotnet_package_installed: dotnet_package_path=/root/.dotnet/sdk/6.0.406
dotnet-install: Generated 1 links.
dotnet-install: Link 0: aka.ms, 6.0.406, https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.406/dotnet-sdk-6.0.406-linux-musl-x64.tar.gz
dotnet-install: Calling: install_dotnet 
dotnet-install: Zip path: /tmp/dotnet.Ww74QNKN1
dotnet-install: Attempting to download using aka.ms link https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.406/dotnet-sdk-6.0.406-linux-musl-x64.tar.gz
dotnet-install: Calling: download https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.406/dotnet-sdk-6.0.406-linux-musl-x64.tar.gz /tmp/dotnet.Ww74QNKN1
dotnet-install: Calling: machine_has curl
dotnet-install: Calling: downloadcurl https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.406/dotnet-sdk-6.0.406-linux-musl-x64.tar.gz /tmp/dotnet.Ww74QNKN1

**Comment by RayWangQvQ** [comment]
日志不完整，需要确认是否是青龙因为超时关停任务
