### ISSUE TITLE
【其他】开发群

### ISSUE THREAD

**Issue by RayWangQvQ** [RayWangQvQ/BiliBiliToolPro#469]
最近收到很多高质量的PR，想想现在还没有一个用于开发交流的群组，还是建一个吧（主要是想跟你们偷学dotnet技术😶）。

之前的微信群被定义为聊天吹水群，前前后后因为举报封禁，转移过四五次群组了。有的是因为图片尺度，但大部分还是因为意识形态。。。

这次建个开发群，用来主聊技术、dotnet、bili、云这些。二极管和对技术不感兴趣的就不要进了（你们可以去吹水群），欢迎对技术感兴趣的朋友，尤其是以前贡献过代码的朋友进。

![mmqrcode1677558865210.png](https://user-images.githubusercontent.com/31154238/221757869-f5d6f3bf-b849-479c-86f2-460a8dae5183.png)

另外，我发现有些资源也是可以（或者说应该）和曾经贡献过的开发人员一起分享的：

- JetBrain免费证书

之前用这个开源仓库申请了一个JetBrain的免费证书，包含resharper，对dotnet开发还是非常有用的，这个应该是与贡献者共享的才对。但之前证书个数好像写成1个了，今年续期时我会留意下。

- bili接口文档

目前有个使用apifox创建的api组织，用于调试和开发，这个也可以分享出来，可以一起维护使用。

**Comment by chenliu1993** [comment]
过期了，请问能拉一下嘛

**Comment by elricccc** [comment]
过期了，能重新拉一下吗

**Comment by ichenc** [comment]
过期了

**Comment by RayWangQvQ** [comment]
![fd1ac95ce9da97e98ef76ff738fd789](https://user-images.githubusercontent.com/31154238/224759605-ea657737-68d6-4482-b1e4-c1600780457a.jpg)

更新了，仅限开发进，非开发被会请出去哈

**Comment by Leon19960120** [comment]
可以搞个TG群吗****

**Comment by YYYet** [comment]
过期了过期了宝

**Comment by jackview** [comment]
过期了，麻烦更新一下

**Comment by xisuo67** [comment]
二维码过期了呢！更新一下呗

**Comment by 2077872725** [comment]
搞个tg群吧

**Comment by fenglindubu** [comment]
过期啦QAQ

**Comment by WhiteCjy** [comment]
过期啦 还能更新下吗

**Comment by KGLongWamg** [comment]
过期拉，能再拉一下吗

**Comment by iven98** [comment]
过期拉，能再拉一下吗****

**Comment by LeeHuas** [comment]
过期罗拉一下~

**Comment by xiaowugui-117** [comment]
过期了

**Comment by w32x42y** [comment]
可以重新发下二维码吗

**Comment by rxxcy** [comment]
可以重新发下二维码吗

**Comment by RayWangQvQ** [comment]
TG群组：https://t.me/+TproSmcI8P44MzU1

**Comment by Taokyla** [comment]
希望作者更新一下docker镜像，github或者docker hub的都可以

**Comment by jiuchu** [comment]
微信群麻烦大佬更新下 谢谢
