### ISSUE TITLE
【其他】请问文档中能否增加Bark的配置指南？

### ISSUE THREAD

**Issue by AHCorn** [RayWangQvQ/BiliBiliToolPro#470]
抱歉打扰您，我在配置Bark推送时遇到了些问题，配置环境变量BARK_PUSH为URL后也并未进行推送（其他脚本可正常推送），查阅文档也没有看到关于Bark的配置介绍，希望能够补充文档关于Bark的部分，非常感谢

**Comment by Akimio521** [comment]
#233中有提到过，可以结合[推送到自定义Api](https://github.com/RayWangQvQ/BiliBiliToolPro/blob/main/docs/configuration.md#367-%E6%8E%A8%E9%80%81%E5%88%B0%E8%87%AA%E5%AE%9A%E4%B9%89api)部分一起观看
====================================================================
添加参数Ray_Serilog__WriteTo__8__Args__api的值为https://api.day.app/push
添加参数Ray_Serilog__WriteTo__8__Args__bodyJsonTemplate值为{"device_key":"keyQAQ","title":"BiliBili\u7B7E\u5230","body":#msg#} 其中keyQAQ更改自己的Bark的Key即可使用。
=====================================================================
如果还需要配置其他参数也可以在bodyJsonTemplate部分加上，例如配置ICON、分组以及时效性通知
{"device_key":"keyQAQ","title":"BiliBiliTool","body":#msg#,"group":"青龙定时任务","icon":"https://qn.whyour.cn/logo.png","level":"passive"}
