### ISSUE TITLE
【Bug】使用docker，近几个月都只有在报cookie错误或过期。去刷新或重新获取后都还是一样

### ISSUE THREAD

**Issue by franco1013** [RayWangQvQ/BiliBiliToolPro#48]
版本号：docker自动更新到的最新版
运行环境：docke

问题描述：使用docker，近几个月都只有在报cookie错误或过期。去刷新或重新获取后都还是一样。有空的时候就会去调试，反馈给作者微信也没回（可能是那个微信弃用了吧）。而且有时的cookie去拉取 的时候，有时过几个小时拉下来的就不一样的，我一开始以为是浏览器问题(chrome）换了edge也一样。原以为是b站cookie改变了，但好像你们都没有这种情况，所以我暂时也不知道什么鬼，也好久没启用了

日志信息：（如果可以，请贴出Debug级别的日志信息，以便更高效的确定和解决问题。）

**Comment by franco1013** [comment]
我刚刚去试了青龙的，用同样的cookie是读取正常的，我现在就很无语，目前准备换到青龙先用一段时间，最终还是用docker舒服

**Comment by RayWangQvQ** [comment]
`Cookie`是配在环境变量里的还是配置文件里的？
![image](https://user-images.githubusercontent.com/31154238/160660823-47b20d6c-9ec9-42c9-8ef6-ad52c3de80da.png)
目前看，环境变量里修改后会热更新，配置文件修改后不一定能热更新。

如果是用的配置文件，修改后，可以试下重启容器。

**Comment by franco1013** [comment]
sorry，之前去学校了没看到。问题解决了，我是配置在群晖的docker上的，今天研究了一下，发现我用的映像还是之前那个tool没用pro这个新版的，应该是之前那个失效了吧。今天刚刚换了新版的已经正常了。谢谢
