### ISSUE TITLE
【其他】为什么一天才5点经验

### ISSUE THREAD

**Issue by TheSaltwaterRoom** [RayWangQvQ/BiliBiliToolPro#481]
每天跑完脚本才5点经验

**Comment by leeima** [comment]
同问，投币成功，经验加0

**Comment by leeima** [comment]
只有登录经验，分享，投币都是0

**Comment by leeima** [comment]
实际经验加了，只是日志显示0

**Comment by RayWangQvQ** [comment]
今天特意观察了下，正常的：
![image](https://user-images.githubusercontent.com/31154238/223604140-4c5f9e3f-9120-4738-88b4-e166056f4668.png)

另外我发现，B站的这个经验查询api，拿到的数据是滞后。也就是刚做完任务，页面看是没完成，但是等一段时间，就刷新成完成了。

你们说的可能就是因为这个滞后导致的。


如果还不放心，日常任务可以设置成每天跑两次。这个任务是幂等的，跑多次也没事。

**Comment by RayWangQvQ** [comment]
> 实际经验加了，只是日志显示0

你这个不是同一个问题，#484 已经在v1.0.2修复了

**Comment by leeima** [comment]
> 今天特意观察了下，正常的： ![image](https://user-images.githubusercontent.com/31154238/223604140-4c5f9e3f-9120-4738-88b4-e166056f4668.png)
> 
> 另外我发现，B站的这个经验查询api，拿到的数据是滞后。也就是刚做完任务，页面看是没完成，但是等一段时间，就刷新成完成了。
> 
> 你们说的可能就是因为这个滞后导致的。
> 
> 如果还不放心，日常任务可以设置成每天跑两次。这个任务是幂等的，跑多次也没事。

可不可以延后推送，确实数据滞后，再运行一遍就可以
这个图片推送怎么设置有教程吗

**Comment by TheSaltwaterRoom** [comment]
<img width="725" alt="image" src="https://user-images.githubusercontent.com/20590174/223624810-5ec0a977-8abe-470a-bf75-c524fb3a56c7.png">
我这才1天10点经验，不能吧

**Comment by RayWangQvQ** [comment]
Talk is cheap, show me the logs

**Comment by catlair** [comment]
> > 今天特意观察了下，正常的： ![image](https://user-images.githubusercontent.com/31154238/223604140-4c5f9e3f-9120-4738-88b4-e166056f4668.png)
> > 另外我发现，B站的这个经验查询api，拿到的数据是滞后。也就是刚做完任务，页面看是没完成，但是等一段时间，就刷新成完成了。
> > 你们说的可能就是因为这个滞后导致的。
> > 如果还不放心，日常任务可以设置成每天跑两次。这个任务是幂等的，跑多次也没事。
> 
> 可不可以延后推送，确实数据滞后，再运行一遍就可以 这个图片推送怎么设置有教程吗

这个不是图片推送，是b站的截图啦
