### ISSUE TITLE
w11系统扫描登录后仍然无账号

### ISSUE THREAD

**Issue by rm-f1024** [RayWangQvQ/BiliBiliToolPro#486]
版本号：bilibili-tool-pro-v1.0.2-win-x64.zip
运行环境：win11

问题描述：
扫描登录后仍然显示无账号,cookies是存在的
![image](https://user-images.githubusercontent.com/57568495/223664982-2b6ccd1a-133c-49a7-b971-3ab4618666f3.png)

日志信息：（如果可以，请贴出Debug级别的日志信息，以便更高效的确定和解决问题。）
![image](https://user-images.githubusercontent.com/57568495/223665040-1125f729-a719-4957-9723-b73bbf4ae434.png)

**Comment by RayWangQvQ** [comment]
为啥目录层级这么深？

你先把x64那个文件夹拷贝到其他目录下，就行了。

等会儿我来检查下cicd脚本，应该是压缩的时候目录没处理好。

**Comment by RayWangQvQ** [comment]
fixed by v1.0.3
