### ISSUE TITLE
【异常】你好，请问下面具版青龙执行脚本报构建失败

### ISSUE THREAD

**Issue by yanhualengleng** [RayWangQvQ/BiliBiliToolPro#487]
版本号：仓库拉取最新版本最新脚本

运行环境：面具青龙2.14.8

问题描述：执行拉取后的除bili_base脚本以外都会报构建失败，需要修复生成错误。以下日志是我在青龙面板里面差取到的相关日志，其余地方并未发现日志

日志信息：已安装dotnet，当前版本：6.0.114

repo目录: /ql/data/repo
bili仓库目录: /ql/data/repo/RayWangQvQ_BiliBiliToolPro

/usr/lib/dotnet/sdk/6.0.114/NuGet.targets(130,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [/ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/Ray.BiliBiliTool.Console.csproj]
/usr/lib/dotnet/sdk/6.0.114/NuGet.targets(130,5): error :   Request headers must contain only ASCII characters. [/ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/Ray.BiliBiliTool.Console.csproj]

The build failed. Fix the build errors and run again.

**Comment by RayWangQvQ** [comment]
>Request headers must contain only ASCII characters.

意思是你机器发出得http请求头里包含异常编码字符，建议检查下自己得网络环境，特别是梯子啥的。

**Comment by yanhualengleng** [comment]
> 

好的，谢谢回复
