### ISSUE TITLE
【Bug】MSBUILD : error MSB1009: 项目文件不存在

### ISSUE THREAD

**Issue by Galiyun** [RayWangQvQ/BiliBiliToolPro#49]
dotnet安装完成，拉取到脚本后，执行脚本文件报错。

```
## 开始执行... 2022-03-28 16:34:29

MSBUILD : error MSB1009: 项目文件不存在。
开关:/ql/repo/raywangqvq_bilibilitoolpro/src/Ray.BiliBiliTool.Console

生成失败。请修复生成错误并重新运行。

## 执行结束... 2022-03-28 16:34:30 耗时 1 秒
```

**Comment by TwShuai** [comment]
我也报错这个

**Comment by RayWangQvQ** [comment]
如 https://github.com/RayWangQvQ/BiliBiliToolPro/issues/44 

新版青龙修改了代码仓库的目录，稍后我来修复下

**Comment by TwShuai** [comment]
> 如 https://github.com/RayWangQvQ/BiliBiliToolPro/issues/44 
> 
> 新版青龙修改了代码仓库的目录，稍后我来修复下

最新版2.12.0就出现这个

**Comment by RayWangQvQ** [comment]
同 #44 ，已于`v0.0.7`版本修复，重新运行下拉库任务即可
