### ISSUE TITLE
找不到要运行的项目。请确保 /root 中存在项目，或使用 --project 传递项目路径。

### ISSUE THREAD

**Issue by gzp-192** [RayWangQvQ/BiliBiliToolPro#490]
版本号：（请贴出你的版本号，请确认是否已通过升级到最新版来解决当前问题？）
运行环境：（请贴出运行环境，比如是Actions或docker或本地？是Win还是Linux？）

问题描述：（提issue前请先确认没有其他人已提过相同的议题，请清晰的描述所您所遇到的问题。）

日志信息：（如果可以，请贴出Debug级别的日志信息，以便更高效的确定和解决问题。）

**Comment by gzp-192** [comment]
![image](https://user-images.githubusercontent.com/55121150/223987747-7ac05aa3-6892-45ba-8629-a705f76015ad.png)
1、运行天选时刻的时候报错
2、青龙版本：v2.10.13
3、服务器Linux

**Comment by gzp-192** [comment]
![image](https://user-images.githubusercontent.com/55121150/224076925-5d7c48b7-70d9-4aae-93fa-812e62f78135.png)
使用project传递项目路径是什么意思啊？？

**Comment by gzp-192** [comment]
救命，现在出现这种问题了。。。
![image](https://user-images.githubusercontent.com/55121150/224226325-bf44861f-060d-49e4-9d9c-75101b9ec6de.png)

**Comment by RayWangQvQ** [comment]
最新版已修复
