### ISSUE TITLE
【建议】不知道天选时刻能不能加入多线程扫描

### ISSUE THREAD

**Issue by GRGK0604** [RayWangQvQ/BiliBiliToolPro#498]
建议内容：现在的天选是单线程还是多线，要是单线的话能否加个多线程

**Comment by RayWangQvQ** [comment]
是因为安全考虑，不会使用多线程。

另外，天选抽太多次，阿b会降低你的中奖率，所以不建议一天跑很多次，随缘就好，别卷。
