### ISSUE TITLE
这是怎么回事

### ISSUE THREAD

**Issue by mmeiwenlong** [RayWangQvQ/BiliBiliToolPro#50]
版本号：（请贴出你的版本号，请确认是否已通过升级到最新版来解决当前问题？）
运行环境：（请贴出运行环境，比如是Actions或docker或本地？是Win还是Linux？）

问题描述：（提issue前请先确认没有其他人已提过相同的议题，请清晰的描述所您所遇到的问题。）

日志信息：（如果可以，请贴出Debug级别的日志信息，以便更高效的确定和解决问题。）
![QQ截图20220328224854](https://user-images.githubusercontent.com/44661424/160424975-7dadef19-d3e4-4397-8b82-5d1903ec6034.png)
这是咋了

**Comment by RayWangQvQ** [comment]
`UserAgent`格式不正确？

**Comment by mmeiwenlong** [comment]
> `UserAgent`格式不正确？

我不单独写user也是这样！依赖我确认装好了，库也拉好了，ck就直接在青龙面板里面的第二个环境里有设RA什么开头的_1贴在里面就开始跑了，开始以为ck不对，重新在rdge获取还是一样，就彻底不知道怎么做了，青龙版本2.11.3拉的脚本常规版，

**Comment by RayWangQvQ** [comment]
配置里把`UserAgent`删掉或置空，然后重启容器
