### ISSUE TITLE
自定义推送中，怎么把content放进去

### ISSUE THREAD

**Issue by qtv587** [RayWangQvQ/BiliBiliToolPro#509]
我在使用Wx_pusher,
比如我在配置中加了：
export Ray_Serilog__WriteTo__8__Args__bodyJsonTemplate='
{
  "appToken":"AT_MFJnJyd2zxxxxx",
  "content":"内容",
  "summary":"标题",
  "contentType":2,
  "uids":["UID_2xxxxx5"]
}'

这个content是写死的，有大佬能告诉我怎么获取到脚本运行的content嘛

**Comment by nickdlkk** [comment]
看[代码](https://github.com/RayWangQvQ/BiliBiliToolPro/blob/11f29155cff71093621ed8e6c9a5285172182706/src/Ray.Serilog.Sinks/Ray.Serilog.Sinks.OtherApiBatched/OtherApiClient.cs#L30)

placeholder变量 定义要被替换的字符,就是你的<内容>
