### ISSUE TITLE
找不到要运行的项目。请确保 /root 中存在项目，或使用 --project 传递项目路径。 解决方法

### ISSUE THREAD

**Issue by nspron** [RayWangQvQ/BiliBiliToolPro#512]
部分设备可能无法定位文件夹位置 需要绝对定位
![223987747-7ac05aa3-6892-45ba-8629-a705f76015ad](https://user-images.githubusercontent.com/79355790/227599053-5b97a3d9-caa4-4569-b51c-7f2d69b1e7d1.png)
![QQ截图20230325013252](https://user-images.githubusercontent.com/79355790/227599065-c4acb0f9-0443-4f6d-98eb-2df8d8e160d8.png)

**Comment by RayWangQvQ** [comment]
不能这么改的，只有较新版青龙的仓库目录才是`/ql/data/repo`，老版本是`/ql/repo`。

然后bili脚本是从青龙的环境变量里读取它的仓库目录的（$dir_repo），从你日志看，它是读取到`/ql/repo`，至于为什么新版读取到的却是老板路径，可能是青龙bug，也可能是你的某些操作导致的，建议再追踪下。

**Comment by hutuhff** [comment]
<img width="504" alt="image" src="https://user-images.githubusercontent.com/112541718/230719586-337fd52c-bda1-42c7-b1a6-d6012623aea3.png">
也遇到了

**Comment by dalant2019** [comment]
哎，我也遇到这个问题，折腾了到深夜最后用finashell telnet过去，直接到目录下面执行算是搞好了，哈哈哈哈

root@qinglong:/ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console $ export Ray_RunTasks=Login && \
> dotnet run
  ____               ____    _   _____           _  
 |  _ \ __ _ _   _  | __ ) _| |_|_   _|__   ___ | | 
 | |_) / _` | | | | |  _ \(_) (_) | |/ _ \ / _ \| | 
 |  _ < (_| | |_| | | |_) | | | | | | (_) | (_) | | 
 |_| \_\__,_|\__, | |____/|_|_|_| |_|\___/ \___/|_| 
             |___/                                  

[18:59:37 INF] BiliBiliToolPro 开始运行...

[18:59:37 INF] 【账号个数】0个

**Comment by RayWangQvQ** [comment]
于 #490 追踪
