### ISSUE TITLE
找不到要运行的项目。请确保 /root 中存在项目，或使用 --project 传递项目路径。

### ISSUE THREAD

**Issue by itiao** [RayWangQvQ/BiliBiliToolPro#516]
bili扫码登录[dev先行版]
## 开始执行... 2023-03-31 11:06:40

已安装dotnet，当前版本：6.0.114

repo目录: /ql/data/repo
bili仓库目录: 

bili_dev_task_login.sh: line 6: cd:: command not found
找不到要运行的项目。请确保 /root 中存在项目，或使用 --project 传递项目路径。

## 执行结束... 2023-03-31 11:06:42  耗时 2 秒

**Comment by itiao** [comment]
青龙版本 2.14.12

**Comment by qzzq2002** [comment]
遇到同样的问题

**Comment by RayWangQvQ** [comment]
于 #490  追踪
