### ISSUE TITLE
【拉库命令成功了 但是定时任务里面找不到

### ISSUE THREAD

**Issue by duliri888** [RayWangQvQ/BiliBiliToolPro#518]
## 开始执行... 2023-04-01 23:43:09

开始更新仓库：/ql/repo/RayWangQvQ_BiliBiliToolPro

Fetching origin
HEAD is now at 11f2915 chore: update
Already up to date.

更新/ql/repo/RayWangQvQ_BiliBiliToolPro成功...

## 执行结束... 2023-04-01 23:43:14  耗时 5 秒

**Comment by RayWangQvQ** [comment]
少做了一步，文档里有，配sh
