### ISSUE TITLE
天选时刻 未登录

### ISSUE THREAD

**Issue by ylegeb** [RayWangQvQ/BiliBiliToolPro#52]
![S20329-10300369(1)](https://user-images.githubusercontent.com/62826329/160521745-7b4e4fd7-de8e-4b31-aaa9-f50cc6d1a112.png)

请问天选时刻提示未登录是什么地方配置错了？（每日任务正常），是需要自己挂着直播吗？

**Comment by RayWangQvQ** [comment]
`Cookie`过期了

**Comment by ylegeb** [comment]
谢谢大佬
