### ISSUE TITLE
【建议】使指定账号运行指定内容

### ISSUE THREAD

**Issue by RAINighty** [RayWangQvQ/BiliBiliToolPro#528]
建议内容：
可以指定账号运行指定内容
如账号A我想让它运行每日任务+天选时刻，账号B我想让它只运行每日任务

**Comment by RayWangQvQ** [comment]
有点复杂。

目前，用docker跑，是直接就支持的，每个账号起一个容器就行了，也就是每个账号都有自己的一套配置。

但是想青龙这种，就不好搞了。因为账号是是一个集合，它们共用了同一套配置。

**Comment by RAINighty** [comment]
了解
