### ISSUE TITLE
如何修改访问青龙面板的端口，我的是5700，好像默认访问5600。

### ISSUE THREAD

**Issue by kaima2022** [RayWangQvQ/BiliBiliToolPro#529]
我的是5700，好像默认访问5600
GET /api/envs?searchValue=Ray_BiliBiliCookies__ HTTP/1.1
Host: localhost:5600
Authorization: Bearer xxxxxxxxxxxxxxx
Accept: application/json; q=0.001, application/xml; q=0.001

[EXCEPTION]
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.

**Comment by DoiiarX** [comment]
请问您如何解决的？

**Comment by DoiiarX** [comment]
https://notion.doiiars.com/article/fixing-bilibilitoolpro-dockercompose-failure

不需要了，谢谢。我解决了这个bug。以下是思路和解决方案。
