### ISSUE TITLE
MSBUILD : error MSB1009: 项目文件不存在。

### ISSUE THREAD

**Issue by jqjhl** [RayWangQvQ/BiliBiliToolPro#53]
qinglong 2.12.0
MSBUILD : error MSB1009: 项目文件不存在。
开关:/ql/repo/raywangqvq_bilibilitoolpro/src/Ray.BiliBiliTool.Console

生成失败。请修复生成错误并重新运行。

**Comment by RayWangQvQ** [comment]
同 #44 ，已于`v0.0.7`版本修复，重新运行下拉库任务即可
