### ISSUE TITLE
【Bug】青龙运行脚本时，cd到repo目录，如果find到多个，会发生异常

### ISSUE THREAD

**Issue by 50801684** [RayWangQvQ/BiliBiliToolPro#54]
![image](https://user-images.githubusercontent.com/42910719/160745768-70e6970a-cf03-4902-b3f5-ca53c3c4d259.png)

**Comment by RayWangQvQ** [comment]
你的目录里为什么会有个换行`\n`，请严格按照文档说明操作

**Comment by hujihan** [comment]
这如何修改？

**Comment by hujihan** [comment]
在哪个配置文件里修改，我完全按照教程来做的啊

**Comment by RayWangQvQ** [comment]
试试`docker exec -it qinglong rm -fr /ql/repo`

其中qinglong 是青龙容器的名字，不知道的可以`docker ps`查看自己容器名

**Comment by hujihan** [comment]
试了你的方法，显示这个
![Screenshot_2022-04-06-20-34-20-018-edit_com alibaba aliyun](https://user-images.githubusercontent.com/46958243/161975763-68eb61fe-bb59-49b6-bb30-0a285fc2188b.jpg)

**Comment by hujihan** [comment]
我解决了，是青龙面板版本太高的问题，2.12.1的版本很多京东的脚本都无法运行，于是我将版本降回了2.10.2，再次安装bilibilitoolpro，成功运行
![image](https://user-images.githubusercontent.com/46958243/162555167-d017ef92-c571-4892-a844-215333ba0cd3.png)

**Comment by drw2005** [comment]
> 我解决了，是青龙面板版本太高的问题，2.12.1的版本很多京东的脚本都无法运行，于是我将版本降回了2.10.2，再次安装bilibilitoolpro，成功运行 ![image](https://user-images.githubusercontent.com/46958243/162555167-d017ef92-c571-4892-a844-215333ba0cd3.png)

并不是，我就是v2.12.1，运行正常。

**Comment by wenrouhao** [comment]
> 

2.11/2.12映射目录不一样他部署的时候路径错了所以……退回老版本就好了

**Comment by RayWangQvQ** [comment]
当前版本（v0.1.1）已解决
