### ISSUE TITLE
bili扫码登录无报错，但是无二维码

### ISSUE THREAD

**Issue by Dlian-Zero** [RayWangQvQ/BiliBiliToolPro#544]
版本号：（请贴出你的版本号，请确认是否已通过升级到最新版来解决当前问题？）
运行环境：青龙

问题描述：bili扫码登录无报错，但是无二维码

日志信息：

**Comment by Dlian-Zero** [comment]
> 版本号：（请贴出你的版本号，请确认是否已通过升级到最新版来解决当前问题？） 运行环境：青龙
> 
> 问题描述：bili扫码登录无报错，但是无二维码
> 
> 日志信息：

bili扫码登录
## 开始执行... 2023-05-20 19:39:35

已安装dotnet，当前版本：6.0.115

repo目录: /ql/data/repo
bili仓库目录: /ql/data/repo/raywangqvq_bilibilitoolpro

[19:39:41 INF] BiliBiliToolPro 开始运行...

[19:39:41 INF] 【目标任务】Login
[19:39:41 INF] 【账号个数】0个

[19:39:41 INF] 运行结束


## 执行结束... 2023-05-20 19:39:41  耗时 6 秒

**Comment by RayWangQvQ** [comment]
确定下是否是最新版本不，你的为啥没有打印logo

![image](https://github.com/RayWangQvQ/BiliBiliToolPro/assets/31154238/bf2157aa-4ff3-45c4-b53b-084c45de4ca0)
