### ISSUE TITLE
运行所有脚本 The build failed. Fix the build errors and run again.

### ISSUE THREAD

**Issue by canxunwangluo** [RayWangQvQ/BiliBiliToolPro#545]
# 开始执行... 2023-05-21 15:34:25

./bili_task_base.sh: line 7: /root/.bashrc: No such file or directory
已安装dotnet，当前版本：6.0.116

repo目录: /ql/data/repo
bili仓库目录: /ql/data/repo/RayWangQvQ_BiliBiliToolPro

/usr/lib/dotnet/sdk/6.0.116/NuGet.targets(130,5): error : Failed to download package 'Newtonsoft.Json.13.0.2' from 'https://api.nuget.org/v3-flatcontainer/newtonsoft.json/13.0.2/newtonsoft.json.13.0.2.nupkg'. [/ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/Ray.BiliBiliTool.Console.csproj]
/usr/lib/dotnet/sdk/6.0.116/NuGet.targets(130,5): error : The download of 'https://api.nuget.org/v3-flatcontainer/newtonsoft.json/13.0.2/newtonsoft.json.13.0.2.nupkg' timed out because no data was received for 60000ms. [/ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/Ray.BiliBiliTool.Console.csproj]
/usr/lib/dotnet/sdk/6.0.116/NuGet.targets(130,5): error :   Exception of type 'System.TimeoutException' was thrown. [/ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/Ray.BiliBiliTool.Console.csproj]
/usr/lib/dotnet/sdk/6.0.116/NuGet.targets(130,5): error : The feed 'nuget.org [https://api.nuget.org/v3/index.json]' lists package 'Newtonsoft.Json.13.0.2' but multiple attempts to download the nupkg have failed. The feed is either invalid or required packages were removed while the current operation was in progress. Verify the package exists on the feed and try again. [/ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/Ray.BiliBiliTool.Console.csproj]
/usr/lib/dotnet/sdk/6.0.116/NuGet.targets(130,5): error :   Unable to find package 'Newtonsoft.Json.13.0.2'. [/ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/Ray.BiliBiliTool.Console.csproj]

The build failed. Fix the build errors and run again.

## 执行结束... 2023-05-21 15:48:03  耗时 818 秒

**Comment by RayWangQvQ** [comment]
有个任务叫`bili尝试修复异常`，运行下试试
