### ISSUE TITLE
【Bug】直播粉丝牌异常

### ISSUE THREAD

**Issue by cachexy123** [RayWangQvQ/BiliBiliToolPro#546]
版本号：最新
运行环境：linux

问题描述：直播粉丝牌任务报错, 访问权限不足

日志信息：昨天开始的吧(不太确定)  大概看了一下, https://api.bilibili.com/x/space/wbi/acc/info?mid=xxxxxxx    是这接口的问题

**Comment by RayWangQvQ** [comment]
收到，稍后修复
