### ISSUE TITLE
【Bug】拉取库未运行

### ISSUE THREAD

**Issue by XiaoZhiQ-Q** [RayWangQvQ/BiliBiliToolPro#547]
版本号：青龙2.10.3
运行环境：Linux

问题描述：（提issue前请先确认没有其他人已提过相同的议题，请清晰的描述所您所遇到的问题。）

![image](https://github.com/RayWangQvQ/BiliBiliToolPro/assets/84890346/31f701c9-db5a-4e57-8774-921ca9a6d562)
![image](https://github.com/RayWangQvQ/BiliBiliToolPro/assets/84890346/1d082a3e-5eb3-4847-a0a6-f087e2474829)

**Comment by XiaoZhiQ-Q** [comment]
![image](https://github.com/RayWangQvQ/BiliBiliToolPro/assets/84890346/430a8561-f715-4837-8002-9001a01c983c)
订阅库 报没有权限拉取

**Comment by gaohan-cmd** [comment]
我也碰见了，请问您解决了吗

**Comment by kotonamihuiren** [comment]
一样 拉取不了
