### ISSUE TITLE
【建议】增加 Microsoft Teams 推送功能。

### ISSUE THREAD

**Issue by AkiraVoid** [RayWangQvQ/BiliBiliToolPro#55]
建议内容：

目前虽然可以通过配置自定义 API 实现需求，但是格式上存在一些问题。Microsoft Teams Connector 支持 Markdown 格式文本，但似乎它只将 `\n\n` 识别为断行，而不识别 `\n`。

相关文档：

- [Webhooks and connectors（主要查看 Create Incoming Webhooks 和 Create and send messages 两个板块）](https://docs.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/what-are-webhooks-and-connectors)
- [Types of cards](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-reference#office-365-connector-card)
- [Text formatting in cards](https://docs.microsoft.com/en-us/microsoftteams/platform/task-modules-and-cards/cards/cards-format?tabs=connector-md%2Cconnector-html)

**Comment by AkiraVoid** [comment]
目前通过自定义 API 实现的效果：

[效果图](https://wvw8c-my.sharepoint.com/:i:/g/personal/me_akiravoid_com/EeqKxw5Vj8hGoT5I3EZnWNMBWimCg2HYHmdE52FiYpdfpA)

**Comment by AkiraVoid** [comment]
我可以提供一个 Microsoft 365 Developers 订阅帐户用于测试，你也可以在 [Microsoft 365 Developer Program](https://developer.microsoft.com/en-us/microsoft-365/dev-program) 上自己申请一个 Developer Subscription 用于开发。

**Comment by RayWangQvQ** [comment]
Good idea!

**Comment by RayWangQvQ** [comment]
已于`v0.0.8`新增`Microsoft Teams`推送：
![image](https://user-images.githubusercontent.com/31154238/160879575-cc0a0542-d678-41b6-8d60-f9026155f35d.png)
![image](https://user-images.githubusercontent.com/31154238/160879714-fcef530e-8691-491a-aba8-840dc9b079ca.png)
感谢提供文档！

**Comment by AkiraVoid** [comment]
好高的效率！谢谢！
________________________________
