### ISSUE TITLE
【Bug】青龙拉取2.0版本后，运行每日任务服务器直接爆满

### ISSUE THREAD

**Issue by WGwuzhi** [RayWangQvQ/BiliBiliToolPro#558]
版本号：（2.0）
运行环境：（青龙面板）

问题描述：（青龙拉群2.0版本后，运行每日任务服务器直接爆满）

日志信息：（## 开始执行... 2023-06-01 10:47:03

已安装dotnet，当前版本：6.0.405

repo目录: /ql/repo
bili仓库目录: /ql/repo/RayWangQvQ_BiliBiliToolPro![image](https://github.com/RayWangQvQ/BiliBiliToolPro/assets/57304774/adb11c2c-2d25-474f-9390-3f9c80f84a53)）

**Comment by RayWangQvQ** [comment]
升级到最新版试试
