### ISSUE TITLE
【其他】青龙拉不出任务

### ISSUE THREAD

**Issue by ALKSDJ0000** [RayWangQvQ/BiliBiliToolPro#56]
（提issue前请先确认没有其他人提过相同的议题）
![Uploading Screenshot_20220330-132727.jpg…]()

**Comment by hug1013** [comment]
这题我会 你应该只装了青龙 没改配置 这个- [ ] 库要改青龙部分配置 不然就拉不了![mmexport1648618767246.png](https://user-images.githubusercontent.com/86723248/160759171-1ce790cd-c5e1-4656-b515-68b7b32bbbc4.png)

**Comment by ALKSDJ0000** [comment]
> 这题我会 你应该只装了青龙 没改配置 这个库要改青龙部分配置 不然就拉不了![mmexport1648618767246.png](https://user-images.githubusercontent.com/86723248/160759171-1ce790cd-c5e1-4656-b515-68b7b32bbbc4.png)

改了 是不是青龙版本一点高2.11.3
![Uploading Screenshot_20220330-193444.jpg…]()

**Comment by mmeiwenlong** [comment]
仔细看说明吧。2.11.3没问题

**Comment by mmeiwenlong** [comment]
![QQ截图20220330211249](https://user-images.githubusercontent.com/44661424/160842768-c533b028-e9c7-48a0-b285-9119869fed01.png)
