### ISSUE TITLE
使用biliup-rs获取的cookie如何对应环境变量

### ISSUE THREAD

**Issue by ljwtorch** [RayWangQvQ/BiliBiliToolPro#563]
请问如果使用biliup-rs进行扫码登录获取的cookie.json文件，应该如何对应环境变量名称使用？

**Comment by RayWangQvQ** [comment]
`biliup-rs`是啥

**Comment by ljwtorch** [comment]
https://github.com/biliup/biliup-rs
您可以看一下这个仓库，我之前用这个获取了cookie；目前我只是担心使用您的工具获取cookie后原来的会失效

**Comment by RayWangQvQ** [comment]
不会使其他失效
