### ISSUE TITLE
docker部署到时间不执行自动任务

### ISSUE THREAD

**Issue by wwkk2580** [RayWangQvQ/BiliBiliToolPro#565]
![image](https://github.com/RayWangQvQ/BiliBiliToolPro/assets/76099203/0c14c146-5c07-4c01-9a52-86b636745fc0)
![image](https://github.com/RayWangQvQ/BiliBiliToolPro/assets/76099203/abc9122c-805c-408f-986a-7fdc3e22f172)
**23:08初始化完成，每日任务23:15开始，到时间后没有自动运行，手动运行无问题**
![image](https://github.com/RayWangQvQ/BiliBiliToolPro/assets/76099203/1fd6b648-0ad3-4bf6-b2da-fb152d838c7f)
**/etc/cron.env文件内容**
![image](https://github.com/RayWangQvQ/BiliBiliToolPro/assets/76099203/8a2e297c-9d13-4ad9-bbf6-f5a02e2725f0)
**appsettings.json文件内容**
![image](https://github.com/RayWangQvQ/BiliBiliToolPro/assets/76099203/ea7f144f-08f0-4c19-8e9a-f884a272f98b)
**docker-compose.yml文件内容**

**版本为2.0.1，win docker部署环境
同时再问个问题，同一时间设置了多个任务，是什么运行结果？？**
**还有一个事，建个群吧，tg群号（好像有）是多少？**

**Comment by AccoutingLearning** [comment]
可以看下logs文件夹里的文件，不要通过容器里看
