### ISSUE TITLE
【Bug】TG不推送信息

### ISSUE THREAD

**Issue by Yat-Muk** [RayWangQvQ/BiliBiliToolPro#567]
其他項目都有推送，唯獨bilibiliToolPro不推送信息

**Comment by taozhiyu** [comment]
一样，一直没意识到这个问题

**Comment by JackZhou77322** [comment]
我也是没推送

**Comment by taozhiyu** [comment]
https://github.com/RayWangQvQ/BiliBiliToolPro/blob/main/docs/configuration.md

解决了，需要单独配置
