### ISSUE TITLE
青龙面板如何使用个性化自定义配置

### ISSUE THREAD

**Issue by hug1013** [RayWangQvQ/BiliBiliToolPro#57]
请问使用青龙面板的话，个性化自定义配置是在哪里设置，是在环境变量中添加还是在脚本管理中修改。麻烦解答一下谢谢
https://github.com/RayWangQvQ/BiliBiliToolPro/blob/main/docs/configuration.md

**Comment by RayWangQvQ** [comment]
都行

**Comment by hug1013** [comment]
您是否会增加动态抽奖 或者是实现脚本全天候监控直播间呢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月30日(周三) 晚上9:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [RayWangQvQ/BiliBiliToolPro] 青龙面板如何使用个性化自定义配置 (Issue #57)




 
都行

**Comment by RayWangQvQ** [comment]
会的
