### ISSUE TITLE
【Bug】发送弹幕失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by taochangle** [RayWangQvQ/BiliBiliToolPro#573]
版本号： v2.0.1 
运行环境：（请贴出运行环境，比如是Actions或docker或本地？是Win还是Linux？）
docker
问题描述： 
发送弹幕失败，继续其他任务。失败信息:Object reference not set to an instance of an object.
日志信息： 
【目标任务】LiveFansMedal
账号 1 #########

=====开始 直播间互动 =====

---开始 发送弹幕 ---
检测到直播 Cookie 未正确配置，尝试自动配置中...
直播 Cookie 配置成功！
【获取直播列表】获取拥有粉丝牌的直播列表
【主播】在7楼 
发送弹幕失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

-------结束-------

---开始 点赞直播间 ---
【获取直播列表】获取拥有粉丝牌的直播列表
【主播】在7楼 
点赞直播间失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

--------结束--------

**Comment by Fizzyi** [comment]
同 op，已经拉到最新的版本了，在 直播粉丝牌的时候还是会报这个错误

**Comment by drowning-in-codes** [comment]
我也遇到了这个问题,可能是因为有了这个主播的粉丝牌,但直播间信息获取有问题,事实上这个账号都被封禁了. 所以只要删掉他的粉丝牌就行了.

**Comment by tjsky** [comment]
我更好奇的是，为什么在没主动关注的前提下，使用脚本的大家都会(自动?)关注这个主播？
顺带一提，取消粉丝牌是在这里【[装扮中心](https://link.bilibili.com/p/center/index#/user-center/wearing-center/my-medal)】

**Comment by Chairowell** [comment]
确实，莫名奇妙就关注了这个“[在7楼](https://space.bilibili.com/220893216)”这个UP
然后根据该UP的uid`220893216`查了下源码
似乎是由于平时执行该程序时会调用`appsettings.json`、`appsettings.Production.json`，
然后这个日常任务配置的自动充电就是这个UP，所以需要自己改一下`appsettings.Production.json`中`AutoChargeUpId`配置
注：Test任务会调用`appsettings.Development.json`，如果有需要，也得改完再执行

![image](https://github.com/RayWangQvQ/BiliBiliToolPro/assets/64683147/9bf31802-7e86-4252-8ff6-fd33f4d08efd)

![image](https://github.com/RayWangQvQ/BiliBiliToolPro/assets/64683147/972666f8-01ee-4bd0-8dd5-289e4e7a9781)

![image](https://github.com/RayWangQvQ/BiliBiliToolPro/assets/64683147/39790b6d-9b97-48b5-a7c2-d58af684eb50)

![image](https://github.com/RayWangQvQ/BiliBiliToolPro/assets/64683147/61b4a242-e90b-4958-9a40-c3b414aedb5b)

**Comment by tjsky** [comment]
>充电对象的upId，需要配合前一个DayOfAutoCharge配置项使用。-1表示不指定，默认为自己充电；其他Id则会尝试为配置的UpId充电。
>**注意：该配置的默认值是作者的upId**，如果你已认证通过了创作身份（即可以为自己充电），则建议将其改为为自己充电（配置为-1即可），也可以配置为某个自己指定的创作者upId。

其实就是因为这个[充电对象配置项](https://github.com/RayWangQvQ/BiliBiliToolPro/blob/main/docs/configuration.md#337-%E5%85%85%E7%94%B5%E5%AF%B9%E8%B1%A1)的原因：
如果你不写充电目标UPID配置，脚本会默认会把你的电池充电给作者的账号。根据脚本的设置，充电前发现你没关注作者的账号，就会自动关注作者。但是作者账号已经被B站封禁了，充值会出错，观看时也会出错。
