### ISSUE TITLE
【Bug】青龙面板订阅拉取失败

### ISSUE THREAD

**Issue by hongzhengli** [RayWangQvQ/BiliBiliToolPro#574]
版本号：：应该是2.0.1
运行环境：centos7-青龙面板v2.15.10

问题描述：青龙面板订阅拉取失败
![image](https://github.com/RayWangQvQ/BiliBiliToolPro/assets/75255267/e0cb5d86-c739-4e86-8897-c68e5020b74e)

**Comment by bigmengbig** [comment]
挂代理就行，文档里有写
