### ISSUE TITLE
【建议】当提示出现账号异常，投币失败时，建议放弃投币配置账号里的视频投币

### ISSUE THREAD

**Issue by xiaoyiying** [RayWangQvQ/BiliBiliToolPro#584]
建议内容：
当提示出现账号异常，投币失败时，建议放弃投币配置账号里的视频投币，
经过我测试这种账号除了新华社等这种官媒的视频，都会投币失败，
所以建议 出现投币账号异常时，去找新华社视频投币。如果没出现异常则不用

**Comment by xiaoyiying** [comment]
分享也是哦

**Comment by xiaoyiying** [comment]
分享也是哦

**Comment by ypw96** [comment]
现在给视频点赞投币很容易异常，异常多了就掉号，需要验证登录。听说给专栏投币没有这些问题，希望可以加个控制可以设置UID（多个），给这些用户的专栏进行投币

**Comment by ypw96** [comment]
另外投币功能是否需要优化，设置5个币时是投5个视频。大大增加了风控次数，我希望能改成满2个币时一个视频按最高2个币投。

**Comment by RayWangQvQ** [comment]
> 当提示出现账号异常，投币失败时，建议放弃投币配置账号里的视频投币

当前不是就是这样吗，先从配置地up里找，再从关注里找，最后从排行榜找
