### ISSUE TITLE
【其他】无法执行，找不到指定的命令或文件

### ISSUE THREAD

**Issue by AKAinthedirt** [RayWangQvQ/BiliBiliToolPro#586]
跟着教程安装的bilitool，登录没有遇到问题
dotnet5使用root及个人账号运行 *dotnet --info* 无异常
但是运行 *dotnet Ray.BiliBiliTool.Console.dll* 时报错：

> 无法执行，因为找不到指定的命令或文件。
可能的原因包括:
   *内置的 dotnet 命令拼写错误。
   *你打算执行 .NET 程序，但 dotnet-Ray.BiliBiliTool.Console.dll 不存在。
   *你打算运行全局工具，但在路径上找不到具有此名称且前缀为 dotnet 的可执行文件。

刚开始学习Linux，望见谅

**Comment by Polaris-cn10086** [comment]
`dotnet5`? 我记得项目用的是`dotnet6`来着

看一下执行命令的目录是不是`Ray.BiliBiliTool.Console.dll`存在的目录

可能是执行命令的路径有问题

**Comment by AKAinthedirt** [comment]
> 

谢谢，是我漏掉了进入容器的一步
