### ISSUE TITLE
【需求】兼容ipv6(ipv6环境概率出问题)

### ISSUE THREAD

**Issue by MengNianxiaoyao** [RayWangQvQ/BiliBiliToolPro#588]
我这里开启ipv6后，b站是正常访问的，但使用软件却出现了登录等各种网络问题.。之后关闭ipv6，软件一切正常，我想是不是ipv6会影响软件的正常使用。但后面又重新开启ipv6，软件又没之前的问题。
查看log，发现ipv6下，延迟很高

**Comment by RayWangQvQ** [comment]
刚好我最近也给路由开了ipv6，稍后我来测试下

**Comment by RayWangQvQ** [comment]
自测了下，开了ipv6后目前正常
