### ISSUE TITLE
【Bug】bili扫码登录 报错无法登录

### ISSUE THREAD

**Issue by klzdy123** [RayWangQvQ/BiliBiliToolPro#591]
版本号：2.0.1
运行环境：青龙面板 v2.15.20

问题描述：bili扫码登录 报错无法登录

日志信息：

./bili_task_base.sh: line 7: /root/.bashrc: No such file or directory
已安装dotnet，当前版本：6.0.121

repo目录: /ql/data/repo
bili仓库目录: 

bili_task_login.sh: line 6: cd: ./src/Ray.BiliBiliTool.Console: No such file or directory
Couldn't find a project to run. Ensure a project exists in /root, or pass the path to the project using --project.

## 执行结束... 2023-08-10 22:05:35  耗时 1 秒

**Comment by bigmengbig** [comment]
我的也是这个问题，有个base脚本，先执行下，；但是我重启后又出现这个问题了，现在还没结局

**Comment by liuyiwuqing** [comment]
同样问题，关注一下

**Comment by klzdy123** [comment]
> 我的也是这个问题，有个base脚本，先执行下，；但是我重启后又出现这个问题了，现在还没结局

先执行了 base 也还会报错

**Comment by mxlt02** [comment]
试试这个的最新回复 https://github.com/RayWangQvQ/BiliBiliToolPro/issues/538

**Comment by RayWangQvQ** [comment]
试试最新版，优化了青龙脚本
