### ISSUE TITLE
大佬能发布下release的包吗

### ISSUE THREAD

**Issue by DumKing** [RayWangQvQ/BiliBiliToolPro#6]
如题 ，感谢

**Comment by RayWangQvQ** [comment]
有了。

当前其实包没什么变化，主要加的功能是支持了下青龙面板。

**Comment by XiaoPika** [comment]
@RayWangQvQ 大佬，能同步更新一下你在dockerhub的镜像吗~~~

**Comment by RayWangQvQ** [comment]
> 

好，稍等我会改下GitHub Actions，新版本发布后，生成release压缩包的同时push镜像到daocker仓库

**Comment by RayWangQvQ** [comment]
> @RayWangQvQ 大佬，能同步更新一下你在dockerhub的镜像吗~~~

已更新，[zai7lou/bilibili_tool_pro](https://hub.docker.com/repository/docker/zai7lou/bilibili_tool_pro)
