### ISSUE TITLE
【Bug】设置充电对象为-1时应该给登录用户充电，但现在给220893216用户充电了

### ISSUE THREAD

**Issue by tencentbook** [RayWangQvQ/BiliBiliToolPro#603]
【Bug】设置充电对象为-1时应该给登录用户充电，但现在给220893216用户充电了，时间为2023.9.1 上午2点

**Comment by zzpop** [comment]
共4641人为TA充电。。

**Comment by tencentbook** [comment]
我看了一下源代码，没有发现明显问题，7月份还正常的，不知道是哪里出了故障

**Comment by Polaris-cn10086** [comment]
220893216不是作者的uid吗😂，我记得是充电的默认配置uid来着？
可能是哪里配置的有问题？
