### ISSUE TITLE
【Bug】扫码登录失败 Unable to load the service index for source https://api.nuget.org/v3/index.json. 

### ISSUE THREAD

**Issue by MicIsHere** [RayWangQvQ/BiliBiliToolPro#610]
版本号：V2.0.1
运行环境：青龙面板2.16.3-Docker

问题描述：扫码登录多次失败,重启容器无效

日志信息：
## 开始执行... 2023-09-26 23:36:33

./bili_task_base.sh: line 7: /root/.bashrc: No such file or directory
已安装dotnet，当前版本：6.0.122

repo目录: /ql/data/repo
bili仓库目录: /ql/data/repo/RayWangQvQ_BiliBiliToolPro

/usr/lib/dotnet/sdk/6.0.122/NuGet.targets(130,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [/ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/Ray.BiliBiliTool.Console.csproj]
/usr/lib/dotnet/sdk/6.0.122/NuGet.targets(130,5): error :   Resource temporarily unavailable (api.nuget.org:443) [/ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/Ray.BiliBiliTool.Console.csproj]
/usr/lib/dotnet/sdk/6.0.122/NuGet.targets(130,5): error :   Resource temporarily unavailable [/ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/Ray.BiliBiliTool.Console.csproj]

The build failed. Fix the build errors and run again.

**Comment by SRwenzi** [comment]
同问

**Comment by MicIsHere** [comment]
使用梯子解决

**Comment by RayWangQvQ** [comment]
可能是nuget的网络抽风了吧，正常不用梯子也是ok的
