### ISSUE TITLE
【建议】可以新增选择是否投币的功能吗

### ISSUE THREAD

**Issue by CheemsaDoge** [RayWangQvQ/BiliBiliToolPro#620]
建议内容：
 新增选择是否投币的功能
 不是很想自动投币

**Comment by Polaris-cn10086** [comment]
当参数`NumberOfCoins`设置为0时不投币[文档](https://github.com/RayWangQvQ/BiliBiliToolPro/blob/main/docs/configuration.md#333-%E6%AF%8F%E6%97%A5%E6%8A%95%E5%B8%81%E6%95%B0%E9%87%8F)

具体配置方法查阅程序文档。

**Comment by Asakushen** [comment]
> 当参数`NumberOfCoins`设置为0时不投币[文档](https://github.com/RayWangQvQ/BiliBiliToolPro/blob/main/docs/configuration.md#333-%E6%AF%8F%E6%97%A5%E6%8A%95%E5%B8%81%E6%95%B0%E9%87%8F)
> 
> 具体配置方法查阅程序文档。

青龙部署呢？手动设置环境变量NumberOfCoins吗？

**Comment by Polaris-cn10086** [comment]
> > 当参数`NumberOfCoins`设置为0时不投币[文档](https://github.com/RayWangQvQ/BiliBiliToolPro/blob/main/docs/configuration.md#333-%E6%AF%8F%E6%97%A5%E6%8A%95%E5%B8%81%E6%95%B0%E9%87%8F)
> > 具体配置方法查阅程序文档。
> 
> 青龙部署呢？手动设置环境变量NumberOfCoins吗？

是设置环境变量，具体的话查阅一下文档

**Comment by rainsum2022** [comment]
> 当参数`NumberOfCoins`设置为0时不投币[文档](https://github.com/RayWangQvQ/BiliBiliToolPro/blob/main/docs/configuration.md#333-%E6%AF%8F%E6%97%A5%E6%8A%95%E5%B8%81%E6%95%B0%E9%87%8F)
> 
> 具体配置方法查阅程序文档。

可通过设置环境变量Ray_DailyTaskConfig__NumberOfCoins=0来禁用投币，这个选项是争对所有账号禁用的吗？能否只禁用某一个账号的投币？

**Comment by Polaris-cn10086** [comment]
> > 当参数`NumberOfCoins`设置为0时不投币[文档](https://github.com/RayWangQvQ/BiliBiliToolPro/blob/main/docs/configuration.md#333-%E6%AF%8F%E6%97%A5%E6%8A%95%E5%B8%81%E6%95%B0%E9%87%8F)
> > 
> > 具体配置方法查阅程序文档。
> 
> 可通过设置环境变量Ray_DailyTaskConfig__NumberOfCoins=0来禁用投币，这个选项是争对所有账号禁用的吗？能否只禁用某一个账号的投币？

目前应该是对所有账户成立的。单独禁用的话可以试着开另一个程序来跑
