### ISSUE TITLE
如何针对每个定制任务进行选择性消息推送

### ISSUE THREAD

**Issue by zouxiaochun2023** [RayWangQvQ/BiliBiliToolPro#623]
使用了钉钉机器人，在青龙面板订阅管理拉任务库时，机器人会通知哪些任务新增成功。
但是在定时任务具体执行时，执行完后，如何进行消息推送，任务库一共有9个任务，没有一个任务执行后进行消息推送。
应该如何设置，才能让任务执行后，消息推送，如果想部分任务消息推送，部分任务不推送该如何设置？
提前感谢各位！🙏

**Comment by RayWangQvQ** [comment]
> 应该如何设置，才能让任务执行后，消息推送

可以参考文档配置

> 部分任务不推送该如何设置？

正在开发中
