### ISSUE TITLE
使用vs直接运行提示没有账户信息

### ISSUE THREAD

**Issue by netXiaoYang** [RayWangQvQ/BiliBiliToolPro#626]
版本号：最新代码
运行环境：本地，windows系统

问题描述：clone代码后，本地使用vs直接运行提示没有账户信息

目的：请问在哪里设置账户信息或者怎么设置扫码登录？

**Comment by Polaris-cn10086** [comment]
没有设置`RunTasks`的话，运行时会提示选择执行的任务，选择`Login`就能登录了

注意项目内的`cookies.json`与编译目录内的`cookies.json`的内容问题，可能会出现登录后没有账户信息，此时可能需要手动更新一下文件。
