### ISSUE TITLE
请教：关于调用二维码是否被扫描接口第一次就报二维码已失效

### ISSUE THREAD

**Issue by zouxiaochun2023** [RayWangQvQ/BiliBiliToolPro#627]
我用java尝试写登录逻辑，在调用/x/passport-login/web/qrcode/poll这个接口时，直接就报二维码已失效状态（86038），请求参数带有qrcode_key=xxx和source=main_mini，是哪里没有问题吗，

**Comment by Polaris-cn10086** [comment]
这个问题到[SocialSisterYi/bilibili-API-collect](https://github.com/SocialSisterYi/bilibili-API-collect)这个里面问更合适吧🤔

还有，`source=main_mini`是用来干啥的，我在api文档里好像没看到过

**Comment by zouxiaochun2023** [comment]
source=main_mini这个应该是指来源，我在笔记本上是main_web

**Comment by zouxiaochun2023** [comment]
@Polaris-cn10086 原来还有这个宝藏地址啊，感谢！
