### ISSUE TITLE
一直下载dotnet报错，我已经手动装了dotnet7.0.404版本，还是报错。

### ISSUE THREAD

**Issue by Ye-Guxuan** [RayWangQvQ/BiliBiliToolPro#630]
版本号：最新版脚本（不是先行版）
运行环境：系统contos7，docker中装青龙2.11.3版本

问题描述：一直下载dotnet报错，我已经手动装了dotnet7.0.404版本，还是报错。

日志信息：## 开始执行... 2023-11-17 18:16:06

bili_task_base.sh: line 10: dotnet: command not found
which dotnet: 
开始安装dotnet
------尝试使用apk安装------
ERROR: unable to select packages:
  aiohttp (no such package):
    required by: world[aiohttp]
  bizCode (no such package):
    required by: world[bizCode]
  bizMsg (no such package):
    required by: world[bizMsg]
  dotnet6-sdk (no such package):
    required by: world[dotnet6-sdk]
  lxm (no such package):
    required by: world[lxm]
  magic (no such package):
    required by: world[magic]
  python-devel (no such package):
    required by: world[python-devel]
bili_task_base.sh: line 20: dotnet: command not found
------再尝试使用官方脚本安装------
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to ghproxy.com:443 
bili_task_base.sh: line 25: dotnet: command not found
------再尝试使用二进制包安装------
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to ghproxy.com:443 
bili_task_base.sh: line 30: dotnet: command not found
安装失败，没办法了，毁灭吧，自己解决吧：https://learn.microsoft.com/zh-cn/dotnet/core/install/linux-alpine

**Comment by oldxianyu** [comment]
重新装个其他来源的青龙

**Comment by cyikns** [comment]
用docker进入容器，修改 Alpine 的镜像 repo（repositories）源为国内源：
# 清华源
sed -i 's/dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn/g' /etc/apk/repositories 
# 阿里源
sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories
# 中科大源
sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories

**Comment by RayWangQvQ** [comment]
感谢反馈，先汇总到 #691 ，稍后统一解决
