### ISSUE TITLE
能否支持大会员经验领取每天少十经验

### ISSUE THREAD

**Issue by q1351022** [RayWangQvQ/BiliBiliToolPro#631]
![Cache_65bbd70d3908ed67](https://github.com/RayWangQvQ/BiliBiliToolPro/assets/111921870/80f1f35c-ef43-462e-ab23-5d7a9c9df680)
![Screenshot_2023-11-18-00-15-49-909_com lemurbrowser exts](https://github.com/RayWangQvQ/BiliBiliToolPro/assets/111921870/997fb597-2754-4401-bc6f-0c2ae71b1e1b)

**Comment by Polaris-cn10086** [comment]
#615 中已提及

**Comment by RayWangQvQ** [comment]
感谢补充截图，后续可以到 #615 跟踪最新信息
