### ISSUE TITLE
文档错误【Bug】请在标题中清晰地概述你要反馈的异常或缺陷

### ISSUE THREAD

**Issue by joshefi** [RayWangQvQ/BiliBiliToolPro#632]
问题描述：readme 中 [3. 方式二：手动Docker Compose](https://github.com/RayWangQvQ/BiliBiliToolPro/blob/main/docker/README.md#3-%E6%96%B9%E5%BC%8F%E4%BA%8C%E6%89%8B%E5%8A%A8docker-compose)  的#启动为  docker-compose up -d而非docker compose up -d

**Comment by catlair** [comment]
这不是 bug，这是特性，docker-compose 已经是过去式（甚至以前文档也是这么写的）。

这里推荐 使用 docker-compose v2 版本也就是 `docker compose`

![image](https://github.com/RayWangQvQ/BiliBiliToolPro/assets/44313800/f40d677b-0a74-4a0c-8a7b-3239336fc618)

**Comment by catlair** [comment]
查看此处修改 

https://github.com/RayWangQvQ/BiliBiliToolPro/commit/a5b9e0bd1897864a80847bdf5d4748a458bebec4#diff-da8fcbe728a9172b578e5d754f8e2df214c658c4321f610e63dd68bea828ab49R48

以及此处评论

https://github.com/RayWangQvQ/BiliBiliToolPro/commit/7741e4db023ad10906c9a50a1224d43dabd5dd55#commitcomment-73151303

**Comment by joshefi** [comment]
抱歉，由于较长时间未使用并未知道已更新至v2，我还在思考为什么会出现这样的问题，感谢告知并学到新的知识。
