### ISSUE TITLE
【Bug】develop最先版投币出现权限不足的问题

### ISSUE THREAD

**Issue by nizhenyu2022** [RayWangQvQ/BiliBiliToolPro#643]
版本号： https://github.com/Polaris-cn10086/BiliBiliToolPro/commit/0ddb6e1d0e0e0e1ad665bfd340ed42c4cb2ddb03
运行环境： linux

问题描述： 这个版本，可以视频投币了，但是专栏投币，还是有BUG，提示[ERR] 投币失败，继续其他任务。失败信息:请求错误，
我下面贴上日志，另外5级升级到6级的经验计算升级时间，有错误。没有按照一天65的经验去计算。

[ELAPSED] 00:00:03.2469779
2023-12-25 00:05:49.541 +08:00 [INF] 【投币前余额】 : 1180
2023-12-25 00:05:49.542 +08:00 [DBG] 开始尝试第0次
2023-12-25 00:05:53.683 +08:00 [DBG] [REQUEST]
GET /x/web-interface/nav HTTP/1.1
Referer: https://www.bilibili.com/
Origin: https://www.bilibili.com
Host: api.bilibili.com
Accept: application/json, text/plain, */*, application/json; q=0.001, application/xml; q=0.001
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
Connection: keep-alive

[RESPONSE]
HTTP/1.1 200 OK
Date: Sun, 24 Dec 2023 16:05:53 GMT
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET,POST,PUT,DELETE
Access-Control-Allow-Origin: https://www.bilibili.com
Bili-Status-Code: 0
Bili-Trace-Id: 192b93fd4e658856
Vary: Origin
X-Bili-Trace-Id: 517cfb358ae45482192b93fd4e658856
X-Ticket-Status: 1
Access-Control-Allow-Headers: Origin,No-Cache,X-Requested-With,If-Modified-Since,Pragma,Last-Modified,Cache-Control,Expires,Content-Type,Access-Control-Allow-Credentials,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Cache-Webcdn,x-bilibili-key-real-ip,x-backend-bili-real-ip,x-risk-header
Cross-Origin-Resource-Policy: cross-origin
Access-Control-Expose-Headers: X-Bili-Gaia-Vvoucher,X-Bili-Trace-Id, X-Cache-Webcdn
Cache-Control: no-cache
X-Cache-Webcdn: BYPASS from blzone01
Content-Type: application/json; charset=utf-8
Expires: Sun, 24 Dec 2023 16:05:52 GMT
Content-Length: 2119

{"code":0,"message":"0","ttl":1,"data":{"isLogin":true,"email_verified":0,"face":"https://i1.hdslb.com/bfs/face/1bcd47932ec96e674e690e7bf6d1d9021ecf16a4.jpg","face_nft":0,"face_nft_type":0,"level_info":{"current_level":4,"current_min":4500,"current_exp":8065,"next_exp":10800},"mid":142372318,"mobile_verified":1,"money":1180,"moral":70,"official":{"role":0,"title":"","desc":"","type":-1},"officialVerify":{"type":-1,"desc":""},"pendant":{"pid":0,"name":"","image":"","expire":0,"image_enhance":"","image_enhance_frame":"","n_pid":0},"scores":0,"uname":"5548DD6","vipDueDate":0,"vipStatus":0,"vipType":0,"vip_pay_type":0,"vip_theme_type":0,"vip_label":{"path":"","text":"","label_theme":"","text_color":"","bg_style":0,"bg_color":"","border_color":"","use_img_label":true,"img_label_uri_hans":"","img_label_uri_hant":"","img_label_uri_hans_static":"https://i0.hdslb.com/bfs/vip/d7b702ef65a976b20ed854cbd04cb9e27341bb79.png","img_label_uri_hant_static":"https://i0.hdslb.com/bfs/activity-plat/static/20220614/e369244d0b14644f5e1a06431e22a4d5/KJunwh19T5.png"},"vip_avatar_subscript":0,"vip_nickname_color":"","vip":{"type":0,"status":0,"due_date":0,"vip_pay_type":0,"theme_type":0,"label":{"path":"","text":"","label_theme":"","text_color":"","bg_style":0,"bg_color":"","border_color":"","use_img_label":true,"img_label_uri_hans":"","img_label_uri_hant":"","img_label_uri_hans_static":"https://i0.hdslb.com/bfs/vip/d7b702ef65a976b20ed854cbd04cb9e27341bb79.png","img_label_uri_hant_static":"https://i0.hdslb.com/bfs/activity-plat/static/20220614/e369244d0b14644f5e1a06431e22a4d5/KJunwh19T5.png"},"avatar_subscript":0,"nickname_color":"","role":0,"avatar_subscript_url":"","tv_vip_status":0,"tv_vip_pay_type":0,"tv_due_date":0,"avatar_icon":{"icon_resource":{}},"wallet":{"mid":142372318,"bcoin_balance":0,"coupon_balance":0,"coupon_due_time":0},"has_shop":false,"shop_url":"","allowance_count":0,"answer_status":0,"is_senior_member":0,"wbi_img":{"img_url":"https://i0.hdslb.com/bfs/wbi/7cd084941338484aae1ad9425b84077c.png","sub_url":"https://i0.hdslb.com/bfs/wbi/4932caff0ff746eab6f01bf08b70ac45.png"},"is_jury":false}

[ELAPSED] 00:00:04.1328023
2023-12-25 00:05:53.683 +08:00 [DBG] 【img_url】https://i0.hdslb.com/bfs/wbi/7cd084941338484aae1ad9425b84077c.png
2023-12-25 00:05:53.683 +08:00 [DBG] 【sub_url】https://i0.hdslb.com/bfs/wbi/4932caff0ff746eab6f01bf08b70ac45.png
2023-12-25 00:05:56.797 +08:00 [DBG] [REQUEST]
GET /x/space/wbi/article?w_rid=635a9f3bf5c34185c2c8700724a3281b&wts=1703433953&mid=0&pn=1&ps=12&sort=publish_time&web_location=1550101&platform=web HTTP/1.1
Referer: https://www.bilibili.com/
Origin: https://space.bilibili.com
Host: api.bilibili.com
Accept: application/json, text/plain, */*, application/json; q=0.001, application/xml; q=0.001
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-site
Connection: keep-alive

[RESPONSE]
HTTP/1.1 200 OK
Date: Sun, 24 Dec 2023 16:05:56 GMT
Connection: keep-alive
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET,POST,PUT,DELETE
Access-Control-Allow-Origin: https://space.bilibili.com
Access-Control-Expose-Headers: X-Bili-Gaia-Vvoucher,X-Bili-Trace-Id
Bili-Status-Code: -400
Bili-Trace-Id: 0c5a6e328b658856
Vary: Origin
X-Bili-Trace-Id: 2a78eaa58a08b0190c5a6e328b658856
X-Client-Sign: 635a9f3bf5c34185c2c8700724a3281b
X-Rid-Result: 0
X-Ticket-Status: 1
Access-Control-Allow-Headers: Origin,No-Cache,X-Requested-With,If-Modified-Since,Pragma,Last-Modified,Cache-Control,Expires,Content-Type,Access-Control-Allow-Credentials,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Cache-Webcdn,x-bilibili-key-real-ip,x-backend-bili-real-ip,x-risk-header
Cross-Origin-Resource-Policy: cross-origin
Cache-Control: no-cache
X-Cache-Webcdn: BYPASS from blzone04
Content-Type: application/json; charset=utf-8
Content-Length: 46
Expires: Sun, 24 Dec 2023 16:05:55 GMT

{"code":-400,"message":"请求错误","ttl":1}
[ELAPSED] 00:00:03.1083485
2023-12-25 00:05:56.801 +08:00 [ERR] 投币失败，继续其他任务。失败信息:请求错误

2023-12-25 00:05:56.804 +08:00 [INF] -----结束-----

**Comment by Polaris-cn10086** [comment]
以下是我自己测试的结果：
大号：
![dc3e5b69a231ddc9d0a97a9377b20610](https://github.com/RayWangQvQ/BiliBiliToolPro/assets/63545780/dbd9f815-7275-4f18-9538-070aa0c25533)
最近注册的小号：
![image](https://github.com/RayWangQvQ/BiliBiliToolPro/assets/63545780/573d25d7-8bc1-4aa3-bb3e-f1f852ca10c4)

两个号的专栏投币都是正常的，没有能复现情况

**Comment by Polaris-cn10086** [comment]
我觉得问题在于`w_rid=635a9f3bf5c34185c2c8700724a3281b&wts=1703433953&mid=0&pn=1&ps=12&sort=publish_time&web_location=1550101&platform=web HTTP/1.1`中`mid`的值为0，生产环境使用请配置`appsettings.Production.json`中的`SupportUpIds`，debug环境中请配置`appsettings.Development.json`中的`SupportUpIds`。

虽然我并不能理解为什么`mid`的值会变成0：
![image](https://github.com/RayWangQvQ/BiliBiliToolPro/assets/63545780/ee3d45ff-e5bb-4d0e-bd5e-7b539206908c)

**Comment by nizhenyu2022** [comment]
> 我觉得问题在于`w_rid=635a9f3bf5c34185c2c8700724a3281b&wts=1703433953&mid=0&pn=1&ps=12&sort=publish_time&web_location=1550101&platform=web HTTP/1.1`中`mid`的值为0，生产环境使用请配置`appsettings.Production.json`中的`SupportUpIds`，debug环境中请配置`appsettings.Development.json`中的`SupportUpIds`。
> 
> 虽然我并不能理解为什么`mid`的值会变成0： ![image](https://private-user-images.githubusercontent.com/63545780/292700667-ee3d45ff-e5bb-4d0e-bd5e-7b539206908c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1MDM0OTQsIm5iZiI6MTcwMzUwMzE5NCwicGF0aCI6Ii82MzU0NTc4MC8yOTI3MDA2NjctZWUzZDQ1ZmYtZTViYi00ZDBlLWJkNWUtN2I1MzkyMDY5MDhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI1VDExMTk1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0OTJiOGY2ZjQ5MjVlM2Q4YWQ4ZTkxNWU3ZDkzZDZlZWQ4ZjdlNDRhYmZlMmEwYzNiMTZlNmQ4YmQ0MGRkNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LGzyEcu18sih7YdU8UWZ9QuVxj2X5uJdJhrDAkN6p-4)

我编译好后，使用的是appsettings.json，待我切换成appsettings.Development.json试试看。

**Comment by nizhenyu2022** [comment]
大佬，已经测了配置appsettings.Production.json就没有mid为0的问题了，那个5级升级6级的天数不准，看了吗

**Comment by Polaris-cn10086** [comment]
> 大佬，已经测了配置appsettings.Production.json就没有mid为0的问题了，那个5级升级6级的天数不准，看了吗

升级时间计算是老问题了，一直没有什么好的改进方案

**Comment by nizhenyu2022** [comment]
> > 大佬，已经测了配置appsettings.Production.json就没有mid为0的问题了，那个5级升级6级的天数不准，看了吗
> 
> 升级时间计算是老问题了，一直没有什么好的改进方案

5级到6级需要18800经验，18800除以65呀

**Comment by Polaris-cn10086** [comment]
> > > 大佬，已经测了配置appsettings.Production.json就没有mid为0的问题了，那个5级升级6级的天数不准，看了吗
> > 
> > 升级时间计算是老问题了，一直没有什么好的改进方案
> 
> 5级到6级需要18800经验，18800除以65呀 

这样算的话没有考虑硬币不足以支持每天投五枚的情况 #621

**Comment by nizhenyu2022** [comment]
> > > > 大佬，已经测了配置appsettings.Production.json就没有mid为0的问题了，那个5级升级6级的天数不准，看了吗
> > > 
> > > 
> > > 升级时间计算是老问题了，一直没有什么好的改进方案
> > 
> > 
> > 5级到6级需要18800经验，18800除以65呀
> 
> 这样算的话没有考虑硬币不足以支持每天投五枚的情况 #621

这种情况肯定是不用考虑的，像分享的5经验，有时候还会分享异常呢。而且一般养号的都是批量买硬币去投的，每天都是能投满的。

**Comment by RayWangQvQ** [comment]
投币问题已解决
