### ISSUE TITLE
【Bug】直播粉丝牌任务异常

### ISSUE THREAD

**Issue by ji-nian** [RayWangQvQ/BiliBiliToolPro#644]
版本号：V2.0.2
运行环境：青龙2.11.3

问题描述：12月24日开始，在任务执行时前几个直播间可以正常显示，然后就报错了

日志信息：

>[21:29:00 INF] BiliBiliToolPro 开始运行...
>
>[21:29:01 INF] 【账号个数】1个
>
>[21:29:01 INF] 【目标任务】LiveFansMedal  
>[21:29:01 INF] ######### 账号 1 #########  
>
>[21:29:01 INF] =====开始 直播间互动 =====  
>
>[21:29:01 INF] ---开始 发送弹幕 ---
>[21:29:01 INF] 检测到直播 Cookie 未正确配置，尝试自动配置中...
>[21:29:08 INF] 直播 Cookie 配置成功！
>[21:29:08 INF] 【获取直播列表】获取拥有粉丝牌的直播列表
>[21:29:13 INF] 【主播】***
>[21:29:47 INF] 【主播】***
>[21:30:07 INF] 【主播】***
>[21:30:37 ERR] [REQUEST]
>GET /room/v1/Room/get_info?room_id=9752040&from=room HTTP/1.1
>Host: api.live.bilibili.com
>Accept: application/json, text/plain, */*, application/json; q=0.001, application/xml; q=0.001
>Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
>Sec-Fetch-Dest: empty
>Sec-Fetch-Mode: cors
>Sec-Fetch-Site: same-site
>Connection: keep-alive
>
>[EXCEPTION]
>System.Net.Http.HttpRequestException: Resource temporarily unavailable (api.live.bilibili.com:443)
> ---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
>   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
>   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
>   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
>   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
>   --- End of inner exception stack trace ---
>   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
>   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
>   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
>   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
>   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>   at Microsoft.Extensions.Http.PolicyHttpMessageHandler.SendCoreAsync(HttpRequestMessage request, Context context, CancellationToken cancellationToken)
>   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
>   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
>   at Microsoft.Extensions.Http.PolicyHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>   at Ray.BiliBiliTool.Agent.HttpClientDelegatingHandlers.IntervalDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /ql/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Agent/HttpClientDelegatingHandlers/IntervalDelegatingHandler.cs:line 32
>   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
>   at WebApiClientCore.Implementations.ApiRequestSender.SendCoreAsync(ApiRequestContext context)
>   at WebApiClientCore.Implementations.ApiRequestSender.SendAsync(ApiRequestContext context)
>
>[ELAPSED] 00:00:17.0166389
>[21:30:37 ERR] 发送弹幕失败，继续其他任务。失败信息:Resource temporarily unavailable (api.live.bilibili.com:443)
>
>[21:30:37 INF] -------结束-------
>
>[21:30:37 INF] ---开始 点赞直播间 ---
>[21:30:37 INF] 【获取直播列表】获取拥有粉丝牌的直播列表
>[21:30:43 INF] 【主播】***
>[21:31:17 INF] 【主播】***
>[21:31:41 INF] 【主播】*** 
>[21:31:58 INF] 【主播】***
>[21:32:23 INF] 【主播】***
>[21:32:49 INF] 【主播】***
>
>## 执行结束...  2023/12/24 21:33:04 
>[21:33:09 INF] 【主播】***
>[21:33:31 INF] 【主播】***
>[21:33:54 INF] 【主播】***
>[21:34:26 INF] 【主播】***
>[21:34:33 ERR] 点赞直播间失败，继续其他任务。失败信息:Value does not fall within the expected range.
>
>Unhandled exception. 

亦或者是以下错误：

>[16:20:22 INF] BiliBiliToolPro 开始运行...
>
>[16:20:23 INF] 【账号个数】1个
>
>[16:20:23 INF] 【目标任务】LiveFansMedal
>[16:20:23 INF] ######### 账号 1 #########
>
>[16:20:23 INF] =====开始 直播间互动 =====
>
>[16:20:23 INF] ---开始 发送弹幕 ---
>[16:20:23 INF] 检测到直播 Cookie 未正确配置，尝试自动配置中...
>[16:20:42 INF] 直播 Cookie 配置成功！
>[16:20:42 INF] 【获取直播列表】获取拥有粉丝牌的直播列表
>[16:20:46 INF] 【主播】***
>[16:21:17 ERR] [REQUEST]
>GET /x/space/wbi/acc/info?w_rid=e8c09f99f94bc8d9ee4ab271d8496e33&wts=1703578859&mid=125526 HTTP/1.1
>Referer: https://www.bilibili.com/
>Origin: https://www.bilibili.com
>Host: api.bilibili.com
>Accept: application/json, text/plain, */*, application/json; q=0.001, application/xml; q=0.001
>Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
>Sec-Fetch-Dest: empty
>Sec-Fetch-Mode: cors
>Sec-Fetch-Site: same-site
>Connection: keep-alive
>
>[EXCEPTION]
>System.Net.Http.HttpRequestException: Resource temporarily unavailable (api.bilibili.com:443)
> ---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
>   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
>   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
>   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
>   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
>   --- End of inner exception stack trace ---
>   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
>   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
>   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
>   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
>   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>   at Microsoft.Extensions.Http.PolicyHttpMessageHandler.SendCoreAsync(HttpRequestMessage request, Context context, CancellationToken cancellationToken)
>   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
>   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
>   at Microsoft.Extensions.Http.PolicyHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>   at Ray.BiliBiliTool.Agent.HttpClientDelegatingHandlers.IntervalDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /ql/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Agent/HttpClientDelegatingHandlers/IntervalDelegatingHandler.cs:line 32
>   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
>   at WebApiClientCore.Implementations.ApiRequestSender.SendCoreAsync(ApiRequestContext context)
>   at WebApiClientCore.Implementations.ApiRequestSender.SendAsync(ApiRequestContext context)
>
>[ELAPSED] 00:00:17.0208471
>[16:21:17 ERR] 发送弹幕失败，继续其他任务。失败信息:Resource temporarily unavailable (api.bilibili.com:443)
>
>[16:21:17 INF] -------结束-------
>
>[16:21:17 INF] ---开始 点赞直播间 ---
>[16:21:17 INF] 【获取直播列表】获取拥有粉丝牌的直播列表
>[16:21:26 INF] 【主播】***
>[16:21:50 INF] 【主播】***
>[16:22:09 INF] 【主播】***
>[16:22:42 ERR] [REQUEST]
>GET /room/v1/Room/get_info?room_id=9752040&from=room HTTP/1.1
>Host: api.live.bilibili.com
>Accept: application/json, text/plain, */*, application/json; q=0.001, application/xml; q=0.001
>Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
>Sec-Fetch-Dest: empty
>Sec-Fetch-Mode: cors
>Sec-Fetch-Site: same-site
>Connection: keep-alive
>
>[EXCEPTION]
>System.Net.Http.HttpRequestException: Resource temporarily unavailable (api.live.bilibili.com:443)
> ---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
>   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
>   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
>   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
>   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
>   --- End of inner exception stack trace ---
>   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
>   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
>   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
>   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
>   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>   at Microsoft.Extensions.Http.PolicyHttpMessageHandler.SendCoreAsync(HttpRequestMessage request, Context context, CancellationToken cancellationToken)
>   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
>   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
>   at Microsoft.Extensions.Http.PolicyHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>   at Ray.BiliBiliTool.Agent.HttpClientDelegatingHandlers.IntervalDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /ql/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Agent/HttpClientDelegatingHandlers/IntervalDelegatingHandler.cs:line 32
>   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
>   at WebApiClientCore.Implementations.ApiRequestSender.SendCoreAsync(ApiRequestContext context)
>   at WebApiClientCore.Implementations.ApiRequestSender.SendAsync(ApiRequestContext context)
>
>[ELAPSED] 00:00:16.0149619
>[16:22:42 ERR] 点赞直播间失败，继续其他任务。失败信息:Resource temporarily unavailable (api.live.bilibili.com:443)
>
>[16:22:42 INF] --------结束--------
>
>[16:22:42 INF] ---开始 直播时长挂机 ---
>[16:22:42 INF] 【获取直播列表】获取拥有粉丝牌的直播列表
>[16:22:49 INF] 【主播】***
>[16:23:38 INF] 【主播】***
>[16:24:04 INF] 【主播】***
>[16:24:28 INF] 【主播】***
>[16:25:00 INF] 【主播】***
>[16:25:17 ERR] [REQUEST]
>GET /x/web-interface/nav HTTP/1.1
>Referer: https://www.bilibili.com/
>Origin: https://www.bilibili.com
>Host: api.bilibili.com
>Accept: application/json, text/plain, */*, application/json; q=0.001, application/xml; q=0.001
>Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
>Sec-Fetch-Dest: empty
>Sec-Fetch-Mode: cors
>Sec-Fetch-Site: same-site
>Connection: keep-alive
>
>[EXCEPTION]
>System.Net.Http.HttpRequestException: Resource temporarily unavailable (api.bilibili.com:443)
> ---> System.Net.Sockets.SocketException (11): Resource temporarily unavailable
>   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
>   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
>   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
>   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
>   --- End of inner exception stack trace ---
>   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
>   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
>   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
>   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
>   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
>   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>   at Microsoft.Extensions.Http.PolicyHttpMessageHandler.SendCoreAsync(HttpRequestMessage request, Context context, CancellationToken cancellationToken)
>   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
>   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
>   at Microsoft.Extensions.Http.PolicyHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>   at Ray.BiliBiliTool.Agent.HttpClientDelegatingHandlers.IntervalDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /ql/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Agent/HttpClientDelegatingHandlers/IntervalDelegatingHandler.cs:line 32
>   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
>   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
>   at WebApiClientCore.Implementations.ApiRequestSender.SendCoreAsync(ApiRequestContext context)
>   at WebApiClientCore.Implementations.ApiRequestSender.SendAsync(ApiRequestContext context)
>
>[ELAPSED] 00:00:17.0178945
>[16:25:17 ERR] 直播时长挂机失败，继续其他任务。失败信息:Resource temporarily unavailable (api.bilibili.com:443)
>
>[16:25:17 INF] ---------结束---------
>
>[16:25:17 INF] ==========结束==========
>
>[16:25:17 INF] 
>
>========================
>
> v2.0.2 开源 by https://github.com/RayWangQvQ/BiliBiliToolPro
>
>[16:25:17 INF] ·开始推送·LiveFansMedal任务·
>[16:25:17 INF] 运行环境：Development
>[16:25:17 INF] 应用目录：/ql/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/bin/Debug/net6.0/
>
>[16:25:17 INF] 运行结束
>
>## 执行结束... 2023-12-26 16:25:17 耗时 313 秒

**Comment by Polaris-cn10086** [comment]
看着像网络问题？

**Comment by ji-nian** [comment]
好像确实是网络问题，放服务器上试了试发现没什么问题。。 不知道能不能加个异常重试的功能

**Comment by Polaris-cn10086** [comment]
我找到了相关文档 https://webapiclient.github.io/guide/retry.html ，但是毕竟调用的是B站的Api，我觉得如果有异常还是及时抛出了比较好，也许能减少被风控的风险？🤔
