### ISSUE TITLE
 line 6: cd: ./src/Ray.BiliBiliTool.Console: No such file or directory

### ISSUE THREAD

**Issue by mzh906687926** [RayWangQvQ/BiliBiliToolPro#646]
bili_task_login.sh: line 6: cd: ./src/Ray.BiliBiliTool.Console: No such file or directory
Couldn't find a project to run. Ensure a project exists in /root, or pass the path to the project using --project.
这个报错是突然有的````之前没有过的啊``重装了青龙按照之前的方法都跑不起来了``其他脚本可以跑得起来

**Comment by aqiu9** [comment]
请问解决了吗

**Comment by jhs1873** [comment]
ql/data/repo 去终端看下下面的目录

**Comment by Testplayers** [comment]
> ![image](https://private-user-images.githubusercontent.com/11732611/324789449-22d188e1-1abb-4aa4-9a8f-c566b7156250.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NDUwNTIsIm5iZiI6MTcxMzk0NDc1MiwicGF0aCI6Ii8xMTczMjYxMS8zMjQ3ODk0NDktMjJkMTg4ZTEtMWFiYi00YWE0LTlhOGYtYzU2NmI3MTU2MjUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDA3NDU1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzZTg4OWQ0MjZlODY4MDE4OGY2N2VlMDNjNzM0ZjljNTEwMzBmNWUwMTdmMDZlNTNlNDQzOGM0N2FkNTZhOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.36lG1deXGrPdDm9s6VSuf5jodZoH1_Vzc3VMNJgN84g) ![image](https://private-user-images.githubusercontent.com/11732611/324789703-b96ac4e0-e9dc-4718-b524-97181cd3ede7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5NDUwNTIsIm5iZiI6MTcxMzk0NDc1MiwicGF0aCI6Ii8xMTczMjYxMS8zMjQ3ODk3MDMtYjk2YWM0ZTAtZTlkYy00NzE4LWI1MjQtOTcxODFjZDNlZGU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDA3NDU1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkMDc1ZjllOWI2NDdmOTZiNjE3YjgxNWM3NzE1MzQ5MmJiM2U4NjA1NjBmYTc2MTBkZjU2MjEyZDY3MTUxNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3Zo2eMVdtJ5b9qT_tJ0SGnOS21MUUtRsHkXefFgwBAg) 脚本管理里面bili_task_base.sh修改对应的目录

对应目录是指啥

**Comment by jhs1873** [comment]
@Testplayers  RayWangQvQ_BiliBiliToolPro_main

**Comment by Testplayers** [comment]
> @Testplayers RayWangQvQ_BiliBiliToolPro_main 这是我的目录名.你的目录名得自己看下

但是目录没问题

**Comment by RayWangQvQ** [comment]
不符合issue模板
