### ISSUE TITLE
【建议】tg推送允许使用第三方代理api

### ISSUE THREAD

**Issue by Rovniced** [RayWangQvQ/BiliBiliToolPro#65]
建议内容：
可以在配置文件里面添加一个新的配置项，让用户可以自己填第三方tg代理api 这样方便使用腾讯云或其他条件下的推送

**Comment by Remonli** [comment]
appsetting 里面的webproxy 是不是在本机有端口可以访问到tg的时候推送 ？

**Comment by RayWangQvQ** [comment]
dev先行版已完成，稍后会更新文档并发布到下个release版本

![image](https://user-images.githubusercontent.com/31154238/186251474-77e59b1b-f336-4873-be07-894b6120b8ef.png)

![image](https://user-images.githubusercontent.com/31154238/186252218-285e6155-9899-4ff8-9ab4-47cdc9b390b1.png)
