### ISSUE TITLE
【Bug】win7 双账号运行LiveFansMedal任务 报错

### ISSUE THREAD

**Issue by Amonologue-z** [RayWangQvQ/BiliBiliToolPro#656]
版本号：v2.0.1 v2.0.2 都试过不行
运行环境：windows7

问题描述：win7 双账号运行LiveFansMedal任务 报错,  第一个账号正常运行，但是zhix执行第二个账号任务就报错了

日志信息：（如果可以，请贴出Debug级别的日志信息，以便更高效的确定和解决问题。）
![](https://pic.imgdb.cn/item/65adea46871b83018a06e208.jpg)

[log20240122.txt](https://github.com/RayWangQvQ/BiliBiliToolPro/files/14004597/log20240122.txt)

**Comment by Polaris-cn10086** [comment]
日志看上去是第二个账号cookie没设置好，试着重新登陆一下？
