### ISSUE TITLE
【Bug】Docker青龙qinglong（debian）安装依赖失败

### ISSUE THREAD

**Issue by Akimio521** [RayWangQvQ/BiliBiliToolPro#661]
版本号：[5cd2aa1](https://github.com/RayWangQvQ/BiliBiliToolPro/commit/5cd2aa1de0230efb31717ee314dbb2c79e73501f)
运行环境：Docker：qinglong:debian

问题描述：apk add dotnet6-sdk安装依赖失败

原因：qinglong:latest是基于apline构建，但是有些依赖apline会导致安装失败，因此我使用基于debian构建的qinglong:debian，apline安装是`apk add`，debian安装是`apt-get install`

解决方法：判断系统版本是apline还是debian再执行相关操作

其他：参考：https://learn.microsoft.com/zh-cn/dotnet/core/install/linux-debian我只找到了`apt-get install -y dotnet-runtime-8.0`，但我不太清楚dotnet6-sdk和dotnet-runtime-8.0的区别，因此没有提交pr

**Comment by 420348264** [comment]
解决了吗 我也是一样的bug![image](https://github.com/RayWangQvQ/BiliBiliToolPro/assets/8722979/7d736072-5a42-4cb5-8a03-e9d0fb839d7d)![image](https://github.com/RayWangQvQ/BiliBiliToolPro/assets/8722979/5efa211b-5f73-4866-aaea-e5444f4b5f5c)![image](https://github.com/RayWangQvQ/BiliBiliToolPro/assets/8722979/8a7e14ce-b324-40f2-aba7-8d6b5db2e1a5)

**Comment by ZiaYao** [comment]
https://github.com/RayWangQvQ/BiliBiliToolPro/issues/648#issuecomment-2009350235

**Comment by RayWangQvQ** [comment]
感谢反馈，先汇总到 #691 ，稍后统一解决
