### ISSUE TITLE
【Bug】青龙扫码登录功能一直反复出错

### ISSUE THREAD

**Issue by cnzh10000** [RayWangQvQ/BiliBiliToolPro#665]
bili_task_base.sh: line 10: dotnet: command not found
which dotnet: 
开始安装dotnet
------尝试使用apk安装------
ERROR: unable to select packages:
  aiohttp (no such package):
    required by: world[aiohttp]
  bizCode (no such package):
    required by: world[bizCode]
  bizMsg (no such package):
    required by: world[bizMsg]
  canvas (no such package):
    required by: world[canvas]
  dotnet (no such package):
    required by: world[dotnet]
  dotnet6-sdk (no such package):
    required by: world[dotnet6-sdk]
  lxml (no such package):
    required by: world[lxml]
  magic (no such package):
    required by: world[magic]
  python-devel (no such package):
    required by: world[python-devel]
bili_task_base.sh: line 20: dotnet: command not found
------再尝试使用官方脚本安装------
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to ghproxy.com:443 
bili_task_base.sh: line 25: dotnet: command not found
------再尝试使用二进制包安装------
curl: (28) Failed to connect to ghproxy.com port 443 after 127218 ms: Operation timed out
bili_task_base.sh: line 30: dotnet: command not found
安装失败，没办法了，毁灭吧，自己解决吧：https://learn.microsoft.com/zh-cn/dotnet/core/install/linux-alpine

以上插件都已经安装

**Comment by RayWangQvQ** [comment]
感谢反馈，先汇总到 #691 ，稍后统一解决
