### ISSUE TITLE
./bili_task_base.sh: line 7: /root/.bashrc: No such file or directory这个是为啥

### ISSUE THREAD

**Issue by wengjialong** [RayWangQvQ/BiliBiliToolPro#668]
bili扫码登录

./bili_task_base.sh: line 7: /root/.bashrc: No such file or directory
突然就这样了

**Comment by kingsleygithub001** [comment]
> bili扫码登录
> 
> ./bili_task_base.sh: line 7: /root/.bashrc: No such file or directory 突然就这样了

请问你解决了吗，我也是报这个错

**Comment by wengjialong** [comment]
我删除了重新拉的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月11日(周一) 晚上11:45
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [RayWangQvQ/BiliBiliToolPro] ./bili_task_base.sh: line 7: /root/.bashrc: No such file or directory这个是为啥 (Issue #668)




  
bili扫码登录
 
./bili_task_base.sh: line 7: /root/.bashrc: No such file or directory 突然就这样了
  
请问你解决了吗，我也是报这个错

**Comment by kingsleygithub001** [comment]
> 我删除了重新拉的
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年3月11日(周一) 晚上11:45 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [RayWangQvQ/BiliBiliToolPro] ./bili_task_base.sh: line 7: /root/.bashrc: No such file or directory这个是为啥 (Issue #668) bili扫码登录 ./bili_task_base.sh: line 7: /root/.bashrc: No such file or directory 突然就这样了 请问你解决了吗，我也是报这个错 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

我重新拉了也不行，请问你的青龙版本是多少？

**Comment by wengjialong** [comment]
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月12日(周二) 中午11:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [RayWangQvQ/BiliBiliToolPro] ./bili_task_base.sh: line 7: /root/.bashrc: No such file or directory这个是为啥 (Issue #668)




  
我删除了重新拉的
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年3月11日(周一) 晚上11:45 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [RayWangQvQ/BiliBiliToolPro] ./bili_task_base.sh: line 7: /root/.bashrc: No such file or directory这个是为啥 (Issue #668) bili扫码登录 ./bili_task_base.sh: line 7: /root/.bashrc: No such file or directory 突然就这样了 请问你解决了吗，我也是报这个错 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
我重新拉了也不行，请问你的青龙版本是多少？

**Comment by RayWangQvQ** [comment]
感谢反馈，先汇总到 #691 ，稍后统一解决
