### ISSUE TITLE
【Bug】青龙面板运行bili扫码登录，日志显示 ./bili_task_base.sh: line 7: /root/.bashrc: No such file or directory，怎么处理呢

### ISSUE THREAD

**Issue by zhaosongonline** [RayWangQvQ/BiliBiliToolPro#671]
版本号：（请贴出你的版本号，请确认是否已通过升级到最新版来解决当前问题？）
运行环境：（请贴出运行环境，比如是Actions或docker或本地？是Win还是Linux？）

问题描述：（提issue前请先确认没有其他人已提过相同的议题，请清晰的描述所您所遇到的问题。）

日志信息：（如果可以，请贴出Debug级别的日志信息，以便更高效的确定和解决问题。）

**Comment by geminicc** [comment]
同遇到这问题，重新拉了库也没用，求大佬

**Comment by RayWangQvQ** [comment]
感谢反馈，先汇总到 #691 ，稍后统一解决
