### ISSUE TITLE
【Bug】青龙面板，只有重启后第一次成功

### ISSUE THREAD

**Issue by SlowFlight** [RayWangQvQ/BiliBiliToolPro#672]
版本号：青龙面板 正式版 v2.16.0
           dotnet，当前版本：6.0.125

运行环境：NAS下青龙面板

问题描述：第一天正常运行，第二天报错。
              重启青龙面板之后运行成功，但第二次运行就失败，尝试重新订阅、bili尝试修复异常，均无效

日志信息：
./bili_task_base.sh: line 7: /root/.bashrc: No such file or directory
已安装dotnet，当前版本：6.0.125

repo目录: /ql/data/repo
bili仓库目录: /ql/data/repo/RayWangQvQ_BiliBiliToolPro

/usr/lib/dotnet/sdk/6.0.125/Roslyn/Microsoft.CSharp.Core.targets(75,5): error MSB6006: "csc.dll" exited with code 137. [/ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Agent/Ray.BiliBiliTool.Agent.csproj]

The build failed. Fix the build errors and run again.

**Comment by RayWangQvQ** [comment]
感谢反馈，先汇总到 #691 ，稍后统一解决
