### ISSUE TITLE
【建议】希望加入windows定时任务启动后，它能自动化启动各项任务

### ISSUE THREAD

**Issue by geniusNFIL** [RayWangQvQ/BiliBiliToolPro#674]
windows电脑打开自带的 定时任务 启动后，仅仅能启动该程序，但是进入程序后，还需要手动选择输入1、2、3、4、5、6……，

建议加入启动程序后，检测账号登录是否正常，

如果正常，就冷却20秒，20秒内添加暂停手动输入功能；

20秒后添加自动执行所有程序，或者指定哪些指令的程序

这样，就能实现windows电脑等的全自动设定挂机。

**Comment by Polaris-cn10086** [comment]
我记得计划任务是可以添加参数来着，可以试着使用参数来控制每次运行执行的任务

**Comment by geniusNFIL** [comment]
怎么做呢？求详细解答！感谢！
