### ISSUE TITLE
【Bug】安卓手机青龙面板安装好dotnet后启动失败

### ISSUE THREAD

**Issue by Yulinom** [RayWangQvQ/BiliBiliToolPro#675]
版本号：release/2.0.2
运行环境：安卓手机青龙面板

问题描述：安卓手机青龙面板安装好dotnet后启动失败

日志信息：
which dotnet: /usr/bin/dotnet
开始安装dotnet
------尝试使用apk安装------
OK: 736 MiB in 113 packages
Error relocating dotnet: _ZSt21__glibcxx_assert_failPKciS0_S0_: symbol not found

**Comment by RayWangQvQ** [comment]
用现在先行版试试呢，最近有优化更新
