### ISSUE TITLE
青龙环境 修改配置的变量 不会同步到脚本里面

### ISSUE THREAD

**Issue by Ice-Whisky** [RayWangQvQ/BiliBiliToolPro#68]
本来两个账号的 删掉了一个账号的变量保存了 在运行脚本还是显示两个账号
BUG吗？ 求解

**Comment by RayWangQvQ** [comment]
是个已知问题了，如果配置是放到青龙的`配置文件`里，目前是没有热更新的，需要重启青龙容器才行。
如果放到青龙的`环境变量`里，是可以热更新的。

原因得去看青龙的源码了。

目前想热更新的话，两种办法：

- 配到`环境变量`里
- 配到`配置文件`里，但每次修改完，重启一次青龙容器

![image](https://user-images.githubusercontent.com/31154238/161678418-7e0c15dc-96b4-4cd4-8673-ee00950aad54.png)

**Comment by Ice-Whisky** [comment]
> 是个已知问题了，如果配置是放到青龙的`配置文件`里，目前是没有热更新的，需要重启青龙容器才行。
> 如果放到青龙的`环境变量`里，是可以热更新的。
> 
> 原因得去看青龙的源码了。
> 
> 目前想热更新的话，两种办法：
> 
> - 配到`环境变量`里
> - 配到`配置文件`里，但每次修改完，重启一次青龙容器
> 
> ![image](https://user-images.githubusercontent.com/31154238/161678418-7e0c15dc-96b4-4cd4-8673-ee00950aad54.png)
> 

这个问题重启解决了  感谢
突然发现又有一个问题 取关主播数量的变量 Count 无论填-1 还是直接填40  都是只取关一个  这个是bug嘛
