### ISSUE TITLE
是否存在自动关注UP主

### ISSUE THREAD

**Issue by assassinliujie** [RayWangQvQ/BiliBiliToolPro#684]
![image](https://github.com/RayWangQvQ/BiliBiliToolPro/assets/68693675/2801acd4-54e6-4e6c-b994-9801eab5b6f8)
每天固定时间就会关注一些王者荣耀或者原神的up主，关注时间在完事十点，和我用crontab移动运行的脚本时间相同，停止脚本后未再出现关注，请问是脚本功能还是我的cookie泄露了

**Comment by Polaris-cn10086** [comment]
开启自动参与天选时刻的话会因为参加抽奖而关注up主，会给这些up主自动放在`天选时刻`分类，如果，脚本默认设置是每月清理一次，你也可以自行设置其他的清理时间

**Comment by jiawen1929** [comment]
那怎么关闭呢，青龙面板部署，不知道给啥环境变量来关

**Comment by Naylenv** [comment]
天选时刻是b站分组吗？我手动创建后青龙执行定时任务，并没有放到"天选时刻"这个分组诶
