### ISSUE TITLE
【Bug】bili_task_base.sh: line 7: /root/.bashrc: No such file or directory

### ISSUE THREAD

**Issue by Luzy0615** [RayWangQvQ/BiliBiliToolPro#687]
bili扫码登录
## 开始执行... 2024-04-19 16:49:49

bili_task_base.sh: line 7: /root/.bashrc: No such file or directory
已安装dotnet，当前版本：6.0.129

repo目录: /ql/data/repo
bili仓库目录: 

bili_task_login.sh: line 6: cd: ./src/Ray.BiliBiliTool.Console: No such file or directory
Couldn't find a project to run. Ensure a project exists in /root, or pass the path to the project using --project.

## 执行结束... 2024-04-19 16:49:50  耗时 1 秒

**Comment by jhs1873** [comment]
https://github.com/RayWangQvQ/BiliBiliToolPro/issues/646#issuecomment-2071918338

**Comment by yang7758258** [comment]
+1 你解决了嘛
