### ISSUE TITLE
青龙上运行异常，需要优化在青龙部署的方式

### ISSUE THREAD

**Issue by leioukupo** [RayWangQvQ/BiliBiliToolPro#691]
版本号：（请贴出你的版本号，请确认是否已通过升级到最新版来解决当前问题？）
6.0.129
运行环境：（请贴出运行环境，比如是Actions或docker或本地？是Win还是Linux？）
青龙面板
问题描述：（提issue前请先确认没有其他人已提过相同的议题，请清晰的描述所您所遇到的问题。）
没有登录的二维码
日志信息：（如果可以，请贴出Debug级别的日志信息，以便更高效的确定和解决问题。）
bili_task_login.sh: line 6: cd: ./src/Ray.BiliBiliTool.Console: No such file or directory
Couldn't find a project to run. Ensure a project exists in /root, or pass the path to the project using --project

**Comment by kongev** [comment]
一样

**Comment by yang7758258** [comment]
一样

**Comment by RayWangQvQ** [comment]
后面我再想想怎么能让青龙上运行更稳定吧，看到太多人环境异常了。。。

**Comment by kirara233** [comment]
一样的报错，部署后第二次使用出现

**Comment by w32x42y** [comment]
青龙方式二拉取bili库，运行时长只有四秒且日志显示任务未运行，无法拉取

**Comment by Jernin** [comment]
我青龙重新部署了好几遍也不行  我以为只有我这样呢····

**Comment by dalant2019** [comment]
提示：line 7: /root/.bashrc: No such file or directory，以前几次都是删除了重新拉就能恢复，但这次不行了

**Comment by Jernin** [comment]
> bili_task_base.sh脚本中加速地址已被墙，请更新为https://mirror.ghproxy.com/
没关系的吧？我不用加速地址

**Comment by HZZformGD** [comment]
> [w32x42y](/w32x42y)

一样.. 我也是未运行, 是青龙的问题吗? 还是方式二的repo 命令有问题?

**Comment by geminicc** [comment]
拉取成功刷新没有任务，青龙版本2.12.2

**Comment by RayWangQvQ** [comment]
dev先行版一更新，详情见：https://github.com/RayWangQvQ/BiliBiliToolPro/blob/develop/qinglong/README.md

**Comment by RayWangQvQ** [comment]
先行版稳定运行3天，现已正式发布`2.1.0`版本

**Comment by lz37** [comment]
仍然存在这个问题，解决方案是在青龙设置环境变量DOTNET_USE_POLLING_FILE_WATCHER=1，最好在文档里加一下
