### ISSUE TITLE
【Bug】青龙面板定时运行脚本，机器就会死

### ISSUE THREAD

**Issue by miaowmint** [RayWangQvQ/BiliBiliToolPro#708]
版本号：2.0.5
运行环境：青龙v2.17.4  服务器腾讯云HK

问题描述：通过青龙定时运行部分脚本就会导致服务器磁盘读写爆满，从而导致服务器GG，只能强行重启，已稳定复现4天

最开始的时候没想到是脚本的问题，重启了下服务器，然后当时手动运行也没什么问题
从第二天开始，发现服务器是在脚本定时运行的时候死的，当时以为是所有脚本同时并发运行导致的问题，所以手动把脚本的运行时间都岔开了
第三天还是死了，发现可能是是 bili扫码登录 和 bili大会员大积分 这两个脚本的锅，因为服务器是在定时运行这两个脚本的时候死的，所以把这两个脚本禁用了
结果今天第四天还是死了，这回是 bili每日任务 的锅，实在是觉得这个bug太神奇了，于是我来提了issue

至于为什么不怀疑是青龙的问题，主要是因为其它项目的脚本没出现过这种情况，包括 bili测试ck 和 bili尝试修复异常 这两个脚本也是没有出现过问题的

日志信息：没法提供日志，青龙面板没有任何异常日志，脚本日志和运行了一下然后停止运行是一样的

更新：之前以为手动运行不会有问题 但是今天 手动运行的时候，服务器也还是G了
![image](https://github.com/RayWangQvQ/BiliBiliToolPro/assets/58991169/bc072ba5-91ab-4f92-94de-6b153a1f3c48)

服务器控制台监控如下，记录了其中两天的
![Screenshot - 2024-05-05 12 43 17](https://github.com/RayWangQvQ/BiliBiliToolPro/assets/58991169/4171ea09-56d3-413e-9ab0-1b354e0e4b0f)
![Screenshot - 2024-05-06 12 47 38](https://github.com/RayWangQvQ/BiliBiliToolPro/assets/58991169/1ffdccbf-af85-49c8-8e4b-832b99282a99)

**Comment by RayWangQvQ** [comment]
麻烦提供下手动运行导致异常的那次运行日志

**Comment by miaowmint** [comment]
> 麻烦提供下手动运行导致异常的那次运行日志

这就是最麻烦的一点，没有日志，青龙容器也没有日志，服务器直接就是硬盘读写爆炸

![image](https://github.com/RayWangQvQ/BiliBiliToolPro/assets/58991169/f600a064-1a42-4a0b-9ece-6ffc518f6445)

![image](https://github.com/RayWangQvQ/BiliBiliToolPro/assets/58991169/3d501eae-9570-4172-8e1b-a43f214a54e8)

![image](https://github.com/RayWangQvQ/BiliBiliToolPro/assets/58991169/97c5b33f-c857-4940-a97a-1d27a621acd6)

**Comment by miaowmint** [comment]
> 麻烦提供下手动运行导致异常的那次运行日志

要不我把青龙面板的地址账号密码给你？

**Comment by RayWangQvQ** [comment]
> > 麻烦提供下手动运行导致异常的那次运行日志
> 
> 要不我把青龙面板的地址账号密码给你？

在群里吗，私聊我

**Comment by miaowmint** [comment]
> > > 麻烦提供下手动运行导致异常的那次运行日志
> > 
> > 
> > 要不我把青龙面板的地址账号密码给你？
> 
> 在群里吗，私聊我

不在（ 能发下群号吗

**Comment by RayWangQvQ** [comment]
置顶issue里有TG链接
