### ISSUE TITLE
【异常】运行登录脚本报错

### ISSUE THREAD

**Issue by EuraGoods** [RayWangQvQ/BiliBiliToolPro#712]
登录脚本运行日志：
## 开始执行... 2024-05-08 18:46:26

bili_task_base.sh: line 76: /ql/shell/env.sh: No such file or directory

**Comment by RayWangQvQ** [comment]
至少说下青龙版本、系统信息啊

**Comment by Candy-yan1** [comment]
> 至少说下青龙版本、系统信息啊

版本v2.15.7
--
更新时间2023-02-12 17:09:07
更新ID437a849

在这之前都可以用  5.9日开始出现问题

**Comment by RayWangQvQ** [comment]
不符合issue模板
