### ISSUE TITLE
【Bug】青龙2.12.2脚本跑不起来，所有除拉库

### ISSUE THREAD

**Issue by yangxiuxin6** [RayWangQvQ/BiliBiliToolPro#713]
版本号：（请贴出你的版本号，请确认是否已通过升级到最新版来解决当前问题？）
运行环境：（请贴出运行环境，比如是Actions或docker或本地？是Win还是Linux？）
青龙
问题描述：（提issue前请先确认没有其他人已提过相同的议题，请清晰的描述所您所遇到的问题。）
运行1秒后自动停止
日志信息：（如果可以，请贴出Debug级别的日志信息，以便更高效的确定和解决问题。）

**Comment by yangxiuxin6** [comment]
bili_task_base.sh: line 76: /ql/shell/env.sh: No such file or directory

**Comment by Candy-yan1** [comment]
> bili_task_base.sh: line 76: /ql/shell/env.sh: No such file or directory

+1

**Comment by yangxiuxin6** [comment]
> > bili_task_base.sh: line 76: /ql/shell/env.sh: No such file or directory
> 
> +1

缺少env.sh文件
