### ISSUE TITLE
【Bug】面具青龙模块解决不能运行脚本方法

### ISSUE THREAD

**Issue by yangxiuxin6** [RayWangQvQ/BiliBiliToolPro#714]
版本号：latest
运行环境：面具青龙模块
问题描述：

解决方法将这个目录下/data/alpine/ql/data/config/env.sh，复制到/ql/shell/目录下就可以正常运行
日志信息：（如果可以，请贴出Debug级别的日志信息，以便更高效的确定和解决问题。）
bili_task_base.sh: line 76: /ql/shell/env.sh: No such file or directory

**Comment by xiaobuboy** [comment]
没有找到楼主说的这个目录啊/data/alpine/ql/data/config/env.sh

**Comment by yangxiuxin6** [comment]
#!/bin/bash

ql_path="/data/alpine/ql"
env_file="$ql_path/shell/env.sh"
config_file="$ql_path/data/config/env.sh"

if [ -f "$env_file" ]; then
    echo "已存在 env.sh 文件，路径为：$env_file"
else
    ql_env=$(find "$ql_path" -name "env.sh")
    if [ -n "$ql_env" ]; then
        echo "已找到 env.sh 文件，路径为：$ql_env"
        cp "$ql_env" "$env_file" && echo "已复制 env.sh 文件到 $ql_path/shell 目录"
    else
        cp "$config_file" "$env_file" && echo "已复制 env.sh 文件到 $ql_path/shell 目录"
    fi
fi

**Comment by yangxiuxin6** [comment]
> 没有找到楼主说的这个目录啊/data/alpine/ql/data/config/env.sh

可以在ql目录里面搜索env.sh这个文件

**Comment by xiaobuboy** [comment]
## 开始执行... 2024-05-09 14:07:57

未找到 env.sh 文件
bilitool: 青龙repo目录: /ql/data/repo
find: /ql/data/repo: No such file or directory

## 执行结束... 2024-05-09 14:07:59 耗时 2 秒

**Comment by RayWangQvQ** [comment]
神奇，你的qinglong版本是什么？是怎么安装的？
`/data/alpine/ql/data/config/env.sh`这个是宿主机的路径？还是容器内的？正常安装qinglong目录不应该在这才对

**Comment by Candy-yan1** [comment]
root@qinglong:/ql/shell $ cp /data/alpine/ql/data/config/env.sh ./
cp: cannot stat '/data/alpine/ql/data/config/env.sh': No such file or directory

**Comment by yangxiuxin6** [comment]
> 神奇，你的qinglong版本是什么？是怎么安装的？
> `/data/alpine/ql/data/config/env.sh`这个是宿主机的路径？还是容器内的？正常安装qinglong目录不应该在这才对

这是面具刷的青龙模块

**Comment by superHao2000** [comment]
> > 神奇，你的qinglong版本是什么？是怎么安装的？
> > `/data/alpine/ql/data/config/env.sh`这个是宿主机的路径？还是容器内的？正常安装qinglong目录不应该在这才对
> 
> 这是面具刷的青龙模块 报错的可能都是使用的青龙模块

我是安装在容器里面的，前天安装的手动运行正常，昨天自动正常运行，今天检查报错了

**Comment by Candy-yan1** [comment]
> > 神奇，你的qinglong版本是什么？是怎么安装的？
> > `/data/alpine/ql/data/config/env.sh`这个是宿主机的路径？还是容器内的？正常安装qinglong目录不应该在这才对
> 
> 这是面具刷的青龙模块 报错的可能都是使用的青龙模块

我是安装在docker容器里的  之前也运行过几次程序，都是没问题的  昨天运行开始提示这个问题

**Comment by a809068872** [comment]
终于解决了，这个情况以往也出现过，我一般重启服务器，重启青龙就解决了，这次不知道咋地一直弄不好，直到看到这个issue。我的env.sh文件藏在
/var/lib/docker/overlay2/61b2b127c530c8b60e8b7db23518c64726ea6ebd32faacaf6b6df6d37ef2ad0f/merged/ql/data/config这里。
把env.sh复制到
/var/lib/docker/overlay2/61b2b127c530c8b60e8b7db23518c64726ea6ebd32faacaf6b6df6d37ef2ad0f/merged/ql/shell后就能正常运行了。感谢楼主。

**Comment by Candy-yan1** [comment]
> 终于解决了，这个情况以往也出现过，我一般重启服务器，重启青龙就解决了，这次不知道咋地一直弄不好，直到看到这个issue。我的env.sh文件藏在 /var/lib/docker/overlay2/61b2b127c530c8b60e8b7db23518c64726ea6ebd32faacaf6b6df6d37ef2ad0f/merged/ql/data/config这里。 把env.sh复制到 /var/lib/docker/overlay2/61b2b127c530c8b60e8b7db23518c64726ea6ebd32faacaf6b6df6d37ef2ad0f/merged/ql/shell后就能正常运行了。感谢楼主。

十分感谢 ，看了你的回复后我尝试进入青龙容器的/ql/data/config里 把这个文件夹下的env.sh复制到了/ql/shell/下，脚本运行正常了，感谢楼主、层主及作者的帮助

**Comment by xiaobuboy** [comment]
我的青龙是v2.11.3，没有data目录

**Comment by yangxiuxin6** [comment]
> 我的青龙是v2.11.3，没有data目录

青龙目录下搜索env.sh文件，然后复制到缺失路径下，
运行上面的文件也可以
