### ISSUE TITLE
运行任务报错 No such file or directory

### ISSUE THREAD

**Issue by hello-world-csx** [RayWangQvQ/BiliBiliToolPro#716]
./bili_task_base.sh: line 7: /root/.bashrc: No such file or directory
bili_task_login.sh: line 6: cd: ./src/Ray.BiliBiliTool.Console: No such file or directory
Couldn't find a project to run. Ensure a project exists in /root, or pass the path to the project using --project.

**Comment by RayWangQvQ** [comment]
不符合模板
