### ISSUE TITLE
【Bug】bili_task_daily.sh: line 6: cd: ./src/Ray.BiliBiliTool.Console: No such file or directory

### ISSUE THREAD

**Issue by Moruin** [RayWangQvQ/BiliBiliToolPro#719]
版本号：最新
运行环境：Linux青龙

问题描述：执行面板一直提示找不到目录

日志信息：
bili_task_daily.sh: line 6: cd: ./src/Ray.BiliBiliTool.Console: No such file or directory
Couldn't find a project to run. Ensure a project exists in /root, or pass the path to the project using --project.

解决方案：把脚本全部给上777权限就可以了。
![image](https://github.com/RayWangQvQ/BiliBiliToolPro/assets/47071816/bf110bb0-f929-4210-bacf-a24bf33e6c66)

**Comment by RayWangQvQ** [comment]
你是docker还是podman？青龙是debian还是alpine？

我这边自测是不需要手动设置权限的，默认的644就可以：

![image](https://github.com/RayWangQvQ/BiliBiliToolPro/assets/31154238/f45ffdfb-1349-4566-8b2a-28fbab8ce21b)

能把你的777该回去再试下不？看是不是还报错？或者报的是不是同样的错误？

**Comment by Moruin** [comment]
bilitool: 青龙repo目录: /ql/data/repo
bilitool: bili仓库目录: /ql/data/repo/RayWangQvQ_BiliBiliToolPro
bilitool: 当前系统发行版本：alpine.3.19.1
bilitool: 当前系统：linux-musl
bilitool: 当前架构：x64
bilitool: 当前选择的运行方式：dotnet
bilitool: 已安装dotnet，当前版本：6.0.129
bilitool: which dotnet: /usr/bin/dotnet
bilitool: 环境正常，本次无需安装



昨天改了权限，开了debug模式，能正常运行。然后今天更新之后，权限回归了，又不报错了，奇怪

**Comment by RayWangQvQ** [comment]
Ok，那再观察观察吧，目前看跟脚本文件的权限关系不大，感谢反馈
