### ISSUE TITLE
【Bug】【青龙】<青龙版本低于2.12无法正常运行，关于文件路径问题>

### ISSUE THREAD

**Issue by ji-nian** [RayWangQvQ/BiliBiliToolPro#728]
### 版本

BiliTool版本号：`6.0.403`

青龙版本号：`2.11.3`

### 确认

- [x] 是的，我已搜索并确认，没有其他相同的议题
- [ ] 是的，我确认，已尝试升级到最新版，但未解决

### 服务器架构

- [x] x64
- [ ] arm64
- [ ] arm
- [ ] 其他（请在下面补充）

### 服务器系统

- [ ] Windows
- [ ] macOS
- [x] Linux
    - [ ] Debian
    - [x] Ubuntu
    - [ ] Windows
    - [ ] Alpine
    - [ ] Centos
    - [ ] 其他（请在下面补充）

### 青龙容器类型

- [x] Docker
- [ ] Podman
- [ ] 其他（请在下面补充）

### 青龙镜像

- [ ] whyour/qinglong:latest（Alpine）
- [ ] whyour/qinglong:debian（Debian）
- [x] whyour/qinglong:2.11.3

### 选择的BiliTool运行模式

- [x] dotnet
- [ ] bilitool

### 如果是青龙拉库相关bug，请贴出拉库方式截图

- [x] 否
- [ ] 是，截图如下

### 如果是缺失文件相关bug，请贴出容器内文件路径信息

- [ ] 否
- [x] 是，信息如下

查看方式参考文档：[提示文件不存在或路径异常怎么排查](https://github.com/RayWangQvQ/BiliBiliToolPro/blob/main/qinglong/README.md#43-提示文件不存在或路径异常怎么排查)

BiliTool仓库文件路径：`/root/ql/repo/RayWangQvQ_BiliBiliToolPro/`

脚本文件路径：`/root/ql/scripts/RayWangQvQ_BiliBiliToolPro/`

### 问题描述

青龙版本号低于2.12的版本里，docker内repo路径为`/ql/repo`，在2.12.0版本后变更为`/ql/data/repo`，在 #706 这一次更新后在[bili_task_base.sh](https://github.com/RayWangQvQ/BiliBiliToolPro/blob/cc11f25f0d89f0daa872e57ceefdc25b56cffe20/qinglong/DefaultTasks/bili_task_base.sh)文件的修改中，似乎将仓库地址指定为了`/ql/data/repo`，我在手动将仓库文件移动到`/ql/data/repo`下后可以正常运行。**希望可以对仓库位置进行判断。**

### 日志信息

<details>

```
## 开始执行... 2024-05-17 10:55:20

bilitool: 青龙repo目录: /ql/data/repo
find: /ql/data/repo: No such file or directory

## 执行结束... 2024-05-17 10:55:21 耗时 1 秒
```

</details>

**Comment by RayWangQvQ** [comment]
收到

**Comment by RayWangQvQ** [comment]
已修复。
