### ISSUE TITLE
【建议】能否支持不做特定任务和2个描述小错误

### ISSUE THREAD

**Issue by Cyiming** [RayWangQvQ/BiliBiliToolPro#73]
1、我的需求仅仅是不想做投币、点赞、观看还有分享，其中投币和点赞可以通过环境变量间接实现，但不观看和分享好像无法实现。

我仔细看了配置文件 里面有跳过执行任务 Ray_Security__IsSkipDailyTask 我理解是每日任务全部跳过 

好像现在我要不就都不做，放弃直播间签到等，要不就全都做。

希望可以有更多细化开关选择

2、https://github.com/RayWangQvQ/BiliBiliToolPro/blob/main/qinglong/README.md

`在容器内路径为 /ql/config/extra.sh`

应修改为 在容器内路径为 /ql/data/config/extra.sh

3、https://github.com/RayWangQvQ/BiliBiliToolPro/blob/main/docs/configuration.md

3.2.2. 随机睡眠的最大时长 

文字描述：默认为10
表格内描述：20

前后矛盾 猜测表格内更准确

**Comment by RayWangQvQ** [comment]
观看和分享视频的开关，其实一直都是有的：

https://github.com/RayWangQvQ/BiliBiliToolPro/blob/f048698e0e8640415ec5a61a3380c0225f1ac166/src/Ray.BiliBiliTool.Console/appsettings.json#L11

https://github.com/RayWangQvQ/BiliBiliToolPro/blob/f048698e0e8640415ec5a61a3380c0225f1ac166/src/Ray.BiliBiliTool.Console/appsettings.json#L12

只是文档里漏了

**Comment by RayWangQvQ** [comment]
上面提到的关于文档的其他错漏信息，我也都一起更新了。

另外，发现错漏的话，欢迎直接提交PR过来修正，我会尽快合并的。

我个人精力有限，文档有时更新会不及时。

**Comment by Cyiming** [comment]
> PR

好的 谢谢 明白了 

不会操作PR 我研究下
