### ISSUE TITLE
【Bug】【青龙】扫码登陆脚本运行保存

### ISSUE THREAD

**Issue by 2375399351** [RayWangQvQ/BiliBiliToolPro#731]
### 版本

BiliTool版本号：`x.x.x`

青龙版本号：`2.11.3`

### 确认

- [ ] 是的，我已搜索并确认，没有其他相同的议题
- [ ] 是的，我确认，已尝试升级bilitool到最新版，但未解决
- [ ] 是的，我确认，已尝试升级青龙到最新版，但未解决

### 服务器架构

- [ ] x64
- [ ] arm64
- [ ] arm
- [ ] 其他（请在下面补充）

### 服务器系统

- [ ] Windows
- [ ] macOS
- [ ] Linux
    - [ ] Debian
    - [ ] Ubuntu
    - [ ] Windows
    - [ ] Alpine
    - [ ] Centos
    - [ ] 其他（请在下面补充）

### 青龙容器类型

- [✓] Docker
- [ ] Podman
- [ ] 其他（请在下面补充）

### 青龙镜像

- [✓] whyour/qinglong:latest（Alpine）
- [ ] whyour/qinglong:debian（Debian）

### 选择的BiliTool运行模式

- [ ] dotnet
- [ ] bilitool

### 如果是青龙拉库相关bug，请贴出拉库方式截图

- [ ] 否
- [ ] 是，截图如下

### 如果是缺失文件相关bug，请贴出容器内文件路径信息

- [ ] 否
- [ ] 是，信息如下

查看方式参考文档：[提示文件不存在或路径异常怎么排查](https://github.com/RayWangQvQ/BiliBiliToolPro/blob/main/qinglong/README.md#43-提示文件不存在或路径异常怎么排查)

BiliTool仓库文件路径：`<粘贴路径>`

脚本文件路径：`<粘贴路径>`

<这里贴截图>

### 问题描述
扫码登陆脚本报错

<这里>

## 开始执行... 2024-05-28 17:48:33

bilitool: 青龙repo目录: /ql/repo
bilitool: bili仓库目录: /ql/repo/RayWangQvQ_BiliBiliToolPro
bilitool: 当前系统发行版本：alpine.3.15.0
bilitool: 当前系统：linux-musl
bilitool: 当前架构：x64
bilitool: 当前选择的运行方式：dotnet
bilitool: 已安装dotnet，当前版本：6.0.420
bilitool: which dotnet: /usr/local/bin/dotnet
bilitool: 环境正常，本次无需安装
/ql/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Application.Contracts/Ray.BiliBiliTool.Application.Contracts.csproj : error NU1301: 无法加载源 https://api.nuget.org/v3/index.json 的服务索引。 [/ql/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/Ray.BiliBiliTool.Console.csproj]
/ql/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Agent/Ray.BiliBiliTool.Agent.csproj : error NU1301: 无法加载源 https://api.nuget.org/v3/index.json 的服务索引。 [/ql/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/Ray.BiliBiliTool.Console.csproj]
/ql/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Config/Ray.BiliBiliTool.Config.csproj : error NU1301: 无法加载源 https://api.nuget.org/v3/index.json 的服务索引。 [/ql/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/Ray.BiliBiliTool.Console.csproj]
/ql/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Application/Ray.BiliBiliTool.Application.csproj : error NU1301: 无法加载源 https://api.nuget.org/v3/index.json 的服务索引。 [/ql/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/Ray.BiliBiliTool.Console.csproj]
/ql/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/Ray.BiliBiliTool.Console.csproj : error NU1301: 无法加载源 https://api.nuget.org/v3/index.json 的服务索引。
/ql/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Application/Ray.BiliBiliTool.Application.csproj : error NU1301: 无法加载源 https://api.nuget.org/v3/index.json 的服务索引。 [/ql/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/Ray.BiliBiliTool.Console.csproj]
/ql/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Infrastructure/Ray.BiliBiliTool.Infrastructure.csproj : error NU1301: 无法加载源 https://api.nuget.org/v3/index.json 的服务索引。 [/ql/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/Ray.BiliBiliTool.Console.csproj]
/ql/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Agent/Ray.BiliBiliTool.Agent.csproj : error NU1301: 无法加载源 https://api.nuget.org/v3/index.json 的服务索引。 [/ql/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/Ray.BiliBiliTool.Console.csproj]
/ql/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Config/Ray.BiliBiliTool.Config.csproj : error NU1301: 无法加载源 https://api.nuget.org/v3/index.json 的服务索引。 [/ql/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/Ray.BiliBiliTool.Console.csproj]
/ql/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Application.Contracts/Ray.BiliBiliTool.Application.Contracts.csproj : error NU1301: 无法加载源 https://api.nuget.org/v3/index.json 的服务索引。 

<details>

```
<这里>
```

</details>

**Comment by RayWangQvQ** [comment]
alpine版本大于等于`3.17`才能运行dotnet6.0

微软文档：https://learn.microsoft.com/zh-cn/dotnet/core/install/linux-alpine#supported-distributions

![image](https://github.com/RayWangQvQ/BiliBiliToolPro/assets/31154238/6ae984d9-9614-47de-909e-98aa7e74f57f)

可以通过升级qinglong版本解决

P.S.推荐`whyour/qinglong:debian`版镜像。

为了让系统精简用alpine，结果为了运行脚本又不得不装回这些被精简掉的一堆依赖，最后跟debian还是差不多大。。。

**Comment by 2375399351** [comment]
> alpine版本大于等于`3.17`才能运行dotnet6.0
> 
> 
> 
> 微软文档：https://learn.microsoft.com/zh-cn/dotnet/core/install/linux-alpine#supported-distributions
> 
> 
> 
> ![image](https://github.com/RayWangQvQ/BiliBiliToolPro/assets/31154238/6ae984d9-9614-47de-909e-98aa7e74f57f)
> 
> 
> 
> 可以通过升级qinglong版本解决
> 
> 
> 
> P.S.推荐`whyour/qinglong:debian`版镜像。
> 
> 
> 
> 为了让系统精简用alpine，结果为了运行脚本又不得不装回这些被精简掉的一堆依赖，最后跟debian还是差不多大。。。

这样啊，我一直用的latest哈哈

**Comment by RayWangQvQ** [comment]
latest是alpine，也是ok的，但你的版本`2.11.3`太老了，可以升级下

**Comment by 2375399351** [comment]
> latest是alpine，也是ok的，但你的版本`2.11.3`太老了，可以升级下

ok

**Comment by 2375399351** [comment]
> latest是alpine，也是ok的，但你的版本`2.11.3`太老了，现在已经`2.17`了，可以考虑升级下

作者重装青龙2.17.5后，拉取了脚本，接着运行扫码登陆脚本后报错

## 开始执行... 2024-06-04 01:22:51

bilitool: 青龙repo目录: /ql/data/repo
bilitool: bili仓库目录: /ql/data/repo/RayWangQvQ_BiliBiliToolPro
bilitool: 当前系统发行版本：alpine.3.20.0
bilitool: 当前系统：linux-musl
bilitool: 当前架构：x64
bilitool: 当前选择的运行方式：dotnet
./bili_task_base.sh: line 264: dotnet: command not found
bilitool: 未安装
bilitool: 开始安装环境
bilitool: 开始安装dotnet
bilitool: 当前系统：alpine
bilitool: 使用apk安装
fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/community/x86_64/APKINDEX.tar.gz
(1/14) Installing dotnet-host (8.0.6-r0)
(2/14) Installing dotnet6-hostfxr (6.0.31-r0)
(4/14) Installing icu-data-full (74.2-r0)
(3/14) Purging icu-data-en (74.2-r0)
(5/14) Installing lttng-ust (2.13.8-r0)
(6/14) Installing libunwind (1.8.1-r0)
(7/14) Installing dotnet6-runtime (6.0.31-r0)
(8/14) Installing aspnetcore6-runtime (6.0.31-r0)
(9/14) Installing aspnetcore6-targeting-pack (6.0.31-r0)
(10/14) Installing dotnet6-apphost-pack (6.0.31-r0)
(11/14) Installing dotnet6-targeting-pack (6.0.31-r0)
(12/14) Installing dotnet6-templates (6.0.131-r0)
(13/14) Installing netstandard21-targeting-pack (8.0.106-r0)
(14/14) Installing dotnet6-sdk (6.0.131-r0)
Executing busybox-1.36.1-r28.trigger
OK: 613 MiB in 102 packages
6.0.131
bilitool: 安装成功
bilitool: which dotnet: /usr/bin/dotnet

Welcome to .NET 6.0!
---------------------
SDK Version: 6.0.131

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
/usr/lib/dotnet/sdk/6.0.131/NuGet.targets(130,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [/ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/Ray.BiliBiliTool.Console.csproj]
/usr/lib/dotnet/sdk/6.0.131/NuGet.targets(130,5): error :   Resource temporarily unavailable (api.nuget.org:443) [/ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/Ray.BiliBiliTool.Console.csproj]
/usr/lib/dotnet/sdk/6.0.131/NuGet.targets(130,5): error :   Resource temporarily unavailable [/ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/Ray.BiliBiliTool.Console.csproj]

The build failed. Fix the build errors and run again.

## 执行结束... 2024-06-04 01:28:38  耗时 347 秒　　

这个是日志，能看下是什么原因吗？
