### ISSUE TITLE
【其他】天选时刻是否可以指定分区抽奖

### ISSUE THREAD

**Issue by Lisuyang426** [RayWangQvQ/BiliBiliToolPro#732]
### 确认

- [x] 是的，我确认要选Other，因为我的内容既不是Bug，也不是Feature
- [x] 是的，我已搜索并确认，没有其他相同的议题

### 描述

不知道天选时刻的时候是否可以指定分区？或者说是否有更好的办法控制只参与某些直播间的天选时刻？

**Comment by RayWangQvQ** [comment]
目前是根据奖品的关键字来筛选或过滤，根据分区是不是意义不大
