### ISSUE TITLE
【Bug】<请在标题中清晰地概述你要反馈的异常或缺陷>

### ISSUE THREAD

**Issue by kotonamihuiren** [RayWangQvQ/BiliBiliToolPro#734]
### 版本

BiliTool版本号：`x.x.x`

### 确认

- [ ] 是的，我已搜索并确认，没有其他相同的议题
- [ ✔️] 是的，我确认，已尝试升级到最新版，但未解决

### 服务器架构

- [✔️ ] x64
- [ ] arm64
- [ ] arm
- [ ] 其他（请在下面补充）

### 服务器系统

- [ ] Windows
- [ ] macOS
- [ ✔️] Linux
    - [ ] Debian
    - [ ✔️] Ubuntu
    - [ ] Windows
    - [ ] Alpine
    - [ ] Centos
    - [ ] 其他（请在下面补充）

### 选择的BiliTool运行模式

- [ ] docker
- [ ] podman
- [ ] 下载的Release包
- [✔️ ] 其他（请在下面补充）

### 问题描述
青龙所有脚本运行如下图

![image](https://github.com/RayWangQvQ/BiliBiliToolPro/assets/56951494/ce0bed3a-fa9d-46e8-b65e-0c6887711fcb)

### 日志信息

<details>

```
<这里>
```

</details>

**Comment by shanyan-wcx** [comment]
我也遇到这个问题了，请问怎么解决的呢？
