### ISSUE TITLE
【Bug】docker部署后不会自动执行配置的任务

### ISSUE THREAD

**Issue by YD-Cat-1996** [RayWangQvQ/BiliBiliToolPro#74]
因原账号被ban不再使用，也不清楚原issues作者是否能看到，因此换新账号重新发issues
原issues发于2022.04.03

版本号：无法确认，看日志可能是v0.0.9
运行环境：Win docker 和 Linux docker

问题描述：根据wiki通过docker部署，docker正常启动，但配置的任务不会自动执行，手动执行则正常
昨天调试时发现不会自动执行任务，我则设置成每分钟执行Daily任务，在Linux服务器上部署放了一天也不会执行任务
![image](https://user-images.githubusercontent.com/61802497/161423480-3363ab3f-6eff-4197-955e-90a53109eee4.png)

日志信息：
Linux上的日志，昨晚启动后一直没有新的日志内容，文件也只有昨天的日志文件
![image](https://user-images.githubusercontent.com/61802497/161424389-8de27c96-1aad-425e-b950-25fb882e8eb5.png)
![image](https://user-images.githubusercontent.com/61802497/161423957-39f19f1e-c399-4564-84af-50f7f95385ca.png)

以下是本地Win docker部署后的日志，和在Linux相同的现象
docker启动后日志，Test任务正常执行
![image](https://user-images.githubusercontent.com/61802497/161423500-862cafbd-7777-4ca1-a5b9-e3bfd4dff4f2.png)

若进入容器手动执行正常，红框是手动执行后的日志
![image](https://user-images.githubusercontent.com/61802497/161423553-90d6d681-4a66-46c1-a6d7-69b6b468e153.png)

**Comment by XmdChmd** [comment]
我连手动启动都会失败

**Comment by jiucai39** [comment]
我的也是，腾讯云函数自动执行 不执行任务
