### ISSUE TITLE
【其他】<Openwrt docker部署只能运行Test任务>

### ISSUE THREAD

**Issue by Lonely-Sit** [RayWangQvQ/BiliBiliToolPro#746]
### 确认

- [ √] 是的，我确认要选Other，因为我的内容既不是Bug，也不是Feature
- [ X] 是的，我已搜索并确认，没有其他相同的议题
- 我找到了这个议题，他与我的问题非常相似但并没有给我带来帮助#74 

### 描述

<
我在openwrt中使用docker部署后无法自动执行任务
我无法确定是什么问题
只能执行默认的测试（Test）任务
参考#74 
![image](https://github.com/RayWangQvQ/BiliBiliToolPro/assets/71547798/9ad23245-6b20-406a-83fe-b5afa7acc7f0)
![image](https://github.com/RayWangQvQ/BiliBiliToolPro/assets/71547798/b8e995ef-909d-41fb-91ca-c39f0457f691)
![image](https://github.com/RayWangQvQ/BiliBiliToolPro/assets/71547798/977de639-d621-47e0-a78d-8f4bfa8ce856)

>

**Comment by RayWangQvQ** [comment]
其他任务由定时器触发，到时间了就自动运行

**Comment by Lonely-Sit** [comment]
你好 我手动指定过任务时间但他并没有按照预期执行

**Comment by Lonely-Sit** [comment]
目前转到了青龙来执行 一切顺利 
但我想要使用多个账号走不同的任务可以实现吗？
比如账号A的投币数是5
账号B的投币数为1

**Comment by Polaris-cn10086** [comment]
> 目前转到了青龙来执行 一切顺利 但我想要使用多个账号走不同的任务可以实现吗？ 比如账号A的投币数是5 账号B的投币数为1

目前应该只能用两个docker部署两个账号的形式来进行。
