### ISSUE TITLE
【Bug】【青龙】<请在标题中清晰地概述你要反馈的异常或缺陷>

### ISSUE THREAD

**Issue by youlan2333** [RayWangQvQ/BiliBiliToolPro#747]
### 版本

BiliTool版本号：`2.1.1`

青龙版本号：`2.10.13`

### 确认

- [x] 是的，我已搜索并确认，没有其他相同的议题
- [x] 是的，我确认，已尝试升级bilitool到最新版，但未解决
- [ ] 是的，我确认，已尝试升级青龙到最新版，但未解决

### 服务器架构

- [ ] x64
- [ ] arm64
- [x] arm
- [ ] 其他（请在下面补充）

### 服务器系统

- [ ] Windows
- [ ] macOS
- [x] Linux
    - [ ] Debian
    - [ ] Ubuntu
    - [ ] Windows
    - [ ] Alpine
    - [ ] Centos
    - [ ] 其他（请在下面补充）

### 青龙容器类型

- [x] Docker
- [ ] Podman
- [ ] 其他（请在下面补充）

### 青龙镜像

- [x] whyour/qinglong:latest（Alpine）
- [ ] whyour/qinglong:debian（Debian）

### 选择的BiliTool运行模式

- [ ] dotnet
- [x] bilitool

### 如果是青龙拉库相关bug，请贴出拉库方式截图

- [x] 否
- [ ] 是，截图如下

### 如果是缺失文件相关bug，请贴出容器内文件路径信息

- [x] 否
- [ ] 是，信息如下

BiliTool仓库文件路径：`<粘贴路径>`

脚本文件路径：`<粘贴路径>`

![image](https://github.com/RayWangQvQ/BiliBiliToolPro/assets/64688148/dfaba4a1-b689-4ed3-bc46-2f2b97a7bea1)

### 问题描述

拉库成功，登录失败

### 日志信息

<details>

```
## 开始执行... 2024-07-02 14:06:02

bilitool: 青龙repo目录: /ql/repo
bilitool: bili仓库目录: /ql/repo/RayWangQvQ_BiliBiliToolPro
bilitool: 当前系统发行版本：alpine.3.12.9
bilitool: 当前系统：linux-musl
bilitool: 当前架构：arm
bilitool: 当前选择的运行方式：bilitool
bilitool: tag.txt记录的版本：2.1.1
bilitool: bilitool未安装
bilitool: 开始安装环境
bilitool: 开始安装bilitool
bilitool: 最新版本：2.1.1
bilitool: 下载地址：https://github.com/RayWangQvQ/BiliBiliToolPro/releases/download/2.1.1/bilibili-tool-pro-v2.1.1-linux-musl-arm.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100     9  100     9    0     0     10      0 --:--:-- --:--:-- --:--:--    10
Archive:  bilitool-2.1.1.zip
unzip: short read
cp: cannot stat '/ql/repo/RayWangQvQ_BiliBiliToolPro/bin/Ray.BiliBiliTool.Console': No such file or directory

## 执行结束... 2024-07-02 14:06:05 耗时 3 秒
```

</details>

**Comment by youlan2333** [comment]
来自：玩客云CasaOS

**Comment by RayWangQvQ** [comment]
可以使用较新版本qinglong解决
