### ISSUE TITLE
【Bug】【青龙】<任务之后完后未正常结束>

### ISSUE THREAD

**Issue by fomodj** [RayWangQvQ/BiliBiliToolPro#756]
[09:11:44 INF] ·开始推送·Daily任务·
[09:11:44 INF] 运行环境：Production
[09:11:44 INF] 应用目录：/ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/bin/Debug/net6.0/

[09:11:44 INF] 运行结束
/ql/shell/share.sh: line 464: task_after: unbound variable

**Comment by fomodj** [comment]
换了青龙版本

**Comment by StarSink9** [comment]
同样得问题，每次打开青龙脚本全在自动运行，不主动点停止就不会停止

**Comment by iNewWay** [comment]
![微信截图_20240730021249](https://github.com/user-attachments/assets/ca32c9e4-059a-4b3e-8a86-7136d8ad330e)
同样的问题

**Comment by chaoqunxie** [comment]
> 换了青龙版本

用的是什么版本

**Comment by he1low0rId** [comment]
我也是

**Comment by PoisonGZ** [comment]
我直接修改了run_task_after方法,目前测试好像没影响
`run_task_after() {
  . $file_task_after "$@"
}`

**Comment by Chilzen-smx** [comment]
> 我直接修改了run_task_after方法,目前测试好像没影响 `run_task_after() { . $file_task_after "$@" }`

这个在哪里改

**Comment by lxcsjk** [comment]
> > 我直接修改了run_task_after方法,目前测试好像没影响 `run_task_after() { . $file_task_after "$@" }`
> 
> 这个在哪里改

进到容器的  /shell/share.sh 
修改第464行的代码
```sh
run_task_after() {
  . $file_task_after "$@"
  if [[ "${task_after:-}" ]]; then
    echo -e "\n执行后置命令\n"
    eval "$task_after" "$@"
    echo -e "\n执行后置命令结束"
  fi
}
```

**Comment by tomatochaoegg** [comment]
<img width="678" alt="Image" src="https://github.com/user-attachments/assets/6f7f0938-59d7-4f66-8b23-5a3edd13bd20" />

**Comment by S29-zg** [comment]
<img width="115" height="71" alt="Image" src="https://github.com/user-attachments/assets/0b9727c3-cd45-4057-9e3f-161f3fbc3935" />
我也出现了同样的问题，任务运行后，一直显示运行中，该如何解决
版本：正式版 V2.20.0
