### ISSUE TITLE
【Bug】运行提示网络超时，大于100秒未回应

### ISSUE THREAD

**Issue by hzg1577** [RayWangQvQ/BiliBiliToolPro#76]
版本号：（0.10.0）
运行环境：（青龙2.11.0）

问题描述：（青龙运行到一半便异常）

日志信息：（如果可以，请贴出Debug级别的日志信息，以便更高效的确定和解决问题。）
![image](https://user-images.githubusercontent.com/74068830/161899101-978f4601-faff-46a8-96f9-1ca2f639fb82.png)

> 看着像网络问题，请求超过100秒未回应

最近一直正常，可能那天服务器出问题了，给大佬添麻烦了🌚

**Comment by RayWangQvQ** [comment]
看着像网络问题，请求超过100秒未回应

**Comment by miaomiaocatmsg** [comment]
您好，您的邮件我已经收到了。
会尽快处理的。
