### ISSUE TITLE
【Bug】<自动给陌生用户充电>

### ISSUE THREAD

**Issue by OldNoobHK** [RayWangQvQ/BiliBiliToolPro#763]
### 版本

BiliTool版本号：`2.1.1`

### 确认

- [ √] 是的，我已搜索并确认，没有其他相同的议题
- [√ ] 是的，我确认，已尝试升级到最新版，但未解决

### 服务器架构

- [ √] x64
- [ ] arm64
- [ ] arm
- [ ] 其他（请在下面补充）

### 服务器系统

- [√ ] Windows
- [ ] macOS
- [ ] Linux
    - [ ] Debian
    - [ ] Ubuntu
    - [ ] Windows
    - [ ] Alpine
    - [ ] Centos
    - [ ] 其他（请在下面补充）

### 选择的BiliTool运行模式

- [ ] docker
- [ ] podman
- [ √] 下载的Release包
- [ ] 其他（请在下面补充）

### 问题描述

<这里>
在appsettings.json中的充电选项填写为-1，没有给自己充电，而是为appsettings.Development.json appsettings.Production.json文件中的341688380 220893216用户充电
![image](https://github.com/user-attachments/assets/ab0de97b-59bf-4b24-a1f3-cee37b165dc4)

### 日志信息

<details>

```
<这里>
```

</details>

**Comment by rainsum2022** [comment]
对，我就说呢刚看了一下最近半年都是给陌生人充电，和你这个一样给都是给341688380这个账号充电。
