### ISSUE TITLE
【Bug】企业微信应用不推送

### ISSUE THREAD

**Issue by Cyiming** [RayWangQvQ/BiliBiliToolPro#77]
版本号：0.1.0

运行环境：青龙

问题描述：企业微信不推送，没有报错，corpId、agentId、secret三个环境变量添加没有错误，青龙同样设置可以推送。

日志信息：全为info级别 没有debug级别日志输出

**Comment by rogueme** [comment]
推送教程写错了,需要添加前缀Ray_
拿corpId做例子,应设置为Ray_Serilog__WriteTo__11__Args__corpId
