### ISSUE TITLE
【Bug】【青龙】<青龙面板扫码后一直报错The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing>

### ISSUE THREAD

**Issue by GitHubServer007** [RayWangQvQ/BiliBiliToolPro#775]
### 版本

BiliTool版本号：`x.x.x`

青龙版本号：`x.x.x`

### 确认

- [x] 是的，我已搜索并确认，没有其他相同的议题
- [ ] 是的，我确认，已尝试升级bilitool到最新版，但未解决
- [ ] 是的，我确认，已尝试升级青龙到最新版，但未解决

### 服务器架构

- [x] x64
- [ ] arm64
- [ ] arm
- [ ] 其他（请在下面补充）

### 服务器系统

- [ ] Windows
- [ ] macOS
- [x] Linux
    - [ ] Debian
    - [ ] Ubuntu
    - [ ] Windows
    - [ ] Alpine
    - [ ] Centos
    - [ ] 其他（请在下面补充）

### 青龙容器类型

- [ ] Docker
- [x] Podman
- [ ] 其他（请在下面补充）

### 青龙镜像

- [x] whyour/qinglong:latest（Alpine）
- [ ] whyour/qinglong:debian（Debian）

### 选择的BiliTool运行模式

- [x] dotnet
- [ ] bilitool

### 如果是青龙拉库相关bug，请贴出拉库方式截图

- [ ] 否
- [ ] 是，截图如下

### 如果是缺失文件相关bug，请贴出容器内文件路径信息

- [ ] 否
- [ ] 是，信息如下

查看方式参考文档：[提示文件不存在或路径异常怎么排查](https://github.com/RayWangQvQ/BiliBiliToolPro/blob/main/qinglong/README.md#43-提示文件不存在或路径异常怎么排查)

BiliTool仓库文件路径：`<粘贴路径>`

脚本文件路径：`<粘贴路径>`

<这里贴截图>

### 问题描述

<这里>

### 日志信息

<details>

```
<这里>
```

</details>

**Comment by GitHubServer007** [comment]
[EXCEPTION]
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: The operation was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.

**Comment by huangjiaxing** [comment]
+1

**Comment by RayWangQvQ** [comment]
超时，一般是服务器网络问题，建议curl测试下请求阿B接口
