### ISSUE TITLE
使用几天就会报错，然后重拉一次仓库，再运行一次，必把服务器卡死

### ISSUE THREAD

**Issue by xdchm0719** [RayWangQvQ/BiliBiliToolPro#778]
使用几天就会报错，然后重拉一次仓库，再运行一次，必把服务器卡死

求解决办法

bilitool: 环境正常，本次无需安装
./bili_task_base.sh: line 463: cd: /src/Ray.BiliBiliTool.Console: No such file or directory
/ql/shell/otask.sh: line 240: pop_var_context: head of shell_variables not a function context
/ql/shell/otask.sh: line 272: pop_var_context: head of shell_variables not a function context

然后重拉，拉完运行，服务器直接卡死，每回得重启

**Comment by YUNHAI001** [comment]
## 开始执行... 2024-08-28 21:41:09

bilitool: 青龙repo目录: /ql/data/repo
bilitool: bili仓库目录: 
bilitool: 当前系统发行版本：alpine.3.20.2
bilitool: 当前系统：linux-musl
bilitool: 当前架构：arm
bilitool: 当前选择的运行方式：dotnet
bilitool: 已安装dotnet，当前版本：6.0.133
bilitool: which dotnet: /usr/bin/dotnet
bilitool: 环境正常，本次无需安装
./bili_task_base.sh: line 463: cd: /src/Ray.BiliBiliTool.Console: No such file or directory
/ql/shell/otask.sh: line 240: pop_var_context: head of shell_variables not a function context
/ql/shell/otask.sh: line 272: pop_var_context: head of shell_variables not a function context

是的我也是这样，两天是正常的

**Comment by gujiangjiang** [comment]
同样，我也开始出现这个问题了。。。

bilitool: 青龙repo目录: /ql/data/repo
bilitool: bili仓库目录: 
bilitool: 当前系统发行版本：alpine.3.20.2
bilitool: 当前系统：linux-musl
bilitool: 当前架构：x64
bilitool: 当前选择的运行方式：dotnet
bilitool: 已安装dotnet，当前版本：6.0.133
bilitool: which dotnet: /usr/bin/dotnet
bilitool: 环境正常，本次无需安装
bili_task_base.sh: line 463: cd: /src/Ray.BiliBiliTool.Console: No such file or directory
/ql/shell/otask.sh: line 240: pop_var_context: head of shell_variables not a function context
/ql/shell/otask.sh: line 277: pop_var_context: head of shell_variables not a function context

**Comment by ldcr1319** [comment]
一样的 也是这个报错  咋解决

**Comment by pooneyy** [comment]
因为之前能获取到bili仓库目录
![image](https://github.com/user-attachments/assets/796c8707-114c-4c01-ac41-aa3e5a4c4549)

现在获取不到，不知道什么原因
![image](https://github.com/user-attachments/assets/b1b9a77a-187a-4957-b731-b5f1b5731d18)

**Comment by dxdxma** [comment]
我也是的，前几天拉的库是没问题的。刚才拉的运行后报错一模一样

## 开始执行... 2024-09-03 22:06:43

bilitool: 青龙repo目录: /ql/data/repo
/ql/shell/otask.sh: line 240: pop_var_context: head of shell_variables not a function context
/ql/shell/otask.sh: line 277: pop_var_context: head of shell_variables not a function context

**Comment by dxdxma** [comment]
> 因为之前能获取到bili仓库目录 ![image](https://private-user-images.githubusercontent.com/85266337/363540132-796c8707-114c-4c01-ac41-aa3e5a4c4549.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNzQ1OTQsIm5iZiI6MTcyNTM3NDI5NCwicGF0aCI6Ii84NTI2NjMzNy8zNjM1NDAxMzItNzk2Yzg3MDctMTE0Yy00YzAxLWFjNDEtYWEzZTVhNGM0NTQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDE0MzgxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiYTY0ODg0NjA5MGIzMzY2ZDg5NDgzNGM2OGQ4YTM4ZmI0NDAxOTFlZjU1OTllOWJjMDMwMzY2ZDk3MTJiYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hpttKxQ6s6iBBBu4IHTquxBVzaQZrDNeNOPzEjZLp5w)
> 
> 现在获取不到，不知道什么原因 ![image](https://private-user-images.githubusercontent.com/85266337/363540266-b1b9a77a-187a-4957-b731-b5f1b5731d18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNzQ1OTQsIm5iZiI6MTcyNTM3NDI5NCwicGF0aCI6Ii84NTI2NjMzNy8zNjM1NDAyNjYtYjFiOWE3N2EtMTg3YS00OTU3LWI3MzEtYjVmMWI1NzMxZDE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDE0MzgxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5ZDY0N2FmODc3ZTJjYzM2ZmRkN2YzOGJmOWU4OTg0ZTA0ZWFkY2Q4ZDk4NTdjYTE2MmRiYzBiZDAyMGM1OGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.09uAhrd06NVXgDlnzNwiZWYRIe2YGVZ8t9cVtP75uwc)
> 
> 日期是2024.09.01开始出现的问题，看路径应该是`/ql/data/repo/RayWangQvQ_BiliBiliToolPro`，我刚才去看，这个目录已经消失了，那就是拉库出了问题。去看拉库的日志，果然 失败了。 ![image](https://private-user-images.githubusercontent.com/85266337/363541377-2b60bef3-afd4-48c7-bbd3-3424f8cc1e99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNzQ1OTQsIm5iZiI6MTcyNTM3NDI5NCwicGF0aCI6Ii84NTI2NjMzNy8zNjM1NDEzNzctMmI2MGJlZjMtYWZkNC00OGM3LWJiZDMtMzQyNGY4Y2MxZTk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDE0MzgxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiMmM4OTNjNTBkOWU2YjBkYmU0NmE1NGQ5MzE4YWE4NGM0NzQ1NmE2ZmU0OGI3MzJkMmQ3NzljZDQyNmM3NzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6TjkynYSVSmT6d1QilIcUxZbroRzOrE2XdqVpVkY6vs)
> 
> **解决方案**拉库链接换成这个试试：https://gitdl.cn/https://github.com/RayWangQvQ/BiliBiliToolPro.git

重新拉库也是这个报错，文件消失不是根本问题。
应该是脚本中地址识别代码出现问题，导致脚本异常退出。
解决方法为直接修改 "bili_base.sh" 第86行的变量为正确的repo地址（如图所示，地址可能因版本而异）
![image](https://github.com/user-attachments/assets/58e6d0fa-6270-4edb-b159-5ca45025e910)


-------debug--------
观察日志发现 “say "青龙repo目录: $dir_repo"” 输出正确，但“say "bili仓库目录: $qinglong_bili_repo_dir"”未正常输出，所以是中间的代码出现问题。
再加上你说仓库目录读不出来，判断 “$qinglong_bili_repo_dir” 变量读取不正确
修改为绝对路径后正常运行
![image](https://github.com/user-attachments/assets/63bd75fc-8b06-4e7e-b7ee-9594cf64c9aa)

**Comment by pooneyy** [comment]
> > 因为之前能获取到bili仓库目录 ![image](https://private-user-images.githubusercontent.com/85266337/363540132-796c8707-114c-4c01-ac41-aa3e5a4c4549.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNzQ1OTQsIm5iZiI6MTcyNTM3NDI5NCwicGF0aCI6Ii84NTI2NjMzNy8zNjM1NDAxMzItNzk2Yzg3MDctMTE0Yy00YzAxLWFjNDEtYWEzZTVhNGM0NTQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDE0MzgxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiYTY0ODg0NjA5MGIzMzY2ZDg5NDgzNGM2OGQ4YTM4ZmI0NDAxOTFlZjU1OTllOWJjMDMwMzY2ZDk3MTJiYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hpttKxQ6s6iBBBu4IHTquxBVzaQZrDNeNOPzEjZLp5w)
> > 现在获取不到，不知道什么原因 ![image](https://private-user-images.githubusercontent.com/85266337/363540266-b1b9a77a-187a-4957-b731-b5f1b5731d18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNzQ1OTQsIm5iZiI6MTcyNTM3NDI5NCwicGF0aCI6Ii84NTI2NjMzNy8zNjM1NDAyNjYtYjFiOWE3N2EtMTg3YS00OTU3LWI3MzEtYjVmMWI1NzMxZDE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDE0MzgxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5ZDY0N2FmODc3ZTJjYzM2ZmRkN2YzOGJmOWU4OTg0ZTA0ZWFkY2Q4ZDk4NTdjYTE2MmRiYzBiZDAyMGM1OGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.09uAhrd06NVXgDlnzNwiZWYRIe2YGVZ8t9cVtP75uwc)
> > 日期是2024.09.01开始出现的问题，看路径应该是`/ql/data/repo/RayWangQvQ_BiliBiliToolPro`，我刚才去看，这个目录已经消失了，那就是拉库出了问题。去看拉库的日志，果然 失败了。 ![image](https://private-user-images.githubusercontent.com/85266337/363541377-2b60bef3-afd4-48c7-bbd3-3424f8cc1e99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNzQ1OTQsIm5iZiI6MTcyNTM3NDI5NCwicGF0aCI6Ii84NTI2NjMzNy8zNjM1NDEzNzctMmI2MGJlZjMtYWZkNC00OGM3LWJiZDMtMzQyNGY4Y2MxZTk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDE0MzgxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiMmM4OTNjNTBkOWU2YjBkYmU0NmE1NGQ5MzE4YWE4NGM0NzQ1NmE2ZmU0OGI3MzJkMmQ3NzljZDQyNmM3NzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6TjkynYSVSmT6d1QilIcUxZbroRzOrE2XdqVpVkY6vs)
> > **解决方案**拉库链接换成这个试试：https://gitdl.cn/https://github.com/RayWangQvQ/BiliBiliToolPro.git
> 
> 重新拉库也是这个报错，文件消失不是根本问题。 应该是脚本中地址识别代码出现问题，导致脚本异常退出。
> 
> ### 解决方法为直接修改 "**bili_base**"第86行的变量为正确的repo地址_（如图所示，地址可能因版本而异）
> ```
> # 目录
> say "青龙repo目录: $dir_repo"
> qinglong_bili_repo="$(echo "$bili_repo" | sed 's/\//_/g')${bili_branch}"
> qinglong_bili_repo_dir="/ql/data/repo/RayWangQvQ_BiliBiliToolPro"
> say "bili仓库目录: $qinglong_bili_repo_dir"
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/56927460/364040378-0bb54b4a-d4e0-4734-ae83-2df6da639d8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNzc4MDgsIm5iZiI6MTcyNTM3NzUwOCwicGF0aCI6Ii81NjkyNzQ2MC8zNjQwNDAzNzgtMGJiNTRiNGEtZDRlMC00NzM0LWFlODMtMmRmNmRhNjM5ZDhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDE1MzE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiN2Y1ZThkZTMyYjBjYTY3MDQ3YTc3YTliMjAxMmU0NTc2Njk1ZjE4MjdkNTZhYWZjNGRiNGMzODhlNmM4YzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R0GblIuJ8bTR7hYvZNizhV4t4vgdmVG4AFeLTkyt90Q)
> 
> _-------debug-------- 观察日志发现 “say "青龙repo目录: $dir_repo"” 输出正确，但“say "bili仓库目录: $qinglong_bili_repo_dir"”未正常输出，所以是中间的代码出现问题。 ![image](https://private-user-images.githubusercontent.com/56927460/364034363-63bd75fc-8b06-4e7e-b7ee-9594cf64c9aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNzc4MDgsIm5iZiI6MTcyNTM3NzUwOCwicGF0aCI6Ii81NjkyNzQ2MC8zNjQwMzQzNjMtNjNiZDc1ZmMtOGIwNi00ZTdlLWI3ZWUtOTU5NGNmNjRjOWFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDE1MzE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyZjJmYjdkZmY2ZmFhOTkwYTE0YzEwNmQ4OTdjYjFiZDE2ODZjZmVkZWUxMjQ4MmU1OTQ5ZDFiNTVjYzYyZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cH1Hea0z4WEZ0J5CGe0qBS88LD4GW6icFjr6wQ8jU8g) 再加上你说仓库目录读不出来，判断 “$qinglong_bili_repo_dir” 变量读取不正确 修改为绝对路径后正常运行 ![image](https://private-user-images.githubusercontent.com/56927460/364039453-e69bc86b-39ba-4bae-a23b-f37fc82de40d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNzc4MDgsIm5iZiI6MTcyNTM3NzUwOCwicGF0aCI6Ii81NjkyNzQ2MC8zNjQwMzk0NTMtZTY5YmM4NmItMzliYS00YmFlLWEyM2ItZjM3ZmM4MmRlNDBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDE1MzE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkYmU5ZTdiMDVjM2I2NDRhNzJjNTBmOGI5YWQ3YWY4MjUyZGNmZmZmM2M2NzliMjhjNGI0Nzk5OWFhOWQ5NDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IEssWKvD2psgS6PGB5U_AN7C-F_PADGhOQ-g_18yp80)_

总之我已经成功了，不然也不会发出来、

**Comment by yelochick** [comment]
经过分析，
find $dir_repo -type d \( -iname $qinglong_bili_repo -o -iname ${qinglong_bili_repo}_main \) | head -1
返回了非零

而由于脚本加了
set -e
set -u
set -o pipefail
配置，所以整个脚本直接退出了

以下是gpt的回答

![PixPin_2024-09-19_18-02-37](https://github.com/user-attachments/assets/998cae8c-69f5-4a83-936f-7645b5ee28b6)

**Comment by MengyuCai** [comment]
bili_base"第86行 改为
qinglong_bili_repo_dir="$(find $dir_repo -type d \( -iname $qinglong_bili_repo -o -iname ${qinglong_bili_repo}_main \) | head -1 || true)"

**Comment by ghsssss** [comment]
|| true好使
