### ISSUE TITLE
【Bug】ERR 程序发生异常：Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by sst2020** [RayWangQvQ/BiliBiliToolPro#791]
### 版本

BiliTool版本号：`2.1.1`

### 确认

- [ √ ] 是的，我已搜索并确认，没有其他相同的议题
- [ √ ] 是的，我确认，已尝试升级到最新版，但未解决

### 服务器架构

- [ √ ] x64
- [ ] arm64
- [ ] arm
- [ ] 其他（请在下面补充）

### 服务器系统

- [ √ ] Windows
- [ ] macOS
- [ ] Linux
    - [ ] Debian
    - [ ] Ubuntu
    - [ ] Windows
    - [ ] Alpine
    - [ ] Centos
    - [ ] 其他（请在下面补充）

### 选择的BiliTool运行模式

- [ ] docker
- [ ] podman
- [ √ ] 下载的Release包
- [ ] 其他（请在下面补充）

### 问题描述

<这里>
大会员无法签到。

### 日志信息

[08:12:41 INF] ---开始 浏览追番频道页10秒 ---
[08:12:41 ERR] 浏览追番频道页10秒失败，继续其他任务。失败信息:Sequence contains no matching element

[08:12:41 INF] -------------结束-------------

[08:12:41 INF] ---开始 浏览会员购页面10秒 ---
[08:12:41 ERR] 浏览会员购页面10秒失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

[08:12:41 INF] -------------结束-------------

[08:12:41 INF] ---开始 浏览装扮商城主页 ---
[08:12:41 ERR] 浏览装扮商城主页失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

[08:12:41 INF] -----------结束-----------

[08:12:41 INF] ---开始 观看剧集内容 ---
[08:12:41 ERR] 观看剧集内容失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

[08:12:41 INF] ---------结束---------

[08:12:41 INF] ---开始 购买单点付费影片（仅领取） ---
[08:12:41 ERR] 购买单点付费影片（仅领取）失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

[08:12:41 INF] ----------------结束----------------

[08:12:41 INF] ---开始 购买指定会员购商品（仅领取） ---
[08:12:41 ERR] 购买指定会员购商品（仅领取）失败，继续其他任务。失败信息:Object reference not set to an instance of an object.

[08:12:41 INF] -----------------结束-----------------

[08:12:41 ERR] 程序发生异常：Object reference not set to an instance of an object.
[08:12:41 INF] ===========结束===========

[08:12:41 WRN] 异常：System.NullReferenceException: Object reference not set to an instance of an object.
   at Ray.BiliBiliTool.Application.VipBigPointAppService.DoTaskAsync(CancellationToken cancellationToken)
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.DoTasksAsync(String[] tasks, CancellationToken cancellationToken)
   at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.StartAsync(CancellationToken cancellationToken)
[08:12:41 INF] 运行环境：Production
[08:12:41 INF] 应用目录：D:\program\bilibili-tool-pro-v2.1.1-win-x64\
<details>

```
<这里>
```

</details>

**Comment by St-Jiuyu** [comment]
同上 MacOS M1也有这个问题

**Comment by zhemed** [comment]
我是通过青龙面板拉取的，也是这样的报错，青龙版本2.17.12 服务器架构x64

**Comment by TaiMiao** [comment]
+1同样问题

**Comment by zywj0han9** [comment]
+1

**Comment by Mtxgeek** [comment]
win11 Release包 问题同样

**Comment by Firfr** [comment]
+1 青龙面板 同样的问题

**Comment by 464946021** [comment]
这个问题是因为任务“浏览追番频道页10秒”已经没有了，把那个任务注释掉，不执行，后面的任务就可以正常执行。
在src/Ray.BiliBiliTool.Application/VipBigPointAppService.cs文件的第142行前面加注释符：
`//taskInfo = await ViewAnimate(taskInfo);`

**Comment by ypq123456789** [comment]
> 这个问题是因为任务“浏览追番频道页10秒”已经没有了，把那个任务注释掉，不执行，后面的任务就可以正常执行。 在src/Ray.BiliBiliTool.Application/VipBigPointAppService.cs文件的第142行前面加注释符： `//taskInfo = await ViewAnimate(taskInfo);`

青龙面板如何修改呢 谢谢老哥

**Comment by 464946021** [comment]
> > 这个问题是因为任务“浏览追番频道页10秒”已经没有了，把那个任务注释掉，不执行，后面的任务就可以正常执行。 在src/Ray.BiliBiliTool.Application/VipBigPointAppService.cs文件的第142行前面加注释符： `//taskInfo = await ViewAnimate(taskInfo);`
> 
> 青龙面板如何修改呢 谢谢老哥

这个项目支持两种运行模式：dotnet和bilitool，前者是直接运行源码，后者是作者编译好的可执行文件。

- [1] 因为要修改源码，所以要确保已经设置成dotnet模式（默认就是这个模式，如果没有改过配置就不用动了）

> 编辑青龙面板的`配置文件`，写入配置`export BILI_MODE="dotnet" # bili运行模式，dotnet或bilitool`

- [2] 进入容器`docker exec -it qinglong bash`，修改源码，源码在`/ql/dada/repo`目录下。

> 这一步需要一点点Linux基础

- [3] 退出容器，像平时一样执行脚本

**Comment by ypq123456789** [comment]
> > > 这个问题是因为任务“浏览追番频道页10秒”已经没有了，把那个任务注释掉，不执行，后面的任务就可以正常执行。 在src/Ray.BiliBiliTool.Application/VipBigPointAppService.cs文件的第142行前面加注释符： `//taskInfo = await ViewAnimate(taskInfo);`
> > 
> > 
> > 青龙面板如何修改呢 谢谢老哥
> 
> 这个项目支持两种运行模式：dotnet和bilitool，前者是直接运行源码，后者是作者编译好的可执行文件。
> 
> * [1] 因为要修改源码，所以要确保已经设置成dotnet模式（默认就是这个模式，如果没有改过配置就不用动了）
> 
> > 编辑青龙面板的`配置文件`，写入配置`export BILI_MODE="dotnet" # bili运行模式，dotnet或bilitool`
> 
> * [2] 进入容器`docker exec -it qinglong bash`，修改源码，源码在`/ql/dada/repo`目录下。
> 
> > 这一步需要一点点Linux基础
> 
> * [3] 退出容器，像平时一样执行脚本

谢谢大佬 没问题了

**Comment by CirnoSalt** [comment]
> Referen

感谢，修好了，脚本作者看上去有段时间没更新了，有些功能坏掉的功能也长时间没维护，这么好的项目希望别是弃坑了……🥲

**Comment by CirnoSalt** [comment]
> 这个问题是因为任务“浏览追番频道页10秒”已经没有了，把那个任务注释掉，不执行，后面的任务就可以正常执行。 在src/Ray.BiliBiliTool.Application/VipBigPointAppService.cs文件的第142行前面加注释符： `//taskInfo = await ViewAnimate(taskInfo);`

感谢，修好了，脚本作者看上去有段时间没更新了，有些功能坏掉的功能也长时间没维护，这么好的项目希望别是弃坑了……🥲

**Comment by ypq123456789** [comment]
> > > 这个问题是因为任务“浏览追番频道页10秒”已经没有了，把那个任务注释掉，不执行，后面的任务就可以正常执行。 在src/Ray.BiliBiliTool.Application/VipBigPointAppService.cs文件的第142行前面加注释符： `//taskInfo = await ViewAnimate(taskInfo);`
> > 
> > 
> > 青龙面板如何修改呢 谢谢老哥
> 
> 这个项目支持两种运行模式：dotnet和bilitool，前者是直接运行源码，后者是作者编译好的可执行文件。
> 
> * [1] 因为要修改源码，所以要确保已经设置成dotnet模式（默认就是这个模式，如果没有改过配置就不用动了）
> 
> > 编辑青龙面板的`配置文件`，写入配置`export BILI_MODE="dotnet" # bili运行模式，dotnet或bilitool`
> 
> * [2] 进入容器`docker exec -it qinglong bash`，修改源码，源码在`/ql/dada/repo`目录下。
> 
> > 这一步需要一点点Linux基础
> 
> * [3] 退出容器，像平时一样执行脚本

大佬 现在又报错了。。。

**Comment by ypq123456789** [comment]
@RayWangQvQ 大佬 这个修复目前还是会报错 同样的错误

**Comment by RayWangQvQ** [comment]
已解决，当任务不存在时，继续执行后续任务。
感谢反馈。

**Comment by ypq123456789** [comment]
## 开始执行... 2024-12-25 00:53:54 bilitool: 青龙repo目录: /ql/data/repo bilitool: bili仓库目录: /ql/data/repo/RayWangQvQ_BiliBiliToolPro bilitool: 当前系统发行版本：alpine.3.19.1 bilitool: 当前系统：linux-musl bilitool: 当前架构：x64 bilitool: 当前选择的运行方式：dotnet bilitool: 已安装dotnet，当前版本：6.0.129 bilitool: which dotnet: /usr/bin/dotnet bilitool: 环境正常，本次无需安装   ____               ____    _   _____           _    |  _ \ __ _ _   _  | __ ) _| |_|_   _|__   ___ | |   | |_) / _` | | | | |  _ \(_) (_) | |/ _ \ / _ \| |   |  _ < (_| | |_| | | |_) | | | | | | (_) | (_) | |   |_| \_\__,_|\__, | |____/|_|_|_| |_|\___/ \___/|_|               |___/                                   [00:54:26 INF] BiliBiliToolPro 开始运行... [00:54:26 INF] 【账号个数】1个 [00:54:26 INF] 【目标任务】VipBigPoint [00:54:26 INF] ######### 账号 1 ######### [00:54:27 INF] =====开始 大会员大积分 ===== [00:54:27 INF] ---开始 测试Cookie --- [00:54:46 INF] 【用户名】帽子xxx了 [00:54:46 INF] 【会员类型】月度大会员 [00:54:46 INF] 【会员状态】正常 [00:54:46 INF] 【硬币余额】548 [00:54:46 INF] 【距升级Lv6】预计335天 [00:54:46 INF] -----------结束----------- [00:55:00 INF] ------当前任务状态------ [00:55:00 INF] 打卡：√ [00:55:00 INF] -福利任务 [00:55:00 INF] ---大会员福利大积分：√ [00:55:00 INF] -体验任务 [00:55:00 INF] ---浏览大会员权益页面：√ [00:55:00 INF] -日常任务 [00:55:00 INF] ---浏览装扮商城主页：X [00:55:00 INF] ---浏览会员购页面10秒：X [00:55:00 INF] ---购买指定会员购商品：X [00:55:00 INF] ---浏览影视频道页10秒：X [00:55:00 INF] ---观看剧集内容：X [00:55:00 INF] ---购买单点付费影片：X [00:55:00 INF] ---购买指定装扮商品：X [00:55:00 INF] ------------------------ [00:55:00 INF] 大会员经验领取任务开始 [00:55:13 INF] 大会员经验已兑换 [00:55:13 INF] ---开始 签到 --- [00:55:13 INF] 已完成，跳过 [00:55:13 INF] 今日获得签到积分：10 [00:55:13 INF] 累计签到26天 [00:55:13 INF] -----结束----- [00:55:13 INF] ---开始 福利任务 --- [00:55:13 INF] 已完成，跳过 [00:55:13 INF] -------结束------- [00:55:13 INF] ---开始 体验任务 --- [00:55:13 INF] 已完成，跳过 [00:55:13 INF] -------结束------- [00:55:13 INF] ---开始 浏览追番频道页10秒 --- [00:55:13 ERR] 浏览追番频道页10秒失败，继续其他任务。失败信息:Sequence contains no matching element [00:55:13 INF] -------------结束------------- [00:55:13 INF] ---开始 浏览会员购页面10秒 --- [00:55:13 ERR] 浏览会员购页面10秒失败，继续其他任务。失败信息:Object reference not set to an instance of an object. [00:55:13 INF] -------------结束------------- [00:55:13 INF] ---开始 浏览装扮商城主页 --- [00:55:13 ERR] 浏览装扮商城主页失败，继续其他任务。失败信息:Object reference not set to an instance of an object. [00:55:13 INF] -----------结束----------- [00:55:13 INF] ---开始 观看剧集内容 --- [00:55:13 ERR] 观看剧集内容失败，继续其他任务。失败信息:Object reference not set to an instance of an object. [00:55:13 INF] ---------结束--------- [00:55:13 INF] ---开始 购买单点付费影片（仅领取） --- [00:55:13 ERR] 购买单点付费影片（仅领取）失败，继续其他任务。失败信息:Object reference not set to an instance of an object. [00:55:13 INF] ----------------结束---------------- [00:55:13 INF] ---开始 购买指定会员购商品（仅领取） --- [00:55:13 ERR] 购买指定会员购商品（仅领取）失败，继续其他任务。失败信息:Object reference not set to an instance of an object. [00:55:13 INF] -----------------结束----------------- [00:55:13 ERR] 程序发生异常：Object reference not set to an instance of an object. [00:55:13 INF] ===========结束=========== [00:55:13 WRN] 异常：System.NullReferenceException: Object reference not set to an instance of an object.    at Ray.BiliBiliTool.Application.VipBigPointAppService.DoTaskAsync(CancellationToken cancellationToken) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Application/VipBigPointAppService.cs:line 157    at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.DoTasksAsync(String[] tasks, CancellationToken cancellationToken) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 194    at Ray.BiliBiliTool.Console.BiliBiliToolHostedService.StartAsync(CancellationToken cancellationToken) in /ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/BiliBiliToolHostedService.cs:line 76 [00:55:13 INF] 运行环境：Production [00:55:13 INF] 应用目录：/ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/bin/Debug/net6.0/ [00:55:13 INF] 运行结束 ## 执行结束... 2024-12-25 00:55:13  耗时 79 秒　　　　　


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RayWangQvQ/BiliBiliToolPro"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月25日(星期三) 凌晨0:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RayWangQvQ/BiliBiliToolPro] 【Bug】ERR 程序发生异常：Object reference not set to an instance of an object. (Issue #791)





 
Closed #791 as completed.
