### ISSUE TITLE
【建议】建议企业微信推送增加图文推送

### ISSUE THREAD

**Issue by Cyiming** [RayWangQvQ/BiliBiliToolPro#80]
由于推送信息太长 太占用空间 建议支持图文推送

**Comment by mmeiwenlong** [comment]
这配置变量是怎么搞的，怎么我按教程设了三个变量了也重启了就是看不到推送，

**Comment by wenrouhao** [comment]
> 
教程那个变量值不对，在“Serilog__WriteTo__11__Args__XXXX”前面加Ray_就解决

**Comment by mmeiwenlong** [comment]
> > 
> 
> 教程那个变量值不对，在“Serilog__WriteTo__11__Args__XXXX”前面加Ray_就解决

谢谢，可以了
