### ISSUE TITLE
【建议】删除或关闭直播签到相关功能

### ISSUE THREAD

**Issue by Lucio-0408** [RayWangQvQ/BiliBiliToolPro#803]
### 确认

- [x] 是的，我已搜索并确认，没有其他相同的议题

### 建议内容

B站已下线直播签到活动，没找到关闭直播签到的自定义配置，建议删除，银瓜子兑换感觉也可以删了

**Comment by RayWangQvQ** [comment]
已更新：#806

感谢反馈
