### ISSUE TITLE
【Bug】<企业微信机器人推送报错>

### ISSUE THREAD

**Issue by ascte** [RayWangQvQ/BiliBiliToolPro#804]
### 版本

BiliTool版本号：`2.1.2`

### 确认

- [√ ] 是的，我已搜索并确认，没有其他相同的议题
- [√ ] 是的，我确认，已尝试升级到最新版，但未解决

### 服务器架构

- [ ] x64
- [ ] arm64
- [ ] arm
- [ √] 其他（请在下面补充）
         x86
### 服务器系统

- [ ] Windows
- [ ] macOS
- [ ] Linux
    - [ ] Debian
    - [ ] Ubuntu
    - [ ] Windows
    - [ ] Alpine
    - [ ] Centos
    - [ ] 其他（请在下面补充）
           飞牛NAS OS FnOS 
### 选择的BiliTool运行模式

- [√ ] docker
- [ ] podman
- [ ] 下载的Release包
- [ ] 其他（请在下面补充）

### 问题描述

企业微信机器人推送报错

### 日志信息

<details>

```
========================

 v2.1.2 开源 by https://github.com/RayWangQvQ/BiliBiliToolPro

[10:52:36 INF] ·开始推送·Test任务·
2024-11-29T02:52:36.6368571Z **Exception while emitting periodic batch from Ray.Serilog.Sinks.WorkWeiXinBatched.WorkWeiXinBatchedSink: Invalid URI: The format of the URI could not be determined.**
[10:52:36 INF] 运行环境：Production
[10:52:36 INF] 应用目录：/ql/data/repo/RayWangQvQ_BiliBiliToolPro/src/Ray.BiliBiliTool.Console/bin/Debug/net6.0/

[10:52:36 INF] 运行结束
**/ql/shell/share.sh: line 464: task_after: unbound variable**
```

</details>

**Comment by RayWangQvQ** [comment]
看下配置`Serilog:WriteTo:4:Args:webHookUrl`，估计url配的有点问题

**Comment by ascte** [comment]
搞定了，原来Serilog:WriteTo:4:Args:webHookUrl的值填写的是微信机器人的整个url而不是像有的项目只填写末端的一串key值，是我理解错了，现在终于可以了，只不过在普通微信上可能由于信息过长提示“暂不支持此消息类型，点击前往企业微信查看”，不过我也装了企业微信app，所以直接跳转就能查看完整日志啦。

**Comment by ascte** [comment]
学习了下，如果测试在企业微信能够收到消息，但是微信里提示“暂不支持此消息类型 请在企业微信中查看”，原因是你发送的消息的类型不对，目前微信只支持text形式。

需要修改 msgtype:text

所以能否请R大指教下有没有什么环境变量可以修改“企业微信机器人”这种推送方式下的推送类型为文本，我看企业微信应用好像就可以，但是我没有固定ip，查了下好像没法用“企业微信应用”的方式进行推送。

**Comment by ascte** [comment]
@RayWangQvQ 辛苦作者了，谢谢，还请不忙的时候帮忙看下。

**Comment by RayWangQvQ** [comment]
可以，感谢反馈，稍后会看。
能麻烦重新提一个针对新问题的issue不，方便追踪，当前这个已经close了

**Comment by KinsonWong** [comment]
可能是因为Log里面账号这里的井号被识别成markdown格式了，可能要从源码里面改

<img width="544" alt="Image" src="https://github.com/user-attachments/assets/58557e42-ca75-4224-b594-fa19e71eea27" />
