### ISSUE TITLE
【Bug】直播签到无法使用

### ISSUE THREAD

**Issue by susulqx** [RayWangQvQ/BiliBiliToolPro#806]
### 版本

BiliTool版本号：2.1.1

### 确认

- [ v] 是的，我已搜索并确认，没有其他相同的议题
- [ ] 是的，我确认，已尝试升级到最新版，但未解决

### 服务器架构

- [ v] x64
- [ ] arm64
- [ ] arm
- [ ] 其他（请在下面补充）

### 服务器系统

- [ ] Windows
- [ ] macOS
- [ ] Linux
    - [ ] Debian
    - [ v] Ubuntu
    - [ ] Windows
    - [ ] Alpine
    - [ ] Centos
    - [ ] 其他（请在下面补充）

### 选择的BiliTool运行模式

- [ ] docker
- [ ] podman
- [ ] 下载的Release包
- [ v] 其他（请在下面补充）
- actions

### 问题描述

直播签到无法使用，其他正常

### 日志信息

[02:17:26 INF] ---开始 直播签到 ---
[02:17:30 INF] 【签到结果】失败
[02:17:30 INF] 【原因】签到活动已下线，无法使用。
[02:17:30 INF] -------结束-------

<details>

```
<这里>
```

</details>

**Comment by St-Jiuyu** [comment]
B站这个功能已经下线了 所以脚本没有办法使用

**Comment by RayWangQvQ** [comment]
已移除失效任务，感谢反馈。
