### ISSUE TITLE
【Bug】青龙面板定时运行任务详情空白

### ISSUE THREAD

**Issue by aosenqaq** [RayWangQvQ/BiliBiliToolPro#87]
版本号：V0.1.0
运行环境：docker 青龙面板2.9.3

问题描述：稳定运行了两天，今天早上发现运行时任务详情空白，无法运行
日志信息：暂无

**Comment by aosenqaq** [comment]
使用dev版本会有这种情况，后续发现出现原因是程序会一直报错，但进程会一直存在，并且还会继续打开新的进程，但依旧报错，以此类推，运行的机器是2h2g，cpu占用直接拉满，后续更换稳定版运行后就没有问题了

**Comment by drw2005** [comment]
我这边是拉正式库日志空白，但是能正常拉取任务。
不知是是何原因！

**Comment by aosenqaq** [comment]
每天都有一个时刻会出现这种情况，稳定版和测试版都一样🌚

**Comment by drw2005** [comment]
> 每天都有一个时刻会出现这种情况，稳定版和测试版都一样🌚

我这边是任务运行日志正常显示，就是拉库日志空白。

**Comment by drw2005** [comment]
今天突然发现拉库日志能正常显示了。。。
