### ISSUE TITLE
【Bug】青龙面板运行sh脚本日志报‘项目文件不存在’错误

### ISSUE THREAD

**Issue by pytwj** [RayWangQvQ/BiliBiliToolPro#88]
版本号：最新版
运行环境：centos7 青龙面板（v2.12.1）

问题描述：MSBUILD : error MSB1009: 项目文件不存在。
开关:./src/Ray.BiliBiliTool.Console

日志信息：
![image](https://user-images.githubusercontent.com/62314967/162367787-35821880-5224-4206-a384-034ea55fb637.png)

**Comment by RayWangQvQ** [comment]
重新跑下拉库任务
