### ISSUE TITLE
这是什么问题啊，donet我放到了extra.sh里面了

### ISSUE THREAD

**Issue by xiaobaiyigejiaru** [RayWangQvQ/BiliBiliToolPro#90]
![屏幕截图 2022-04-10 103509](https://user-images.githubusercontent.com/87192483/162598712-899ebbff-fad4-497e-8e09-bd9df6a7b768.jpg)

**Comment by mangrove2014** [comment]
我也是这个问题。。

**Comment by Nvsdyi** [comment]
请认真阅读文档

**Comment by wanmeixiaoyuan2001** [comment]
我也是这个问题，你们解决了吗
