### ISSUE TITLE
【Bug】青龙面板无法拉库

### ISSUE THREAD

**Issue by a993209221** [RayWangQvQ/BiliBiliToolPro#92]
操作步骤:正常添加定时任务，拉取bilibili库。
操作结果：面板内查看并没有添加定时任务，测试过先行版本，成功拉取bilibili库
期望：正常拉取定时任务
青龙版本V2.10.13 系统LIUNX
![a0c034f07f991c0edaed4f08701a684](https://user-images.githubusercontent.com/64553540/162628830-98ae4d01-4cf7-439f-9977-b79d8fef7ff8.png)

**Comment by a993209221** [comment]
![image](https://user-images.githubusercontent.com/64553540/162729950-4834e852-7d28-4a14-8efe-b046c34ab0e9.png)
就显示拉取成功，查看定时任务内并没有任务更新

**Comment by a993209221** [comment]
![image](https://user-images.githubusercontent.com/64553540/162730027-5eb074c1-f256-41bf-9776-8ad7bdaa3939.png)

**Comment by Nvsdyi** [comment]
这个问题不应该找青龙么
