### ISSUE TITLE
编辑serverless.yml过程的问题

### ISSUE THREAD

**Issue by forchannot** [RayWangQvQ/BiliBiliToolPro#98]
我在进行云函数部署填写yml时，如果只填写cookie能够正常部署，但是当我想加其他的比如推送等，就会部署失败，是按照给定的格式进行的部署，就是填完cookie后回车进入下一行然后输入环境变量名字:然后空格+我的value，但是这样会部署失败，请问下正确方式应该是怎样呢

**Comment by DoveBoy** [comment]
用代码编辑器书写

**Comment by forchannot** [comment]
> 用代码编辑器书写

我用的notepad++写的然后复制过去的

**Comment by DoveBoy** [comment]
GA日志都告诉你了格式不对

**Comment by DoveBoy** [comment]
换行符改成LF试试

**Comment by forchannot** [comment]
> GA日志都告诉你了格式不对

把crlf改成了lf确一样不行，给的参考代码我看了下也是crlf

**Comment by forchannot** [comment]
> @forchannot GA日志显示从第二个环境变量开始格式就是错误的，换其他编辑器或者检测yaml格式

我下载本地包到云函数上传部署，用云函数自带的直接添加环境变量也会测试失败，那个应该不会出现格式问题吧

**Comment by forchannot** [comment]
> @forchannot GA日志显示从第二个环境变量开始格式就是错误的，换其他编辑器或者检测yaml格式

已经解决了，使用了在线yaml格式化的工具改了下，感谢耐心指导，我close了

**Comment by forchannot** [comment]
> @forchannot GA日志显示从第二个环境变量开始格式就是错误的，换其他编辑器或者检测yaml格式

老哥，还有个问题，虽然用yaml在线格式化工具后，能部署了，但是云函数只识别到了cookie这一个环境变量，另外几个我加的环境变量一个没弄进去，这是改了后的格式
![image](https://user-images.githubusercontent.com/100580891/162969794-e95af987-cfb6-485b-afc4-4f84e49bc50f.png)

**Comment by forchannot** [comment]
> 格式还是不对
那到底什么格式啊，懵了😂

**Comment by DoveBoy** [comment]
@forchannot 用vscode编辑不好吗？

**Comment by DoveBoy** [comment]
@forchannot sublime-text编辑，同时转换LF

**Comment by DoveBoy** [comment]
不是部署成功了吗？[auto-deploy-tencent-scf](https://github.com/forchannot/BiliBiliToolPro/actions/runs/2167396316)

**Comment by DoveBoy** [comment]
直接下载[serverless.yml](https://raw.githubusercontent.com/RayWangQvQ/BiliBiliToolPro/main/tencentScf/serverless.yml)，在sublime-text编辑，不会出现这种问题的啊

**Comment by forchannot** [comment]
> 直接下载[serverless.yml](https://raw.githubusercontent.com/RayWangQvQ/BiliBiliToolPro/main/tencentScf/serverless.yml)，在sublime-text编辑，不会出现这种问题的啊

一个一个手打可以部署，直接复制环境变量名字就失败

**Comment by catlair** [comment]
Here's the mistake

![image](https://user-images.githubusercontent.com/44313800/163518991-182e69ed-cfb0-497c-8da8-5900e8f97114.png)
